### ISSUE TITLE
[Feature] Keyword to execute 2+ browser keywords in parallel

### ISSUE THREAD

**Issue by idxn** [MarketSquare/robotframework-browser#103]
**Is your feature request related to a problem? Please describe.**
Sometimes we would have a use case to find out whether or not a network request is sent to the server after clicking a button. To do this we would use playwright's waitForRequest method and we may write the RBFW script like this. My assumption that we will implement Wait For Request keyword.
```
Click       #button
Wait For Request    xxx  xxxx
```

However the requests aren't captured consistently. On multiple occasions the command times out which results in a failed test. That is because the request is finished before waitForRequest was called.

**Describe the solution you'd like**
Have a keyword to execute 2 keywords in parallel e.g.
```
Run Async Keywords           Click       #button     AND    Wait For Request    xxx  xxxx
```

**Describe alternatives you've considered**
I have no idea at the moment.

**Comment by xylix** [comment]
After some thinking one idea we had for this specific need was:

How using the keyword that sets the `Wait For Request` wait before you execute the `Click` keyword. 

Example of another keyword that behaves like that here:
https://github.com/MarketSquare/robotframework-browser/blob/2e2ecd8f38739bff30f15efd48f4490686aa1de1/atest/test/01_Browser_Management/new_windows.robot#L6

So basically I would suggest the syntax 
```
Wait For Request    xxx  xxxx
Click       #button
```

Technically it just sets a playwright `waitForEvent` (or any other listener) with custom behaviour. It will fail the test if the wait is never fulfilled. One problem with this approach right now is that without a `Sleep` on robot side the control can move too quickly, and then even though Playwright is still waiting for the event our robot side library code closes the test. 

This syntax without an explicit `Run Async Keywords` would probably be better at conserving the return values of the robot keywords, but asynchronity might cause variables to not be set at times when they are expected if you tried something like:
```
${result}  Wait For Request    xxx  xxxx
Click       #button
Log  ${result}
```

But I think we could go forward without a `Run Async Keywords` for now. Do you think that using the `Wait For Request` before you have clicked the button makes sense?

**Comment by xylix** [comment]
Actually after discussing with @mkorpela I think I agree that having a keyword that says `Wait For` not stop to wait is a bit weird.

How would you feel about syntax like this
```
${request}=  Request  xxxx  xxxxx
Click  #button
Wait For  ${request}
```

**Comment by idxn** [comment]
@xylix That is also another good approach for request. However, there is also another use case we might need this keyword I can think of.
```
Fill Text       #email        invalid_email@d
Click       #button
Wait For Elements State     #toast           visible       1s
```
Toast may just appear for a second and disappear so our test may pass sometimes but sometimes not

**Comment by idxn** [comment]
it's ok if we have some kind of thing like request you have mentioned

**Comment by mkorpela** [comment]
**WHY**
This issue introduces a problem of an event (request) that might happen so close to our action (click) that we might not have time to set our waiting observer after making the action.

There exists also another situation where we are expecting two events to happen and we do not control in which order these events will actually happen. Handling this in a naive procedural way will randomly fail as we are bound to wait first for one thing to happen and then another. Sometimes the events will occur in opposite order thus first wait will observe its event but the second will not as the event has already happened.

**WHAT**
Let's introduce the concept of promises to Robot Framework. [A Promise](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise) is a proxy for a value not necessarily known when the promise is created.

**HOW**
Let's make it possible to execute Robot Framework Browser library keywords inside of a higher order promise wrapping keyword `Promise to Wait`.


    ${promise1}=  Promise to Wait  Get Title  ==  IMPORTANT  timeout=30s
    ${promise2}=  Promise to Wait  Get Request Response  /user/1  timeout=10s
    Click  #funnyButton
    Wait Until  ${promise1}  ${promise2}

**Comment by idxn** [comment]
That's a good solution. Thanks a lot @mkorpela

**Comment by mkorpela** [comment]
Yes. It should return the results or raise exceptions if a promised keyword fails.

**Comment by mkorpela** [comment]
@all-contributors Please add idxn for ideas

**Comment by mkorpela** [comment]
Future + thread pool as an implementation https://docs.python.org/3/library/concurrent.futures.html ?

**Comment by mkorpela** [comment]
- [ ] Logging from threads should happen only at `Wait for` -keyword
- [ ] Support for all keywords in Browser library (figure out argument conversion).

**Comment by mkorpela** [comment]
https://docs.python.org/3/library/threading.html#threading.get_ident

**Comment by mkorpela** [comment]
Related to https://github.com/robotframework/robotframework/issues/1791

**Comment by mkorpela** [comment]
We discussed with team that we are now first targeting few specific keywords for waiting on background.

**Comment by mkorpela** [comment]
Raising error if unwaited promises at the end of suite / test? Wait for all keyword.

**Comment by mkorpela** [comment]
@idxn Version 0.9.0 now contains promise keywords. Could you test if they work for you?

**Comment by xylix** [comment]
After merging #158 we now have `Wait For Request` and `Wait For Response` keywords. For example use see https://github.com/MarketSquare/robotframework-browser/blob/master/atest/test/03_Waiting/wait_for_http.robot

**Comment by idxn** [comment]
@mkorpela @xylix It really works for me. Thanks a bunch 👍

**Comment by xylix** [comment]
I'll just close this issue off then, let's create new issues for future needs related to this.
