### ISSUE TITLE
Allow reusing already authenticated contexts when opening a new context

### ISSUE THREAD

**Issue by msirkka** [MarketSquare/robotframework-browser#1030]
It would be very useful if it would be possible to reuse already authenticated contexts when opening new Browser contexts. As described in https://playwright.dev/docs/auth/#reuse-authentication-state, this would enable creating login once - run multiple tests scenarios.

**Comment by aaltat** [comment]
@all-contributors please add @msirkka for Ideas & Planning

**Comment by Snooz82** [comment]
@msirkka 
What is it that you can not just use the same context?

You can open a Browser, open a Context and the reuse that Context all the time...

**Comment by msirkka** [comment]
@Snooz82 Sure I can, but in my case I'd like to get authentication state from Context A when creating Context B, which would have different options than Context A. This way I would not need to relogin after creating Context B.

**Comment by aaltat** [comment]
I think we could provide keywords which allows to save the information. But where to save is good question.
1) We could serialize the context to a disk 
If we save information to disk, it will allow usage between test runs. Which could be handy in test case development. The down side is that it is saved to disk, which is a security concern. 
2) Only in memory
This would meet @msirkka need, but would lack the saving information between test runs. 

Third option would be to allow users to decide, but I would rather avoid complexity (in code and for from users)

**Comment by aaltat** [comment]
Decided to go with saving content to a file. It allows more possibilities, but there are also more risks because it can leak many things and also it might not work in all the cases as wanted.
