### ISSUE TITLE
Lingering node processes when running in Python

### ISSUE THREAD

**Issue by osrjv** [MarketSquare/robotframework-browser#1033]
**Describe the bug**
When using the library in pure Python, without a Robot Framework execution, the library does not close its node processes.

All automatic clean-up is currently handled with Robot Framework listener methods, including killing the spawned subprocess on `close()`. This however does not happen inside Python, and this is not obvious to users (and the API isn't documented AFAIK).

**To Reproduce**

Naive implementation:
```python
import Browser

try:
    browser = Browser.Browser()
    browser.new_browser()
    # Do stuff
finally:
    browser.close_browser()
```

Working implementation:
```python
import Browser

try:
    browser = Browser.Browser()
    browser.new_browser()
    # Do stuff
finally:
    browser.playwright.close()
```

**Expected behavior**
I think the library should register an `atexit` function (or similar) to ensure the spawned node process is killed when the Python process exits.

**Desktop (please complete the following information):**
 - OS: All
 - Browser: All
 - Version: 5.0.0

**Comment by osrjv** [comment]
I can also make a PR for this if you think this should be fixed.

**Comment by aaltat** [comment]
I agree that this is bug and using `atexit` should like a good option to go.

**Comment by aaltat** [comment]
@all-contributors please add @osrjv for code
