### ISSUE TITLE
Access adjacent sibling of an element fails

### ISSUE THREAD

**Issue by mickey06** [MarketSquare/robotframework-browser#1041]
**trying to access adjacent sibling fails with "Error: No element handle found with id `element`."**

Link to failing [code](https://gist.github.com/mickey06/9f2b7b087d5048faef555e3868c9433b) 

Pip freeze ->
appdirs==1.4.4
attrs==20.3.0
Authlib==0.15.3
backports.cached-property==1.0.1
beautifulsoup4==4.9.3
cached-property==1.5.2
certifi==2020.12.5
cffi==1.14.5
chardet==3.0.4
click==7.1.2
cryptography==3.4.7
decorator==5.0.7
defusedxml==0.7.1
dnspython==2.1.0
docutils==0.17
et-xmlfile==1.0.1
exchangelib==3.3.2
fpdf2==2.3.2
furl==2.1.2
graphviz==0.13.2
grpcio==1.37.1
grpcio-tools==1.37.1
idna==2.10
isodate==0.6.0
jsonpath-ng==1.5.2
jsonschema==3.2.0
lxml==4.6.3
mss==6.1.0
netsuitesdk==1.20.0
notifiers==1.2.1
ntlm-auth==1.5.0
oauthlib==3.1.0
openpyxl==3.0.7
orderedmultidict==1.0.1
overrides==6.1.0
pdfminer.six==20201018
Pillow==8.2.0
ply==3.11
protobuf==3.17.0
pycparser==2.20
Pygments==2.8.1
pynput-robocorp-fork==2.0.0
pyobjc-core==6.2.2
pyobjc-framework-Cocoa==6.2.2
pyobjc-framework-Quartz==6.2.2
PyPDF2==1.26.0
pyperclip==1.8.2
pyrsistent==0.17.3
PySocks==1.7.1
pytz==2021.1
requests==2.25.1
requests-file==1.5.1
requests-ntlm==1.1.0
requests-oauthlib==1.3.0
requests-toolbelt==0.9.1
rfc3987==1.3.8
robotframework==4.0.3
robotframework-assertion-engine==0.0.6
robotframework-browser==5.0.0
robotframework-pythonlibcore==2.2.1
robotframework-requests==0.7.2
robotframework-seleniumlibrary==5.1.3
robotframework-seleniumtestability==1.1.0
rpaframework==9.5.0
rpaframework-core==6.2.0
rpaframework-pdf==0.5.0
selenium==3.141.0
simple-salesforce==1.11.1
six==1.15.0
sortedcontainers==2.3.0
soupsieve==2.2.1
tqdm==4.60.0
tweepy==3.10.0
typing-extensions==3.7.4.3
typing-utils==0.1.0
tzdata==2021.1
tzlocal==2.1
urllib3==1.26.4
webdrivermanager==0.10.0
wrapt==1.12.1
xlrd==2.0.1
xlutils==2.0.0
xlwt==1.3.0
zeep==4.0.0

**Comment by aaltat** [comment]
Ah, now I see where the bug is. You are using keyword like:
```
${text}    Get Text    element=${ref} >> //header
```
But it should be used like: 
```
${text}    Get Text    ${ref} >> //header
```
The `Get Element` keyword return value already starts with string  `element=` and it is not needed to repeat it. 

Because all is working as expected, I am going to close the issue.
