### ISSUE TITLE
httpCredentials with $variable is not working

### ISSUE THREAD

**Issue by adrian-evo** [MarketSquare/robotframework-browser#1046]
When using the following code, the credential variables are not resolved and the variable name is used instead of actual value:

```
    ${user}    Set Variable    myuser
    ${pw}    Set Variable    mypassword
    New Browser    chromium  headless=false
    New Context    httpCredentials={'username': '$user', 'password': '$pw'}

```

I tested this by temporarily disabling _mask_credentials function.

![image](https://user-images.githubusercontent.com/19324942/120795675-77010100-c542-11eb-8b10-d79445f86bad.png)

**Comment by aaltat** [comment]
Credentials are also hidden from the logs, is there something else that would indicate that credentials are not working correctly?

**Comment by adrian-evo** [comment]
For the site I am testing it is not working unless I am using old way, i.e. httpCredentials={'username': '${user}', 'password': '${pw}'}

That's why I disabled the _mask_credentials function from playwright_state.py file, so that to see what's wrong. In this way you can see that actually the password used by New Context is literally '$pw' and not 'mypassword' as expected.

**Comment by aaltat** [comment]
I looked the code and could not see anything obvious.  But there is hole in our test and they do not ensure that we actually pass the argument value to Playwright side. Need to investigate this more deeply.

**Comment by aaltat** [comment]
@all-contributors please add @adrian-evo  for code bugs

**Comment by aaltat** [comment]
Found the bug, good catch.
