### ISSUE TITLE
Playwright state KW improvements

### ISSUE THREAD

**Issue by xylix** [MarketSquare/robotframework-browser#105]
progress in #115 

- [x] Rename Keywords starting New _ to Create _
- [x] `Switch Browser`, `Switch Context` and rename page KW to `Switch Page`
- [x] test that switches error correctly when no available target to switch exists
- Assert in tests that browser / context has actually switched correctly
  - [x] Create some pages in browser 0 and 1, and switch and see that active page is different
  - [x] Create some pages in context's 0 and 1 and switch and see that active page is different
- [x] Let Switch Browser and Switch Context remember what page was active in them before switch happened
- [ ] ~~Support giving an alias when creating [Browsers, Contexts, Pages] and switching by alias. Print alias in error messages when existing~~ moved to #116
- Closing objects
  - [x] Close Browser actually remove browser from open browser list
  - [x] Close All Browsers KW
  - [x] Close Page
  - [x] Close Context

- [x] `New Browser`, `New Page` etc shall return the index of the newly created object
- [x] `Switch Browser` `Switch Page` shall return the index of the current Object before the switch

**Comment by Snooz82** [comment]
- [ ] `New Browser`, `New Page` etc shall return the index of the newly created object

- [ ] `Switch Browser` `Switch Page` shall return the index of the current Object before the switch
