### ISSUE TITLE
rfbrowser show-trace can't find zipfile

### ISSUE THREAD

**Issue by emakaay** [MarketSquare/robotframework-browser#1085]
**Describe the bug**
I created a trace zip file using running a few test in Ride. I checked the trace.zip exists and contains files. That all checks out.
When running "rfbrowser show-trace -F <location> of file it keeps telling me that the file does not exists (FileNotFoundError).
I'm a 100 procent sure the file does exists. To check this I copied the argument to rfbrowser (the File parameter) and pasted that in TotalCommander. TotalCommander navigated directory to the File. This is a check to see that a given filename exists and can be found.

Any idea how to fix this ? Or how to start the trace by directly accessing the playwright component ?

**To Reproduce**
1. run "rfbrowser init" , to ensure all libraries are up-to-date
2. Run test that has parameter "tracing=trace.zip" on the New Context keyword used
3. run "rfbrowser show-trace -F \<complete path to trace.zip\>" in my case the file was: "c:\users\<userid>\AppData\Local\Temp\RIDEozn6tf.d\trace.zip" Notice that are NO spaces which could throw off the rfbrowser command.
4. Get the error FileNotFoundError

**Expected behavior**
trace contained in zipfile is shown

**Screenshots**
- na

**Desktop (please complete the following information):**
 - Windows 8
 - Browser 5.10
 - Ride 1.7.4.2
 - robotframework 4.0.3
 - Node 14
-  Python 3.7.3 (64 bits)

**Comment by aaltat** [comment]
In Python the Windows folder separator is an escape caracter

**Comment by emakaay** [comment]
Ok I didn't think about that. But still after adding extra backspaces it doesn't work. Note I moved the zip file

```
C:\Python37\Lib\site-packages\Browser>rfbrowser show-trace --file c:/ws/trace.zip
Opening file: c:/ws/trace.zip
Traceback (most recent call last):
  File "c:\python37\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\python37\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Python37\Scripts\rfbrowser.exe\__main__.py", line 7, in <module>
  File "c:\python37\lib\site-packages\Browser\entry.py", line 150, in run
    show_trace(args.file)
  File "c:\python37\lib\site-packages\Browser\entry.py", line 98, in show_trace
    subprocess.run(trace_arguments)
  File "c:\python37\lib\subprocess.py", line 472, in run
    with Popen(*popenargs, **kwargs) as process:
  File "c:\python37\lib\subprocess.py", line 775, in __init__
    restore_signals, start_new_session)
  File "c:\python37\lib\subprocess.py", line 1178, in _execute_child
    startupinfo)
FileNotFoundError: [WinError 2] Het systeem kan het opgegeven bestand niet vinden

C:\Python37\Lib\site-packages\Browser>7z t c:/ws/trace.zip

7-Zip 19.00 (x64) : Copyright (c) 1999-2018 Igor Pavlov : 2019-02-21

Scanning the drive for archives:
1 file, 2394304 bytes (2339 KiB)

Testing archive: c:\ws\trace.zip
--
Path = c:\ws\trace.zip
Type = zip
Physical Size = 2394304

Everything is Ok

Files: 693
Size:       7121482
Compressed: 2394304

C:\Python37\Lib\site-packages\Browser>7z t c:\\ws\\trace.zip

7-Zip 19.00 (x64) : Copyright (c) 1999-2018 Igor Pavlov : 2019-02-21

Scanning the drive for archives:
1 file, 2394304 bytes (2339 KiB)

Testing archive: c:\\ws\\trace.zip
--
Path = c:\\ws\\trace.zip
Type = zip
Physical Size = 2394304

Everything is Ok

Files: 693
Size:       7121482
Compressed: 2394304

C:\Python37\Lib\site-packages\Browser>rfbrowser show-trace --file c:\\ws\\trace.zip
Opening file: c:\\ws\\trace.zip
Traceback (most recent call last):
  File "c:\python37\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\python37\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Python37\Scripts\rfbrowser.exe\__main__.py", line 7, in <module>
  File "c:\python37\lib\site-packages\Browser\entry.py", line 150, in run
    show_trace(args.file)
  File "c:\python37\lib\site-packages\Browser\entry.py", line 98, in show_trace
    subprocess.run(trace_arguments)
  File "c:\python37\lib\subprocess.py", line 472, in run
    with Popen(*popenargs, **kwargs) as process:
  File "c:\python37\lib\subprocess.py", line 775, in __init__
    restore_signals, start_new_session)
  File "c:\python37\lib\subprocess.py", line 1178, in _execute_child
    startupinfo)
FileNotFoundError: [WinError 2] Het systeem kan het opgegeven bestand niet vinden
```

**Comment by aaltat** [comment]
I also can reproduce the issue. and it looks like there is bug in the windows OS.

**Comment by aaltat** [comment]
I think in Windows OS, command needs a shell. Could you also try it, by changing this [line](https://github.com/MarketSquare/robotframework-browser/blob/master/Browser/entry.py#L98) to `subprocess.run(trace_arguments, shell=True)`

**Comment by aaltat** [comment]
@all-contributors please add @emakaay  for bugs

**Comment by emakaay** [comment]
Hello Tatu,

After adding 'shell=True' I get the following error:

C:\Python37\Lib\site-packages\Browser>rfbrowser show-trace --file
c:/ws/trace.zip
Opening file: c:/ws/trace.zip
Traceback (most recent call last):
  File "C:\Python37\Lib\site-packages\Browser\playwright.py", line 29, in
<module>
    from .base import LibraryComponent
ModuleNotFoundError: No module named '__main__.base'; '__main__' is not a
package

C:\Python37\Lib\site-packages\Browser>rfbrowser show-trace --file
c:\\ws\\trace.zip
Opening file: c:\\ws\\trace.zip
Traceback (most recent call last):
  File "C:\Python37\Lib\site-packages\Browser\playwright.py", line 29, in
<module>
    from .base import LibraryComponent
ModuleNotFoundError: No module named '__main__.base'; '__main__' is not a
package

But the zip file isn't a problem anymore 🤣

**Comment by aaltat** [comment]
Interesting. I did not see that error in my windows, athough I am using Python 3.9. I need to debug it further at some later point.

**Comment by aaltat** [comment]
Do you see the error if you run `rfbrowser --help` command?

**Comment by emakaay** [comment]
When running 'rfbrowser --help' I don't get this error.

**Comment by emakaay** [comment]
That's fine. If I can help in any way .. Just ask. But this import
statement is looking strange to me.

I don't understand what .base refers to

**Comment by aaltat** [comment]
Then it could be that we set PATH inside of the command .

**Comment by emakaay** [comment]
Maybe. But I can't find the code were the PATH is set explicitly

**Comment by aaltat** [comment]
Base refers to this folder https://github.com/MarketSquare/robotframework-browser/tree/master/Browser/base

And library manipulates the environment in here https://github.com/MarketSquare/robotframework-browser/blob/master/Browser/entry.py#L91

**Comment by aaltat** [comment]
Most likely using the `env` argument in the `run` will resolve issue.

**Comment by emakaay** [comment]
changed function 'show_trace' from file entry.py to:

def show_trace(file: str):
    print(f"Opening file: {file}")
    playwright = INSTALLATION_DIR / "node_modules" / "playwright"
    local_browsers = playwright / ".local-browsers"
    # os.environ["PLAYWRIGHT_BROWSERS_PATH"] = str(local_browsers)
    environment = os.environ.copy()
    environment['PLAYWRIGHT_BROWSERS_PATH'] = str(local_browsers)
    trace_arguments = [
        "npx",
        "playwright",
        "show-trace",
        file,
    ]
    subprocess.run(trace_arguments, env=environment, shell=True)


and run again (rfbrowser show-trace -F c:\ws\trace.zip) and got:
c:\Python37\Lib\site-packages\Browser>rfbrowser show-trace -F
c:\ws\trace.zip
Opening file: c:\ws\trace.zip
Traceback (most recent call last):
  File "C:\Python37\Lib\site-packages\Browser\playwright.py", line 29, in
<module>
    from .base import LibraryComponent
ModuleNotFoundError: No module named '__main__.base'; '__main__' is not a
package

Note: also tried without copying the current environment, but then i
couldn't find the npx program


From the commandline I get the same error:

c:\Python37\Lib\site-packages\Browser>set
PLAYWRIGHT_BROWSERS_PATH=c:\Python37\Lib\site-packages\Browser\wrapper\node_modules\playwright\.local-browsers

c:\Python37\Lib\site-packages\Browser>npx playwright show-trace
c:\ws\trace.zip
Traceback (most recent call last):
  File "C:\Python37\Lib\site-packages\Browser\playwright.py", line 29, in
<module>
    from .base import LibraryComponent
ModuleNotFoundError: No module named '__main__.base'; '__main__' is not a
package

**Comment by aaltat** [comment]
Interesting, I can not reproduce the problem. Using the shell=True fixes the problem and passing own enviroment

**Comment by aaltat** [comment]
There definitely was a bug, which is now fixed in master. I do not quite understand why that does not fix the problem in your side. I will push out a new release and if there is still a problem, then we need to take another look.

**Comment by aaltat** [comment]
New release, 5.1.1 is in PyPi

**Comment by emakaay** [comment]
Thanks Tatu,
I just installed it. And it fixed the problem.
I guess that we had some code difference... Perhaps.

Glad it works now!

**Comment by aaltat** [comment]
Good to hear that it works and thank you for reporting the problem.
