### ISSUE TITLE
Suggest the way to change timeout when timeout occurs

### ISSUE THREAD

**Issue by mkorpela** [MarketSquare/robotframework-browser#1105]
**Is your feature request related to a problem? Please describe.**

People sometimes get timeouts and don't know how to handle them.

**Describe the solution you'd like**

When a timeout occurs the logged messages should suggest ways to extent the timeout in question.

**Additional context**

Something like:
"Timeout 10s gone. To extent the timeout use `Set Browser Timeout` keyword or set default timeout in Browser library import.

**Comment by cmin764** [comment]
I was looking for the source of the message and is coming from one of these places (`egrep -rni "Timeout .+ exceeded\." *`):
```
537 node_modules/playwright-core/lib/server/progress.js:96:    const timeoutError = new _errors.TimeoutError(`Timeout ${this._timeout}ms exceeded.`);

538 node_modules/playwright-core/lib/client/frame.js:128:    waiter.rejectOnTimeout(timeout, `Timeout ${timeout}ms exceeded.`);
```

**Comment by JaPyR** [comment]
Option to silent such tips would be useful especially if more tips would be added in future. For me it's just additional lines on the screen which is a little bit annoying when running tests after some significant changes.
