### ISSUE TITLE
Message formatting in "Wait For Elements State" uses the given timeout even when it is None

### ISSUE THREAD

**Issue by ssallmen** [MarketSquare/robotframework-browser#1110]
**Description**
When "Wait For Elements State" keyword is called with timeout argument set as None, and message argument containing formatter for timeout (i.e. {timeout}), the message for raised AssertionError is formatted with the timeout being None, instead of using the default timeout, which is used for the actual timeout for wait.

**To Reproduce**
```
from Browser import Browser
browser = Browser()
browser.new_browser()
browser.set_browser_timeout('20s')
browser.new_page('https://robotframework.org/')
browser.wait_for_elements_state('//not-found-locator', timeout=None, message='Did not find {selector} in {timeout}')
```

**Actual behavior**
"AssertionError: Did not find //not-found-locator in None"

**Expected behavior**
"AssertionError: Did not find //not-found-locator in 20s" (or 20000ms)

**Versions**
robotframework: 4.0.3
robotframework-assertion-engine: 0.0.6
robotframework-browser: 5.1.1
Python: 3.8.10

**Comment by aaltat** [comment]
@all-contributors please add @ssallmen  for bugs

**Comment by aaltat** [comment]
Also changes Wait For Function keyword with same bug.
