### ISSUE TITLE
Some mobile devices fail to start the browser

### ISSUE THREAD

**Issue by anton264** [MarketSquare/robotframework-browser#1116]
**Describe the bug**
Running `New Context` with some, but not all devices fails.

**To Reproduce**
```
*** Settings ***
Library     Browser

*** Test Cases ***
Works
    ${device}=    Get Device    Galaxy S9+
    New Browser
    New Context    &{device}    acceptDownloads=True

Fails
    ${device}=    Get Device    iPhone 11
    New Browser
    New Context    &{device}    acceptDownloads=True

```

**Expected behavior**
Both devices will work

**Additional context**
Some devices in https://github.com/microsoft/playwright/blob/master/src/server/deviceDescriptorsSource.json has the attribute screen as well as viewport. Browser can not handle this attribute.

**Comment by aaltat** [comment]
Could you tell how it doesn't work?

**Comment by anton264** [comment]
In the case of the iPhone 11 new context fails:
`Keyword 'Browser.New Context' got unexpected named argument 'screen'.`

**Comment by tatu-aalto** [comment]
Ah, now I see where the fault is. Yes, looks like we have bug in our side.

**Comment by aaltat** [comment]
Ah, now I see where the fault is. Yes, looks like we have bug in our side.

**Comment by aaltat** [comment]
As a workaround, you could remove the key from the dictionary which causes the problem.

**Comment by mkorpela** [comment]
FIxed in next version
