### ISSUE TITLE
Improved troubleshooting output on `rfbrowser init` failure

### ISSUE THREAD

**Issue by xylix** [MarketSquare/robotframework-browser#1117]
**Is your feature request related to a problem? Please describe.**

Sometimes there are missing details in bug reports.

**Describe the solution you'd like**
- [ ] add output of `pip freeze` to output of rfbrowser init in error cases
- [ ] add a tree or other representation of contents of Browser/wrapper/node_modules in error cases
- [ ] ^put the above and other detailed debugging information into an `rfbrowser-install-failure-log.log` file or such

**Comment by aaltat** [comment]
#1485 is good example why we should do this.

**Comment by aaltat** [comment]
Running: `npx playwright info` would be useful too.
