### ISSUE TITLE
Permission denied when install language package on docker images.

### ISSUE THREAD

**Issue by nixuewei** [MarketSquare/robotframework-browser#1124]
**Is your feature request related to a problem? Please describe.**
Permission denied when install language package on docker images.

**Describe the solution you'd like**
I just want to test taiwan and chinese webpage. and i need to install the language package on docker. but i failed to install due to Permission denied and I don't know the pwuser or root user password. how to do that. thanks
pwuser@d285bd6e3701:/$ apt-get install  language-pack-zh-han*
E: Could not open lock file /var/lib/dpkg/lock-frontend - open (13: Permission denied)
E: Unable to acquire the dpkg frontend lock (/var/lib/dpkg/lock-frontend), are you root?
marketsquare/robotframework-browser             latest           932f598ed77a   5 days ago     1.92GB

**Describe alternatives you've considered**

**Additional context**

**Comment by mkorpela** [comment]
Dockerfiles produce use non root user as default.
You could add your installations with ``USER root``
https://github.com/MarketSquare/robotframework-browser/blob/master/atest/docker/Dockerfile.latest_release#L6
Please see docker project documentations for more information on this.
Closing this as this is not a Browser library issue, and more about how to use Dockerfiles.
