### ISSUE TITLE
Add information about playwright version to documentation

### ISSUE THREAD

**Issue by JaPyR** [MarketSquare/robotframework-browser#1126]
Currently it's hard to tell which version of playwright come with Browser library without checking release history or yarn.lock file. 

Additional section in Readme (or separate file) would be really helpful.

**Comment by aaltat** [comment]
Yes, this is good idea. We should mention this also in the release notes

**Comment by aaltat** [comment]
Because PW version may change between releases, it most cleanest to add the version in the release notes.

**Comment by JaPyR** [comment]
> 
> 
> Because PW version may change between releases, it most cleanest to add the version in the release notes.

Isn't it better to pin specif version for reproducible builds or to use tilde version instead of caret range?

**Comment by aaltat** [comment]
Yes, there is a separate issue about it #591
