### ISSUE TITLE
Assertion should fail if expected value is given without operator

### ISSUE THREAD

**Issue by pekkaklarck** [MarketSquare/robotframework-browser#1142]
For example, this passes always:

    Get Title    assertion_expected=Login Page

This example is from a student in my training course who's new to Browser. I know the usage is wrong, assertion operator is missing, but it actually looks like it could work. Would definitely be better if there was a failure if `assertion_expected is not None and assertion_operator is None`.

Example in the keyword documentation would obviously help with correct usage as well.

**Comment by mkorpela** [comment]
@all-contributors please add @pekkaklarck for code bugs
