### ISSUE TITLE
Wait For URL

### ISSUE THREAD

**Issue by emilszymecki** [MarketSquare/robotframework-browser#1150]
Work for me

module.js
```
async function wait_For_URL(page, args) {
  await page.waitForURL(args[0],{waitUntil: args[1]});
}

exports.__esModule = true;
exports.wait_For_URL = wait_For_URL;
```

```
*** Settings ***
Documentation     Playwright template.
Library           RPA.Browser.Playwright    jsextension=${CURDIR}/module.js
*** Keywords ***

Starting a browser with a page
    New Browser    chromium    headless=false
    New Context    viewport={'width': 1920, 'height': 1080}
    New Page       https://marketsquare.github.io/robotframework-browser/Browser.html
    Click    \#keyword-shortcuts-container > li:nth-child(12) > a
    Wait For URL    https://marketsquare.github.io/robotframework-browser/Browser.html#Download    networkidle
    #Wait For URL   **/Browser.html*      #with glob pattern

*** Tasks ***
Minimal task
    Starting a browser with a page
```

https://playwright.dev/docs/api/class-page#page-wait-for-url

**Comment by aaltat** [comment]
I don't understand, could you explain more what you want?

**Comment by mkorpela** [comment]
How is this different from `Wait for Navigation` ?

**Comment by emilszymecki** [comment]
`New Browser    chromium    headless=false
    New Context    viewport={'width': 1920, 'height': 1080}
    New Page       https://marketsquare.github.io/robotframework-browser/Browser.html
    Click    \#keyword-shortcuts-container > li:nth-child(12) > a
    #Wait For URL    https://marketsquare.github.io/robotframework-browser/Browser.html#Download    networkidle <- work!!!
    #Wait For URL   **/Browser.html*      #with glob pattern <- work!!!
    #Wait For Navigation    url=https://marketsquare.github.io/robotframework-browser/Browser.html#Download     #<- doesn't work
    #Wait For Navigation   url=**/Browser.html*      #with glob pattern <- doesn't work
    #Wait For Navigation    url=/https:\/\/marketsquare\.github\.io\/robotframework-browser\/Browser.html#Download/  #<- doesn't work
    #Wait For Navigation    url=/https:\/\/marketsquare\.github\.io\/robotframework-browser\/Browser.html#Download/    regex=True  #<- doesn't work`

I don't understand why my code "Wait For URL" work for me after keyword Click but build-in Wait For Navigation not work. 
Maybe you better show me what I'm doing wrong

**Comment by aaltat** [comment]
Have yo seen our acceptance tests: https://github.com/MarketSquare/robotframework-browser/blob/master/atest/test/03_Waiting/wait_for_http.robot#L38

**Comment by mkorpela** [comment]
I think changing hash / fragment is not a navigation event.

**Comment by aaltat** [comment]
Due inactivity, I am going to close this issue. Please comment if you feel that this is problem in library side.

**Comment by lgaitan** [comment]
I've faced the same issue.
Indeed, the change of the `fragment` part of the url does not trigger a navigation event.

Maybe this is something that we could add to the documentation to make it clear?

Thanks.

**Comment by aaltat** [comment]
Yes, we should definitely mention that.  Will do it as part of is #1214

**Comment by aaltat** [comment]
Also it possible to add keyword or enhance existing one to use PW [waitForURL](https://playwright.dev/docs/api/class-page/#page-wait-for-url)

**Comment by tomekTieto** [comment]
wait for url would be really useful to be implemented in Browser library
