### ISSUE TITLE
Assertion engine 0.1.0 breaks keyword Get Element State

### ISSUE THREAD

**Issue by sijet-dot** [MarketSquare/robotframework-browser#1152]
**Describe the bug**
#1142 was fixed by updating dependencies with `robotframework-assertion-engine >= 0.1.0` but this appears to have the side effect of breaking the keyword `Get Element State` when not assigning values to the arguments `assertion_operator` and `assertion_expected`. When not assigned, this keyword defaults their values to `assertion_operator=None` and `assertion_expected=True`.

In this case, v0.1.0 of the assertion engine will return the error message "It is not possible perform assertion when operator is None type(nonetype)" when using that keyword.

**To Reproduce**
1. Use keyword like
```Robot Framework
Get Element State    div#myDivId    visible
```
2. Receive error message in log file.

**Expected behavior**
Element's state is returned as a `bool` depending on the returned `state` provided to the keyword.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: chrome
 - Version: 91.0.4472.124

**Additional Context**
I am using this inside of a Robocorp robot which I have configured to use `v5.1.2` of Browser, which is also puzzling as `v5.1.2` of Browser should have used `v0.0.6` of the assertion engine, but regardless, it led me to detect this bug.

**Comment by mkorpela** [comment]
@sijet-dot thank you for the information.

**Comment by mkorpela** [comment]
We could fix this by defaulting to equals in get_element_state https://github.com/MarketSquare/robotframework-browser/blob/e88e103fc18799c8dedb9976817e4bdf46676b75/Browser/keywords/getters.py#L887

same bug could now be in many other places..

**Comment by mkorpela** [comment]
Actually get_element_state has to pass None as expected to verify if no assertion.

**Comment by aaltat** [comment]
This somewhat backwards incommunicable, because it used work in different way. But it is very minor use case and I am happy to change it.
