### ISSUE TITLE
Setting Webkit locale works differently from Chrome and Firefox 

### ISSUE THREAD

**Issue by apple-blossom** [MarketSquare/robotframework-browser#1172]
**Describe the bug**
Setting Browser context locale works differently for webkit then for other browsers. From screenshot you can see that locale is DE in firefox, but in Webkit it switches back to default (EN) after running the 1st test. I am creating new browser and new context in suite folder setup in init.robot (see screenshots)

**Screenshots**
![Screenshot 2021-07-15 181347](https://user-images.githubusercontent.com/16157583/126609701-94f4a43c-411e-4c09-90e8-6f1334f82ac5.png)
![Screenshot 2021-07-15 181647](https://user-images.githubusercontent.com/16157583/126609706-54ca465d-f9e0-4910-b043-da4554614766.png)
![Screenshot 2021-07-15 181518](https://user-images.githubusercontent.com/16157583/126608521-3ca39262-45ba-4ea7-a194-31fffd0f6c9a.png)
![Screenshot 2021-07-15 181543](https://user-images.githubusercontent.com/16157583/126608529-8e1b25ab-05a9-4b3c-b930-8d48b83aa74a.png)

**To Reproduce**
1. Create new browser and new context instance in folder test suite setup (__init__.robot file in test suite folder)
2. Set browser as Weblit
3. Set locale to other, than default (de-DE in my case)
4. Create new page in each test file suite setup
5. Run the tests
6. Locale in webkit works for the 1st test, then it returns back to default (maybe context is closing, but it works fine for firefox and chrome)

**Expected behavior**
Locale stays de-DE for the whole test run

**Desktop (please complete the following information):**
 - OS: WIndows
 - Browser Webkit
 - Version : robotframework-browser==4.2.0, tried with latest version too

**Comment by aaltat** [comment]
I have seen few similar reports in other community channels. This library doesn't have code that would handle different browsers in different in this case. Basically I see three choices 
Basically I see three choices. 
1) There is a bug in your app and it's doesn't work for WebKit. 
2) There is bug in Playwright side
3) Bug in Webkit side.

**Comment by aaltat** [comment]
Because this is most likely problem in downstream, I am going to close this issue. If you feel differently, please tell why you think so.
