### ISSUE TITLE
Chrome.json download link is broken

### ISSUE THREAD

**Issue by AllanMedeiros** [MarketSquare/robotframework-browser#1179]
**Describe the bug**
Follow this file docker file instructions:
https://github.com/MarketSquare/robotframework-browser/blob/master/atest/docker/README.md#robotframework-browser-dockerfiles

But the download link to get detailed instructions and the chrome.json is broken.

**To Reproduce**
1. Go to file https://github.com/MarketSquare/robotframework-browser/blob/master/atest/docker/README.md#robotframework-browser-dockerfiles
2. Click on **Explanations and the chrome.json can be found here** link.
3. See 404 error

**Expected behavior**
Should point to a valid page.

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by aaltat** [comment]
@all-contributors please add @AllanMedeiros  for bugs

**Comment by aaltat** [comment]
It seems PW instructions have changed and it does not anymore talk about `chrome.json` files, see https://playwright.dev/docs/docker#end-to-end-tests

**Comment by xylix** [comment]
I'm pretty sure the chrome.json was replaced by https://github.com/microsoft/playwright/blob/master/docs/src/docker.md#crawling-and-scraping this seccomp_profile.json thing. Playwright repo's commit 69127ad8d314f7350291b81b7c45a3664f2784e3 seems to make it look like that at least. We should update the docker docs to reflect this new info and then we can close this.

**Comment by xylix** [comment]
Fixed in https://github.com/MarketSquare/robotframework-browser/commit/f8d310aef176ae9f0b931829688006067e7590fa
