### ISSUE TITLE
Write example to keyword documentation

### ISSUE THREAD

**Issue by aaltat** [MarketSquare/robotframework-browser#1184]
**Describe the bug**
Many keywords are missing example how to actually use the keyword. We should go trough each keyword and write them examples and same go read the docs and see does it make sense. 

Also adding links to assertion engine would be good idea. 

**To Reproduce**
Read docs like https://marketsquare.github.io/robotframework-browser/Browser.html#Select%20Options%20By

**Expected behavior**
Better docs with examples.

**Comment by mkorpela** [comment]
Done
