### ISSUE TITLE
Enhance run on failure functionality to accept arguments

### ISSUE THREAD

**Issue by aaltat** [MarketSquare/robotframework-browser#1215]
**Is your feature request related to a problem? Please describe.**
Now run on failure functionality supports keywords which does not need arguments. It would be better to add support for arguments in the keyword. Example it is possible to use `Take Screenshot` keyword but it is not possible to provide arguments to keyword. It would be nice to enhance functionality to support arguments

**Describe the solution you'd like**
There was discussion in the slack about separator, `run_on_failure=Take Screenshot \ yourpath/foo/bar.png` or perhaps `run_on_failure=Take Screenshot|-|yourpath/foo/bar.png` could work nicely. Other options?

**Comment by mkorpela** [comment]
This is by the way there already as a PR https://github.com/MarketSquare/robotframework-browser/pull/571

**Comment by aaltat** [comment]
We actually support arguments: https://github.com/MarketSquare/robotframework-browser/blob/main/Browser/browser.py#L866-L875  but only for https://marketsquare.github.io/robotframework-browser/Browser.html#Register%20Keyword%20To%20Run%20On%20Failure and not in library import.

**Comment by aaltat** [comment]
In Slack discussion people seemed to more pleased with space, backslash space syntax ` \ `. Example `keyword \ arg1 \ arg`. So lets go with that.

**Comment by mkorpela** [comment]
Done in #1242
