### ISSUE TITLE
Strict mode

### ISSUE THREAD

**Issue by emakaay** [MarketSquare/robotframework-browser#1233]
**Is your feature request related to a problem? Please describe.**
Some test fail because testers do not known that used selector, select more then one element on the page. Possibly because they are hidden

**Describe the solution you'd like**
Playwright 1.14.0 introduces concept of "strict mode" (see: https://github.com/microsoft/playwright/blob/master/docs/src/release-notes-python.md)

**Describe alternatives you've considered**
Will the robotframework-browser support this construct ?

**Additional context**
not applicable

**Comment by aaltat** [comment]
How you would like to control the feature?

**Comment by emakaay** [comment]
That's a good question.

For me it could be a setting on initialization if a new browser object.

Which in turn, turns all requests into strict (without adding additional
options in the robot code)

But maybe other users have more fine grained wishes.

Greets

**Comment by aaltat** [comment]
Well, I see three different and common options to control it.
1) Library import controls the default behaviour.
2) There is new keyword which can change the default behaviour.
3) Default behaviour can be changed in each keyword by an new argument.

**Comment by emakaay** [comment]
I agree, these are the most common chosen  solutions...
Starting with least impact, Ending with most impact in my opinion.

For me: the first option would suffice for now...

**Comment by mkorpela** [comment]
I think we should enable strict mode by default.

**Comment by mkorpela** [comment]
It will generate some problems, but every failure with selector finding more than one element can be fixed.
In the long term enforcing strict mode will spot more errors in tests and is good for all.

**Comment by aaltat** [comment]
I am leaning towards same direction, although it is backwards incomplete change. But I am happy to do so and release 8.0 next.

**Comment by emakaay** [comment]
I think we also need an option to change the default option to the old way
of working.

Otherwise, potentially, a lot of errors can occur without a way to get the
old behavior back.

But I agree that these errors can and should be fixed.

My 2 cents

**Comment by aaltat** [comment]
This also changes drastically some keywords signature.

**Comment by aaltat** [comment]
Decided to go with options 
1. Library import controls the default behaviour.
2. There is new keyword which can change the default behaviour.

**Comment by emakaay** [comment]
Hello Tatu.

Great solution. A all or nothing is fine by me.
I see the code is merged to master, but no new release is created?
When do you think when this is released?
Fingers are itching to test it.

Greets,
Erik

**Comment by aaltat** [comment]
Most likely we will create release early next week. I wanted to give some time to thing about and at least change this one https://github.com/MarketSquare/robotframework-browser/pull/1293

**Comment by emakaay** [comment]
@aaltat 
Thanks for both releases (8.0.0 and 8.0.1). I think this is the first time in my life that I'm the first to download a link. 

I already did some tests and noticed some errors (which I did expect). Now its up to us to fix them!

Thanks for all the great work
