### ISSUE TITLE
Open (Development) Browser as a test development keyword

### ISSUE THREAD

**Issue by mkorpela** [MarketSquare/robotframework-browser#124]
**Is your feature request related to a problem?**
Opening new page has defaults to fast execution (headless and other stuff).
There is a constant need also to open tests in “development mode” (headful, devtools, slowmo etc.) to make test development easy.

**Describe the solution you'd like**
Change open browser defaults to this development mode. Also rename open browser to “Open Development Browser” that explicitly states that now we are running in not so efficent development mode.

**Describe alternatives you've considered**
We could also add just another keyword for this. But then I think that new page and new browser  should work in other situations such as multibrowser testing.

**Comment by Snooz82** [comment]
I would prefer an argument.
`debug_mode=False`

The  this can easily toggled by vars.

**Comment by mkorpela** [comment]
But there are many options that will change when doing development vs when running automation. Headless, Slowmow, Devtools etc.

**Comment by Snooz82** [comment]
Dev tool do not really make sense, because these are overlapping the page and woth pressing F12 you can still open it.

But with debugmode=  you could easily switch your current test case to that uses Open Browser to debug. 

With debugmode on we could also activate the env var PWDEBUG=1 to be able to debug selectors.

**Comment by mkorpela** [comment]
Test / task creation is not an edge case.

**Comment by mkorpela** [comment]
One goal here is to enforce good behaviour. In this case we do not want users to open browser when they could have reused an existing one. `New Page` should be the default for starting a new test session.
`Open Development Browser` should look different and should have different defaults. It should communicate clearly that this should be replaced with `New Page`, `New Browser` and `New Context` where needed.
It should also be very easy to just take `Open Development Browser` into use in places where `New Page` was previously used. To check and debug an existing test / task.

**Comment by mkorpela** [comment]
No
