### ISSUE TITLE
Multiple frame piercing does not work

### ISSUE THREAD

**Issue by mkorpela** [MarketSquare/robotframework-browser#1259]
determineElement was not doing frame piercing correctly.
This is used in:
Take Screenshot,
Execute Javascript,
Wait For Function,
Get Bounding Box

**Comment by aaltat** [comment]
I was thinking same thing when I am doing #1243, but I think it might work for some keywords. I think keywords using [waitUntilElementExists](https://github.com/MarketSquare/robotframework-browser/blob/main/node/playwright-wrapper/playwirght-invoke.ts#L22) frame piercing does not work. For keywords using  [invokePlaywrightMethod](https://github.com/MarketSquare/robotframework-browser/blob/main/node/playwright-wrapper/playwirght-invoke.ts#L72) they might work. 

Also I think it means that element reference does not work for all keywords and I recall seeing that some user have complained this problem in slack.

**Comment by mkorpela** [comment]
https://github.com/MarketSquare/robotframework-browser/pull/1266

**Comment by mkorpela** [comment]
https://github.com/MarketSquare/robotframework-browser/pull/1266
