### ISSUE TITLE
Automatic Closing Level MANUAL: keep open after terminating the test

### ISSUE THREAD

**Issue by 3WlVzK0N** [MarketSquare/robotframework-browser#1263]
**Is your feature request related to a problem? Please describe.**
Currently auto_closing_level=MANUAL keeps the browser open during the test execution.
It might be useful however to keep the window even after finishing the test. 

**Describe the solution you'd like**
``` diff 
- If automatic closing level is MANUAL, nothing is closed automatically during the test execution is ongoing.
+ If automatic closing level is MANUAL, nothing is closed automatically and the browser is kept open even after the test execution is finished.
```

**Describe alternatives you've considered**
Using seleniumLibrary

**Additional context**
This might come in handy in RPA settings where RPA tasks no only require human intervention but where RPA prepares a session for the user.

RPA use case:
I would like to open a browser which opens a website and logs me in so that I can use it for what ever my job is.

**Comment by Snooz82** [comment]
I think this needs to be decided.
I would not do it this way. At least introduce either a new AutoClosingLevel `KEEP` or so or add an argument to New Browser

**Comment by aaltat** [comment]
Let’s add new Enum which doesn’t close anything
