### ISSUE TITLE
Get Element Style or CSS value

### ISSUE THREAD

**Issue by mkorpela** [MarketSquare/robotframework-browser#127]
Can't currently easily access element css values. Should.

- [x] Get Element Style
  - [x] Support for getting dict or specific key
- [x] Assertion syntax support

**Comment by aaltat** [comment]
This gets asked now and then also in the  SL side.

**Comment by mkorpela** [comment]
https://developer.mozilla.org/en-US/docs/Web/API/Window/getComputedStyle

**Comment by xylix** [comment]
Implemented in #af041d2
