### ISSUE TITLE
Get Elements optionally to return unique css selectors

### ISSUE THREAD

**Issue by mkorpela** [MarketSquare/robotframework-browser#1307]
Element Handles can go stale when iterating over them and doing actions that modify the DOM.

I propose we add an argument to optionally return unique css selectors instead of Element Ids.
This should be usable also if DOM is manipulated by some action.
https://marketsquare.github.io/robotframework-browser/Browser.html#Get%20Elements

**Comment by aaltat** [comment]
Is this still valid, because we have mostly moved using Playwrights Locators?

**Comment by sebplais** [comment]
Hey just experienced problem with latest release 
get elements returned me a list of 4 elements
trying to interact with them in a loop  , randomly some elements can no more be usable
(exemple : timeout  waiting for selector "button.mericon-delete >> nth=3" )

robotframework                  4.1.2
robotframework-browser          11.0.0

**Comment by aaltat** [comment]
@sebplais 
1) It's not nice to post your problem to a issue which is not relevant. Instead using one of the https://robotframework.org/#community is usually better choice 
2) When reaching out to the community, provide more details. Full stack trace, what keyword you use,  playwright trace file and so one.

**Comment by sebplais** [comment]
@aaltat 
I am really sorry, it did not want to offense 
I just wanted to point that I fought faced the same issue as described here to let you know
Please apologize 
I did report in the community this issue
Thanks for the amazing job you are doing

**Comment by mkorpela** [comment]
Locators solved this.
