### ISSUE TITLE
Feature to switch to main window from a child window

### ISSUE THREAD

**Issue by ankurbhalla-gmail** [MarketSquare/robotframework-browser#1311]
**Is your feature request related to a problem? Please describe.**
Currently it is required to save the ID of the main window while switching to a new/child window opened as part of the testing flow. 

**Describe the solution you'd like**
It would be really good to have a feature similar to **Selenium Library** wherein we can switch back to the main window by keyword **"Switch Window    main"** where 'main' is the parameter passed to the keyword.

**Comment by aaltat** [comment]
@all-contributors please add @ankurbhalla-gmail for ideas

**Comment by mkorpela** [comment]
Good point. I was thinking maybe ”previous” instead of ”main”? Parent / child relationship between pages is vaque in many cases.

**Comment by mkorpela** [comment]
@ankurbhalla-gmail started to prototype this. Then I thought that we actually have a bit different method in Browser library.
When you `Close Page` it will automatically switch to previous.
Could you give an example where adding `MAIN` or `PREVIOUS` would help you?

**Comment by Snooz82** [comment]
no news since three month. closed. Maybe open again if really needed
