### ISSUE TITLE
New Browser to skip if exists and switch

### ISSUE THREAD

**Issue by mkorpela** [MarketSquare/robotframework-browser#1319]
**Is your feature request related to a problem? Please describe.**

New Context by default either attaches to existing browser or creates a one with default options. For several cases default options are not good enough. For instance a headfull browser might be needed or a firefox.

add an option to skip and switch to `New Browser` that can find the right default browser for you.

**Comment by mkorpela** [comment]
https://github.com/MarketSquare/robotframework-browser/pull/1318

**Comment by Snooz82** [comment]
New Implementation done.
Fixed By #2626
