### ISSUE TITLE
Docu keywords: "Drag And Drop By Coordinates" and "Go To"

### ISSUE THREAD

**Issue by UliSei** [MarketSquare/robotframework-browser#1328]
Source file: interaction.py
https://marketsquare.github.io/robotframework-browser/Browser.html#Drag%20And%20Drop%20By%20Coordinates

- The word "the" is duplicated two times

![grafik](https://user-images.githubusercontent.com/89480399/133935170-131ca838-1e01-40fd-bfb5-2be4ecb59861.png)

Source file: browser_control.py
https://marketsquare.github.io/robotframework-browser/Browser.html#Go%20To

- The word "the" is duplicated
- The arguments should be listed in separate lines

![grafik](https://user-images.githubusercontent.com/89480399/133935385-d63bd48f-230a-4055-8245-e2d761b10715.png)

**Comment by aaltat** [comment]
@all-contributors please add @UliSei for bugs

**Comment by UliSei** [comment]
This is my very first RF browser issue and I am going to solve it.

**Comment by UliSei** [comment]
I prepared a pull request and there are two further changes included in interaction.py:

1) keyword **type_secret**
    valu -> value
    $USERANME/%USERANME% -> $USERNAME/%USERNAME%

2) keyword **Select Options By**
    The argument order in the example was adapted to the definition. 
    The select attributes are e.g. label, value, index or text.
    Calling the keyword the **selector** comes first and the **attribute** afterwards.

**Comment by aaltat** [comment]
@all-contributors please add @UliSei for code

**Comment by aaltat** [comment]
Done in #1366
