### ISSUE TITLE
Issue with keyword documentation example - Select Options By

### ISSUE THREAD

**Issue by dalaakso** [MarketSquare/robotframework-browser#1335]
In example: 
Select Options By    label    select[name=preferred_channel]    Direct mail
Select Options By    value    select[name=interests]    males    females    others
Select Options By    index    select[name=possible_channels]    0    2
Select Options By    text     select[name=interests]    Males    Females

However these are not working examples as selector should come first.
Working ones would be:
Select Options By    select[name=preferred_channel]   label    Direct mail
Select Options By    select[name=interests]    value     males    females    others
Select Options By    select[name=possible_channels]    index    0    2
Select Options By     select[name=interests]    text   Males    Females

https://marketsquare.github.io/robotframework-browser/Browser.html#Select%20Options%20By

**Comment by aaltat** [comment]
@all-contributors please add @dalaakso for bugs
