### ISSUE TITLE
Cookbook of example test code / common best practices

### ISSUE THREAD

**Issue by xylix** [MarketSquare/robotframework-browser#134]

**Comment by adrianyorke** [comment]
RF Browser recipes are most welcome in the Robot Framework Cookbook:
https://github.com/adrianyorke/robotframework-cookbook

We already have a recipe in Section 13 for SeleniumLibrary which demonstrates setting up a local environment where to test websites against multiple locally running browsers.:
https://github.com/adrianyorke/robotframework-cookbook/blob/master/src/section_13/recipe131_selenium_setup.robot
