### ISSUE TITLE
Document BrowserLibrarys `Get Selected Options` differences to SeleniumLibrarys `Select Element _`

### ISSUE THREAD

**Issue by xylix** [MarketSquare/robotframework-browser#136]
- [ ] Add some more "complicated" tests (maybe from SL side)
- [ ] Document API and behaviour differences from SL's similar keywords

**Comment by Snooz82** [comment]
i think we are fine here. @xylix please comment

**Comment by xylix** [comment]
Closed as unnecessary. Lets do better docs if some user has problems with this functionality
.
