### ISSUE TITLE
After executing rfbrowser clean node, rfbrowser init is not possible anymore

### ISSUE THREAD

**Issue by emakaay** [MarketSquare/robotframework-browser#1390]
**Describe the bug**
After using "rfbrowser clean-node" it is not possible to re-install the node modules using "rfbrowser init"

**To Reproduce**

1. pip install robotframework-browser==9.0.0
2. rfbrowser init
3. rfbrowser clean-node
4. rfbrowser init

`
Installing node dependencies...
Installation directory `c:\python37\lib\site-packages\Browser\wrapper` does not contain the required package.json
Printing contents:
Traceback (most recent call last):
  File "c:\python37\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\python37\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Python37\Scripts\rfbrowser.exe\__main__.py", line 9, in <module>
  File "c:\python37\lib\site-packages\Browser\entry.py", line 164, in run
    rfbrowser_init(args.skip_browsers)
  File "c:\python37\lib\site-packages\Browser\entry.py", line 43, in rfbrowser_init
    raise RuntimeError("Could not find robotframework-browser's package.json")
RuntimeError: Could not find robotframework-browser's package.json`

**Expected behavior**
After removing the node modules, I would expect to reinstall it again.

**Screenshots**

**Desktop (please complete the following information):**
 - Windows 10/11
 - Browser 
 - Version 9.0.0

**Comment by aaltat** [comment]
This is what I get when I do not test properly, oh dear. Well in any case, workaround is easy: `pip uninstall` and `pip install` library again. 

Will be fixed asp.
