### ISSUE TITLE
With New Page keyword return also path to video

### ISSUE THREAD

**Issue by Leemur89** [MarketSquare/robotframework-browser#1424]
Hello,

**Describe the solution you'd like**
Currently the recorded video is displayed in the "New Context" keyword, I think it would add value to have the video directly in the test documentation, that way we'd be able to see the video directly without having to look for the specific keyword where it is

**Describe alternatives you've considered**
I could manually append that to the documentation, but I would need to have the video filename for that (currently it seems kind of random, and we have nothing to access the video name)

Thanks

**Comment by aaltat** [comment]
@allcontributors please add @Leemur89 for ideas

**Comment by Leemur89** [comment]
thanks! 😃
