### ISSUE TITLE
Record video by default from New Browser keyword

### ISSUE THREAD

**Issue by Leemur89** [MarketSquare/robotframework-browser#1425]
Hello,

**Is your feature request related to a problem? Please describe.**
If I want to record video of all my tests, I need to specify the video option in all my "New Context" keywords

**Describe the solution you'd like**
As I'm using the keyword "New Browser" only once for my whole suite, it would simplify the factorization if I could set the record video option directly in that keyword.
Also it would be even nicer to have a boolean to drive the video recording (instead of the current dictionary)

Thanks,

**Comment by aaltat** [comment]
I think we are not going to do this. You can create dictionary once, declared it as a global variable and use it every time you call new context keyword. Therefore closing the issue.
