### ISSUE TITLE
Keywords to capture / wait for HTTP requests

### ISSUE THREAD

**Issue by xylix** [MarketSquare/robotframework-browser#144]
Keywords to use playwights waitForResponse and waitForRequest methods

https://github.com/microsoft/playwright/blob/master/docs/api.md#browsercontextwaitforeventevent-optionsorpredicate

**Comment by mkorpela** [comment]
Some additional:

- [ ] `Wait until network is idle`
- [ ] `Do not allow 5xx return codes` .. or something with a better name
