### ISSUE TITLE
Wait For Element State 'hidden' results to locator.elementHandle failed

### ISSUE THREAD

**Issue by ealap** [MarketSquare/robotframework-browser#1442]
**Describe the bug**
Since v10.0.0, RfBrowser fails at executing
```
Wait For Element State    ${selector}    hidden
```
playwright-log.txt:
```
{"level":30,"time":"2021-10-29T03:13:27.009Z","pid":31180,"hostname":"dummy_hostname","msg":"Strict mode is disbaled, return first Locator: css=td.loading-state in page."}
2021-10-29T03:13:27.009Z pw:api => locator.elementHandle started
2021-10-29T03:13:27.010Z pw:api waiting for selector "css=td.loading-state >> nth=0"
2021-10-29T03:13:37.014Z pw:api <= locator.elementHandle failed
```

**Expected behavior**
In v9.0.2, the keyword is executing as expected
playwright-log.txt:
```
{"level":30,"time":"2021-10-29T03:47:22.304Z","pid":31112,"hostname":"dummy_hostname","msg":"Page|Frame|Element resolved elementSelector: css=td.loading-state"}
2021-10-29T03:47:22.305Z pw:api => page.$ started
2021-10-29T03:47:22.305Z pw:api     finding element using the selector "css=td.loading-state"
2021-10-29T03:47:22.309Z pw:api <= page.$ succeeded
2021-10-29T03:47:22.309Z pw:api => page.waitForSelector started
2021-10-29T03:47:22.310Z pw:api waiting for selector "css=td.loading-state" to be hidden
2021-10-29T03:47:22.332Z pw:api <= page.waitForSelector **succeeded**
```

**Desktop (please complete the following information):**
 - OS: Windows, Linux (via WSL)
 - Browser: Chrome

**Comment by aaltat** [comment]
I could not reproduce this problem exactly, but found few interesting stuff. By reading the logging and looking code, I have clear assumption view where the problem is, but still this is fixed blindly.

**Comment by emakaay** [comment]
Thanks @aaltat 

The 10.0.2 release fixed the problem. At least for the first project tested 😁

Great stuff

**Comment by emakaay** [comment]
@aaltat 
unfortunately I tested some more projects (with robotframework-browser 10.0.2), and I encountered some more bugs.

```
Example 1: Project with strict=False
Robot code
 Click //*[@id='list']//table/tbody/tr[1]
Error in robot result report
New message: TimeoutError: locator.click: Timeout 10000ms exceeded.
=========================== logs ===========================
waiting for selector "//*[@id='list']//table/tbody/tr[1] >> nth=0"
============================================================

```
```
Example 2: project with strict=False
robot code
Wait For Elements State //*[@id="list"]/div/table/tbody/tr, visible

Error in robot result report
New message: TimeoutError: locator.waitFor: Timeout 10000ms exceeded.
=========================== logs ===========================
waiting for selector "//*[@id="list"]/div/table/tbody/tr >> nth=0" to be visible

```  
This release is not fixing all issues with the refactored code, in my opinion

**Comment by aaltat** [comment]
Could you raise separate issues about those problems, so that we remember to fix those and to ease tracking the problems. Also if it possible to create an example which demonstrates the problem it would ease the problem debugging a lot.

**Comment by aaltat** [comment]
Created #1448 for improving the Playwright side log reading, because it is separate issue.

**Comment by aaltat** [comment]
I tried to find a way where this would work with 9.0.2 and would fail with 10.0.2. All the cases fail in both versions, the error text is different because internal logic is different, but both fail from the same reason, first element is not visible.

**Comment by emakaay** [comment]
@aaltat 
I will raise a new issue and try to create examples.
Currently I don't have the time to do it. 
I think what your saying is that the error can only be created when a invisible element is expected to be visible. In both versions. Is that true. That would mean that my issue is wrong altogether. I will look into that also

**Comment by emakaay** [comment]
Seems that 10.0.3 fixed all my problems. No need for additional issue
