### ISSUE TITLE
Wrong arguments order for "Select Options By" in documentation

### ISSUE THREAD

**Issue by zastress** [MarketSquare/robotframework-browser#1443]
**Describe the bug**
Documentation about "Select Options By" has the wrong arguments order in example section: https://marketsquare.github.io/robotframework-browser/Browser.html#Select%20Options%20By

In documentation there are examples for usage like this: 
`Select Options By    label    select[name=preferred_channel]    Direct mail`

In real life, locator comes before attribute:
`Select Options By    select[name=preferred_channel]    label  Direct mail`
Same for all other examples

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser all
 - Version 9.0.2

**Comment by aaltat** [comment]
Darn, this should not have been closed.

**Comment by aaltat** [comment]
I am sorry about it. I am pushing next release out and wanted to fix it.
