### ISSUE TITLE
ImportError: cannot import name 'DialogAction' from 'Browser'

### ISSUE THREAD

**Issue by luchoagomezt** [MarketSquare/robotframework-browser#1455]
**Describe the bug**
while developing and running a Python sript, with the following import statement and call:

from Browser import Browser, DialogAction
[..]

I received the following error traceback:

[..]
    from Browser import Browser, DialogAction
ImportError: cannot import name 'DialogAction' from 'Browser' (C:\Users\t936665\AppData\Local\Programs\Python\Python37-32\lib\site-packages\Browser\__init__.py)

**To Reproduce**
1. In a Python script, 
    from Browser import Browser, DialogAction
2. Excute the script

**Expected behavior**
The import of DialogAction must not generate an ImportError

**Screenshots**

**Desktop (please complete the following information):**
 - Windows 10
 - Cromium
 - robotframework-browser 10.0.2

**Smartphone (please complete the following information):**
N/A

**Additional context**
NA
[automation-training-bug.zip](https://github.com/MarketSquare/robotframework-browser/files/7454301/automation-training-bug.zip)

**Comment by aaltat** [comment]
This is correct `DialogAction` is not available directly from library root.  Why this is a problem?

**Comment by luchoagomezt** [comment]
The fix for this issue is to add the missing class, DialogAction, to the Browser/__init__.py

from assertionengine import AssertionOperator

from .browser import Browser
from .utils.data_types import (
    ColorScheme,
    ElementState,
    KeyboardModifier,
    MouseButton,
    RequestMethod,
    SelectAttribute,
    SupportedBrowsers,
    ViewportDimensions,
    **DialogAction,**
)
from .version import __version__ as VERSION

__version__ = VERSION
__all__ = [
    "AssertionOperator",
    "ElementState",
    "ColorScheme",
    "ViewportDimensions",
    "SupportedBrowsers",
    "SelectAttribute",
    "KeyboardModifier",
    "MouseButton",
    "RequestMethod",
    "**DialogAction**",
    "Browser",
]

**Comment by luchoagomezt** [comment]
> This is correct `DialogAction` is not available directly from library root. Why this is a problem?

I could not import it to my project. Is there another way?

**Comment by aaltat** [comment]
We should actually list it there, so it is a bug. It can be found from here https://github.com/MarketSquare/robotframework-browser/blob/main/Browser/utils/data_types.py

**Comment by aaltat** [comment]
@allcontributors please add @luchoagomezt for bugs
