### ISSUE TITLE
Get Element Count returns 1 when counting elements inside iframe

### ISSUE THREAD

**Issue by Pakkanen1** [MarketSquare/robotframework-browser#1457]
**Describe the bug**
When executing the `Get Element Count` keyword on elements that are inside an iframe, the keyword always returns 1 instead of the count of the elements matching the selector.

**To Reproduce**
1. Create a robot test that counts elements inside an iframe. There should be more than 1 matching element.
2. Run test
3. Count is 1

```
*** Settings ***
Library    Browser    strict=${False}

*** Test Cases ***
Count Fails In iFrame
	new browser    chromium    ${False}
	new page    https://smashfinland.fi
	wait for elements state    id=frontpageBlogpost
	#Count elements that are not inside iframe
	${count}=    get element count    css=#frontpageBlogpost p    ==    6
	#Count elements inside iframe
	${count}=    get element count    id=emb_515jbl >>> css=#cards div    ==    4
```

**Expected behavior**
The count should be the amount of elements that match the selector. The keyword works as excpected when not counting elements inside an iframe.

**Desktop:**
 - OS: Windows 10 & Ubuntu 20.04 LTS
 - Browser: chromium (930007)
 - Version: robotframework-browser 10.0.2

**Additional context**
I also tested counting elements inside shadow dom, but that worked as expected.

**Comment by aaltat** [comment]
Yes, there is some special handling for frames in the node side, which could explain the problem. Need to take a look.

**Comment by aaltat** [comment]
@allcontributors please add @Pakkanen1 for bugs

**Comment by aaltat** [comment]
Yes, I reproduce the problem and I see where the problem actually is. Need to think how to fix it.
