### ISSUE TITLE
Crawler fails if site has a link to a pdf

### ISSUE THREAD

**Issue by ePlanLori** [MarketSquare/robotframework-browser#1463]
**Describe the bug**
I am checking out Browser Library and was playing with crawling our site but every time Crawl Site hits a pdf url it dies. 

I’ve tried using Run Keyword And Ignore Error and Run Keyword And Continue On Failure but execution stops each time due to a privacy policy pdf we have on every page on our site

Error: page.goto: net::ERR_ABORTED at ${url}privacy_statement.pdf
=========================== logs ===========================
navigating to "${url}privacy_statement.pdf", waiting until "load"

**To Reproduce**
Run the following:
    Crawl Site  url=https://secure.eplanservices401k.com/

**Expected behavior**
I expected the crawler to traverse all pages of our website however it errors out on a pdf and stops running.  If the crawl could handle or allow the user to exclude pdfs that would be great.

**Screenshots**

<img width="958" alt="Crawl_Site_PDF_Error" src="https://user-images.githubusercontent.com/61252623/139912010-ae823b8d-9fe4-4316-859d-5d673f8cbf11.png">

**Desktop (please complete the following information):**
 - OS: Mint OS 20 / Linux
 - Browser : Chrome
  - Version 95.0.4638.69

**Additional context**

**Comment by aaltat** [comment]
@allcontributors please add @ePlanLori for bugs

**Comment by mkorpela** [comment]
Done
