### ISSUE TITLE
No library '<Browser.browser.Browser object at 0x0AB06030>' found.

### ISSUE THREAD

**Issue by luchoagomezt** [MarketSquare/robotframework-browser#1465]
**Describe the bug**
When invoking in a Python script promise_to("wait_for_alert", DialogAction.accept, "any text here") I receive the following error:
No library '<Browser.browser.Browser object at 0x0AB06030>' found.
  

**To Reproduce**

1) In python:

from Browser import Browser, DialogAction
...
class MedAccessLogin:
    def __init__(self):
        self.browser_library = Browser(timeout="20 s", retry_assertions_for="900 ms")
        self.browser_library.new_browser(headless=False)
        self.browser_library.new_context(
            acceptDownloads=True,
            viewport={"width": 1920, "height": 1080},
            recordVideo={'dir':'videos', 'size':{'width':800, 'height':400}}
        )
        self.selectors = {"info": "css=#null", "login": "css=#LoginButton"}
        self.promise = None
...

    def **promise_to_wait_for_alert_with_text**(self, text: str = "", action: str = "accept"):
        dialog_action = DialogAction.accept if action == "accept" else DialogAction.dismiss
        self.promise = **self.browser_library.promise_to("wait_for_alert", dialog_action, text)**
        return self.promise

2) From Robot

AUTQA 160 Navigate to the MedAccess login page click on login accept pop up verify message in popup
    **promise to wait for alert with text**     A username is required.
    click on login button

3) Execute the test using robot.exe 

**Expected behavior**
I expect to get a promise as return in this line of code:
        self.promise = **self.browser_library.promise_to("wait_for_alert", dialog_action, text)**

**Screenshots**
NA

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chromium

**Smartphone (please complete the following information):**
NA

**Additional context**

**Comment by xylix** [comment]
What exactly are you using `robot.exe` here for? It is unclear to me, I don't think there is any Robot script in the pasted example?

**Comment by luchoagomezt** [comment]
> What exactly are you using `robot.exe` here for? It is unclear to me, I don't think there is any Robot script in the pasted example?

*** Settings ***
Library                         pages.medaccess_login_page_browser.MedAccessLogin

Test Setup                      navigate to page and maximize
Test Teardown                   close page and quit

*** Test Cases ***
AUTQA 100 Navigate to the MedAccess login page verify the nformation button is present
    ${button is present}=       is the info button present
    Should Be True              ${button is present}

AUTQA 120 Navigate to the MedAccess login page click on the information button
    click on the info button
    Sleep   2

AUTQA 140 Navigate to the MedAccess login page click on login accept pop up
    after clicking element handle future dialog with message
    click on login button

**AUTQA 160 Navigate to the MedAccess login page click on login accept pop up verify message in popup**
    promise to wait for alert with text     A username is required.
    click on login button

**Comment by xylix** [comment]
Hm.

In this chase it does seem like lines
```
self.browser_library = Browser(timeout="20 s", retry_assertions_for="900 ms")
self.browser_library.new_browser(headless=False)
```
Should work just fine. Do the steps before the "promise to wait" manage to run?

**Comment by luchoagomezt** [comment]
> Hm.
> 
> In this chase it does seem like lines
> 
> ```
> self.browser_library = Browser(timeout="20 s", retry_assertions_for="900 ms")
> self.browser_library.new_browser(headless=False)
> ```
> 
> Should work just fine. Do the steps before the "promise to wait" manage to run?

yes, all the steps before the promise to work as expected. 

I wrote a Python only test, and I noticed that it requires a Robot Framewok context:
import unittest
from Browser import Browser, DialogAction


class TestBrowserLibrary(unittest.TestCase):
    def __init__(self, *args, **kwargs):
        super(TestBrowserLibrary, self).__init__(*args, **kwargs)
        self.browser_library = Browser(timeout="20 s", retry_assertions_for="900 ms")
        self.browser_library.new_browser(headless=False)
        self.browser_library.new_context(
            acceptDownloads=True,
            viewport={"width": 1920, "height": 1080},
            recordVideo={'dir': 'videos', 'size': {'width': 800, 'height': 400}}
        )
        self.promise = None
        self.url = "https://emr03automation07.emrlab.ca/"
        self.selectors = {"info": "css=#null", "login": "css=#LoginButton"}

    def test_accept_login_error_pop_up_dialog(self):
        self.browser_library.new_page(self.url)
        self.browser_library.handle_future_dialogs(action=DialogAction.accept, prompt_input="A username is required.")
        self.browser_library.click(self.selectors["login"])

    def test_accept_login_error_pop_up_dialog(self):
        self.browser_library.new_page(self.url)
        self.browser_library.promise_to("Wait For Alert", "action=accept", "text=A username is required.")
        self.browser_library.click(self.selectors["login"])


if __name__ == '__main__':
    unittest.main()

Error is as follows:
Error
Traceback (most recent call last):
  File "C:\Users\t936665\AppData\Local\Programs\Python\Python37-32\lib\unittest\case.py", line 59, in testPartExecutor
    yield
  File "C:\Users\t936665\AppData\Local\Programs\Python\Python37-32\lib\unittest\case.py", line 615, in run
    testMethod()
  File "C:\Users\t936665\Documents\git\medaccess-ui-automation\untest\test_browser_libray.py", line 26, in test_accept_login_error_pop_up_dialog
    self.browser_library.promise_to("Wait For Alert", "action=accept", "text=A username is required.")
  File "C:\Users\t936665\AppData\Local\Programs\Python\Python37-32\lib\site-packages\Browser\keywords\promises.py", line 51, in promise_to
    browser_lib = EXECUTION_CONTEXTS.current.namespace._kw_store.get_library(
AttributeError: 'NoneType' object has no attribute 'namespace'

**Comment by luchoagomezt** [comment]
it looks like a object was not instantiated generating the error.

**Comment by luchoagomezt** [comment]
Hello, 
I sent the information that was requested.  Do you need more info?
Thanks

**Comment by aaltat** [comment]
I wrote an example how to use Browser library from Python.

**Comment by Massukio** [comment]
Hi @aaltat, I did follow the example, and I still got the error. 
Below are the simple example of my scripts. Please help to check if I done something wrong ..

py file
```
from robot.api.deco import keyword
from Browser import Browser

@keyword
def test_keyword():
    LIB = Browser()
    LIB.new_browser()
    LIB.new_page(url='http://www.google.com')
    PROMISE = LIB.promise_to('Wait For Response')
```

robot file
```
==============================================================================
Test
==============================================================================
Test                                                                  | FAIL |
No library '<Browser.browser.Browser object at 0x000001B127FC01F0>' found.    
------------------------------------------------------------------------------
Test                                                                  | FAIL |
1 test, 0 passed, 1 failed
==============================================================================
```

result
```
==============================================================================
Test
==============================================================================
Test                                                                  | FAIL |
No library '<Browser.browser.Browser object at 0x000001B127FC01F0>' found.    
------------------------------------------------------------------------------
Test                                                                  | FAIL |
1 test, 0 passed, 1 failed
==============================================================================
```
