### ISSUE TITLE
Disable screenshot when error is expected

### ISSUE THREAD

**Issue by Leemur89** [MarketSquare/robotframework-browser#1472]
**Is your feature request related to a problem? Please describe.**
I'm handling error cases, and I am using the builtin keyword "Run Keyword And Expect Failure". Problem is that the "Run On Failure" keyword will always kick and take screenshot. As the error is expected I don't think it is necessary to take that screenshot (especially to not overload the size of the artefacts when running from a pipeline)

**Describe the solution you'd like**
When the error is expected, no screenshot should be taken.
If there is no error whereas one is expected, a screenshot should be taken
If there is an unexpected error, a screenshot should be taken

Note that I tried to supercharge the "Run Keyword And Expect Failure" keyword as below, but I'm struggling calling the "Run On Failure" from python (I don't know which parameter I should provide in input of ``RunOnFailureKeywords()``)

```python
from robot.libraries.BuiltIn import _RunKeyword, ExecutionFailed
from Browser.keywords.runonfailure import RunOnFailureKeywords


class customBuiltIn(_RunKeyword):
    def run_keyword_and_expect_error(self, expected_error, name, *args):
        """Same as the builtin method of the same name, but don't take
        screenshot if error is expected"""
        run_on_failure_keywords = RunOnFailureKeywords()  # here I need to provide a library in input but I don't know how
        old_keyword = \
            run_on_failure_keywords.register_keyword_to_run_on_failure(None)
        try:
            super().run_keyword_and_expect_error(expected_error, name, *args)
        except ExecutionFailed as err:
            run_on_failure_keywords.register_keyword_to_run_on_failure(
                old_keyword
            )
            raise err
```

Note: if you help me fix that argument issue and point me towards the place where I can put it in that lib I'm open to raise a PR myself

**Alternative**
Currently I'm simply disabling the "Take Screenshot" before calling the "Run Keyword And Expect Error", but that also prevents taking a screenshot in case of unexpected error

**Comment by aaltat** [comment]
You should use [Get Library Instance](https://robotframework.org/robotframework/latest/libraries/BuiltIn.html#Get%20Library%20Instance) to get the Browser library active instance. Then you could call the `register_keyword_to_run_on_failure` method from Browser library.

**Comment by aaltat** [comment]
Closing because this is not a feature request or bug report.
