### ISSUE TITLE
Use Playwright video to allow recording video of the test execution.

### ISSUE THREAD

**Issue by mkorpela** [MarketSquare/robotframework-browser#148]
**Is your feature request related to a problem? Please describe.**
Currently we offer a keyword to take a screenshot. Video can be more informative and is already used in many browser automation tools.

**Describe the solution you'd like**
Add keywords to start and store video recording. Video recording should be also embedded to the log file.

**Additional context**
https://playwright.dev/#version=v1.5.1&path=docs%2Fapi.md&q=class-video
https://playwright.dev/#version=v1.5.1&path=docs%2Fapi.md&q=browsernewpageoptions--options-videosize
https://playwright.dev/#version=v1.5.1&path=docs%2Fapi.md&q=browsernewpageoptions--options-videospath

**Comment by idxn** [comment]
From my point of view, sometimes the video is not that significant for me because you need to fast forward to the point you need to see and it's not cost effective in terms of machine utilization e.g. cpu, memory and disk space. 

I think what important is to have a feature to capture the screenshot on before each keywords or steps you are interested in.
It could be a regex argument in library import.

**Comment by mkorpela** [comment]
Thanks @idxn for the insight!
The playwright-video takes fps (frames per second) argument. I think that could be very low by default (such as 3 frames per second). So machine utilization would not be such a big problem.
Linking the video frames to specific parts of the log might be a technical challenge.

**Comment by idxn** [comment]
@mkorpela The default is 25 fps but I might be wrong. Still, I really love to see the screenshot on each keyword instead of the video. This is also the key people love cypress.

**Comment by idxn** [comment]
![image](https://user-images.githubusercontent.com/2438992/88266241-15a0bc80-ccf9-11ea-9994-7405e0eeff8f.png)
This is an example of cypress. You would see steps on the left and the screenshot before step is executed on the right.

**Comment by mkorpela** [comment]
If I am assuming correctly, we are mostly interested about differences in screenshots before and after?
Python has very good support for image processing. We could take that one step further and make an image that highlights the changes.

**Comment by idxn** [comment]
That is also a good one if we would like to cover visual regression testing but should it be a separated story?

**Comment by mkorpela** [comment]
Yes. Visual regressions or snapshot testing in general is not at least the idea that I had in mind for this issue.
More on how to best visualise what is happening in the UI when executing the test.

**Comment by idxn** [comment]
I got you then. You mean highlights the change from the previous keywords. That's rock. I love the idea.

**Comment by mkorpela** [comment]
Then we might consider adding OpenCV as an dependency.
