### ISSUE TITLE
Keyword "Wait For Elements State" is not working

### ISSUE THREAD

**Issue by gdroes** [MarketSquare/robotframework-browser#1485]
**Describe the bug**
Using the Keyword return always the error message
"TypeError: locator.waitFor is not a function"

**To Reproduce**
Steps to reproduce the behavior: Try this simple test
*** Settings ***
Library             Browser

*** Test Cases ***
Check Wait For Elements State
    New Browser    chromium    headless=false
    New Page       https://github.com/MarketSquare/robotframework-browser
    ${ret_txt} =       Get Text    xpath=//*[@id="issues-repo-tab-count"]
    ${ret_state} =       Wait For Elements State    xpath=//*[@id="issues-repo-tab-count"]   visible

**Expected behavior**
I expect to get True or False as return value. I the example above I expect True.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser  chrome
 - Version latest

**Comment by aaltat** [comment]
The `//[@id="issues-repo-tab-count"]` is not valid xpath. Instead `//*[@id="issues-repo-tab-count"]` or //span[@id="issues-repo-tab-count"]` would work in this case. 

Closing because library is working as expected.

**Comment by gdroes** [comment]
Sorry, it seems that by copy and past the example code I left one char :-(
Neither //*[@id="issues-repo-tab-count"] or //span[@id="issues-repo-tab-count"] is working.

**Comment by aaltat** [comment]
Did you test with the latest 10.0.3 release? Also could you run the test with --loglevel trace set and show the full error message and stack trace.

**Comment by gdroes** [comment]
<?xml version="1.0" encoding="UTF-8"?>
<robot generator="Robot 4.1.1 (Python 3.8.5 on win32)" generated="20211109 07:05:46.677" rpa="false" schemaversion="2">
<suite id="s1" name="Mytest" source="H:\git\testautomation\mytest.robot">
<test id="s1-t1" name="Check Wait For Elements State">
<kw name="New Browser" library="Browser">
<arg>chromium</arg>
<arg>headless=false</arg>
<tag>BrowserControl</tag>
<tag>Setter</tag>
<doc>Create a new playwright Browser with specified options.</doc>
<msg timestamp="20211109 07:05:49.684" level="TRACE">Arguments: [ &lt;SupportedBrowsers.chromium: 1&gt; | headless=False ]</msg>
<msg timestamp="20211109 07:05:49.685" level="INFO">{"browser": "chromium", "headless": false, "handleSIGINT": true, "handleSIGTERM": true, "handleSIGHUP": true, "timeout": 30000.0, "devtools": false, "slowMo": 0.0, "tracesDir": "H:\\git\\testautomation\\browser\\traces\\d82aeb83-69da-45e0-af11-d7e13ce769e7"}</msg>
<msg timestamp="20211109 07:05:50.657" level="INFO">Successfully created browser with options: {"browser":"chromium","headless":false,"handleSIGINT":true,"handleSIGTERM":true,"handleSIGHUP":true,"timeout":30000,"devtools":false,"slowMo":0,"tracesDir":"H:\\git\\testautomation\\browser\\traces\\d82aeb83-69da-45e0-af11-d7e13ce769e7"}</msg>
<msg timestamp="20211109 07:05:50.657" level="TRACE">Return: 'browser=c4893548-c125-4dcc-9511-432226ac7a14'</msg>
<status status="PASS" starttime="20211109 07:05:49.684" endtime="20211109 07:05:50.657"/>
</kw>
<kw name="New Page" library="Browser">
<arg>https://github.com/MarketSquare/robotframework-browser</arg>
<tag>BrowserControl</tag>
<tag>Setter</tag>
<doc>Open a new Page. A Page is the Playwright equivalent to a tab.
See `Browser, Context and Page` for more information about Page concept.
Returns a stable identifier for the created page.</doc>
<msg timestamp="20211109 07:05:50.658" level="TRACE">Arguments: [ 'https://github.com/MarketSquare/robotframework-browser' ]</msg>
<msg timestamp="20211109 07:05:53.651" level="INFO">Successfully initialized new page object and opened url: https://github.com/MarketSquare/robotframework-browser</msg>
<msg timestamp="20211109 07:05:53.651" level="INFO">No context was open. New context was automatically opened when this page is created.</msg>
<msg timestamp="20211109 07:05:53.651" level="DEBUG">Video is not enabled.</msg>
<msg timestamp="20211109 07:05:53.651" level="TRACE">Return: 'page=2c1ea380-6210-4d89-aabf-a52d63830b9b'</msg>
<status status="PASS" starttime="20211109 07:05:50.658" endtime="20211109 07:05:53.651"/>
</kw>
<kw name="Get Text" library="Browser">
<var>${ret_txt}</var>
<arg>xpath=//span[@id="issues-repo-tab-count"]</arg>
<tag>Assertion</tag>
<tag>Getter</tag>
<tag>PageContent</tag>
<doc>Returns text attribute of the element found by ``selector``.</doc>
<msg timestamp="20211109 07:05:53.652" level="TRACE">Arguments: [ 'xpath=//span[@id="issues-repo-tab-count"]' ]</msg>
<msg timestamp="20211109 07:05:53.758" level="DEBUG">Text received successfully.</msg>
<msg timestamp="20211109 07:05:53.758" level="DEBUG">Assertion polling statistics:
First element asserted in: 0.10547709465026855 seconds
Total tries: 1
Elapsed time in retries 0.0 seconds</msg>
<msg timestamp="20211109 07:05:53.758" level="TRACE">Return: '46'</msg>
<msg timestamp="20211109 07:05:53.758" level="INFO">${ret_txt} = 46</msg>
<status status="PASS" starttime="20211109 07:05:53.651" endtime="20211109 07:05:53.758"/>
</kw>
<kw name="Wait For Elements State" library="Browser">
<var>${ret_state}</var>
<arg>xpath=//span[@id="issues-repo-tab-count"]</arg>
<arg>visible</arg>
<tag>PageContent</tag>
<tag>Wait</tag>
<doc>Waits for the element found by ``selector`` to satisfy state option.</doc>
<msg timestamp="20211109 07:05:53.758" level="TRACE">Arguments: [ 'xpath=//span[@id="issues-repo-tab-count"]' | &lt;ElementState.visible: 3&gt; ]</msg>
<msg timestamp="20211109 07:05:53.958" level="DEBUG">Suppress error: TypeError: locator.waitFor is not a function</msg>
<msg timestamp="20211109 07:05:54.142" level="DEBUG">Suppress error: TypeError: locator.waitFor is not a function</msg>
<msg timestamp="20211109 07:05:54.326" level="DEBUG">Suppress error: TypeError: locator.waitFor is not a function</msg>
<msg timestamp="20211109 07:05:54.490" level="DEBUG">Suppress error: TypeError: locator.waitFor is not a function</msg>
<msg timestamp="20211109 07:05:54.660" level="DEBUG">Suppress error: TypeError: locator.waitFor is not a function</msg>
<msg timestamp="20211109 07:05:54.822" level="DEBUG">Suppress error: TypeError: locator.waitFor is not a function</msg>
<msg timestamp="20211109 07:05:55.004" level="DEBUG">Suppress error: TypeError: locator.waitFor is not a function</msg>
<msg timestamp="20211109 07:05:55.178" level="DEBUG">Suppress error: TypeError: locator.waitFor is not a function</msg>
<msg timestamp="20211109 07:05:55.361" level="DEBUG">Suppress error: TypeError: locator.waitFor is not a function</msg>
<msg timestamp="20211109 07:05:55.545" level="DEBUG">Suppress error: TypeError: locator.waitFor is not a function</msg>
<msg timestamp="20211109 07:05:55.740" level="DEBUG">Suppress error: TypeError: locator.waitFor is not a function</msg>
<msg timestamp="20211109 07:05:55.908" level="DEBUG">Suppress error: TypeError: locator.waitFor is not a function</msg>
<msg timestamp="20211109 07:05:56.093" level="DEBUG">Suppress error: TypeError: locator.waitFor is not a function</msg>
<msg timestamp="20211109 07:05:56.262" level="DEBUG">Suppress error: TypeError: locator.waitFor is not a function</msg>
<msg timestamp="20211109 07:05:56.433" level="DEBUG">Suppress error: TypeError: locator.waitFor is not a function</msg>
<msg timestamp="20211109 07:05:56.610" level="DEBUG">Suppress error: TypeError: locator.waitFor is not a function</msg>
<msg timestamp="20211109 07:05:56.779" level="DEBUG">Suppress error: TypeError: locator.waitFor is not a function</msg>
<msg timestamp="20211109 07:05:56.948" level="DEBUG">Suppress error: TypeError: locator.waitFor is not a function</msg>
<msg timestamp="20211109 07:05:57.122" level="DEBUG">Suppress error: TypeError: locator.waitFor is not a function</msg>
<msg timestamp="20211109 07:05:57.307" level="DEBUG">Suppress error: TypeError: locator.waitFor is not a function</msg>
<msg timestamp="20211109 07:05:57.492" level="DEBUG">Suppress error: TypeError: locator.waitFor is not a function</msg>
<msg timestamp="20211109 07:05:57.662" level="DEBUG">Suppress error: TypeError: locator.waitFor is not a function</msg>
<msg timestamp="20211109 07:05:57.834" level="DEBUG">Suppress error: TypeError: locator.waitFor is not a function</msg>
<msg timestamp="20211109 07:05:57.997" level="DEBUG">Suppress error: TypeError: locator.waitFor is not a function</msg>
<msg timestamp="20211109 07:05:58.165" level="DEBUG">Suppress error: TypeError: locator.waitFor is not a function</msg>
<msg timestamp="20211109 07:05:58.334" level="DEBUG">Suppress error: TypeError: locator.waitFor is not a function</msg>
<msg timestamp="20211109 07:05:58.503" level="DEBUG">Suppress error: TypeError: locator.waitFor is not a function</msg>
<msg timestamp="20211109 07:05:58.668" level="DEBUG">Suppress error: TypeError: locator.waitFor is not a function</msg>
<msg timestamp="20211109 07:05:58.836" level="DEBUG">Suppress error: TypeError: locator.waitFor is not a function</msg>
<msg timestamp="20211109 07:05:59.012" level="DEBUG">Suppress error: TypeError: locator.waitFor is not a function</msg>
<msg timestamp="20211109 07:05:59.185" level="DEBUG">Suppress error: TypeError: locator.waitFor is not a function</msg>
<msg timestamp="20211109 07:05:59.349" level="DEBUG">Suppress error: TypeError: locator.waitFor is not a function</msg>
<msg timestamp="20211109 07:05:59.522" level="DEBUG">Suppress error: TypeError: locator.waitFor is not a function</msg>
<msg timestamp="20211109 07:05:59.699" level="DEBUG">Suppress error: TypeError: locator.waitFor is not a function</msg>
<msg timestamp="20211109 07:05:59.875" level="DEBUG">Suppress error: TypeError: locator.waitFor is not a function</msg>
<msg timestamp="20211109 07:06:00.043" level="DEBUG">Suppress error: TypeError: locator.waitFor is not a function</msg>
<msg timestamp="20211109 07:06:00.313" level="DEBUG">Suppress error: TypeError: locator.waitFor is not a function</msg>
<msg timestamp="20211109 07:06:00.481" level="DEBUG">Suppress error: TypeError: locator.waitFor is not a function</msg>
<msg timestamp="20211109 07:06:00.657" level="DEBUG">Suppress error: TypeError: locator.waitFor is not a function</msg>
<msg timestamp="20211109 07:06:00.829" level="DEBUG">Suppress error: TypeError: locator.waitFor is not a function</msg>
<msg timestamp="20211109 07:06:00.998" level="DEBUG">Suppress error: TypeError: locator.waitFor is not a function</msg>
<msg timestamp="20211109 07:06:01.183" level="DEBUG">Suppress error: TypeError: locator.waitFor is not a function</msg>
<msg timestamp="20211109 07:06:01.346" level="DEBUG">Suppress error: TypeError: locator.waitFor is not a function</msg>
<msg timestamp="20211109 07:06:01.530" level="DEBUG">Suppress error: TypeError: locator.waitFor is not a function</msg>
<msg timestamp="20211109 07:06:01.699" level="DEBUG">Suppress error: TypeError: locator.waitFor is not a function</msg>
<msg timestamp="20211109 07:06:01.884" level="DEBUG">Suppress error: TypeError: locator.waitFor is not a function</msg>
<msg timestamp="20211109 07:06:02.062" level="DEBUG">Suppress error: TypeError: locator.waitFor is not a function</msg>
<msg timestamp="20211109 07:06:02.231" level="DEBUG">Suppress error: TypeError: locator.waitFor is not a function</msg>
<msg timestamp="20211109 07:06:02.400" level="DEBUG">Suppress error: TypeError: locator.waitFor is not a function</msg>
<msg timestamp="20211109 07:06:02.584" level="DEBUG">Suppress error: TypeError: locator.waitFor is not a function</msg>
<msg timestamp="20211109 07:06:02.763" level="DEBUG">Suppress error: TypeError: locator.waitFor is not a function</msg>
<msg timestamp="20211109 07:06:02.947" level="DEBUG">Suppress error: TypeError: locator.waitFor is not a function</msg>
<msg timestamp="20211109 07:06:03.116" level="DEBUG">Suppress error: TypeError: locator.waitFor is not a function</msg>
<msg timestamp="20211109 07:06:03.300" level="DEBUG">Suppress error: TypeError: locator.waitFor is not a function</msg>
<msg timestamp="20211109 07:06:03.468" level="DEBUG">Suppress error: TypeError: locator.waitFor is not a function</msg>
<msg timestamp="20211109 07:06:03.631" level="DEBUG">Suppress error: TypeError: locator.waitFor is not a function</msg>
<msg timestamp="20211109 07:06:03.816" level="DEBUG">Using fail-screenshot-{index} to take screenshot.</msg>
<msg timestamp="20211109 07:06:03.831" level="TRACE">fail-screenshot-1</msg>
<msg timestamp="20211109 07:06:04.707" level="DEBUG">Screenshot succesfully captured to: H:\git\testautomation\browser\screenshot\fail-screenshot-1.png</msg>
<msg timestamp="20211109 07:06:04.833" level="INFO" html="true">&lt;/td&gt;&lt;/tr&gt;&lt;tr&gt;&lt;td colspan="3"&gt;&lt;a href="browser/screenshot/fail-screenshot-1.png"&gt;&lt;img src="browser/screenshot/fail-screenshot-1.png" width="800px"&gt;&lt;/a&gt;</msg>
<msg timestamp="20211109 07:06:04.833" level="FAIL">TypeError: locator.waitFor is not a function</msg>
<msg timestamp="20211109 07:06:04.833" level="DEBUG">Traceback (most recent call last):
  File "C:\Users\gdroes\AppData\Local\Programs\Python\Python38-32\lib\site-packages\Browser\browser.py", line 875, in run_keyword
    raise e
  File "C:\Users\gdroes\AppData\Local\Programs\Python\Python38-32\lib\site-packages\Browser\browser.py", line 865, in run_keyword
    return DynamicCore.run_keyword(self, name, args, kwargs)
  File "C:\Users\gdroes\AppData\Local\Programs\Python\Python38-32\lib\site-packages\robotlibcore.py", line 94, in run_keyword
    return self.keywords[name](*args, **(kwargs or {}))
  File "C:\Users\gdroes\AppData\Local\Programs\Python\Python38-32\lib\site-packages\Browser\keywords\waiter.py", line 92, in wait_for_elements_state
    return self._wait_for_elements_state(
  File "C:\Users\gdroes\AppData\Local\Programs\Python\Python38-32\lib\site-packages\Browser\keywords\waiter.py", line 132, in _wait_for_elements_state
    logger.info(response.log)
  File "C:\Users\gdroes\AppData\Local\Programs\Python\Python38-32\lib\contextlib.py", line 131, in __exit__
    self.gen.throw(type, value, traceback)
  File "C:\Users\gdroes\AppData\Local\Programs\Python\Python38-32\lib\site-packages\Browser\playwright.py", line 153, in grpc_channel
    raise AssertionError(error.details())</msg>
<status status="FAIL" starttime="20211109 07:05:53.758" endtime="20211109 07:06:04.833"/>
</kw>
<status status="FAIL" starttime="20211109 07:05:49.682" endtime="20211109 07:06:04.833">TypeError: locator.waitFor is not a function</status>
</test>
<status status="FAIL" starttime="20211109 07:05:47.109" endtime="20211109 07:06:05.187"/>
</suite>
<statistics>
<total>
<stat pass="0" fail="1" skip="0">All Tests</stat>
</total>
<tag>
</tag>
<suite>
<stat pass="0" fail="1" skip="0" id="s1" name="Mytest">Mytest</stat>
</suite>
</statistics>
<errors>
</errors>
</robot>

**Comment by gdroes** [comment]
Sorry I'v found the bug. 
My npm update failed.

**Comment by aaltat** [comment]
Good that you did figure the problem out.
