### ISSUE TITLE
Ease installation of nodejs

### ISSUE THREAD

**Issue by mkorpela** [MarketSquare/robotframework-browser#150]
**Is your feature request related to a problem? Please describe.**
Node must be separately installed. This is an extra step that can prevent some users from taking the lib into use.

**Describe the solution you'd like**
`rfbrowser init` should check if node is installed. If not open node installation page with [Python open browser](https://docs.python.org/3/library/webbrowser.html) or directly install nodejs.

**Describe alternatives you've considered**
Node could also be backed in the lib. But this works in odd way in cases where node is already available. Also many web projects will have node.

TODO:
- [x] On library import check that node is installed
- [x] Print error message in Robotland when library imported without correct dependencies / without node
- automate rfbrowser init

**Comment by xylix** [comment]
I added the check to `__init__.py` since now we also install node_modules there if not found. See a1c51041b6c5d87213dcd61b9417a75703e86c31 for details

**Comment by xylix** [comment]
https://github.com/MarketSquare/robotframework-browser/pull/170 Need some nice solution to pass a message when robot library import fails and then this should be done and mergeable.

**Comment by mkorpela** [comment]
Try writing to sys.__stdout__ and sys.__stderr__

**Comment by yanne** [comment]
Improved the error message behaviour in c3d337a2e48a2fa1791a190d62948a8247ef1d84
