### ISSUE TITLE
Code coverage possibility by using monocart-coverage-reports

### ISSUE THREAD

**Issue by pokaalinkanssayohon** [MarketSquare/robotframework-browser#1502]
**Is your feature request related to a problem? Please describe.**
We could run e.g. js based front end test coverage. 

**Describe the solution you'd like**
Solution / instructions / best practices to install needed plugins and configuration 

**Describe alternatives you've considered**
Cypress as js based framework but Robot framework with browser is cool. Playwright is brilliant base for browser plugin.

**Additional context**

**Comment by aaltat** [comment]
There is [Playwright API](https://playwright.dev/docs/api/class-coverage/) for coverage. It is not currently supported by Browser library, but is really interesting idea for enhancement. It also needs some node side dependency handling, most likely we need enhance `rfbrowser init` command. 

As workaround you install dependencies manually and write [JS extension](https://marketsquare.github.io/robotframework-browser/Browser.html#Extending%20Browser%20library%20with%20a%20JavaScript%20module) to start/stop coverage and report generation.

**Comment by aaltat** [comment]
@allcontributors please add @pokaalinkanssayohon for ideas.

**Comment by aaltat** [comment]
I am leaning towards https://www.npmjs.com/package/monocart-coverage-reports plugin. It has easier interface report configuration, good support for PW and allows good integration for Browser library.

**Comment by aaltat** [comment]
- Add link for coverage report in log.html
- Add possibly to give name for the coverage folder 
- Add command line method to combine reports 
- Move collection stop logic to node side.
