### ISSUE TITLE
Unable to launch webkit on Mac M1

### ISSUE THREAD

**Issue by Leemur89** [MarketSquare/robotframework-browser#1526]
**Describe the bug**
Hello, from a Mac machine with M1, the webkit browser fails to launch.
This was an issue in playwright v1.16.3n which has been fixed in v1.17.0
More details [here](https://github.com/microsoft/playwright/issues/10108)
Could you please upgrade the playwright version?

Thanks,

**Comment by aaltat** [comment]
When Playwright releases, we usually follow soonish with a new release which sets the new Playwright release as minimum supported version. Our Playwright version is not pinned, but might soon be #591 , so if you reinstall library currently you will get the latest Playwright release. 

For the 1.17.0, it's still in release candidate stage and we don't have plans to support beta/alpha/pre release versions from Playwright. 

We use https://docs.github.com/en/code-security/supply-chain-security/managing-vulnerabilities-in-your-projects-dependencies/configuring-dependabot-security-updates which automatically updates our dependencies for node side. Therefore I am going to close this issue.
