### ISSUE TITLE
yarn run lint does not work on Windows because lint script in package.json is using single quotes

### ISSUE THREAD

**Issue by rsandbach** [MarketSquare/robotframework-browser#1536]
**Describe the bug**
On Windows, `inv lint` fails to progress past yarn run lint because eslint requires double quotes when using globs ([on Windows](https://eslint.org/docs/user-guide/command-line-interface)).

**To Reproduce**
1. Run `inv lint` or `yarn run lint` on Windows.

**Expected behavior**
Linting succeeds.

**Screenshots**
![image](https://user-images.githubusercontent.com/8907955/143268757-dac4aed7-3c2c-4344-954e-5ece2088b06d.png)

**Additional context**
I have no way to test on Linux/Mac, unsure if changing to double quotes will break.

**Proposed Solution**
Update package.json
`"lint": "eslint \"node/**/*.{ts,tsx}\" --quiet --fix"`

**Comment by aaltat** [comment]
@allcontributors please add @rsandbach for bugs

**Comment by aaltat** [comment]
We did remove yarn as needed software. Therefore done in #1553

**Comment by rsandbach** [comment]
I think I incorrectly blamed yarn. the true culprit is that **eslint** requires double quotes.

**Comment by aaltat** [comment]
Could you try out with latest code in the `main` branch.

**Comment by rsandbach** [comment]
Still appears to be an issue, in windows environment, the quotes around the glob MUST be double quotes for some reason.

![image](https://user-images.githubusercontent.com/8907955/143657848-88860c56-424b-447f-a498-62bd669a9b40.png)

**Comment by aaltat** [comment]
Thank you for your patience. This should be now be fixed in master.
