### ISSUE TITLE
Install on a Docker image

### ISSUE THREAD

**Issue by fede-green** [MarketSquare/robotframework-browser#1588]
**Describe the bug**
I'm not able to install this with pip on a Docker image. 

**To Reproduce**
```
FROM ubuntu:18.04
[..]
RUN curl -fsSL https://deb.nodesource.com/setup_14.x | bash -
RUN apt-get install -y nodejs  #v12.22.7
RUN pip install robotframework-browser
```
This is the error i get: 

```
ERROR: Could not find a version that satisfies the requirement robotframework-browser (from versions: none)
ERROR: No matching distribution found for robotframework-browser
```
**Expected behavior**
I'd expect to install.

**Additional context**
BTW: i can't find a way to install this even directly on my laptop which runs on Ubuntu. Getting the same problem.

I wonder is this caused by having installed a bad version of node or something?

**Comment by aaltat** [comment]
Most likely pip in that image points to Python 2 and Browser library supports only Python 3.6+. I would assume that changing `pip` to  `pip3` solves the problem. But I am going to close this issue, because this is not Browser library problem. 

For future you will get faster and better support when reaching the Robot Framework community: https://robotframework.org/#community

**Comment by fede-green** [comment]
Thanks for helping... using pip3 doesn't solve the issue though. Same exact problem.

As i can install without any problem all the other libraries i tried: 

```
#Install the required libraries
RUN pip install --user robotframework
RUN pip install --user robotframework-sshlibrary
RUN pip install --user robotframework-seleniumlibrary
RUN pip install --user robotframework-requests
RUN pip install --user pyperclip
RUN pip install --user robotframework-xvfb
RUN pip install --user robotframework-csvlib
RUN pip install --user robotframework-browser
```
and browser is the only one i can't find a way to install... then i'd say the problem is indeed with this library?
