### ISSUE TITLE
Closing pages, contexts, browsers when scope ends

### ISSUE THREAD

**Issue by mkorpela** [MarketSquare/robotframework-browser#162]
**Is your feature request related to a problem? Please describe.**
It is rather easy to accidentally leave a page, a context or a browser open after it is no more needed.
We already close these at the end of execution.

**Describe the solution you'd like**
As a library listener we can define the position where test execution is when creating a page, a context or a browser.
We can also detect when the scope ends.
For example if "New Page" is called inside of a test case, we could close that page at the end of that test.
If a context is created in a suite setup we can also detect when that suite ends and close the context.

**Comment by aaltat** [comment]
What does scope here means?

**Comment by mkorpela** [comment]
For example a suite. If a browser is opened at the suite setup, then when exiting that suite, that browser would automatically be closed. Thus this same browser would not leak to other suites.

**Comment by mkorpela** [comment]
So a scope could be a suite or a test. And that would define the max life of that resource.

**Comment by xylix** [comment]
I was very skeptical at first but after some discussion in slack we figured some points out. Even more design is probably needed before this will be useful.

Why:
- Save time with test bugs where state has implicitly been passed from previous test / suite

What:
- Opened resources (browsers, contexts, pages) should not implicitly be available in following tests and / or suites
    - Maybe have the default be to have browsers available but contexts and pages close between suites

How:
- Use the robot framework Library Listener hooks to automatically clean up resources when suites change. This could also enable behaviour like parent folder `__init__.robot` opened resources being available to all suites but when set up in a suite's own setup let the resources close with the suite.

**Comment by mkorpela** [comment]
We can detect where a test execution is when creating a new resource and we have a hook on when test execution contexts change.

**Comment by mkorpela** [comment]
We are automating resource management. This is similar in my opinion to automatic memory management.

Making these tests the same:


   *** Test Cases ***
   Test non automatic
      New Page  url
      Do stuff
      Close Page

  Test automatic page close
      New Page  url
      Do stuff
   
So in ideal situation running a test individually should result in same test env as running the test in a set of suites.

**Comment by idxn** [comment]
Should we just let users specify a scope themselves and have a default value to suite? Then, the library would close things based on scope argument. Handle automatically might be too much and confused some users if they haven't read the document.

**Comment by mkorpela** [comment]
I propose the following:

When inside of a **test** or **test setup** or **test teardown**:

_New Page_:
- close page at the end of test
- close context at the end of test if not opened before test
- do not close browser

_New Context_:
- close context at the end of test
- do not close browser

_New Browser_ or _Open Browser_:
- close browser at the end of test

When in a **suite setup** or **suite teardown**:

_New Page_:
- close page at the end of suite
- close context at the end of suite if not opened before suite
- do not close browser

_New Context_:
- close context at the end of suite
- do not close browser

_New Browser_ or _Open Browser_:
- close browser at the end of suite

**Comment by mkorpela** [comment]
Also *Add ability* to disable autoclosing to library init

**Comment by mkorpela** [comment]
Related pull request https://github.com/MarketSquare/robotframework-browser/pull/196

**Comment by mkorpela** [comment]
Now auto_closing_level argument controls level.
