### ISSUE TITLE
Select Options By Keyword throws TimeoutError: locator.elementHandle

### ISSUE THREAD

**Issue by rlall07** [MarketSquare/robotframework-browser#1622]
**Describe the bug**
I am using robotframwork-browser 11.1.0. When running the following code, robot throws an error even though I can see the UI choosing the right option from dropdown. 

`Select Options By    select[id="shortcutsSimpleSelect"]    text   1w`

![image](https://user-images.githubusercontent.com/20052315/146403685-29b0a607-9649-4ebe-9458-fb539f89e613.png)
`
**To Reproduce**
Consider a dropdown element as : 
![image (12)](https://user-images.githubusercontent.com/20052315/146402401-0bd4cebf-00ef-427b-a298-7f43c1448bf5.png)

The testcode needs to select 1w from the dropdown. 
`Select Options By    select[id="shortcutsSimpleSelect"]    text   1w`

During runtime, I can see the UI selecting the correct option from the dropdown. But the robot still fails at the step with 
![image](https://user-images.githubusercontent.com/20052315/146403685-29b0a607-9649-4ebe-9458-fb539f89e613.png)`

**Expected behavior**
I expect the robot to select the correct option from the UI and pass. 
Same testcode used to pass for Browser library 3.2

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser:  chromium
 - Version:  Version 98.0.4695.0 (Developer Build) (64-bit)

**Comment by Snooz82** [comment]
actually i think the locator that is build by playwright is wrong! 
it should not search for value when using label

**Comment by aaltat** [comment]
This is actually bug in our side, our code does: 
```typescript
const locatorOptions = locator.locator(`option[value="${selectedOption}"]`); 
```
Which is not correct.

**Comment by aaltat** [comment]
@allcontributors please add @rlall07 for bugs.

**Comment by Snooz82** [comment]
@aaltat 
But Value and Text are different things!

label and text is same.
