### ISSUE TITLE
Type conversions not "working"

### ISSUE THREAD

**Issue by VernonCrabtree** [MarketSquare/robotframework-browser#1640]
**Describe the bug**
When I use ENum related arguments in Robot Framework and debug in Browser, I see the plain text in the argument variable.
From what I can tell, Robot Framework is supposed to perform automatic conversion on these arguments.

**To Reproduce**
Install latest versions of Python, Robot Framework and Browser.
Use any getter keyword with an assertion.

**Expected behavior**
The keyword accepts text and the text is converted to an ENum

**Screenshots**
I get an error: Attribute element=69e7e536-2798-4615-ae77-30fc51b8db8a `evaluate` is not a valid assertion operator.
This is because the text "evaluate" was not converted to an ENum.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome
Python 3.9.4
robotframework==4.1.3
robotframework-browser==11.1.1

**Additional context**

**Comment by VernonCrabtree** [comment]
I can't tell if this is specifically Browser related, or if it is something in Robot Framework.
I am not facing this issue with any other library - only with Browser. Browser library may be depending on some devilish trickery that has broken between versions of python/robot framework/browser.

**Comment by aaltat** [comment]
Would you be able to provide an example and show us the full stack trace.

**Comment by VernonCrabtree** [comment]
[Tests.zip](https://github.com/MarketSquare/robotframework-browser/files/7768398/Tests.zip)

Zip file contains a test script and debug output.

**Comment by VernonCrabtree** [comment]
I found a truly horrendous workaround:
${_:Given |When |Then |AND |}${id} button is ${state:enabled|disabled}
    Get element state    id=${id}    ${{Browser.ElementStateKey.disabled}}    ${{Browser.AssertionOperator.equal}}    ${{$state == 'disabled'}}

I would rather have this fixed. Considering downgrading my python version to see if that has something to do with it . . .

**Comment by VernonCrabtree** [comment]
I installed python 3.7 . . . it works absolutely perfectly.
I am guessing that Browser is depending on something that works in Robot Framework under python 3.7 now doesn't work in python 3.9
I wonder if python 3.10 fixes it again???
I also wonder if doing explicit type conversion in the library (in a generic fashion, like in the keyword decorator) might provide more stability for future releases.
Any thought?

**Comment by VernonCrabtree** [comment]
I have been staring at the code and I don't understand it.
ENums are complicated voodoo magic!
I don't think it worked previously because of Robot Framework auto argument conversion; I think Browser is broken in the new version of python because ENums in python has changed somehow. To prove this I have to debug Browser in the old version of python. This is very time consuming . .  .  I could really use some guidance here

**Comment by mkorpela** [comment]
I looked into the zip example.
Unfortunately it is not in a shape where it would be a reproducible example.
You are using some library `Library    BrowserForms`

The log shows failure on `New Browser` keyword and nothing related to the issues described here.
<img width="578" alt="Screenshot 2021-12-26 at 15 35 16" src="https://user-images.githubusercontent.com/136885/147409752-a87348d2-580d-4431-a43c-ad742c8c971f.png">

To help in this situation we need a repeatable example.

**Comment by VernonCrabtree** [comment]
Sorry - I forgot to remove "Forms": BrowserForms inherits from Browser and behaves the same in this case.
Attached a new run with Browser instead.
[Tests.zip](https://github.com/MarketSquare/robotframework-browser/files/7779593/Tests.zip)

You see the exact behavior I describe in the screen dump shown above: "'str' object has no attribute 'name'". 
This happens because New Browser has been passed a string rather than an object converted from the string to an ENum by Robot Framework automatic conversion. So my description of the problem should be "any keyword using ENums" instead of any getter keyword.

**Comment by VernonCrabtree** [comment]
I found it, after much debugging: "self.keywords_spec[kw_name] = KeywordBuilder.build(kw)" was missing in the code of robotlibcore. I discovered I had an extra module installed from somewhere.
Fixed it with:
pip uninstall robotlibcore-temp
