### ISSUE TITLE
Feature: Introduce ``AssertionsEngine``'s formatter to BrowserLibrary

### ISSUE THREAD

**Issue by robinmatz** [MarketSquare/robotframework-browser#1645]
**Is your feature request related to a problem? Please describe.**
In Version 0.3.0 [AssertionEngine](https://github.com/MarketSquare/AssertionEngine) introduced a new class, [Formatter](https://github.com/MarketSquare/AssertionEngine/blob/b1a8da662bb665657811d781f49392156a04eacd/assertionengine/formatter.py). It allows to configure library keywords to apply certain rules to values before performing the assertion on them.

Assume, for instance, ``Get Text    id=identifier`` returned "Hello${SPACE*3}World"

If you configure ``Get Text`` like the following
```
Set Keyword Formatters    {"Get Text": ["normalize spaces"]}
```

you can run the following assertion

```
Get Text    id=identifier    Hello World
```

without having to take care of eventual white spaces in the actual value. More formatters are defined in [formatter.py](https://github.com/MarketSquare/AssertionEngine/blob/b1a8da662bb665657811d781f49392156a04eacd/assertionengine/formatter.py).

**Describe the solution you'd like**
To introduce ``Formatter`` to BrowserLibrary, the following things are necessary
- ``Formatter`` needs to become part of ``libraries`` in browser.py
- Calls to AssertionEngine's ``verify_assertion`` need an additional argument ``formatter``
- Documentation needs to updated

**Describe alternatives you've considered**

**Additional context**
[This comment](https://github.com/MarketSquare/AssertionEngine/pull/35#issuecomment-997097455) contains links to examples how the implementation is done:
- https://github.com/MarketSquare/AssertionEngine/pull/40/files#diff-cde673d88ebf26e79cc8951f63bd62214082896fdee427f5e119bf8049f33a5d

**Comment by aaltat** [comment]
@allcontributors please add @robinmatz  for ideas.
