### ISSUE TITLE
[Feature] Add timeout argument to Wait For Alert

### ISSUE THREAD

**Issue by MoreFamed** [MarketSquare/robotframework-browser#1655]
**Is your feature request related to a problem? Please describe.**
I sometimes want to wait for alerts for different times. The cause of the difference is whether I know the alert has to appear (and thus I want to wait even for a longer time) versus it needs not to appear (and I want to wait for it just for a very short time).

**Describe the solution you'd like**
I'd like `Wait For Alert` keyword to have `timeout` argument, like almost all waiting keywords have.

**Describe alternatives you've considered**
The only workaround I know about is to set default timeout value before `Wait For Alert` runs and set it back again afterwards. It seems very inconvenient to me.

**Comment by Snooz82** [comment]
fixed in #3245
