### ISSUE TITLE
Python script promise_to always got error "No library '<Browser.browser.Browser object at 0x...>' found."

### ISSUE THREAD

**Issue by Massukio** [MarketSquare/robotframework-browser#1685]
**Describe the bug**
Python script promise_to always got error "No library '<Browser.browser.Browser object at 0x...>' found."

**To Reproduce**
test.py
```
from robot.api.deco import keyword
from Browser import Browser

@keyword
def test_keyword():
    lib = Browser()
    lib.new_browser(headless=False)
    lib.new_page(url='http://www.google.com')
    promise = lib.promise_to('Wait For Response')
    body = lib.wait_for(promise)
```
test.robot
```
*** Settings ***
Library  test.py

*** Test Cases ***
Test
    Test Keyword
```
test.robot result
```
==============================================================================
Test
==============================================================================
Test                                                                  | FAIL |
No library '<Browser.browser.Browser object at 0x000001B127FC01F0>' found.    
------------------------------------------------------------------------------
Test                                                                  | FAIL |
1 test, 0 passed, 1 failed
==============================================================================
```

**Expected behavior**
Run keyword succeed and the promise_to works properly

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: chrome
 - Version: robotframework-browser==11.1.1

**Additional context**
Use the "Promise To" in robot file, the test can be executed and pass properly

test2.robot
```
*** Settings ***
Library  Browser

*** Test Cases ***
Test
    New Browser
    New Page    url=http://www.google.com
    ${promise}=  Promise To    Wait For Response
    ${body}=  Wait For  ${promise}
```
test2.robot result
```
==============================================================================
Test2
==============================================================================
Test                                                                  | PASS |
------------------------------------------------------------------------------
Test2                                                                 | PASS |
1 test, 1 passed, 0 failed
==============================================================================
```

**Comment by aaltat** [comment]
@allcontributors please add @Massukio for bugs

**Comment by luchoagomezt** [comment]
> This is true and I can reproduce the problem. The problem lies in [here](https://github.com/MarketSquare/robotframework-browser/blob/main/Browser/keywords/promises.py#L50), library expect that it is imported in RF side and finds itself. Most likely you can workaround the problem by importing the Browser library in RF side and using this `lib = BuiltIn().get_library_instance("Browser")`.
> 
> But your way should be made possible and therefore I am considering this a bug.

@aaltat hello, I would like to help fixing this issue.  Are the instructions in CONTRIBUTING.md all that I need to follow?

**Comment by aaltat** [comment]
Well, we do not have any specific guidelines. How to setup dev environment is explained in https://github.com/MarketSquare/robotframework-browser/blob/main/CONTRIBUTING.md#development-environment Please ask if you find problems or inconsistencies.

**Comment by luchoagomezt** [comment]
> Well, we do not have any specific guidelines. How to setup dev environment is explained in https://github.com/MarketSquare/robotframework-browser/blob/main/CONTRIBUTING.md#development-environment Please ask if you find problems or inconsistencies.

Thanks, I create a local branch and tried to push it up stream, I received the following error:

**Comment by luchoagomezt** [comment]
> I remember when that was made, but it is some RF internal magic, which I am unfamiliar of. Perhaps summoning @Snooz82 @xylix or @mkorpela could share light why that is done like that. Also why we just do not use available library instance direct

I found that there isn't an entry  for Promise To in playwrigt.proto, I believe this is this is required

**Comment by aaltat** [comment]
> I found that there isn't an entry for Promise To in playwrigt.proto, I believe this is this is required

It is not needed, that keyword runs only in Python land.

**Comment by Snooz82** [comment]
I am not really on track, but Robot specific things can not be tested in pure python, without Robot execution context.

One thing that came to my mind to also import the library from a python lib would be first call BuiltIn().import_library and then get the imported Browser instance with BuiltIn().get_library_instance

Also had Browser these Listener features running, that only work with robot execution context. 

Maybe we should mark the keywords that are only executable with execution context?! 

Stuff like registering a keyword for failures male also no sense when running from pure python.

another thing to test would be Browser lib with RemoteLibrary...

**Comment by aaltat** [comment]
We do promote our Python API and this bug prevents extending library when promises are used. That is pretty big bug, running our library trough Python unit test is just easy way to demonstrate the problem. There is also example which uses RF as executor. 

I did look the code and it makes pretty big assumptions about the usage. Also I think there is room for improving the code. The failing part is the code which gets the arguments from Robot Framework, but it might be possible to solve that problem in other ways, example the argument specification is available in [PLC](https://github.com/robotframework/PythonLibCore).

**Comment by luchoagomezt** [comment]
> We do promote our Python API and this bug prevents extending library when promises are used. That is pretty big bug. Running our library trough Python unit test is just easy way to demonstrate the problem and there is also example which uses RF as executor.
> 
> I did look the code and it makes pretty big assumptions about the usage. Also I think there is room for improving the code. The failing part is the code which gets the arguments from Robot Framework, but it might be possible to solve that problem in other ways, example the argument specification is available in [PLC](https://github.com/robotframework/PythonLibCore).

Thanks for the link to the PLC, I am studying the code now.

**Comment by luchoagomezt** [comment]
@aaltat What do you think of the code in my previous comment?

**Comment by aaltat** [comment]
It hard codes the keyword, which is not good thing. Something more dynamic should be created. 

Side note: Discussing code is easier if you create a PR, then it is easier for us to read the code (it has nice syntax highlight) and we will see what part you changed and how it was changed. Also commenting code is easier.

**Comment by luchoagomezt** [comment]
> It hard codes the keyword, which is not good thing. Something more dynamic should be created.
> 
> Side note: Discussing code is easier if you create a PR, then it is easier for us to read the code (it has nice syntax highlight) and we will see what part you changed and how it was changed. Also commenting code is easier.

Thanks. I have opened a PR, please review

**Comment by aaltat** [comment]
Done in #1685
