### ISSUE TITLE
Python scripts Browser(run_on_failure=..) & register_keyword_to_run_on_failure both not working

### ISSUE THREAD

**Issue by Massukio** [MarketSquare/robotframework-browser#1686]
**Describe the bug**
Python scripts Browser(run_on_failure=..) & register_keyword_to_run_on_failure both not working

**To Reproduce**
test.py
```
from robot.api.deco import keyword
from Browser import Browser

@keyword
def test_keyword():
    lib = Browser()
    lib.new_browser()
    lib.new_page(url='http://www.google.com')
    lib.click("//img[@alt='Fake']")    <---  Expecting failure and take screenshot here

@keyword
def test_keyword2():
    lib = Browser()
    lib.register_keyword_to_run_on_failure('Take Screenshot')  <---  Expecting screenshot to be taken when failure occurs
    lib.new_browser()
    lib.new_page(url='http://www.google.com')
    lib.click("//img[@alt='Fake']")    <---  Expecting failure and take screenshot here
```
test.robot
```
*** Settings ***
Library  test.py

*** Test Cases ***
Test
    Test Keyword

Test Register Keyword On Failure
    Test Keyword2
```
output report
### *No screenshot being taken even if the register_keyword_to_run_on_failure is defined!*
![image](https://user-images.githubusercontent.com/13176540/149717103-8aab46a2-edf7-4369-b1f1-3285d8892437.png)

**Expected behavior**
Take screenshot on failure.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: chrome
 - Version: robotframework-browser==11.1.1

**Additional context**
Use the same test keyword on robot level, and the screenshot is taken properly.
```
*** Settings ***
Library  Browser

*** Test Cases ***
Test
    New Browser
    New Page    url=http://www.google.com
    Click  //img[@alt='Fake']
```
output report:
![image](https://user-images.githubusercontent.com/13176540/149716718-24bdaf45-e5e1-4ed8-8ac2-215594541998.png)

**Comment by aaltat** [comment]
Yes this is true and correct. The run on failure only works when library methods are run as keyword from Robot Framework. If methods are executed directly from Python, run on failure functionality does not work. Luckily implementing such functionality in your library should not be hard to do. 

But because this is not documented anywhere, we could improve the docs.
