### ISSUE TITLE
Incorrect path and filename when Take Screenshot registered to run on failure

### ISSUE THREAD

**Issue by tomekPawlak** [MarketSquare/robotframework-browser#1688]
**Describe the bug**
When **Take Screenshot** being registered to run on failure a filename is incorrectly named and storage path is incorrect.
`file:///C:/temp/Robot_output/Sandbox/Incorrect_path_and_filename_when_Take_Screenshot_registered_to_run_on_failure_FAILURE_SCREENSHOT_2.png`

**To Reproduce**
Look at the example code snippets:

```
Incorrect path and filename when Take Screenshot registered to run on failure
    [Setup]  New Page  https://www.yahoo.com/
    Browser.Register Keyword To Run On Failure  Take Screenshot
    Click  //button[@name="agree"]
    Wait Until Network Is Idle
    Wait For Elements State  ddd
    [Teardown]  Close Page

Correct path and filename when Take Screenshot implicitly called
    [Setup]  New Page  https://www.yahoo.com/
    Click  //button[@name="agree"]
    Wait Until Network Is Idle
    Wait For Elements State  ddd
    [Teardown]  Close Page

Correct path and filename when Take Screenshot explicitly called
    [Setup]  New Page  https://www.yahoo.com/
    Click  //button[@name="agree"]
    Wait Until Network Is Idle
    Take Screenshot
    [Teardown]  Close Page
```

**Expected behavior**
As described in doc:
`'filename' Filename into which to save. The file will be saved into the robot framework
         ${OUTPUTDIR}/browser/screenshot directory by default, but it can overwritten by providing
         custom path or filename. String '{index}' in filename will be replaced with a rolling
         number. Use this to not override filenames.`
So for this case it should be:
`file:///C:/temp/Robot_output/Sandbox/browser/screenshot/fail-screenshot-1.png`

**Screenshots**
INCORRECT
![image](https://user-images.githubusercontent.com/39945193/149741436-73b5fc09-74ef-487c-9428-2f7df76e513c.png)

CORRECT
![image](https://user-images.githubusercontent.com/39945193/149741658-d7c508a6-dc48-406f-bf6e-830a4820cc18.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 / docker image rfbrowser-stable:v11.1.1
 - Browser Chrome
 - Version 97.0.4692.71 (Official Build) (64-bit)

**Comment by aaltat** [comment]
Yes, this seems to be partially correct. Screenshot is created in wrong directory, in the ${OUTPUT} directory. But I think filename is correct, but it is undocumented feature.

**Comment by aaltat** [comment]
@allcontributors please add @tomekTieto for bugs

**Comment by aaltat** [comment]
Filename is undocumented feature. Improved docs to explain it better and also tell how to use the Take Screenshot default value.
