### ISSUE TITLE
Har file is not created

### ISSUE THREAD

**Issue by adrian-evo** [MarketSquare/robotframework-browser#1694]
I am trying to create a har file with the following code, however there is no har file saved anywhere. This used to work previously, but I don't know from which Browser version is not working anymore since I am not updating regularly.

```
*** Settings ***
Library    Browser    strict=False

*** Test Cases ***   

Test Har
    New Browser    chromium    headless=false
    ${har_data} =    Create Dictionary    path=test.har    omitContent=False
    New Context    recordHar=${har_data}
    New Page    https://edition.cnn.com/
    Wait For Elements State    text=World
    Close Page
    Close Context
    Close Browser
```

**Comment by aaltat** [comment]
Most likely har file is created, but it is created in the installation directory. Try this one: ` ${har_data} =    Create Dictionary    path=${OUTPUTDIR}/test.har    omitContent=False`

**Comment by adrian-evo** [comment]
Thanks. This issue was caused initially by https://github.com/microsoft/playwright/issues/11435. Closing a context created with recordHar would hang my test runs, so as a quick solution I commented out Close Context but then har file was not created. Later I discovered this playwright issue and that if I Close Page before Close Context, it will not hang test runs.
