### ISSUE TITLE
Browser / Pabot stuck forever

### ISSUE THREAD

**Issue by mkorpela** [MarketSquare/robotframework-browser#1712]
https://github.com/mkorpela/pabot/issues/321

Might be related to closing pw process

**Comment by tomekPawlak** [comment]
Observed this also with single run when redirecting to different page; occurs randomly. So pabot was not used. 
Also noticed that sometimes there's an error about pw process.

**Comment by aaltat** [comment]
I have never seen this, as far I can recall. So it is really rare event, closing.
