### ISSUE TITLE
Ability to reuse a browser context for parallel testing

### ISSUE THREAD

**Issue by aarondawg14** [MarketSquare/robotframework-browser#1722]
**Is your feature request related to a problem? Please describe.**
I would like the ability to open a browser and a new context, login once and then run numerous tests in parallel in that same context using different pages(tabs) for each test to run in parallel

**Describe the solution you'd like**
I would like the ability to open a browser and a new context, login once and then run numerous tests in parallel in that same context using different pages(tabs) for each test to run in parallel

**Describe alternatives you've considered**
Currently am opening up new browsers for parallel testing

**Additional context**
The overhead for spinning up browsers seems like a waste

**Comment by aaltat** [comment]
I think this is not easily possible, but there are ways to overcome the problem. Example you can login once, save the storage state and reuse it multiple times. Or se the token in headers. 

But because what you want, is not possible I am closing this issue.
