### ISSUE TITLE
Docstring abstraction

### ISSUE THREAD

**Issue by xylix** [MarketSquare/robotframework-browser#173]
Move often used docstrings into a file of constant docstrings and use them in specific documentation to ease editing and lessen clutter. Maybe use some i18n etc library for this

**Comment by Snooz82** [comment]
Not that i know.

We typically always do something like:
"For more information how to use assertions, see `Get Title`"

**Comment by aaltat** [comment]
And it's possible to link to the keyword. But it is not always that nice, because one needs to jump back and forth with the documentation. don't know, but it does not hurt to try it out.
