### ISSUE TITLE
Better handling of `downloadPath` and better documentation. Adding of `saveAs` argument to `Download` keyword.

### ISSUE THREAD

**Issue by xylix** [MarketSquare/robotframework-browser#1734]
**Describe the bug**

The docs for `New Browser` downloadsPath say this:
```
downloadsPath If specified, accepted downloads are downloaded into this folder. Otherwise, temporary folder is created and is deleted when browser is closed.
```

It does not state anything about what happens to files at browser close, if this is defined. At least a couple users have been mislead by this. 

**Expected behavior**
Either make the docs for `downloadsPath` clearly say that files get deleted in _any case_, or have files not be deleted if downloadsPath is set.

**Comment by aaltat** [comment]
The #1889 and this might have same root cause. Should be retested when next release goes out.

**Comment by Snooz82** [comment]
I also implemented that the `saveAs` argument, if given a relative path and if `downloadsPath` is set, will be relative to downloadsPath.
