### ISSUE TITLE
Fill Secret keyword fails with `${EMPTY}`

### ISSUE THREAD

**Issue by Atihinen** [MarketSquare/robotframework-browser#1738]
**Describe the bug**
If fill Secret is called with locator and value of builtin `${EMPTY}` the outcome is `Invalid variable name ''.`

**To Reproduce**
1. Call keyword like this:
```
Fill Secret   id=password_field   ${EMPTY}
```

2. See error `Invalid variable name ''.`

**Expected behavior**
I would expect to see something else.

**Desktop (please complete the following information):**
 - OS: bigSur
 - Browser: default
 - Version: default
 
**Additional context**
pip freeze content:

```
backports.cached-property==1.0.1
grpcio==1.43.0
grpcio-tools==1.43.0
overrides==6.1.0
protobuf==3.19.3
robotframework==4.1.3
robotframework-assertion-engine==0.4.0
robotframework-browser==11.3.0
robotframework-lint==1.1
robotframework-pythonlibcore==3.0.0
six==1.16.0
typing-utils==0.1.0
typing_extensions==4.0.1
wrapt==1.13.3
```

**Comment by aaltat** [comment]
@allcontributors please add @Atihinen for bugs

**Comment by aaltat** [comment]
I can reproduce the problem. Need to think how to fix it.
