### ISSUE TITLE
Some pages are not full-page screenshotted when fullPage argument is set

### ISSUE THREAD

**Issue by xylix** [MarketSquare/robotframework-browser#1743]
**Describe the bug**
It seems some web pages, including https://robotframework-browser.org/, do not get properly full page screenshot when trying to take a full page screenshot of them.

**To Reproduce**

Run the following robot
```
*** Settings ***
Library    Browser

Test Setup     Browser.New Browser    headless=True

*** Test Cases ***
Take Fullpage Screenshot of robotframework-browser.org
    Browser.New Page    https://robotframework-browser.org/
    Browser.Wait For Elements State    id=training
    Browser.Take Screenshot    fullPage=True    filename=EMBED
```

**Expected behavior**
Run above code but set URL to https://il.fi/ . A long full-page screenshot appears.
**Screenshots**

Bad case:
![robotframework-browser-screenshot-3](https://user-images.githubusercontent.com/13387304/152517355-3142d8bc-6633-417b-ad02-3056b14798aa.png)

Good case:

https://user-images.githubusercontent.com/13387304/152517392-b905108f-ad42-45e7-ae69-1177968bd752.png

**Desktop (please complete the following information):**
- OS: all seem to be affected
 - Browser: all 3
 - Versions affected: 8.0.3, latest 11.3.0

**Comment by xylix** [comment]
Possibly related to https://github.com/microsoft/playwright/issues/6188

**Comment by aaltat** [comment]
Because this is issue in PW, we can not fix this in our library side. If you want this to be fixed, please vote the issue in PW side.

Therefore closing this issue.
