### ISSUE TITLE
Make our 3 dockerfile setup simpler

### ISSUE THREAD

**Issue by xylix** [MarketSquare/robotframework-browser#1756]
**Is your feature request related to a problem? Please describe.**
Reported here on RF slack https://robotframework.slack.com/archives/C015KB1QSDN/p1644109575977369

Basically the fact that we have 3 separate dockerfiles is a bit misleading for users, and also means that we run our docker tests in a different docker than the one we publish.

**Describe the solution you'd like**
Have fewer docker images and same image for tests and publishing. The problem with this is that we don't want dev dependencies and our test app inside the published docker image. Perhaps we can just mount them when running our tests?

** Related **
https://github.com/MarketSquare/robotframework-browser/issues/211

**Comment by aaltat** [comment]
Should we move on using Playwright docker as base.

**Comment by xylix** [comment]
Yes we should.


Other changes discussed during weekly on 02.10.2022

- We should probably move to running our "test application" in a separate docker or on the system, instead of "building" test data into the docker.
  - So, we could have a flow where we build 1 publishable docker image, then we use it for our tests similarly to how we would instruct our users to use it.

**Comment by xylix** [comment]
Fixed by https://github.com/MarketSquare/robotframework-browser/pull/2683
