### ISSUE TITLE
'Run keyword if timeout occurred' keyword does not work with Browser keywords

### ISSUE THREAD

**Issue by Kahiis** [MarketSquare/robotframework-browser#1757]
**Describe the bug**
Timeouts related to Browser keywords don't seem to trigger the `Run keyword if timeout occurred` at all

**To Reproduce**
I've managed to recreate the behavior using the following page.html file
```
<html lang="en">
<head>
</head>
<body>
<button id="ThisIdDoesExist"> 
    <h3>namegoeshere</h3>
    <p>42</p>
    <p>24</p>
</button>
<button id="DisabledButton" disabled> 
    <h3>disabled</h3>
    <p>42</p>
    <p>24</p>
</button>
</body>
</html>
```

And the following test file
```
*** Settings ***
Library    Browser
Suite Setup    Example suite Setup

*** Test Cases ***
# Works and prints Foo
Non-Browser keyword timeout
    Artificial timeout
    [Teardown]    Run keyword if timeout occurred    Foo

# Does not work :(
Browser keyword timeout
    New page    ${EXECDIR}/page.html
    Wait for elements state    id=ThisIdDoesNotExist
    [Teardown]    Run keyword if timeout occurred    Foo

# Does not seem to work either
Another browser keyword timeout
    New page    ${EXECDIR}/page.html
    Click    id=DisabledButton
    [Teardown]    Run keyword if timeout occurred    Foo

*** Keywords ***
Example suite Setup
    New browser    chromium    headless=false
    New context
    
Artificial timeout
    [Timeout]    5s
    Sleep    6s

Foo
    Log to console    Foo going to RF
    New page    https://robotframework.org/
    Sleep    5s
    Close page
```
I also noticed that the in the test logs, they claim that the teardown was successful. However, when the timeout originates from a browser keyword, the log does not show that any of the steps in the `Foo` keyword were executed, unlike in the first test case. See the screenshot.

Should be mentioned I haven't tested this with all keywords that can throw a timeout error.

**Expected behavior**
In the last 2 test cases I expect every action in the Foo-keyword to be executed.

**Screenshots**
![image](https://user-images.githubusercontent.com/26903759/152995390-399f4375-59c4-41e1-828c-6459d25acc00.png)

**Desktop (please complete the following information):**
 - OS: Windows 21H2
 - Browsers: Chromium, firefox and webkit
 - Python version 3.10.0, Robot Framework version 4.1.3, Browser version 11.3.0

**Comment by aaltat** [comment]
Discussed in slack and it's working as designed. Above example has timeout only for one test case.
