### ISSUE TITLE
virtual_mouse.robot with keyword test that is always true

### ISSUE THREAD

**Issue by UliSei** [MarketSquare/robotframework-browser#1794]
It is about virtual_mouse.robot, Test Case **Drag and Drop with coordinates**, lines 64 and 65.
The assertion is about testing whether the dragged object coordinates are the same as the coordinates of the destination object.
However the tests with given numbers for x and y ...
```
    Should Be True    ${x_diff} < 1 or ${x_diff} > -1
    Should Be True    ${y_diff} < 1 or ${y_diff} > -1
```
... are always true. 

**Suggestion:**
```
    Should Be True    -1 < ${x_diff} and ${x_diff} < 1
    Should Be True    -1 < ${y_diff} and ${y_diff} < 1
```

**Comment by UliSei** [comment]
Test result with changed lines 64 and 65:
![grafik](https://user-images.githubusercontent.com/89480399/155298007-6980cce4-927a-42c6-8709-459416f01e46.png)

If there aren't any objections I'd create a PR.

**Comment by aaltat** [comment]
Done in #1799
