### ISSUE TITLE
Keyword for "waiting for the page to load completely"

### ISSUE THREAD

**Issue by gvr-kumar** [MarketSquare/robotframework-browser#1795]
**Is your feature request related to a problem? Please describe.**
I think we dont have a keyword to "wait for the page to load completely" so that it also waits for asynchronous calls.

**Describe the solution you'd like**
Looking for a keyword in Browser Library to "Wait for the page to load completely" so that it also waits for asynchronous calls. In my AUT, I have 2 scenarios:

Scenario1: After navigating to the page, top section of the page loads first and then couple of seconds later the remaining section of the page loads.

Scenario2: In this scenario, even after page loads, couple of seconds later I see a loading icon and there is asynchronous call. 

**Describe alternatives you've considered**

In Scenario1, I am using multiple "Wait For Elements State" keywords.

In Scenario2 also, I am using "Sleep" and also "Wait For Elements State" keyword.

Instead of these, it would be great if is there a keyword for waiting the page to load completely **(something like this: document.readyState is complete?)**, tests would pass consistently and reduce redundant lines of code.

**Comment by aaltat** [comment]
That is very hard problem, which can not be solved in way which would suite in every need. Instead you should look at different [http keywords](https://marketsquare.github.io/robotframework-browser/Browser.html?tag=HTTP) which may offer the functionality you need.

If you have enhancement ideas after reviewing the keywords, please do not hesitate to say what functionality library is missing.

**Comment by aaltat** [comment]
Because there are other keyword to accomplish the needs, I will close the issue. If your needs are not met, please raise an issue and explain what you are missing.

**Comment by gvr-kumar** [comment]
thankyou Aaltat.
