### ISSUE TITLE
Select Options By is mixing value and text SelectAttribute and wrongly returns strict mode violation

### ISSUE THREAD

**Issue by adrian-evo** [MarketSquare/robotframework-browser#1796]
In the latest Browser version 12.0, this keyword behaves differently and thus it breaks some particular test cases.

I have the following combo box:
![image](https://user-images.githubusercontent.com/19324942/155326793-899e46bf-17b7-48f1-9b13-3b212a7c1d5b.png)

and when I select with:

`Select Options By  .cstic-required >> text=1-channel >> xpath=..//select    text    0`

it returns:

```
waiting for selector ".cstic-required >> text=1-channel >> xpath=..//select >> nth=0 >> xpath=./option[@value="1" or text()="1"]"
  strict mode violation: ".cstic-required >> text=1-channel >> xpath=..//select >> nth=0 >> xpath=./option[@value="1" or text()="1"]" resolved to 2 elements:
    1) <option value="1">0</option> aka playwright.$("text=1-channel012 >> select")
    2) <option value="2">1</option> aka playwright.$("text=1-channel012 >> select")


```
If I select by value or by index, the error is the same. I don't see any workaround for this situation currently.

**Comment by aaltat** [comment]
This is regression caused by https://github.com/MarketSquare/robotframework-browser/pull/1786 @Snooz82 warned me about this one and looks like I need to go with the direction he did suggested.

@allcontributors please add @adrian-evo for bugs

**Comment by Snooz82** [comment]
Wow. That was quick.

**Comment by aaltat** [comment]
Indeed it was, but I am fixing it and then I will push new release out.

**Comment by aaltat** [comment]
12.0.1 is out which should fix the problem.
