### ISSUE TITLE
Add waitUntil support for New Page and Go To keywords 

### ISSUE THREAD

**Issue by aaltat** [MarketSquare/robotframework-browser#1811]
[Wait For Navigation](https://marketsquare.github.io/robotframework-browser/Browser.html#Wait%20For%20Navigation) has support for `wait_until` which allows support for different [page load](https://playwright.dev/docs/api/class-page#page-goto) states. Similar functionality should be implemented for Go To and New Page keywords.

**Comment by Snooz82** [comment]
implemented by #3232
