### ISSUE TITLE
Why Browser library still requires to install NodeJS 

### ISSUE THREAD

**Issue by lynhbn** [MarketSquare/robotframework-browser#1814]
Just my concern, but I saw that playwright native python support is available, why Browser library still requires to install NodeJS to run?

Thank you for your answer!

**Comment by aaltat** [comment]
Browser library was build before native Python support was available for Playwright. We have discussed this internally few times and the conclusion is the following. 
1) It is lot of work
Moving to Python only land would be lot of work. There is lot of code in the node side, which would need to rewritten in Python. Also it is not only about library code, we could need be rewriting installation, providing migration, do support and many more activities. The cost of the moving to Python only land, even it is tempting and would bring benefits, is currently too high. All that time would be taken away from the library development/features and so one. Also like many other open source projects, most of the work is not funded by a company/foundation. Some people may be able to contribute hour or two in company time, but this work would require few people in few months in full time. 

2) Losing features
Also the change would be backwards incompatible, we would loose our NodeJS library API, which we think will ease the usage in the front end development. Also we might loose something else which  I am not able remember right now. 

3) Loosing the fun of development
At least for me this project has provided me learning platform and reason to learn NodeJS world. If we would move to Python only land, at least I would loose some part of my motivation to develop the library. 

We understand that living in both Python and NodeJS worlds is not always seamless from the users point of view (also same feeling is sometimes seen in dev side), but currently we do not have any plans to move in Python only land.

**Comment by aaltat** [comment]
Closing issue because question is from my point of view answered. If you have more questions, please don't hesitate to ask.
