### ISSUE TITLE
Received message larger than max (5406604 vs. 4194304)

### ISSUE THREAD

**Issue by JaPyR** [MarketSquare/robotframework-browser#1815]
**Describe the bug**
I have a test case where I need to wait for request end before further interacting with page so my code look like:
```
${promise}    Promise To    Wait For Response    matcher
....
<Some Actions>
....
Wait For    ${promise}

```
If I understand correctly size of the response (big json, around 5 megabytes and I am not interested in it's content) is the reason why keyword `Wait For` fails with message "Received message larger than max (5406604 vs. 4194304)".

**Comment by aaltat** [comment]
We use gRPC to communicate between Python and Node lands. Messages have max limit and if that exceeded, keyword will fail. Unfortunately there is not way to increase the max limit of the message. 

I guess we could cut the json and make it fit to the maximum message size. But in that case, we would not return valid json and are in dancer to loose something important information. 

But I agree that how keyword works now, is not correct either and it should be fixed, in one way or another.

**Comment by aaltat** [comment]
@allcontributors please add @JaPyR for bugs.

**Comment by Sathish787** [comment]
Any updates on this guys? Is there any alternative approach for this

**Comment by aaltat** [comment]
Currently there is not, I tried once to solve the problem, but could not get the node side working.

**Comment by lgaitan** [comment]
I'm facing the same issue

**Comment by aaltat** [comment]
Fix is available in next release
