### ISSUE TITLE
Should be able to change color and timeout for "enable_presenter_mode" argument in the "Library"

### ISSUE THREAD

**Issue by gvr-kumar** [MarketSquare/robotframework-browser#1816]
**Is your feature request related to a problem? Please describe.**
Yes, the default color for **"enable_presenter_mode"** argument in the "Browser Library" is blue and its getting mixed with html elements in our UI which are of same color 

**Describe the solution you'd like**
I would like to be able to change the default color, **change the border style as well (solid border for example)** and time out for "enable_presenter_mode" argument in the "Browser Library"

**Describe alternatives you've considered**
I am using "Highlight Elements" keyword instead

As you could see in the screenshot, Yes button is in blue and cant see it highlighted when used "enable_presenter_mode"

![image](https://user-images.githubusercontent.com/11802756/156045559-3d033250-a478-45db-a303-e666b6010f8d.png)

**Comment by aaltat** [comment]
@allcontributors please add @gvr-kumar for ideas.

**Comment by aaltat** [comment]
Decided at same go support all the configuration options which are currently supported by the [Highlight Elements](https://marketsquare.github.io/robotframework-browser/Browser.html#Highlight%20Elements) keyword: duration, width, style and color. duration will also affect how long keyword will sleep after highlight.

**Comment by gvr-kumar** [comment]
Thankyou so much Aaltat
