### ISSUE TITLE
JS extensions to support more than just positional arguments

### ISSUE THREAD

**Issue by mkorpela** [MarketSquare/robotframework-browser#1833]
**Is your feature request related to a problem? Please describe.**
Currently only positional string arguments are supported.
This limits how the interface can be used and how an editor can help the RF developer with it.

**Describe the solution you'd like**
Add possibility to expose arguments with names.
Reserve specific names to be (mostly) backwards compatible and future proofed.

Reserved at least (and also must be in python specific order)
```
self (no allowed use)
this (no allowed use)
page => https://playwright.dev/docs/api/class-page
args => ..args: string[]
logger => (data:string):void (logger function)
playwright => playwright module (* from 'playwright')
kwargs => **kwargs
```

Previous setup has not considered names. This may result in breaking some of the old extensions.

Also improve the docs. (no more experimental and add rfdoc example etc).

Example
```
function myFunc(a, b, c, args, d='default', kwargs, page, logger, playwright) {
..
}
```
I think the order is also meaningful to match how python and robot framework work.
Special vars must be after others OR follow the old API `(page, args, logger, playwright)`.

**Comment by Snooz82** [comment]
@mkorpela 

i was more thinking of having a more lightweight argument interface.

```javascript

function setLibraryContext(page, logger, playwright) {
  this.playwright = playwright 
  this.logger = logger
  this.page = page
}

function myFunc(a, b, c, args, d='default', kwargs) {
..
}
```

this would reduce args on each function,
We could easily check if the `setLibraryContext` function is present, and if not, it is the old behavior.
And this would allow us to add more context fields in the future.

we could also create a master class that just could be inherited maybe? So users do not have to care about the context creation!?

**Comment by mkorpela** [comment]
https://github.com/MarketSquare/robotframework-browser/pull/1834

**Comment by mkorpela** [comment]
```
❯ python -m robot.libdoc Browser::jsextension=docs/examples/babelES2015/lib/index.js show funkkari
Funkkari
--------
Arguments:  [*args]

argumentti, argu2, argu3
```

**Comment by mkorpela** [comment]
https://robotframework.org/robotframework/latest/RobotFrameworkUserGuide.html#getting-keyword-arguments

**Comment by mkorpela** [comment]
Still:
docs and more tests.

**Comment by aaltat** [comment]
is this backwards incompatible or should we remove the label?

**Comment by mkorpela** [comment]
Depends on what we have promised so far

**Comment by mkorpela** [comment]
I'll remove the backwards incompatible warning.

**Comment by aaltat** [comment]
This was done in #1834
