### ISSUE TITLE
Should be able to highlight for "Get Text" keyword also when the "enable_presenter_mode" argument is True in the "Library"

### ISSUE THREAD

**Issue by gvr-kumar** [MarketSquare/robotframework-browser#1835]
**Is your feature request related to a problem? Please describe.**
Yes, should be able to highlight for "Get Text" keyword also when the "enable_presenter_mode" argument is True in the "Library".

May be we can highlight for "Get Attribute" and  "Get Property" as well.

**Describe alternatives you've considered**
I am using "Highlight Elements" keyword instead

**Comment by aaltat** [comment]
Added support for `Get Text`, `Get Property`, `Get Attribute`, `Get Select Options`, `Get Style` and `Get Element States` keywords.

**Comment by gvr-kumar** [comment]
thankyou Aaltat
