### ISSUE TITLE
Method get_elements returns invalid references

### ISSUE THREAD

**Issue by luchoagomezt** [MarketSquare/robotframework-browser#1849]
**Describe the bug**
When passing a selector to get multiple elements, the method get_elements returns a list of references with the first reference containing a recursive invalid value.  
 
**To Reproduce**

![image](https://user-images.githubusercontent.com/4672517/157711823-a9d1a25b-dd80-461e-acf8-ee64fb754693.png)

line 608, **headers_alt** is assigned a list of references to all the headers in the table  
line 617, while executing get_text(header_alt), an exception ElementNotFoundException: Error: strict mode violation is thrown.

![image](https://user-images.githubusercontent.com/4672517/157718308-16ac3334-f84c-4942-bd92-303205015917.png)

Setting strict_mode(False)  results to the same exception error.

**Expected behavior**
In the snipped code, line 613, does not make get_text throw an exception.  

The headers are obtained in two steps, refer to lines 600 and 604.  At line 600, the code first gets the reference to the table and then in line 604 chains the reference to another selector to get the headers.

Both methods should not make get_text throw an exception.

**Screenshots**
Please refer to the description of the bug above. 

**Desktop (please complete the following information):**
 - OS: Windows 10 Enterprise
 - Browser: Chromium
 - Version

**Smartphone (please complete the following information):**
Not Applicable

**Additional context**
This is the sample table, with headers and two test data rows

![image](https://user-images.githubusercontent.com/4672517/157718623-fcf18af0-f5eb-4282-a403-36965c73b8f0.png)

**Comment by aaltat** [comment]
@allcontributors please add @luchoagomezt for bugs.

**Comment by luchoagomezt** [comment]
I am attaching a sample scenario with html files and python unit test cases: 

[Website.zip](https://github.com/MarketSquare/robotframework-browser/files/8257492/Website.zip)
[test_get_elements.py.txt](https://github.com/MarketSquare/robotframework-browser/files/8257512/test_get_elements.py.txt)

The issue presents itself when part of the selector is as an iframe, for instance as follows:

**Comment by aaltat** [comment]
I can reproduce the problem based on the provided example. 

@allcontributors please add @luchoagomezt for bugs.
