### ISSUE TITLE
jsextension is not possible to call

### ISSUE THREAD

**Issue by Krata4** [MarketSquare/robotframework-browser#1866]
**Describe the bug**
In last veriosn (12.2) it is not possible to call jsextension. When I tried same code in 12.1 version, it is working.

**To Reproduce**
- some jsextension.js file with custom KW or register locator
- call this KW from Robot Framework
- and you are gettting error:
Keyword 'Browser.Register My Selector 2' missing named-only argument 'log'.

**Expected behavior**
you can call KWs from JS

**Comment by mbondarew** [comment]
Hello @Krata4,
I got the same error. To solve this rename the third argument `log  --> logger`, e.g.:
```js
module.exports[keyword] = async (page, args, logger) => {
    //...
}
```
https://github.com/MarketSquare/robotframework-browser/blob/e8b4657ba17ce995c1d92007c67272b1f68393fd/Browser/browser.py#L807

**Comment by Krata4** [comment]
When I changed log --> logger it is working. Thanks for help

**Comment by Krata4** [comment]
not possible fix. It was incopatible change from version 12.1 to 12.2  It is important to change JS interface.
