### ISSUE TITLE
Support installation also from enviroments which do not have access to public internet.

### ISSUE THREAD

**Issue by aaltat** [MarketSquare/robotframework-browser#188]
Currently installation is two step process. 

1. Install library with `pip` 
1. When RF imports library, it install node packages

The 1. step can be done also in environments where access to public internet is not available, example by using custom pypi repository or mirror. But the 2. step is more problematic because it is done during run time and there are not a way to configure a npm mirror (or something else which is possible in the npm world.)

I think it would be nice to have possibility to install all from command line. I think the main usage case is to prep VM/container or whatever for CI usage, where stuff is preppared before hand and deployed automatically.

**Comment by xylix** [comment]
Seems like this feature https://docs.npmjs.com/misc/config is the one that is usually used to configure npm install mirrors / proxies. In theory just setting correct environment variables should? work. I have no experience with NPM proxies though.

Would be best to find a real world user case so we can figure out what workings we need to verify.

**Comment by xylix** [comment]
One option would be to offer pre-installed binaries for users in settings where they can't use internet

**Comment by xylix** [comment]
Since we provide Docker images now and NPM and pypi support PROXY environment variables this will be closed. If user's have new kinds of needs in offline environments lets open new issues.
