### ISSUE TITLE
${OUTPUT_DIR}/browser has deleted between suites, when test case fails

### ISSUE THREAD

**Issue by jokinr** [MarketSquare/robotframework-browser#1889]
**Describe the bug**
Test case fails, but screenshot is not visible in log.html file. When we debugging  this, we noticed that browser folder has beed deleted between suites. Looks like that browser folder has lost after first failure and after that it not happen again in same run. It could be difficolt to notice this, because if second failure will came, then 1. and 2. failure will share the screenshot file and then user can see picture in log.html, even if wrong screenshot in case of 1. failure

**To Reproduce**
![image](https://user-images.githubusercontent.com/46047015/159431453-b87dd3e1-35bc-4d4d-a55b-b739c15fde68.png)

**Screenshots**
![image](https://user-images.githubusercontent.com/46047015/159431869-2476d7f0-430a-4427-82e9-76c12d9aa6a7.png)

**Desktop (please complete the following information):**
 - OS: Windows 10/Ubuntu 20
 - Browser: chromium/firefox
 - Version: robotframework-browser 11.0.0/12.2.0

**Comment by aaltat** [comment]
I can reproduce this, also when test case does not fail. 

@allcontributors please add @jokinr for bugs.
