### ISSUE TITLE
Docs: New Browser keyword documentation mentions a wrong default value for `headless`

### ISSUE THREAD

**Issue by janipalsamaki** [MarketSquare/robotframework-browser#1890]
[`New Browser`](https://marketsquare.github.io/robotframework-browser/Browser.html#New%20Browser) keyword documentation section mentions a wrong default value for `headless`:

> headless Set to False if you want a GUI. Defaults to False.

**Comment by aaltat** [comment]
Thank you for spotting the problem 

@allcontributors please add @janipalsamaki for bugs.
