### ISSUE TITLE
Drag and Drop Relative To does nothing

### ISSUE THREAD

**Issue by piyushasaran12** [MarketSquare/robotframework-browser#1892]
**Describe the bug**
Drag And Drop Relative  To does not move the mouse by coordinates specified

**To Reproduce**
1. Go to ' the browser '
2. Identify the selector to perform the swipe action.
3. Extract some coordinate of a swipe action from starting point to end point
4. Use the Drag And Drop Relative To with the coordinates extracted in step3

**Expected behavior**
The mouse is moved to exact coordinates and proceeded to next step.

**Desktop (please complete the following information):**
 - OS: Windows 
 - Browser Chrome
 - Version 99.0

**Comment by aaltat** [comment]
With this information it is not possible to provide solution for you. 

Could you provide an example, how you actually use the keywords and what is not expected. Also could you show us the relevant parts from the log file.

**Comment by aaltat** [comment]
Closing due inactivity.
