### ISSUE TITLE
Unable to launch robot script in Firefox using Open Browser keyword

### ISSUE THREAD

**Issue by akhilPanickerJPL** [MarketSquare/robotframework-browser#1901]
Unable to launch robot script using firefox in _Open Browser_ keyword

**Steps to reproduce the behavior:**
1. Keyword used - `Open Browser    https://www.amazon.in/    firefox`
2. Run the Robot file
3. See error
```
console.warn: SearchSettings: "get: No settings file exists, new profile?" (new NotFoundError("Could not open the file at C:\\Users\\user\\AppData\\Local\\Temp\\playwright_firefoxdev_profile-PdZ4Ra\\search.json.mozlz4", (void 0)))
[pid=22080][out] console.error: Region.jsm: "Error fetching region" (new Error("TIMEOUT", "resource://gre/modules/Region.jsm", 772))
[pid=22080][out] console.error: Region.jsm: "Failed to fetch region" (new Error("TIMEOUT", "resource://gre/modules/Region.jsm", 419))
```
**Expected behavior**
Firefox should launch and script should work fine. 
Note - Works fine for chromium and webkit.

**Desktop:**
 - Windows 10
 - Firefox
 - Nightly 96.0.1
 - IDE: VS Code

**Additional query**
I have the latest `geckodriver` and a newer version of stable Firefox (98.0.2) on my machine. Is there a way I can use that instead of the nightly builds that are installed after `rfbrowser init`?
[playwright-log.txt](https://github.com/MarketSquare/robotframework-browser/files/8342969/playwright-log.txt)

**Comment by akhilPanickerJPL** [comment]
Log file - 
[playwright-log.txt](https://github.com/MarketSquare/robotframework-browser/files/8342956/playwright-log.txt)

**Comment by aaltat** [comment]
It is not possible to use Firefox which Mozilla provides. Playwright does customization on WebKit and Firefox, so that they can provide same functionality that is available that is Chromium. Therefore browser binaries are bundled in the Playwright installation. 

I could run `pip install --upgrade robotframework-browser`, `rfbrowser clean-node` and `rfbrowser init` again and see does it help.

**Comment by akhilPanickerJPL** [comment]
> I could run pip install --upgrade robotframework-browser, rfbrowser clean-node and rfbrowser init again and see does it help.

I did this. No luck.

> rfbrowser init

Did this as well. Got a success message and no errors. 

Anyway, closing this ticket for now. Will see if I can figure out a solution for #1902 and then retry firefox launch.
