### ISSUE TITLE
Add Capture Console Messages keyword

### ISSUE THREAD

**Issue by dgalezow** [MarketSquare/robotframework-browser#1937]
It would be great if we could gather logs from browser console for easier debugging of test fails

[From slack by René](https://robotframework.slack.com/archives/C015KB1QSDN/p1649142992754909?thread_ts=1649142776.828639&cid=C015KB1QSDN)

Quote internal idea:
----------------------------
we could collect all console messages, once a keyword like “Capture Console Messages” is called on a page.
Then we collect an array of ConsoleMessage objects as dictionaries/json plain objects.

`{
  type: ..,
  text: ..,
  location: {
    url: ..,
    lineNumber: ..,
    columnNumber: ..
  }
}`

https://playwright.dev/docs/api/class-consolemessage

With Get Captured Console Messages we return the array, which has been collected by the event listener

The Get Captured Console Messages keyword could also have some kind of arguments to filter the messages. by time or amount
Like:
`Get Captured Console Messages    history=20 sec`
or
`Get Captured Console Messages    last=30`

**Comment by aaltat** [comment]
@allcontributors please add @dgalezow for ideas.

**Comment by mkorpela** [comment]
Removing priority high as this is already available in `Close Context`

**Comment by aaltat** [comment]
Closing this on favor of #2176
