### ISSUE TITLE
Preloaded page

### ISSUE THREAD

**Issue by mkorpela** [MarketSquare/robotframework-browser#1949]
**Is your feature request related to a problem? Please describe.**
Webapp we are testing takes time to initialize.
Creating a page per test or reloading the page to cleanup takes some time.
I would like to speed up this.

**Describe the solution you'd like**
I was thinking that a mechanism to initialize two pages at the beginning. Then initializing an extra one whenever a test is executed.
This would make the new page to be loaded on the background while still executing the previous test.

**Describe alternatives you've considered**
One other thing I was thinking was a conditional new page if the previous test failed..

**Comment by aaltat** [comment]
I think creating pool/cache of pages is good idea.

**Comment by aaltat** [comment]
I am going to close this one, if we need to do this, we can reopen or create new issue.
