### ISSUE TITLE
Reuse ESM Playwright page object Angular library as Robot keywords

### ISSUE THREAD

**Issue by testgitdl** [MarketSquare/robotframework-browser#1959]
**Describe the bug**
We have several flavors of TA frameworks and would like at a higher level to be able to reuse the page objects created in TypeScript as keywords that can be executed via Robot via the Playwright browser. This we did achieve but it implies changing the original *.po.ts files. Our typescript page objects can only be imported if we remove the classes and change the imports. So ESM seem not to be supported and the functions set as keywords cannot be inside classes.
It seems like ESM is not supported. Is there any way we can use this kind of POlibraries?

**To Reproduce**
1. Create a Robot test case that uses Playwright browser and a "StartApplication" keyword as below:
 *** Settings ***
Library Browser jsextension=${CURDIR}/Test.ts
*** Tasks ***
Use a JavaScript-based keyword
New Browser chromium headless=false
New Page http://playwright.io
startApplication

2. try to reuse the PO that is part of an inhouse PO library
Contents of App.ts:
import { expect } from 'chai';
import { Page } from 'playwright';
export class App {
    // public page: Page;
    static page: any;
    constructor(page1: Page) {
    App.page = page1;
    }
      static async startApp() {
          await this.page.waitForSelector("#title > span");
          const found_title = await this.page.locator('#title > span').nth(0).textContent();
          expect(found_title.trim()).equals('Playwright');
        }
}

Contents of Test.ts (that is imported in the Robot test as library and exposes the StartApplication TS function as a keyword):
import {App } from "./app.ts";
async function startApplication(page) {
  await App.startApp();
};
exports.__esModule = true;
exports.startApplication = startApplication;

**Expected behavior**
In this case we get an error that the import cannot be used outside of a module
Error in file 'C:\Utils\Playwright\Robot\tests\Test1.robot' on line 2:
Initializing library 'Browser' with arguments [
jsextension=C:\Utils\Playwright\Robot\tests/Test.ts ] failed:
SyntaxError: Cannot use import statement outside a module
Traceback (most recent call last):
File
"c:\utils\robotframework\lib\site-packages\Browser\playwright.py", line
149, in grpc_channel
yield playwright_pb2_grpc.PlaywrightStub(self._channel)
File "c:\utils\robotframework\lib\site-packages\Browser\browser.py",
line 780, in _initialize_jsextension
response = stub.InitializeExtension(
File "c:\utils\robotframework\lib\site-packages\grpc\_channel.py",
line 946, in __call__
return _end_unary_response_blocking(state, call, False, None)
File "c:\utils\robotframework\lib\site-packages\grpc\_channel.py",
line 849, in _end_unary_response_blocking
raise _InactiveRpcError(state)
grpc._channel._InactiveRpcError: <_InactiveRpcError of RPC that
terminated with:
status = StatusCode.RESOURCE_EXHAUSTED
details = "SyntaxError: Cannot use import statement outside a module"
debug_error_string =
"{"created":"@1649833553.009000000","description":"Error received from
peer
ipv6:[::1]:51905","file":"src/core/lib/surface/call.cc","file_line":906,"grpc_message":"SyntaxError:
Cannot use import statement outside a module","grpc_status":8}"
>
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
File "c:\utils\robotframework\lib\site-packages\Browser\browser.py",
line 745, in __init__
libraries.append(self._initialize_jsextension(jsextension))
File "c:\utils\robotframework\lib\site-packages\Browser\browser.py",
line 788, in _initialize_jsextension
self._jskeyword_call(component, name, args, doc)
File "c:\utils\robotframework\lib\contextlib.py", line 131, in
__exit__
self.gen.throw(type, value, traceback)
File
"c:\utils\robotframework\lib\site-packages\Browser\playwright.py", line
153, in grpc_channel
raise AssertionError(error.details())
AssertionError: SyntaxError: Cannot use import statement outside a
module

**Comment by aaltat** [comment]
This is something that @mkorpela should take a look.

**Comment by aaltat** [comment]
We do not support .ts files as Node side extension, also we are strick
