### ISSUE TITLE
how can I record in a page which start with a link? 

### ISSUE THREAD

**Issue by Aino1980** [MarketSquare/robotframework-browser#1977]
maybe not a issue:
        In web,I make video record in context. I open page with that context,video can be record.
        and I click a link start a new page,viedo record stoped.
        how can I record in a page which start with a link?

**Comment by aaltat** [comment]
I don't understand what you doing and what the problem actually is. Could you provide an example which I can run and demonstrates the problem.

**Comment by aaltat** [comment]
Closing due inactivity. Please report back if you are still having the problem.
