### ISSUE TITLE
Make some playwright outputs more actionable for our users

### ISSUE THREAD

**Issue by xylix** [MarketSquare/robotframework-browser#2012]
* [ ] Install failures give out "please use `npx install playwright`" instruction. We should replace this with something like "please run `rfbrowser clean-node` and `rfbrowser init` again
* [ ] Strict mode failures sometimes output playwright selectors that are not directly copy-pasteable to RF Browser code.

**Comment by Snooz82** [comment]
Closed. 
Playwright changes their output pretty often and we would come into a maintenance hell if we would do it.
And no one voted for this issue.
