### ISSUE TITLE
Tests dont run on Firefox engine only on MAC

### ISSUE THREAD

**Issue by gvr-kumar** [MarketSquare/robotframework-browser#2017]
**Describe the bug**
Using browser library, **On Firefox engine** on MAC, never opens the URL. Just open the browser but never opens the URL. Its working on Windows but dont work on MAC.

**To Reproduce**

**Case1:** I am using the below code and it never opens the URL at New Page line
New Browser  firefox  headless=false
New Context  acceptDownloads=True    httpCredentials=${credentials}  ignoreHTTPSErrors=true
New Page    ${myAppURL}

**Case2:** In this case also I am using Go To URL,  it never opens the URL at New Page line
New Browser  firefox  headless=false
New Context  acceptDownloads=True    httpCredentials=${credentials}  ignoreHTTPSErrors=true
New Page
Browser.Go To    ${myAppURL}

**Case3:** In his case, I am using new page and then new context, then I am getting error: **"Exception has occurred.
Suspended due to logged failure: Error: page.goto: SEC_ERROR_UNKNOWN_ISSUE"**
New Browser  firefox  headless=false
New Context  acceptDownloads=True    httpCredentials=${credentials}  ignoreHTTPSErrors=true
New Page    ${myAppURL} 

**Expected behavior**
Expecting to run tests on Firefox engine as well. Used to work before like few months back. But it stopped working on **Firefox**.
Attached screenshot.

**Desktop (please complete the following information):**
 - OS: MAC
 - Browser: Firefox (engine)

<img width="1277" alt="image" src="https://user-images.githubusercontent.com/11802756/167465515-a4007bbe-7fda-4dc9-a0ce-ab2e96fee93e.png">

**Comment by aaltat** [comment]
With these details we are not able to help you. I tested Firefox on Mac M1 chip and it work. I can run your tests, because important content is not visible because they are masked by RF variables. 

If you can provide example which demonstrates the problem and we can also run, perhaps then we are able to help you better.

**Comment by aaltat** [comment]
Closing due inactivity

**Comment by aaltat** [comment]
If you can provide example which demonstrates the problem and we can also run, perhaps then we are able to help you better.
