### ISSUE TITLE
Log file name typo (`"rfborwser.log"` -> `"rfbrowser.log"`)

### ISSUE THREAD

**Issue by cmin764** [MarketSquare/robotframework-browser#2035]
**Describe the bug**

Just a typo under [this](https://github.com/MarketSquare/robotframework-browser/blob/main/Browser/entry.py#L41) line:
```python
def rfbrowser_init(skip_browser_install: bool):
    ...
    install_log = current_folder / "rfborwser.log"
```

Same applies here. Is [this](https://github.com/MarketSquare/robotframework-browser/blob/main/Browser/entry.py#L199) intended?

**Comment by aaltat** [comment]
@allcontributors please add @cmin764 for bugs
