### ISSUE TITLE
New Persistent Context docs improvements

### ISSUE THREAD

**Issue by xylix** [MarketSquare/robotframework-browser#2048]
* [ ] Document how it is special context 
  * Actionable steps in "tried to open new context while persistent context was open" error
* [ ] Document you need another `New Browser ` and to use `Switch Browser` to switch between a persistent and a non-persistent context
* [ ] Clear documentation wether to use a string list literal or a list of arguments.

* [ ] adding tests https://github.com/MarketSquare/robotframework-browser/pull/2084

**Comment by Snooz82** [comment]
close due to no progress.
