### ISSUE TITLE
Click Argument 'modifiers' doesn't work as expected

### ISSUE THREAD

**Issue by shenthils** [MarketSquare/robotframework-browser#2049]
**Describe the bug**
Argument 'modifiers' don't work in the 'Click' keyword.
As per the document, allowed Values are Alt, Control, Meta, Shift. But it doesn't work.
`Click    selector   modifiers = Control`

`ValueError: Argument ‘button’ got value ‘modifiers = Control’ that cannot be converted to MouseButton: MouseButton does not have member ‘modifiers = Control’. Available: ‘left’, ‘middle’ and ‘right’`

**To Reproduce**
1. Use this keyword `Click    selector   modifiers = Control`

**Expected behavior**
I should be able to Click an option by pressing the control button.

**Comment by Snooz82** [comment]
@shenthils That actually is not a bug in the keyword or its functionality.
The keyword works as intended.

The Problem you are facing is, that Robot Framework (as python) does not allow positional arguments like `*modifiers` after named arguments.
`*modifiers` is a positional only argument and therefore is only allowed before named arguments.
So if you try to do something like this:

```robotframework
Click     selector    modifiers = Control
```
As you see from the error, the string `"modifiers = Control` is interpreted as the second positional argument of that keyword, which is the `button` argument.

Therefore the way how to set modifiers, is to set all preceding arguments positional.
I will take this issue as a bug in out documentation and try to fix that.


```robotframework
lick With All Modifier
    Click    \#clickWithOptions    left    1    None    None    None    False    False    Alt    Control    Meta    Shift
    Get Text    \#mouse_button    ==    left
    Get Text    \#alt_key    ==    true
    Get Text    \#ctrl_key    ==    true
    Get Text    \#meta_key    ==    true
    Get Text    \#shift_key    ==    true

Click With Control Modifier
    Click    \#clickWithOptions    right    1    None    None    None    False    False    Control
    Get Text    \#mouse_button    ==    right
    Get Text    \#alt_key    ==    false
    Get Text    \#ctrl_key    ==    true
    Get Text    \#meta_key    ==    false
    Get Text    \#shift_key    ==    false

Click With Shift Modifier
    Click    \#clickWithOptions    middle    1    None    None    None    False    False    Shift
    Get Text    \#mouse_button    ==    middle
    Get Text    \#alt_key    ==    false
    Get Text    \#ctrl_key    ==    false
    Get Text    \#meta_key    ==    false
    Get Text    \#shift_key    ==    true

Click With Meta Modifier
    Click    \#clickWithOptions    left    1    None    None    None    False    False    Meta
    Get Text    \#mouse_button    ==    left
    Get Text    \#alt_key    ==    false
    Get Text    \#ctrl_key    ==    false
    Get Text    \#meta_key    ==    true
    Get Text    \#shift_key    ==    false

Click With Alt Modifier
    Click    \#clickWithOptions    left    1    None    None    None    False    False    Alt
    Get Text    \#mouse_button    ==    left
    Get Text    \#alt_key    ==    true
    Get Text    \#ctrl_key    ==    false
    Get Text    \#meta_key    ==    false
    Get Text    \#shift_key    ==    false

Click With No Modifier
    Click    \#clickWithOptions    left    1    None    None    None    False    False
    Get Text    \#mouse_button    ==    left
    Get Text    \#alt_key    ==    false
    Get Text    \#ctrl_key    ==    false
    Get Text    \#meta_key    ==    false
    Get Text    \#shift_key    ==    false
```

**Comment by Snooz82** [comment]
#2078

**Comment by shenthils** [comment]
@Snooz82 , I have a list of files.  I want to ctrl-click the files one by one to select. 
For this, I use the command below,
FOR    ${File}    IN    @{Files}
        Click    //table[@class='VariantsTable']/descendant::*[text()='${File}']    left    1    None    None    None    False    False    Control
    END

This command selects all the files. That is good, but I see this command also does the right-click context menu. 
Left-click selects the file one by one, But I see the context menu is also open. The context menu normally opens when we do right-click. I do not understand why the context menu is open here.  
I tried to change the argument from 'left' to 'right'. But I see the same result. 

Because the context menu is open, the teardown doesn't work. 
![image](https://user-images.githubusercontent.com/68647820/197889756-e777fdf3-0854-4567-9818-eeac062d2f51.png)

**Comment by shenthils** [comment]
It works fine if I change 'control' to 'Meta'

FOR ${File} IN @{Files}
Click //table[@Class='VariantsTable']/descendant::*[text()='${File}'] left 1 None None None False False Meta
END

**Comment by aaltat** [comment]
Are you using mac?

**Comment by shenthils** [comment]
Yes, I am using Mac

**Comment by shenthils** [comment]
does this command differ for Mac? 
Some use Mac and some others use Windows in my team. We use Linux for daily run.

**Comment by aaltat** [comment]
Yes it does affect. Different OS will use different combinations to do same thing. Like if you think copy/paste between mac/windows/linux. 

If you really need support for multiple operating systems, then you need to solve the correct key combinations outside of the Browser library.

**Comment by shenthils** [comment]
Can you please explain how I can solve that outside of the Browser Library?

**Comment by aaltat** [comment]
There is not a ready made keyword for it, but example in Python you can get this, example is run in Linux 

```python 
>>> import platform
>>> platform.system()
'Linux' 
```
Then you can build your own keyword which will return you correct key combination based on the OS which you are using.

I would build an library keyword,  which is explained in the user guide https://robotframework.org/robotframework/latest/RobotFrameworkUserGuide.html#creating-test-libraries

**Comment by shenthils** [comment]
Thank you.
