### ISSUE TITLE
Option --timestampoutputs does not work for playwright-log.txt

### ISSUE THREAD

**Issue by UliSei** [MarketSquare/robotframework-browser#2050]
Tested with RF 5.0:
My robot file started by
`robot sample.robot`
generates the output files
```
log.html
output.xml
report.html
playwright-log.txt
```

The docu says:
-T, --timestampoutputs
 	Adds a timestamp to all output files.

When I run the script as
`robot --timestampoutputs sample.robot`
I get
```
log-20220523-161214.html
output-20220523-161214.xml
report-20220523-161214.html
playwright-log.txt
```

It's the same with option -T or option --timestamp that there is no timestamp added to playwright-log.txt

-> What do you think should be updated: the docu or the functionality?

**Comment by aaltat** [comment]
That is correct, only output files created by Robot Framework core have timestamp. Libraries don't know about the option, so it's not possible to add timestamp in the file. I think this is Robot Framework feature and it should be documented in Robot Framework user guide.

**Comment by UliSei** [comment]
So it would be ok when I close the issue here and raise a new one for RF core project?
