### ISSUE TITLE
Docker improvements

### ISSUE THREAD

**Issue by xylix** [MarketSquare/robotframework-browser#211]
- [ ] test a rolling version of the stable Docker image on commits to master
- [ ] Include `seccomp_profile.json` and a good entrypoint.sh for running robot tests within the docker file
  - [ ] improved ctrl-c handling so that the docker running robot / pabot tests can be stopped.
- ? Add common robotframework utility libraries into the image
  - https://github.com/ppodgorsek/docker-robot-framework/blob/master/Dockerfile has a nice list

- Not really possible with our libraries and baked in browsers: ~~Slim the image a bit (it's almost 2 gb which is a LOT for a docker image. It does contain graphical support though so unsure how much can be thinned)~~
- [x] test stable Docker image in CI on releases. 
- [x] Wait for upstream to support 20.04 and then base our dockerfiles on upstream PW docker (https://github.com/microsoft/playwright/pull/2758 )
- [x] Document base docker image's features and why tests should be run as non-root user 
- [x] Publish a base docker image for testing with rfbrowser
- ~~Base docker file(s) on https://github.com/microsoft/playwright/blob/master/docs/docker/Dockerfile.bionic to avoid having to maintain a lot of apt installs in our dockerfile~~
Current work in https://github.com/MarketSquare/robotframework-browser/pull/221

**Comment by mkorpela** [comment]
I think we should also add dockerfile as an optional installation method. This file should use the pypi package instead of building from source.

So after:
Installation instructions
Only Python 3.8 or later is supported.

Install node.js e.g. from https://nodejs.org/en/download/
Install robotframework-browser from the commandline: pip install robotframework-browser
Install the node dependencies: run rfbrowser init in your shell

[Add]
.. or use our Dockerfile [with a link to the dockerfile]

**Comment by xylix** [comment]
There's problems starting our node side grpc service in docker... Seems to be at least somewhat of an upstream issue https://github.com/grpc/grpc/issues/19430 . But there was a time when our grpc server worked in docker, right?

**Comment by xylix** [comment]
GRPC service and express are working in my local docker test environment now but getting them to work in CI has been troublesome.

**Comment by xylix** [comment]
Current problem is that we can't keep the docker environment on CI "clean" while also building the test application. Granular support for test app building might help this, but might also be able to work around this through github actions
