### ISSUE TITLE
`statusText` is empty for HTTP/2 request in Chromium

### ISSUE THREAD

**Issue by JaPyR** [MarketSquare/robotframework-browser#2129]
**Describe the bug**
Documentation for `HTTP` and `Wait For Response` keyword make impression that `statusText` that is something present and if everything is good it would be "OK", but in HTTP/2 there is not such concept (https://fetch.spec.whatwg.org/#concept-response-status-message) and Chromium follows this approach while Firefox returns something.

**Comment by aaltat** [comment]
@allcontributors please add @JaPyR  for bugs

**Comment by Snooz82** [comment]
fixed in #3243
