### ISSUE TITLE
Do not blindly delete ${OUTPUT_DIR}/browser folder, because it might not be desired

### ISSUE THREAD

**Issue by aaltat** [MarketSquare/robotframework-browser#2134]
**Is your feature request related to a problem? Please describe.**
Do not blindly delete ${OUTPUT_DIR}/browser folder, because it might not be desired. Example user might have saved files in the browser folder, which should be kept between test runs and we blindly delete the folder. We should perform check on files and folder and delete files which are only created by us. 

**Describe the solution you'd like**
More intelligent cleaning.

**Comment by mkorpela** [comment]
Pabot uses `blind` removal of [pabot_results](https://github.com/mkorpela/pabot/blob/3cc4ca5d8f52f9d1212c19c19618c756bf048f2f/pabot/pabot.py#L1296) . I think the only difference here is that browser (as a folder name) is such a common name.
What if we just used some more unique name like `browser_library_results`?

**Comment by aaltat** [comment]
That is good idea too.

**Comment by aaltat** [comment]
Do not delete `browser` folder, but delete the subfolders we create. The `browser` folder should have files only in the subfolder which are created by the library.
