### ISSUE TITLE
Lorem ipsum detector

### ISSUE THREAD

**Issue by mkorpela** [MarketSquare/robotframework-browser#2137]
Crawler or other.. why not have a heuristic to fail when "lorem ipsum" on page?

**Comment by aaltat** [comment]
What would be the use case?

**Comment by mkorpela** [comment]
The use case would be to check site for accidentally leaving lorem ipsums on some place.

**Comment by aaltat** [comment]
I agree that it is good check, but is that something which belongs to core library or would it better live as extension?

**Comment by mkorpela** [comment]
There are several heuristical (or”common” pattern based) tests to make. Maybe templating might be better place for this
