### ISSUE TITLE
Docu linting "Finding elements" and "Set Strict Mode"

### ISSUE THREAD

**Issue by UliSei** [MarketSquare/robotframework-browser#2147]
English is not my native language but I'd suggest:

**[Finding elements](https://marketsquare.github.io/robotframework-browser/Browser.html#Finding%20elements)**
Old: "If keyword does not state that is used strict mode, then strict mode is not applied for the keyword."
New: "If the keyword does not state that strict mode is used, then strict mode is not applied for the keyword."

**[Set Strict Mode](https://marketsquare.github.io/robotframework-browser/Browser.html#Set%20Strict%20Mode)**
Old: "Keyword changes library strict mode value and keyword also return the previous strict mode value."
New: "Keyword changes library strict mode value and keyword also returns the previous strict mode value."

If you like I could generate a PR.

**Comment by UliSei** [comment]
Fine, so I'd include some other corrections.
Old: "If automatic closing level is MANUAL, nothing is closed automatically during the test execution is ongoing."
New: "If automatic closing level is MANUAL, nothing is closed automatically **while** the test execution is ongoing."

However I can't find the document where to change the word?
In browser.py line 161 there is just a placeholder     %AUTO_CLOSING_LEVEL%

**Comment by aaltat** [comment]
Yes it's placeholder. I comes from https://github.com/MarketSquare/robotframework-browser/blob/main/Browser/utils/data_types.py#L460 if my memory serves me correctly.

**Comment by UliSei** [comment]
Your memory is amazing :-) 
-> PR #2151 was checked successfully.
