### ISSUE TITLE
Get Element States causes an uncaught error in the browser

### ISSUE THREAD

**Issue by rousku** [MarketSquare/robotframework-browser#2164]
**Describe the bug**
Running `Get Element States` against a node that is not a checkbox will result in an uncaught error in the browser console.

**To Reproduce**
1. `Get Element States  xpath=//*[@id="node_that_is_not_checkbox"]`
2. **Uncaught (in promise) Error: Not a checkbox or radio button** message appears in the console.

**Expected behavior**
No error should be thrown.

**Screenshots**
![image](https://user-images.githubusercontent.com/2264792/177321190-cb28d1eb-0c97-4626-86af-712adfd4a5fe.png)
![image](https://user-images.githubusercontent.com/2264792/177321355-485c5580-981e-4576-a808-4877e97405ce.png)

**Desktop:**
 - OS: Windows 11
 - Browser: chromium
 - Version: 13.2.0

**Comment by aaltat** [comment]
@allcontributors please add @rousku for bugs.

**Comment by Snooz82** [comment]
@rousku can you please post a screenshot of that element in DOM.
And can you please show what the content of the attribute "role" is of that element.

you can just copy the jsPath of that element in the DOM. Then go into console of the browsers dev tools.
Then past the copied path and add `.getAttribute("role")` 
and hit Enter.

It seems that your element has the role checkbox or radio, but it is something different.

**Comment by Snooz82** [comment]
@rousku 

I can not reproduce anymore.

Please ping us again, if this still appears on your side.
