### ISSUE TITLE
`New Persistent Context` documentation URL is not pointing to the right resource (`404` Not Found)

### ISSUE THREAD

**Issue by cmin764** [MarketSquare/robotframework-browser#2185]
**Describe the bug**
Documentation (docstring) URL is not resolved correctly on `New Persistent Context` keyword.

**To Reproduce**
Go to Robocorp [New Persistent Context](https://robocorp.com/docs/libraries/rpa-framework/rpa-browser-playwright/keywords#new-persistent-context) (or [rpaframework](https://rpaframework.org/libraries/browser_playwright/index.html)) and if you click (not copy-paste in the address bar) the correctly displayed [URL](https://playwright.dev/docs/api/class-browsertype#browser-type-launch-persistent-context) will actually redirect you to an invalid `/persistent context` address relative to the location you are at the moment.

**Expected behavior**
Clicking the URL should really open the page described by its address: `https://playwright.dev/docs/api/class-browsertype#browser-type-launch-persistent-context`

I believe the docstring should be refactored into:
```python
"""Open a new `persistent context <https://playwright.dev/docs/api/class-browsertype#browser-type-launch-persistent-context>`_.

...
"""
```
instead of the current: `"""Open a new [persistent context | https://playwright.dev/docs/api/class-browsertype#browser-type-launch-persistent-context].`

**Screenshots**
<img width="1113" alt="Screenshot 2022-07-18 at 12 59 54" src="https://user-images.githubusercontent.com/709053/179490864-1233f5dc-5d28-4b32-9bb6-32d0c8feba68.png">
<img width="654" alt="Screenshot 2022-07-18 at 13 02 26" src="https://user-images.githubusercontent.com/709053/179490875-16691361-59ce-4b08-91f9-cfb491856ea9.png">
<img width="1310" alt="Screenshot 2022-07-18 at 13 04 45" src="https://user-images.githubusercontent.com/709053/179490876-01998149-baa5-4499-ab27-c468fec3e451.png">

**Additional context**
Community Slack [thread](https://robocorp-developers.slack.com/archives/C010WNVBT4M/p1657798971307559)

**Comment by aaltat** [comment]
I can reproduce the problem also with Browser library keyword documentation.

**Comment by aaltat** [comment]
@allcontributors please add @cmin764 for bugs.
