### ISSUE TITLE
Host released version's documentation differently from masters (only update gh pages on releases?)

### ISSUE THREAD

**Issue by xylix** [MarketSquare/robotframework-browser#220]
Currently our gh pages only hosts latest master's documentation. It might be quite different from latest releases', which could cause confusion with users.

**Comment by aaltat** [comment]
Most of the libraries host only one version of the keyword document, which doesn't cause that much of a trouble. Also users can generate docs by libdoc if they need it. But it would be good to start adding notes what (new keyword or enhancements in existing keyword) came out in which version

**Comment by xylix** [comment]
Right. Maybe we could automatically add tags new keywords when generating releases? And keywords that don't have a tag for which release they were added in could have a "NOT_RELEASED" tag or something like that

**Comment by aaltat** [comment]
It is not only indicating what keyword came out in which release. It's also indicating changes in the keyword.  Example document could contain:

Keyword  X is new in release  1.0
Argument  b was added in release 1.2
Argument c was added in release 2.0

Keyword docs is the most convenient place to house the document. But it's little bit grag to keep this information in the keyword docs. After rethink, I think it could be better to have old version docs available

**Comment by xylix** [comment]
Yeah I think a changelog document / old version docs would be good for usage ergonomics if we will end up having users using old versions of the library (which is pretty likely in the long run)
