### ISSUE TITLE
New Page keyword is not working all times. Sometimes app is not launched and page becomes stale gives a "TimeoutError: page.goto: Timeout 10000ms exceeded"

### ISSUE THREAD

**Issue by Sathish787** [MarketSquare/robotframework-browser#2207]
**Describe the bug**
This issue is raised already here but closed
https://github.com/MarketSquare/robotframework-browser/issues/1902

So I am creating a new bug:
1.In order to get this issue, try open browser and context one time and execute each test in new page. Repeat the test suite for atleast 5 times. Then, you will be getting the error as we get. 
2. perform some actions in the page in each test.

Log shows only failure/error of next step but not showing actual failure.
On my close observation, I noticed new page gets disconnected in few seconds and hangs till timeout.

Currently, handling this by using 
```
${Status} =  Run keyword and get status  new page ${url} 
IF  ${Status} == False  new page ${url}
```

This is happening in every execution, 2 out of 10 tests fails because of this.
Please check implementation of new page.

**Expected behavior**

App should be launched every time without page stale in all browsers.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser : Chrome, Chromium, Firefox and Edge
Python: 3.9.13
Browser Library: 13.3.0

**Additional context**
![image](https://user-images.githubusercontent.com/22374311/180842090-9a1487ac-fbee-4a5b-ad48-28fc6a68b6b8.png)

![image](https://user-images.githubusercontent.com/22374311/180842024-07cb9cf2-4930-48ea-a9ff-d06dcaeed60e.png)

**Comment by mkorpela** [comment]
Can't reproduce. Tried with:
```RobotFramework
*** Settings ***
Library  Browser
Suite Setup   New Context

*** Variables ***
${url}   https://www.google.com

*** Test Cases ***
Test 1
   Do something

Test 2
   Do something

Test 3
   Do something

Test 4
   Do something

Test 5
   Do something

Test 6
   Do something

Test 7
   Do something

Test 8
   Do something

Test 9
   Do something

Test 10
   Do something

*** Keywords ***
Do something
   New Page  ${url}
   get title  ==  Google
```
Could you provide an executable example where this happens?

**Comment by Sathish787** [comment]
This is happening from  version 13.0.0 - 13.3.0. I downgraded version 12.3.0, tests are executed successfully without page stale. but have to give up ms edge browser which is not supported at 12.3.0.

**Comment by aaltat** [comment]
If you want us to be able to investigate this one, then could you provide an executable example where this happens?

**Comment by Sathish787** [comment]
When I executed below suite continuously (minimum 5 times), I start to get above stated error:

```

*** Settings ***
Library   Browser
Suite Setup  Launch the browser
Suite Teardown  close browser

*** Keywords ***
Launch the browser
    # new browser  chromium  channel=msedge  headless=false   timeout=20s
    new browser  firefox  false  timeout=20s
    new context  viewport={'width': 1920, 'height': 1080}  ignoreHTTPSErrors=True  bypassCSP=True
    set strict mode  false
    
*** Test Cases ***
Test 1    
    new Page  https://www.espncricinfo.com/
    Wait For Elements State  .slick-slide.slick-active  visible
    Get Element States  .slick-slide.slick-active  contains  visible
    # close page  ALL  ALL  ALL 

Test 2
    new Page  https://www.espncricinfo.com/
    Get Attribute  .navbar-brand img  src  ==  https://wassets.hscicdn.com/static/images/logo.png
    # close page  ALL  ALL  ALL

Test 3
    new Page  https://www.espncricinfo.com/
    click  .navbar-brand
    # close page  ALL  ALL  ALL

Test 4
    new page  https://www.espncricinfo.com/
    Wait For Elements State  .icon-search-outlined  visible
    Get Element States  .icon-search-outlined  contains  visible
    # close page  ALL  ALL  ALL

```

robotframework-browser: 13.3.0
python: 3.9.13
node.js: 14.15.0
OS: Windows 10 professional

![image](https://user-images.githubusercontent.com/22374311/181087962-854f7384-77bd-4ef3-abb5-24bc1f0457b6.png)

**Comment by mkorpela** [comment]
I'm sorry but this is not happening in my environment.

```bash
❯ node --version
v16.13.0
❯ python --version
Python 3.9.7
```
(OSX)

Test 3 fails because it does not discover the clickable element, but otherwise it works.

As pointed previously by @aaltat the problem is a timeout error, which may happen for many reasons and 99% of the time the reason is outside of the scope of the Robot Framework Browser library.
For example if you are in a VPN or in an environment where the internet connectivity is limited, then page loading might take too much time and you then have to increase the timeout from the default 10 seconds.

If I set the browser timeout to 1 second, then I can see similar problem that you have described.

```RobotFramework
*** Keywords ***
Launch the browser
    # new browser  chromium  channel=chrome  headless=false   timeout=20s
    new browser  firefox  false  timeout=20s
    new context  viewport={'width': 1920, 'height': 1080}  ignoreHTTPSErrors=True  bypassCSP=True
    set browser timeout  1 second
    set strict mode  false
```

But I think you can side-step this problem by `set browser timeout  30 seconds` could you try that?

**Comment by Sathish787** [comment]
Thanks for the response.

![image](https://user-images.githubusercontent.com/22374311/181113429-b3ef230b-0779-48dc-80b1-db133b914860.png)

I don't think it is VPN or environment. Because I was not getting this issue in robotframework-browser:12.3.0. 

From the image, Error says 'Tried to take screenshot, but no page was open". What I see in the monitor, after page launch, page's first instance gets disconnected in 3-4 seconds and second instance is launched. 



I will try to different python, node.js versions and browser versions as it could be compatibility issue.

Do you know how to install different version of browser binaries. Also location these binaries are installed?

When can we expect new version of pwr1.24

**Comment by Sathish787** [comment]
Problem has got resolved after restarting my system. If someone get same problem after installing robotframework-browser package, rfbrowser init. restart your system.
