### ISSUE TITLE
Calling "New Page" fails after creating the context using "New Persistent Context" with recordVideo argument

### ISSUE THREAD

**Issue by ssallmen** [MarketSquare/robotframework-browser#2214]
**Describe the bug**
If the context is created using `New Persistent Context` and video recording is wanted by giving recordVideo argument a call to `New Page` using that context will fail.

**To Reproduce**
```
*** Settings ***
Library    Browser

*** Test Cases ***
Record Video with Browser.New Persistent Context
    &{recordVideo}=    Create Dictionary    dir=${OUTPUT_DIR}/videos
    Browser.New Browser    headless=False
    Browser.New Persistent Context    recordVideo=${recordVideo}
    Browser.New Page    https://google.com
```

**Expected behavior**
The call to `New Page` succeeds without any errors, taken that the arguments are correct.

**Screenshots**
![Log file screenshot](https://user-images.githubusercontent.com/39527407/181208957-1313310b-a98b-49cd-a9b8-abaee9c175b3.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Chrome
 - Browser library version 13.3.0

**Additional context**
The bug is in `new_persistent_context` method as it does not store the context uuid with the video size to the context_cache, as new_context does. And, `_embed_video` method called by `new_page` is expecting the video's context uuid to be in the context_cache to get the size of the video. This could be fixed by adding this call for example to the end of `new_persistent_context` method:
`self.context_cache.add(response.id, self._get_video_size(params))`

**Comment by ssallmen-pro** [comment]
@mkorpela at al. Anyone looking into this? The bug is still valid with the latest versions:
robotframework==6.0
robotframework-browser==14.2.1
