### ISSUE TITLE
Question about Save Storage State

### ISSUE THREAD

**Issue by emakaay** [MarketSquare/robotframework-browser#2254]
**Describe the bug**
I don't have a bug, but a question.
Is it possible to "Save Storage State" in the Setup phase of robotframework ?

I'f done so, and when I want to reuse the saved storage state((by creating a New Context with parameter storageState=<saved storage state file>), it replies with 'storage argument value '/tmp/<some directory>/some .json file' is not a file, but it should be.

**To Reproduce**
not required yet(I think). If you think differently I will create an example!

**Expected behavior**
I would like to re-use the save Save Storage State. But it seems to be cleared before it can be used.
I have 4 different project that I use the exact same code to re-use the storage state. The only difference is that this project already logs in to the application during the **setup** phase. Other project do that during 'normal' tests

**Screenshots**
not applicable

**Desktop (please complete the following information):**
RHEL8
playwright (chromium)
12.2.0

Thanks in advance

**Comment by mkorpela** [comment]
> Is it possible to "Save Storage State" in the Setup phase of robotframework ?

Yes it is. Short example is then needed to make this a reproducible bug.

**Comment by emakaay** [comment]
@mkorpela 
Thanks for answering my question. 
I've been working on a short example, and can't seem to reproduce(on windows). Issue was on unix.
Also I don't want to share any credentials, so this (non-)issue can be closed. Must be some other problem.
