### ISSUE TITLE
Update geolocation keyword

### ISSUE THREAD

**Issue by mkorpela** [MarketSquare/robotframework-browser#226]
**Is your feature request related to a problem? Please describe.**
Many GIS solutions (systems under test) need and interact with users location. There are also situations where these systems have functionality that is specifically related to user moving.
For instance a railway ticket sales system that suggests "from station" and "to station" based on users location and history information. Or a velocity calculator such as https://www.zpeed.in/ 

**Describe the solution you'd like**
We should have a keyword that updates context geolocation so that library users can test these geolocation features completely.

**Comment by Snooz82** [comment]
`Update GeoLocation    latitude=0    longitude=0    accuracy=0`
