### ISSUE TITLE
Setting context offline keyword

### ISSUE THREAD

**Issue by mkorpela** [MarketSquare/robotframework-browser#227]
**Is your feature request related to a problem? Please describe.**
There are sites that should work also when connection to internet is lost. For instance SPA in aircraft with satellite connectivity should behave ok even though the connection is completely lost.
Currently this flag is set at context creation.. I don't know what "offline" would actually achieve there as you can not even load initial page.

**Describe the solution you'd like**
We should expose https://playwright.dev/#version=v1.3.0&path=docs%2Fapi.md&q=browsercontextsetofflineoffline as a keyword

**Comment by xylix** [comment]
I added this in ec64e4c3659e3f732d40591c51ab3ee3731d165b . Still needs a test to be considered done. Did you have something in mind?

**Comment by mkorpela** [comment]
In aero SPAs there usually is an indicator for connectivity.. So some reoccuring ping fetch that will populate some div with text when ping fails for example.
