### ISSUE TITLE
Latest release incorrectly displayed

### ISSUE THREAD

**Issue by tomekPawlak** [MarketSquare/robotframework-browser#2277]
Latest release incorrectly displayed on github repo.

**Screenshots**
![image](https://user-images.githubusercontent.com/39945193/188098977-602ef7a3-61ce-4bd0-97e5-9bd3f2b0610e.png)
![image](https://user-images.githubusercontent.com/39945193/188099103-cc386e88-8f8b-4b2f-8558-7f15a222185e.png)

**Comment by aaltat** [comment]
Interesting, we made mistake with something.

**Comment by Snooz82** [comment]
another release and it works again
