### ISSUE TITLE
Add support for browserContext.routeFromHAR

### ISSUE THREAD

**Issue by leeuwe** [MarketSquare/robotframework-browser#2285]
I'd like to extend New Context keyword to allow testing with prerecorded data. Recording the HAR is already possible, now I want to use this HAR as MOCK.

New in PlayWright 1.23
https://playwright.dev/docs/api/class-browsercontext#browser-context-route-from-har

**Comment by aaltat** [comment]
Sounds like a good idea, are planning to provide also PR for the implementation?

**Comment by leeuwe** [comment]
After Robocon DE I'm hoping to provide a PR - yes. Now I haven't got time

**Comment by mkorpela** [comment]
Really nice @leeuwe !

**Comment by leeuwe** [comment]
@Snooz82 @mkorpela @aaltat What would you think? Should this fit better in core browser, of shall I use the new plugin API?

**Comment by Snooz82** [comment]
Good question.
The problem with `New Context` is, that it is already oversized by arguments.

But an additional keyword is also not that good.

**Comment by mkorpela** [comment]
Recorded mock would be pretty nice way to make tests and also at the same time our `New Context` is bloated with arguments.

Somehow would be great to create a way where one could state that in this suite / test we are using this mock.

**Comment by mkorpela** [comment]
```Javascript
// Replay API requests from HAR.
// Either use a matching response from the HAR,
// or abort the request if nothing matches.
await page.routeFromHAR('example.har');
```

@leeuwe as this seems rather easy to implement with a python plugin or JS extension.. Maybe start with that?

**Comment by leeuwe** [comment]
Implementing elsewhere. Closing issues

**Comment by rasjani** [comment]
Quick implementation that i've been using to mock error scenarios against API endpoints: https://github.com/MarketSquare/robotframework-browser-extensions/pull/26
