### ISSUE TITLE
Wait for response matchers not working

### ISSUE THREAD

**Issue by mkorpela** [MarketSquare/robotframework-browser#230]
**Describe the bug**
I want this to return the result of route search. So ${r} should be that result. And matcher should work as a JS regexp.

**To Reproduce**
```RobotFramework
*** Settings ***
Library  Browser
Suite Setup  New Browser   headless=${False}

*** Test Cases ***
Graphhopper
   New Page    https://graphhopper.com/maps/
   wait until network is idle  timeout=5s
   type text  //*[@id="0_Input"]  Turku
   type text  //*[@id="1_Input"]  Helsinki
   wait until network is idle  timeout=5s
   ${p}=   promise to  wait for response  matcher=/.*\/api\/1.*/  timeout=5s
   Click   \#searchButton
   ${r}=  wait for  ${p}
```

**Comment by mkorpela** [comment]
This now works after https://github.com/MarketSquare/robotframework-browser/pull/432

```
*** Settings ***
Library  Browser
Suite Setup  New Browser   headless=${False}

*** Test Cases ***
Graphhopper
   New Page    https://graphhopper.com/maps/
   wait until network is idle  timeout=5s
   type text  //*[@id="0_Input"]  Turku
   type text  //*[@id="1_Input"]  Helsinki
   wait until network is idle  timeout=5s
   ${p}=   promise to  wait for response  matcher=/api/1/  timeout=5s
   Click   \#searchButton
   ${r}=  wait for  ${p}
```

**Comment by mkorpela** [comment]
Fixed after https://github.com/MarketSquare/robotframework-browser/pull/437

**Comment by vincenzo-gasparo** [comment]
Hi, I need to match a request with this uri: `/api/table/customers?id=1234`. I'm able to match it with `matcher=/api/table/customers` and `matcher=id=1234` but `matcher=/api/table/customers?id=1234` gives me TimeoutError: Timeout while waiting for event "response". 
Is there a problem with special characters like `?` or am I missing something? Thanks 

(I can match it with `page.waitForResponse(/\/api\/table\/customers\?id=1234/)` in typescript playwright)

**Comment by mkorpela** [comment]
The system uses regex matching so `?`and `=` might be problems and might need to be escaped with `\\`. As Robot Framework uses `\` as a escape char that actually might not require two of those. Hope this helps you to solve the problem!

**Comment by vincenzo-gasparo** [comment]
Ok I tried `\\` to escape `?` and it didn't work, but `\\\\?` works, I don't know if it's the expected behavior but at least I solved the problem!

**Comment by mkorpela** [comment]
That is a lot of escaping, thanks for letting us know!

**Comment by aaltat** [comment]
Is it because the we need double escape, one for Robot Framework side and another in Python side? If yes, it might be good idea to find way to support Python [raw-strings](https://docs.python.org/3/reference/lexical_analysis.html#string-and-bytes-literals).
