### ISSUE TITLE
new keyword provide for playwright locator.tap

### ISSUE THREAD

**Issue by nixuewei** [MarketSquare/robotframework-browser#2301]
**Is your feature request related to a problem? Please describe.**
browser librsry can't support locator.tap for playwrigh
hopeful well creating keyword which calls https://playwright.dev/docs/api/class-locator#locator-tap
the datepicker we used is not work by current browser keyword.  I try the click keyword on both browserlibrary and playwright, but failed. And tap success. The same datepicker can work use seleniumlibrary drag and drop but failed on browserlibrary drag and drop serials keyword. So strange.

**Describe the solution you'd like**
new keyword provide for locator.tap

**Describe alternatives you've considered**
none

**Additional context**
none

**Comment by aaltat** [comment]
@allcontributors please add @nixuewei for ideas.
