### ISSUE TITLE
protobuf package has a vulnerability that is fixed in v3.20.2

### ISSUE THREAD

**Issue by kariharju** [MarketSquare/robotframework-browser#2334]
**Is your feature request related to a problem? Please describe.**
There is a [vulnerability](https://security.snyk.io/vuln/SNYK-PYTHON-PROTOBUF-3031740) in the `protobuf` package version 3.20.1 that has a fix available in 3.20.2

robotframework-browser has a [dependency](https://github.com/MarketSquare/robotframework-browser/blob/main/Browser/requirements.txt#L4) protobuf==3.20.1. 
Is that possible to update this dependency to protobuf==3.20.2 and release a new robotframework-browser version?

**Comment by aaltat** [comment]
@allcontributors please add @kariharju for bugs
