### ISSUE TITLE
Augment the documentation of Highlight Elements for the case that it apparently did nothing

### ISSUE THREAD

**Issue by mardukbp** [MarketSquare/robotframework-browser#2335]
**Is your feature request related to a problem? Please describe.**

When I call Highlight Elements with a selector that does not correspond to any element on the web page I see no element highlighted. Same happens when the selector corresponds to an element located outside of the viewport (e.g. 1000px to the left). This possibility is not obvious to less experienced users, who waste time in vain trying to "fix" the selector.

**Describe the solution you'd like**

The documentation of Highlight Elements should provide the following advice:

If you do not see any element highlighted then either the selector corresponds to no element on the page or the element lies outside of the viewport. Call Get BoundingBox to disambiguate.

**Describe alternatives you've considered**

Suggest that Highlight Elements fails when no element is found (like most keywords in the library) or that it returns the number of highlighted elements (which violates [CQRS](https://en.wikipedia.org/wiki/Command%E2%80%93query_separation) and there is already Get Element Count).

**Additional context**

**Comment by aaltat** [comment]
@allcontributors please add @mardukbp for bugs

**Comment by aaltat** [comment]
Failing keyword is backwards incompatible change, although not very big one. Instead keyword returns the number of highlighted elements. Also improved log message when zero elements are highlighted, in past it did say: `Highlighted 0 elements for 200.`, which is confusing. Now, if zero elements are found, keyword will log: `Could not find elements to highlight.`
