### ISSUE TITLE
Is there  any way we can open chrome instead of chromium browser?

### ISSUE THREAD

**Issue by everlighting** [MarketSquare/robotframework-browser#2342]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by aaltat** [comment]
Yes, see the `channel` argument in [New Browser](https://marketsquare.github.io/robotframework-browser/Browser.html#New%20Browser) keyword. 

Next time we would like if you preferred this type of question in the Robot Framework community channels.
