### ISSUE TITLE
[Question] Adding extra headers for specific browser page

### ISSUE THREAD

**Issue by 4nif** [MarketSquare/robotframework-browser#2345]
Hello,

I use `extraHTTPHeaders` to add an additional header in the browser requests in the browser context. However additional browsers get carried over to all page

How can I set `extraHTTPHeaders` for a specific page only and remove that header when the browser move to the next page

illustration
homepage (open with additional headers) --> click registration button --> open registration button without additional header --> continue with all step without additional headers

Thank you

**Comment by aaltat** [comment]
Have you looked at Playwright API document is the removal of the headers possible?

**Comment by aaltat** [comment]
Closing due inactivity.
