### ISSUE TITLE
new keyword provide for playwright mouse wheel

### ISSUE THREAD

**Issue by nixuewei** [MarketSquare/robotframework-browser#2347]
**Is your feature request related to a problem? Please describe.**
we have config page and it can use drag and drop to put element. but failed to wheel the cellphone config page to scroll.
when i physical operate, it just can be done by mouse wheel to scroll element.

**Describe the solution you'd like**
 It should be have the mouse wheel keyword same as https://playwright.dev/docs/api/class-mouse#mouse-wheel

**Describe alternatives you've considered**

**Additional context**
<img width="574" alt="123" src="https://user-images.githubusercontent.com/20495497/193605240-3620b233-a7f9-4c83-8891-28e1de446cca.png">

**Comment by aaltat** [comment]
To make sure that I understand you correctly, you would like to have a separate keyword which Playwright mouse wheel API from Playwright side?

**Comment by nixuewei** [comment]
@aaltat yes. exactly. thank you for update in the near future

**Comment by aaltat** [comment]
Done in #2586
