### ISSUE TITLE
Using library without internal browser startup

### ISSUE THREAD

**Issue by slavaGanzin** [MarketSquare/robotframework-browser#2350]
**Is your feature request related to a problem? Please describe.**
I want to use my own playwright server. So I'm using connect_to_browser command. It successfully connects and run all tests. But robotframework-browser starts another browser process as well, which is not needed in my case. And I don't know any way to disable starting browser inside library.

**Describe the solution you'd like**
An option, to not start any browser process at library startup.

**Describe alternatives you've considered**
Tried to use internal server, but it didn't work as I expected.

**Comment by aaltat** [comment]
@allcontributors please add @slavaGanzin for ideas

**Comment by slavaGanzin** [comment]
@aaltat Tatu, could you just give me a quick hack how I can do it. Because I need this ASAP, and I don't think this could be resolved properly fast.

**Comment by aaltat** [comment]
I don't see any other way than modifying the code. If you want it fast, is you to look at the code and implement it.

**Comment by slavaGanzin** [comment]
@aaltat I tried to look into code. But it seems it has a lot of interconnections inside a library. I'm not asking for you to resolve this fast, but maybe as one of developers of this code you could point me what should I take into considerations while trying to implement it myself? Where to look?

Because I've tried to do it couple of times and has no success: library just stop working when I return fake puppeteer, for example.

**Comment by slavaGanzin** [comment]
I've tried to make changes in a proper way, but I couldn't active mock grpc connection. 

So I've ended up with launching:
`node wrapper/index.js 9000` as systemd service
and setting `Library  Browser  playwright_process_port=9000`

and then using connect_to_browser internally.

Which speed up everything and I could use parallel robot processes without using pabot.

**Comment by aaltat** [comment]
I do not have any better idea currently, if it works for you then it is good solution.
