### ISSUE TITLE
Compatibility issue with newest grpcio-tools and protobuf

### ISSUE THREAD

**Issue by axiom41** [MarketSquare/robotframework-browser#2379]
Hello.
During installation of robotframework-browser, a compatibility message is shown:

**ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
robotframework-browser 14.1.0 requires grpcio-tools==1.48.1, but you have grpcio-tools 1.49.1 which is incompatible.
robotframework-browser 14.1.0 requires protobuf==3.20.1, but you have protobuf 4.21.7 which is incompatible.**

grpcio-tools and protobuf were updated during update of rpaframework-google package.

Would it be then possible to release a robotframework-browser version (or workaround) to make it compatible with the newest grpcio-tools and protobuf?

Thanks

**Comment by aaltat** [comment]
@allcontributors please @axiom41 for bugs. 

This is fixed in  ##2393

**Comment by aaltat** [comment]
@allcontributors please add @axiom41 for bugs.
