### ISSUE TITLE
Add information about version in which keyword was introduced to documentation

### ISSUE THREAD

**Issue by JaPyR** [MarketSquare/robotframework-browser#2446]
I am upgrading my library dependencies every few months, so I am not always up to date with Browser version, but always using the latest documentation (not sure whether it's possible to select particular version). I think it would be nice to have something like 'New in <version number>' as in case of python docs.

**Comment by aaltat** [comment]
We have discussed this few times, but always ended not doing it. I understand the need and I was in favor of doing it, but other project member where not favor of doing it. I think their mind has not changed, so I think we will decline this proposal.
