### ISSUE TITLE
Red herring: Installation directory `[..]\venv\Lib\site-packages\Browser\wrapper` does not contain the required files

### ISSUE THREAD

**Issue by jcb-entrnce** [MarketSquare/robotframework-browser#2479]
**Describe the bug**
When `npm` fails as part of the `rfbrowser init` command, the following error is printed: 
`Installation directory [..]\venv\Lib\site-packages\Browser\wrapper does not contain the required files`.

However the `npm` failure can be due to any reason, not just missing files. The error message should point to the `npm` error, instead of assuming it is because of missing files.

**To Reproduce**
1. Simulate an `npm` failure, such as no internet, or a non-existing repository
2. run `rfbrowser init`
3. watch the confusing error message appear, even if the package.json in the described directory exists.

**Expected behavior**
A better error message

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser n/a
 - Version 14.3.0

**Comment by aaltat** [comment]
@allcontributors please add @jcb-entrnce for bugs
