### ISSUE TITLE
Broken docstring links for keywords like: `New Browser`, `Wait For Request`, `Wait For Response`

### ISSUE THREAD

**Issue by cmin764** [MarketSquare/robotframework-browser#2494]
**Describe the bug**
The _playwright.dev_ URLs are broken in the docstring source of such keywords containing references to https://playwright.dev.

**To Reproduce**
Surf docs and look for the ones containing external links like `Wait For Request` keyword found at this [line](https://github.com/MarketSquare/robotframework-browser/blob/main/Browser/keywords/network.py#L132).

**Expected behavior**
Should direct to this URL:
```
https://playwright.dev/docs/api/class-page#page-wait-for-response
```
instead of:
```
https://playwright.dev/docs/api/class-page/#page-wait-for-response
```
so the fragment pointing to the right method works correctly.

**Screenshots**

On both Robocorp's [docs](https://robocorp.com/docs/libraries/rpa-framework/rpa-browser-playwright/keywords#wait-for-request) and [rpaframework.org](https://rpaframework.org/libraries/browser_playwright/index.html) ones:
<img width="789" alt="Screenshot_2022-12-20_at_14_48_10" src="https://user-images.githubusercontent.com/709053/208650303-fe40ed12-18ed-4279-8ea7-f408747e28dd.png">

**Comment by Snooz82** [comment]
fixed in 15.0.0
