### ISSUE TITLE
Select Options By does not recognize a dynamic selector, after it has changed

### ISSUE THREAD

**Issue by TeleBack** [MarketSquare/robotframework-browser#2497]
**Describe the bug**
The id attribute changes, after the selection, to the selected item.
For example:
The select element with the locator, select#custom-msku-option-ASIN, changes its id after selecting LISTPRICE, in the dropdown, to custom-msku-option-LISTPRICE

When this line is executed, it does indeed select the proper item in the dropdown. However, it times out with an error after 10s, because the selector has now changed.
I should note that it works fine with Selenium, when I use:
Select From List By Value    ${sCurrentID}    ${sOptionToChoose}

**To Reproduce**
See this Slack link
https://robotframework.slack.com/archives/C015KB1QSDN/p1671720773657069

**Expected behavior**
I expected Select Options By to be able to work without throwing an error, like Select From List does, in Selenium

**Screenshots**
![image](https://user-images.githubusercontent.com/9593273/209404348-fb94d033-2d03-4623-bced-46bfd524a225.png)

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser: Chrome
 - Version 108.0.5359.124 

**Smartphone (please complete the following information):**

**Additional context**

**Comment by Snooz82** [comment]
It needs to be mentioned that the `id` attr changes after the selection to the selected item.

so the select element with the locator
`select#custom-msku-option-ASIN`
changes its id after selecting `LISTPRICE` to `custom-msku-option-LISTPRICE`

my guess is that either we use the original selector to verify the selected elements or Playwright does.

we should create a test for that behavior and verify.

if it is really our feature, that we return the selected options, that could be made configurable.

**Comment by TeleBack** [comment]
Thanks @Snooz82, I edited the original text, to include your words.

**Comment by TeleBack** [comment]
Thanks @Snooz82, I edited the original text, to include your words.
