### ISSUE TITLE
Value of variable '@{attributes}' is not list or list-like.

### ISSUE THREAD

**Issue by 4WvgqJu** [MarketSquare/robotframework-browser#2513]
**Describe the bug**
My observation concerns function `Get Attribute Names` of library `Browser`. The error occurs when the script on the website examines the attributes of the elements with context HREF.

**To Reproduce**
Run the code snippet with an appropriate website:
```
Library     Browser
Library     Collections
Library     CryptoLibrary

*** Variables ***
${attribute}=           empty
${attributes}=          empty
${element}=             empty
${elements}=            empty
${elementHref}=         xpath=//a
${page2}=               @your-page/your-script.php
${protocol}=            http://
${value}=               empty
${url2}=                ${protocol}${this_is_whoever}:${this_is_secret}${page2}

Test Insert
    [Tags]    AI    INSERT
    
    New Browser
    Suppress Logging
    Log                     ${this_is_whoever}
    Log                     ${this_is_secret}
    New Page                ${url2} 
    Unsuppress Logging               
    Take Screenshot
    ${elements} =           Get Elements        ${elementHref} 
    FOR     ${element}      IN  @{elements}
            Log             ${element}
            ${value}=       Get Property    ${element}      href
            Log             ${value} 
            ${attributes}=  Get Attribute Names     ${element}       
            FOR     ${attribute}    IN  @{attributes}
                Log             ${attribute}
            END            
    END
    Take Screenshot                
    Close Browser           CURRENT
```

**Expected behavior**
The `Get Attribute Names` function does not change the data type from list to string if the list contains only one attribute name. Or in other words, the return value of the function is always the list data type even if the list contains only one element. 

**Screenshots**
![image](https://user-images.githubusercontent.com/121932909/210537339-78f56424-1f98-4cb6-948f-21c680a2cd63.png)

**Desktop (please complete the following information):**
 - OS Microsoft Windows 10 Pro
 - Version	10.0.19044 Build 19044
 - Browser Google Chrome
 - Version Version 108.0.5359.125 (Offizieller Build) (64-Bit)

**Additional context**
I am now changing my paradigm to get around the behavior with the standard `Run Keyword If` function and an additional keyword for a `FOR ... END` loop and case distinction. But that's work for me again! Once to identify the error and look for a solution. I would find it better if the data type is always list, if only one element.

**Comment by aaltat** [comment]
You are correct  the return type is always list of strings, even there is only one item in the list. I think it's better that keywords have only one return type, in this case a list. Because then one doesn't need write extra handling if  user have a scenario where keyword can return zero or more elements.

**Comment by 4WvgqJu** [comment]
Workaround:

robotframework-browser issues 2513
    [Documentation]     
    ...     https://https://github.com/MarketSquare/robotframework-browser/issues/2513                
       
    [Arguments]         ${attributes}   ${attribute}
    FOR     ${attribute}    IN  @{attributes}
            Log             ${attribute}
    END 

Test Insert
    [Tags]    AI    INSERT
    
    New Browser
    Suppress Logging
    Log                     ${this_is_whoever}
    Log                     ${this_is_secret}
    New Page                ${url2} 
    Unsuppress Logging               
    Take Screenshot
    ${elements} =           Get Elements        ${elementHref} 
    FOR     ${element}      IN  @{elements}
            Log             ${element}
            ${attributes}=  Get Attribute Names     ${element}
            Log             ${attributes}
            ${type}=        Evaluate        type($attributes)                
            Run Keyword If  "${type}" == "<class${space}'list'>"        robotframework-browser issues 2513      ${attributes}   ${attribute}
            ${list}=        Run Keyword If  "${type}" == "<class${space}'str'>"         Create List     ${attributes}
            Run Keyword If  "${type}" == "<class${space}'str'>"         robotframework-browser issues 2513      ${list}   ${attribute}                
    END
    Take Screenshot                
    Close Browser           CURRENT

**Comment by Snooz82** [comment]
Posted by @4WvgqJu in a new issue.
I closed that new issue and reopened this one for clarification.

Hard for me to understand what you write. Or are there no more issues? Maybe it is more understandable this way? 
To my great surprise, the functions Get Count, Get Length from the library BuiltIn  are not useful for counting the elements of the list. Because, the functions count either the number of characters of the element for one element in the container and the functions count the number of elements for more than one element in the container. Return value for `${attributes} = href` is 4, return value for `${attributes} = ['href', 'onclick']` is 2. In other words, in the first case the function counts the characters of one element, in the other case the function counts the number of elements of the list.

It's a workaround using kind of reflection on types:

```
robotframework-browser issues 2513
    [Documentation]     
    ...     https://https://github.com/MarketSquare/robotframework-browser/issues/2513                
       
    [Arguments]         ${attributes}   ${attribute}
    FOR     ${attribute}    IN  @{attributes}
            Log             ${attribute}
    END 

Test Insert
    [Tags]    AI    INSERT
    
    New Browser
    Suppress Logging
    Log                     ${this_is_whoever}
    Log                     ${this_is_secret}
    New Page                ${url2} 
    Unsuppress Logging               
    Take Screenshot
    ${elements} =           Get Elements        ${elementHref} 
    FOR     ${element}      IN  @{elements}
            Log             ${element}
            ${attributes}=  Get Attribute Names     ${element}
            Log             ${attributes}
            ${type}=        Evaluate        type($attributes)                
            Run Keyword If  "${type}" == "<class${space}'list'>"        robotframework-browser issues 2513      ${attributes}   ${attribute}
            ${list}=        Run Keyword If  "${type}" == "<class${space}'str'>"         Create List     ${attributes}
            Run Keyword If  "${type}" == "<class${space}'str'>"         robotframework-browser issues 2513      ${list}   ${attribute}                
    END
    Take Screenshot                
    Close Browser           CURRENT
```

**Comment by Snooz82** [comment]
@aaltat We actually have the current behaviour that Keywords that use `list_verify_assertion` do return a single value if there is only one element in that list and `None` if the list is empty.

it is done by `map_list` in `assertionengine` project. so technically it would be a BWIC in AssersionEngine and Browser
