### ISSUE TITLE
You are correct  the return type is always list of strings, even there is only one item in the list. I think it's better that keywords have only one return type, in this case a list. Because then one doesn't need write extra handling if  user have a scenario where keyword can return zero or more elements.

### ISSUE THREAD

**Issue by 4WvgqJu** [MarketSquare/robotframework-browser#2514]
You are correct  the return type is always list of strings, even there is only one item in the list. I think it's better that keywords have only one return type, in this case a list. Because then one doesn't need write extra handling if  user have a scenario where keyword can return zero or more elements.

_Originally posted by @aaltat in https://github.com/MarketSquare/robotframework-browser/issues/2513#issuecomment-1370807235_

**Comment by 4WvgqJu** [comment]
Hard for me to understand what you write. Or are there no more issues? Maybe it is more understandable this way? 
To my great surprise, the functions Get Count, Get Length from the library BuiltIn  are not useful for counting the elements of the list. Because, the functions count either the number of characters of the element for one element in the container and the functions count the number of elements for more than one element in the container. Return value for `${attributes} = href` is 4, return value for `${attributes} = ['href', 'onclick']` is 2. In other words, in the first case the function counts the characters of one element, in the other case the function counts the number of elements of the list.

**Comment by Snooz82** [comment]
Closed. Please continue on the same issue and do not open new ones.
