### ISSUE TITLE
Can't write rfbrowser.log to Browser lib installation directory

### ISSUE THREAD

**Issue by stude1** [MarketSquare/robotframework-browser#2519]
I have a Jenkins agent where root user installs everything needed and then passes the ball to Jenkins user for running the job. When I try to run

`rfbrowser init`

I get a problem that the log file can't be written to the Browser lib installation directory because it's protected. I think the location for the log file should be different:

`+ rfbrowser init
Traceback (most recent call last):
File "/usr/local/bin/rfbrowser", line 5, in <module>
from Browser.entry import main
File "/usr/local/lib/python3.9/site-packages/Browser/entry.py", line 36, in <module>
logging.FileHandler(INSTALL_LOG, mode="w"),
File "/usr/local/lib/python3.9/logging/__init__.py", line 1142, in __init__
StreamHandler.__init__(self, self._open())
File "/usr/local/lib/python3.9/logging/__init__.py", line 1171, in _open
return open(self.baseFilename, self.mode, encoding=self.encoding,
PermissionError: [Errno 13] Permission denied: '/usr/local/lib/python3.9/site-packages/Browser/rfbrowser.log'`

**Comment by aaltat** [comment]
@allcontributors please add @stude1 for bugs.

**Comment by stude1** [comment]
Still problems with "rfbrowser init". After the log file is written I get:
RuntimeError: `rfbrowser init` needs write permissions to /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/Browser/wrapper

Looks like the try-except is causing this. Log file is written to current dir and it contains also that error in the beginning. Also the whole log is printed to stdout in that case.

**Comment by stude1** [comment]
Silly me - it's not just the log file but all node modules that need to be installed to wrapper folder!

**Comment by aaltat** [comment]
No worries, it's good idea anyway. Because it's confusing if log file open fails, but clear if node side installation fail, at least I hope so.
