### ISSUE TITLE
New persistent context - "Switch page" to tab opened by a test cannot see the new tab 

### ISSUE THREAD

**Issue by ciadoh** [MarketSquare/robotframework-browser#2535]
**Describe the bug**
When using new persistent context for the setup, as part of a test it clicks a link and a new tab opens. When trying to use the switch page keyword, it cannot recognise the new page opened. If you use new browser and new context and do the same test steps it can see the new page fine and switch to it. 

**To Reproduce**
1. Use new persistent context for the setup
2. During the test click a url that will open a new tab in the browser
3. Use Switch Page keyword to switch the newly opened tab
4. It doesnt recognise the new page and error in the log is "Error: Tried to activate a new page but no new pages were detected in context."

**Expected behavior**
Newly opened page is switched to

**Desktop (please complete the following information):**
 - OS: MacOS Ventura
 - Browser chromium

**Additional context**
If you switch from using new persistent context and use new browser and then new context and run the same test steps, the switch page works fine. Also adding in Get Browser Catalog doesnt return the newly opened page when using new persistent context

**Comment by aaltat** [comment]
@allcontributors please add @ciadoh for bugs
