### ISSUE TITLE
Keyword "Wait Until Network Is Idle" is not using the default timeout

### ISSUE THREAD

**Issue by gdroes** [MarketSquare/robotframework-browser#254]
**Describe the bug**
using the keyword without a certain timeout should use the default. But the test result is an error.

Invalid time string ''

By using a certain timeout like 500ms the keyword is working fine.

**To Reproduce**
use this core to reproduce
*** Settings ***
Library   Browser

*** Test Cases ***
Example Test
    New Page    https://playwright.dev
    Get Text    h1    ==    🎭 Playwright
    Wait Until Network Is Idle

**Expected behavior**
The Test should not exit without a certain timeout

**Comment by xylix** [comment]
Thanks for the report :).

We didn't correctly get the library-wide default if timeout was not set in this keyword. Fixed in 8feed8e9b98d0b1f9a161ff14428af1f9934cbcf

**Comment by mkorpela** [comment]
@all-contributors please add gdroes for data

**Comment by mkorpela** [comment]
@all-contributors please add gdroes for test
