### ISSUE TITLE
Docker image 14.0.1 is 14.4.1 actually?

### ISSUE THREAD

**Issue by adrian-evo** [MarketSquare/robotframework-browser#2546]
I am asking this because I still want to use 14.4.1 and not yet the latest 15.0.0

**Comment by Snooz82** [comment]
It seems that the 14.0.1 is somehow a bit strange.
I can not really say which version it is, but between the 14.3.0 and the 14.4.1 there are really not many changes.

@adrian-evo 
May i ask why you do not want to go to 15.0.0?

**Comment by adrian-evo** [comment]
@Snooz82 I was testing 14.4.1 today and planned to deploy also docker image. I was not expecting 15.0.0 and I can see some backward incompatible changes which I didn't checked yet.

**Comment by aaltat** [comment]
We found a bug in our release process and we need to fix the problem.

**Comment by aaltat** [comment]
@allcontributors please add @adrian-evo for bugs

**Comment by aaltat** [comment]
This is actually fixed now
