### ISSUE TITLE
The docker images starting with v14.2.0 give playwright process error when run on CI/CD environment

### ISSUE THREAD

**Issue by adrian-evo** [MarketSquare/robotframework-browser#2558]
I was trying to use docker image with gitlab CI/CD, which means to build own image from a rfbrowser-stable version, install some python and node.js packages and then run tests.

When I build the image with any rfbrowser-stable version from 15.0.0 down to v14.1.0, the test fails with the below error. Only v14.1.0 and below works fine. I tried very simple Dockerfile steps like this:

```
FROM ghcr.io/marketsquare/robotframework-browser/rfbrowser-stable:v14.1.0
USER pwuser

```
```
Could not connect to the playwright process at port 40817.
Traceback (most recent call last):
  File "/home/pwuser/.local/lib/python3.8/site-packages/Browser/browser.py", line 825, in __init__
    libraries.append(self._initialize_jsextension(params["jsextension"]))
  File "/home/pwuser/.local/lib/python3.8/site-packages/Browser/browser.py", line 877, in _initialize_jsextension
    with self.playwright.grpc_channel() as stub:
  File "/usr/lib/python3.8/contextlib.py", line 113, in __enter__
    return next(self.gen)
  File "/home/pwuser/.local/lib/python3.8/site-packages/Browser/playwright.py", line 139, in grpc_channel
    playwright_process = self._playwright_process
  File "/usr/lib/python3.8/functools.py", line 967, in __get__
    val = self.func(instance)
  File "/home/pwuser/.local/lib/python3.8/site-packages/Browser/playwright.py", line 57, in _playwright_process
    self.wait_until_server_up()
  File "/home/pwuser/.local/lib/python3.8/site-packages/Browser/playwright.py", line 125, in wait_until_server_up
    raise RuntimeError(
RuntimeError: Could not connect to the playwright process at port 40817.

```

**Comment by frodo23g** [comment]
I think it is related to this issue: https://github.com/MarketSquare/robotframework-browser/issues/1037
I get the Same issue, when I use 
`export http_proxy http://proxy-xxxx:8080/
export https_proxy http://proxy-xxxxxxx:8080/`
with version higher then 14.1.0. 
When you try it with no Proxy, then I don't get that issue, but for my Project I need that Proxy Settings. 
I stick with version 14.1.0 for now.

**Comment by adrian-evo** [comment]
Tried with no_proxy=localhost,127.0.0.1 as suggested in the issue #1037 and it works for me now with the latest docker image rfbrowser-stable:16.0.2

**Comment by TerryMcCabe-EN0038** [comment]
> Tried with no_proxy=localhost,127.0.0.1 as suggested in the issue #1037 and it works for me now with the latest docker image rfbrowser-stable:16.0.2

Are you adding this as a env variable when running container

e.g.

docker run --env no_proxy=localhost,127.0.0.1

**Comment by adrian-evo** [comment]
I defined the variable in .gitlab-ci.yml file like this:

variables:
  http_proxy: server_name
  https_proxy: server_name
  no_proxy: "localhost,127.0.0.1,maybe_other_local_domain"
  HTTP_PROXY: $http_proxy
  HTTPS_PROXY:$https_proxy
  NO_PROXY: $no_proxy

but I think it works also in the stage script section with e.g.

  script:
    - export no_proxy=...

**Comment by TerryMcCabe-EN0038** [comment]
> I defined the variable in .gitlab-ci.yml file like this:
> 
> variables: http_proxy: server_name https_proxy: server_name no_proxy: "localhost,127.0.0.1,maybe_other_local_domain" HTTP_PROXY: $http_proxy HTTPS_PROXY:$https_proxy NO_PROXY: $no_proxy
> 
> but I think it works also in the stage script section with e.g.
> 
> script: - export no_proxy=...

Thank you!

I'm using Azure DevOps so will try that in script stage as passing in as a docker environment variable is not working.

It's very frustrating as it the tests run fine in my local docker instance without having to do any manipulation but fail miserably in pipelines. :-(

**Comment by TerryMcCabe-EN0038** [comment]
> Thank you!
> 
> I'm using Azure DevOps so will try that in script stage as passing in as a docker environment variable is not working.
> 
> It's very frustrating as the tests execute fine in my local docker instance without having to do any manipulation but fail miserably in pipelines. :-(

Unfortunately this never worked.

**Comment by aaltat** [comment]
I think this is now fixed and I am closing the issue. If problems are seen, please contact us
