### ISSUE TITLE
Ability to use the Get Style keyword to get CSS pseudo-element style

### ISSUE THREAD

**Issue by sandeepvaidya** [MarketSquare/robotframework-browser#2564]
**Is your feature request related to a problem? Please describe.**
I wanted to get styles of the '::before'  pseudo-element:
e.g.:    "border-left-color": "rgb(0, 0, 255)", "border-left-style": "solid", "border-left-width": "3px",

**Describe the solution you'd like**
I want to use the browser keyword, Get Style, instead of JavaScript methods, getPropertyValue , and getComputedStyle.

**Describe alternatives you've considered**
I was able to achieve the goal with the 'Evaluate JavaScript' keyword:

`Evaluate Javascript    li[title = "Folder 2"] .MuiTreeItem-content   e => window.getComputedStyle(e, '::before').getPropertyValue('border-left')``

**Additional context**

**Comment by aaltat** [comment]
@allcontributors please add @sandeepvaidya for ideas
