### ISSUE TITLE
console is hang longer when closing chrome browser

### ISSUE THREAD

**Issue by rarajabs** [MarketSquare/robotframework-browser#2569]
**Describe the bug**
I have run my script in windows powershell environment. I noticed console will hang when closing chrome browser after test.

**To Reproduce**
my test code:

chrome.robot
```
*** Settings ***
Library     Browser


*** Variables ***
${url}      https://www.youtube.com


*** Test Cases ***
Chrome
    New Browser    headless=False    channel=chrome
    New Page    url=${url}
```

chromium.robot
```
*** Settings ***
Library     Browser


*** Variables ***
${url}      https://www.youtube.com


*** Test Cases ***
Chromium
   New Browser    browser=chromium    headless=False
   New Page    url=${url}

```

The run both robot files in powershell and compare the time when console is release again by
```
robot .\chrome.robot
```

**Expected behavior**
I have compare same steps with node.js, but console able to release fast, almost same when test with stock chromium browser

**Screenshots**
https://user-images.githubusercontent.com/1460421/212905453-bf38d9d1-aa91-4176-921b-3a7d1787ba61.mp4

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser Chrome

**Comment by aaltat** [comment]
@allcontributors please add @rarajabs for bugs

**Comment by aaltat** [comment]
At the end of the execution we close the browser, context and page automatically. For some reason it takes longer with Chrome. I am pretty sure that problem is somewhere in the Chrome side, because with both browser, our code is the same. 

Because we can not fix the problem in Browser library side, I am closing the issue.
