### ISSUE TITLE
Keyword "Set Assertion Formatters" should have a scope

### ISSUE THREAD

**Issue by simonmeggle** [MarketSquare/robotframework-browser#2571]
As discussed on the Robocon23 workshop. 
See other "Set... " keywords, which have one.

**Comment by aaltat** [comment]
@allcontributors please add @simonmeggle for ideas

**Comment by Snooz82** [comment]
@simonmeggle I checked the code and that keyword is actually a keyword from AssertionEngine itself and is not implemented in Browser. Therefore it is not possible to implement a scope to it without overwriting the whole keyword.

@aaltat do you have a different opinion?

**Comment by aaltat** [comment]
If we want to implement similar scopes are in Browser library, that implementation most likely needs to live in Browser library side. But it is easy to implement default scope, example test in AssertionEngine side, but that is not very flexible or useful for all users. I would go with option implement scope in Browser library side.

**Comment by aaltat** [comment]
I have an idea how to make it work, but it needs more co-operation from AssertionEngine and library using it. Also my idea is backwards incompatible. But if my idea works it’s step to right direction

**Comment by aaltat** [comment]
Set Assertion Formatters keyword was deprecated and new  Set Assertion Formatter keyword was created, with different interface and possibly to create an scope.
