### ISSUE TITLE
Open chrome browser instead of chromium

### ISSUE THREAD

**Issue by everlighting** [MarketSquare/robotframework-browser#2577]
Is there way to open chrome browser (except using channel =chrome way)

**Comment by aaltat** [comment]
In [New Browser](https://marketsquare.github.io/robotframework-browser/Browser.html#New%20Browser) keyword ` executablePath` argument.

**Comment by everlighting** [comment]
getting this error message while using executable path **Only local connections are allowed.)**

**Comment by aaltat** [comment]
Would it be possible to see full error message?

**Comment by everlighting** [comment]
pid=31504][out] Starting ChromeDriver 108.0.5359.71 (1e0e3868ee06e91ad636a874420e3ca3ae3756ac-refs/branch-heads/5359@{#1016}) on port 9515
[pid=31504][out] Only local connections are allowed.
[pid=31504][out] Please see https://chromedriver.chromium.org/security-considerations for suggestions on keeping ChromeDriver safe.
[pid=31504][out] ChromeDriver was started successfully.
============================================================
Tip: Use "Set Browser Timeout" for increasing the timeout or double check your locator as the targeted element(s) couldn't be found.

**Comment by aaltat** [comment]
Errr, are you sure that is the full error message? I was more looking error from the keyword start to the keyword end. Also please set ` enable_playwright_debug` as true in library import and show us the `playwright-log.txt` file. But please note that `playwright-log.txt` contains everything as plain text, including secrets.

**Comment by aaltat** [comment]
Closing due inactivity
