### ISSUE TITLE
how to pass --allowed-ips option in Browser library while oprning browser?I need to open chrome instead of chromium so I am using executablepath option

### ISSUE THREAD

**Issue by everlighting** [MarketSquare/robotframework-browser#2591]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by aaltat** [comment]
Is this still relevant?

**Comment by aaltat** [comment]
Closing due inactivity
