### ISSUE TITLE
Using `Record Selector` twice crashes the browser

### ISSUE THREAD

**Issue by fabioz** [MarketSquare/robotframework-browser#2598]
When trying to use `Record Selector` along with the `Interactive Console`, the second call to `Record Selector` makes the browser crash.

This can also be reproduced by simply running the code below (run the code, select the first text entry, then select "Take it" and then see it crash).

```
*** Settings ***
Library    Browser

*** Tasks ***
Automate https://robotsparebinindustries.com/
    Open Browser    url=https://robotsparebinindustries.com/
    Record Selector
    Record Selector
```

Version:  `robotframework-browser==15.1.0`.

**Comment by aaltat** [comment]
@allcontributors please add @fabioz for bugs.

**Comment by aaltat** [comment]
@mkorpela this is your baby

**Comment by mkorpela** [comment]
🤣

**Comment by mkorpela** [comment]
Still need to be released, but the fix is in the main.
