### ISSUE TITLE
`New Context  httpCredentials=$someVar` doesn't work

### ISSUE THREAD

**Issue by MHHenriksen** [MarketSquare/robotframework-browser#2665]
**Describe the bug**
The documentation for the HttpCredentials type (in the [New Context keyword doc](https://marketsquare.github.io/robotframework-browser/Browser.html#New%20Context)) gives an example with using variables as `New Context  httpCredentials=${someVar}`. That's no longer supported as of 5.0.0 due to #2523 and an error message is rightly given, but the documentation here needs to be updated.

However, the error message instructs me to use `$someVar` instead, i.e. `New Context  httpCredentials=$someVar`, but this also doesn't work. :( The only thing that works is the much more verbose `New Context  httpCredentials={'username': '$username', 'password': '$pwd'}`.

I suspect the reason is that [the keyword implementation](https://github.com/MarketSquare/robotframework-browser/blob/main/Browser/keywords/playwright_state.py#L481) specifies the httpCredentials argument type as `httpCredentials: Optional[HttpCredentials] = None` which fails because '$someVar' is still just a string when passed here.

So some of the documentation definitely needs to be updated to align with #2523, but I'll leave it to you to decide if you want to support `New Context  httpCredentials=$someVar` or not.

**To Reproduce**
```
*** Variables ***
&{AdminAdmin}    username=admin    password=admin

*** Test Cases ***
Context with credentials
        New Context    httpCredentials=$AdminAdmin
```

**Expected behavior**
The context is created.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser default
 - Version latest?

**Comment by aaltat** [comment]
@allcontributors please add @MHHenriksen for bugs

**Comment by aaltat** [comment]
Correct syntax would be

```
Context with credentials
        New Context    httpCredentials=${AdminAdmin}
```

There actually was very confusing documentation, but that is now fixed in the resent 16.x release. Therefore I am going to close the issue. 

If you have suggestion how to make documentation better, please tell and we can take it in use.
