### ISSUE TITLE
New Browser and Get Browser Ids - wrong browser ID on ver 16.0.0

### ISSUE THREAD

**Issue by alexinoDr** [MarketSquare/robotframework-browser#2669]
**Describe the bug**
It seems there is a problem with New Browser keyword and browser's ID returned in Get Browser Ids keyword. 

I used Suite Setup with New Browser, New Context and New Page kw's for all Test Cases (TC), except one (third TC), which called New Browser, New Context and New Page separately inside TC (and also closed it inside TC) - in the background was still opened browser from suite setup.

When I run this test on robotframework-browser ver 15.0.0 and 16.0.0 - there is a different behaviour on each version.

On 15.0.0 version - in all test cases were returned browser ID from suite setup, in third TC was returned also next browser ID, used as active and in the last TC continued with browser from suite setup. This seems to be, according to my opinion, correctly.

On 16.0.0 version - in first, second and third TC were returned browser ID from suite setup - even though in the third TC I expected a new browser ID - and it caused there was closed browser (because of the same ID), so the last TC failed with an 'no active page' error

**To Reproduce**
run attached file on both Browser versions
[test_NewBrowser_inSuite_and_oneTestCase.txt](https://github.com/MarketSquare/robotframework-browser/files/10845198/test_NewBrowser_inSuite_and_oneTestCase.txt)

**Expected behavior**
new opened browser gets a new id

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser default - chromium
 - Version  robotframework-browser 16.0.0
- python version 3.11.2

**Comment by aaltat** [comment]
@allcontributors please add @alexinoDr for bugs

**Comment by aaltat** [comment]
@alexinoDr is your problem explained by this https://github.com/MarketSquare/robotframework-browser/issues/2821#issuecomment-1564993077

**Comment by aaltat** [comment]
Closing due inactivity.
