### ISSUE TITLE
storageState can't use in New Persistent Context

### ISSUE THREAD

**Issue by Aino1980** [MarketSquare/robotframework-browser#2679]
**Describe the bug**
storageState can't use in New Persistent Context

**To Reproduce**
1. storageState use in New Context Working properly
   eg：'storageState': '/var/folders/nx/j8n9189d3jj8plg9rdg14lbw0000gn/T/info/user1.json'
2. storageState can't use in New Persistent Context

**Desktop (please complete the following information):**
 - OS: [MACOS 13.2.1]
 - Browser [chromium]
 - Version [robotframework-browser-16.0.0]

**Comment by aaltat** [comment]
What can't use actually means? Is there error, if yes what error? Is something not working, what that might be and how do you see it? 

@allcontributors please add @Aino1980 for bugs

**Comment by Snooz82** [comment]
I think it just means, that storageState is not supported by playwright for [launchPersistentContext](https://playwright.dev/docs/api/class-browsertype#browser-type-launch-persistent-context) .

this is imho added without test or reason.

**Comment by Snooz82** [comment]
Will be removed in 18.0.0 
see #2990

**Comment by Snooz82** [comment]
remove `storageState` from persistent context in 18.0.0

**Comment by aaltat** [comment]
Remove also `hideRfBrowser` from `New Context` and `New Persistent Context` keyword.
