### ISSUE TITLE
Keyword local assertion timeout override

### ISSUE THREAD

**Issue by xylix** [MarketSquare/robotframework-browser#270]
There is need for ability to override retry mechanism / implicit waits when page has for example moving parts, which need to be asserted to be at a specific location

**Comment by Snooz82** [comment]
@xylix How is that not solvable with [Retry Assertion For](https://marketsquare.github.io/robotframework-browser/Browser.html#Set%20Retry%20Assertions%20For) ?

**Comment by xylix** [comment]
Should be solvable. Closing.
