### ISSUE TITLE
Chrome DLL issue 

### ISSUE THREAD

**Issue by amankul** [MarketSquare/robotframework-browser#2710]
**Describe the bug**
Tests started failing suddenly after 14-March-2023.  Chrome binaries are found to be present on the agent. 
Firefox runs fine. 

**To Reproduce**
1. Install robotframework, robotframework-requests, robotframework-browser via pip
2. rfbrowser init
3. Try to launch chromium browser

Error: browserType.launch: Browser closed.
==================== Browser output: ====================
<launching> C:\Python39\lib\site-packages\Browser\wrapper\node_modules\playwright-core\.local-browsers\chromium_win64_special-1050\chrome-win\chrome.exe --disable-field-trial-config --disable-background-networking --enable-features=NetworkService,NetworkServiceInProcess --disable-background-timer-throttling --disable-backgrounding-occluded-windows --disable-back-forward-cache --disable-breakpad --disable-client-side-phishing-detection --disable-component-extensions-with-background-pages --disable-component-update --no-default-browser-check --disable-default-apps --disable-dev-shm-usage --disable-extensions --disable-features=ImprovedCookieControls,LazyFrameLoading,GlobalMediaControls,DestroyProfileOnBrowserClose,MediaRouter,DialMediaRouteProvider,AcceptCHFrame,AutoExpandDetailsElement,CertificateTransparencyComponentUpdater,AvoidUnnecessaryBeforeUnloadCheckSync,Translate --allow-pre-commit-input --disable-hang-monitor --disable-ipc-flooding-protection --disable-popup-blocking --disable-prompt-on-repost --disable-renderer-backgrounding --disable-sync --force-color-profile=srgb --metrics-recording-only --no-first-run --enable-automation --password-store=basic --use-mock-keychain --no-service-autorun --export-tagged-pdf --no-sandbox --user-data-dir=D:\BuildAgent\temp\buildTmp\playwright_chromiumdev_profile-LENWzH --remote-debugging-pipe --no-startup-window
<launched> pid=7676
[pid=7676][err] [0321/175125.728:ERROR:main_dll_loader_win.cc(109)] Failed to load Chrome DLL from C:\Python39\lib\site-packages\Browser\wrapper\node_modules\playwright-core\.local-browsers\chromium_win64_special-1050\chrome-win\chrome.dll: The specified procedure could not be found. (0x7F)
=========================== logs ===========================
<launching> C:\Python39\lib\site-packages\Browser\wrapper\node_modules\playwright-core\.local-browsers\chromium_win64_special-1050\chrome-win\chrome.exe --disable-field-trial-config --disable-background-networking --enable-features=NetworkService,NetworkServiceInProcess --disable-background-timer-throttling --disable-backgrounding-occluded-windows --disable-back-forward-cache --disable-breakpad --disable-client-side-phishing-detection --disable-component-extensions-with-background-pages --disable-component-update --no-default-browser-check --disable-default-apps --disable-dev-shm-usage --disable-extensions --disable-features=ImprovedCookieControls,LazyFrameLoading,GlobalMediaControls,DestroyProfileOnBrowserClose,MediaRouter,DialMediaRouteProvider,AcceptCHFrame,AutoExpandDetailsElement,CertificateTransparencyComponentUpdater,AvoidUnnecessaryBeforeUnloadCheckSync,Translate --allow-pre-commit-input --disable-hang-monitor --disable-ipc-flooding-protection --disable-popup-blocking --disable-prompt-on-repost --disable-renderer-backgrounding --disable-sync --force-color-profile=srgb --metrics-recording-only --no-first-run --enable-automation --password-store=basic --use-mock-keychain --no-service-autorun --export-tagged-pdf --no-sandbox --user-data-dir=D:\BuildAgent\temp\buildTmp\playwright_chromiumdev_profile-LENWzH --remote-debugging-pipe --no-startup-window
<launched> pid=7676
[pid=7676][err] [0321/175125.728:ERROR:main_dll_loader_win.cc(109)] Failed to load Chrome DLL from C:\Python39\lib\site-packages\Browser\wrapper\node_modules\playwright-core\.local-browsers\chromium_win64_special-1050\chrome-win\chrome.dll: The specified procedure could not be found. (0x7F)

**Expected behavior**
Browser should run. 

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Chromium
 - Version 1045

**Comment by Snooz82** [comment]
For me it is unclear what chrome you have installed


Current Release is compatible with the following releases.


Browser Versions[​](https://playwright.dev/docs/release-notes#browser-versions)

Chromium 111.0.5563.19
Mozilla Firefox 109.0
WebKit 16.4
This version was also tested against the following stable channels:

Google Chrome 110
Microsoft Edge 110

**Comment by amankul** [comment]
Did not install anything explicitly. Whatever "rfbrowser init"  does. And this is has been always like this.

**Comment by aaltat** [comment]
Closing because this is upstream problem.
