### ISSUE TITLE
Attach video recording to robot log report

### ISSUE THREAD

**Issue by rarajabs** [MarketSquare/robotframework-browser#2719]
Hi,

I would like to request to have video attachment to robot framework report log.

The expected outcome should same with `Take Screenshot` keyword. Currently screenshot image will attached to report log, but it is not able to do so with video recording.

**Comment by aaltat** [comment]
Video should be in the log.html file, in the Open Page keyword. 

Video can not be separate keyword, because recording of the video starts when page starts and stops when page closes.

**Comment by aaltat** [comment]
Basically what you want is not possible, because video recording can not be controlled in the way you wanting. Therefore I am going to close the issue.
