### ISSUE TITLE
Docs are confusing regarding assertion operator for "not contains" 

### ISSUE THREAD

**Issue by Krisseck** [MarketSquare/robotframework-browser#2734]
**Describe the bug**
Reading the documentation, there is a table for assertions. 

![image](https://user-images.githubusercontent.com/471887/229484942-e6c8ea7b-b7a8-40bc-965c-154ae63ae15c.png)

It is unclear what is the operator for "not contains". There is a row for the assertion, but the operator is missing. Is it because:

- There is no operator for "not contains"?
- There is a HTML content/layout bug?

**To Reproduce**
https://marketsquare.github.io/robotframework-browser/Browser.html#Assertions

**Expected behavior**
I should be able to understand that there is either no operator for "not contains", or that there's a bug in documentatio.

**Comment by aaltat** [comment]
Closing due inactivity
