### ISSUE TITLE
Click with Options: click_count, delay and position_x/y not working

### ISSUE THREAD

**Issue by Finalrykku** [MarketSquare/robotframework-browser#275]
**Describe the bug**
None of the features are behave as designed so far. Look at https://github.com/MarketSquare/robotframework-browser/pull/274 for further details.

I modified the login page and added a button for the tests.

Delay click should fail, but succeeded due to another bug in the assertions.

**Comment by aaltat** [comment]
I don't quite understand what the bug is, could you explain more?

**Comment by Snooz82** [comment]
afaik it is fine now
