### ISSUE TITLE
Examples at https://robotframework-browser.org/ broken

### ISSUE THREAD

**Issue by pekkaklarck** [MarketSquare/robotframework-browser#2754]
Both RF and Python examples fail due to Playwright page being changed so that validation `h1    ==    🎭 Playwright` isn't anymore correct. Probably should just check that `h1` contains `Playwright`.

Python example fails already earlier when trying to set `httpCredentials={"username": "admin", "password": "123456"}` for this error:
> `ValueError: Direct assignment of values or variables as 'httpCredentials' is not allowed. Use special variable syntax ($var instead of ${var}) to prevent variable values from being spoiled.`

Probably easiest to just remove that seemingly unnecessary `httpCredentials` altogether. The error is pretty confusing in this context as well, though.

**Comment by Snooz82** [comment]
Examples updated
