### ISSUE TITLE
Docker image not working, says incompatible Playwright version

### ISSUE THREAD

**Issue by frirasyidi** [MarketSquare/robotframework-browser#2804]
**Describe the bug**
When running on my CI pipeline using the latest version docker (FROM marketsquare/robotframework-browser/rfbrowser-stable:16.1), I was told that the Playwright version needs to be updated from 1.30 to 1.33.

This issue does not happen when I install the RF Browser in my local machine using pip. So it's exclusively on the docker version.

I have tried adding Playwright installation on my CI script using `npx playwright install` before running my test, which successfully install Playwright 1.33, but it did not solve the issue.

Anyone can help me solve this?

**Screenshots**
_The error shown on the test log:_
<img width="937" alt="Screenshot 2023-05-16 at 17 57 55" src="https://github.com/MarketSquare/robotframework-browser/assets/4636602/887858a3-5535-4f66-a7c1-0e929d91744f">

_The console log of Playwright 1.33 installation being initiated before the test:_
<img width="1038" alt="Screenshot 2023-05-16 at 18 05 27" src="https://github.com/MarketSquare/robotframework-browser/assets/4636602/9be5a34e-4cca-47f9-8706-673c8ef6ebd8">

**Comment by frirasyidi** [comment]
I am astonished that there is no response nor other person who commented on this even after two weeks since its post date.
Am I the only one using the latest Browser version? Or does everyone else not encounter the same issue?

**Comment by Snooz82** [comment]
Hi @frirasyidi 

This sometimes happen, on Open-Source projects that are totally free to use.
Sometimes we just have no time to answer or no clue why this is not working on your maching.

Please try it again with the newest docker image.

**Comment by frirasyidi** [comment]
@Snooz82 thanks for your reply, most appreciated.

I fully understand the limitation of an open source project, just amazed that with the popularity of the project, even after 2 months, nobody else seemed to face the same issue as I do.

So, closing the issue now.
