### ISSUE TITLE
Support of embeded argument method

### ISSUE THREAD

**Issue by Zoupers** [MarketSquare/robotframework-browser#2828]
**Is your feature request related to a problem? Please describe.**
> A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]
Recently, I am using declearitive style to format a test, and found that It seems robotframework-browser does not support that.

**Describe the solution you'd like**
> A clear and concise description of what you want to happen.
I have found that we can easily do it by modify the text body in `_jskeyword_call` method. Robotframework support define embedding arguments into keyword name even it is defined in python.

**Describe alternatives you've considered**
> A clear and concise description of any alternative solutions or features you've considered.
I don't know.

**Additional context**
> Add any other context or screenshots about the feature request here.

**Comment by aaltat** [comment]
Do I get you right, you want embedded argument support also in the JS api keywords?

**Comment by aaltat** [comment]
@allcontributors please add @Zoupers for ideas.

**Comment by Zoupers** [comment]
> Do I get you right, you want embedded argument support also in the JS api keywords?

I don't know if we are thinking about the same thing. But here is a example.

![image](https://github.com/MarketSquare/robotframework-browser/assets/29817738/f73a916e-de04-4990-9622-38d7dcfacc32)

And then we can use it as a embed argument keyword `embed argument js func ${a}` in rf.

**Comment by aaltat** [comment]
Basically what you want is possible, one can call keyword from Python side and have embedded arguments and call the the method from JS side. Here is an [example](https://github.com/Snooz82/robotframework-browser-advanced-workshop/tree/main/2.2.Python_Plugin-API#223-python-plugin-with-nodejs-implementation

**Comment by Zoupers** [comment]
Yes, I can accomplish my goal by the python extension. And it seems I can using a dynamic way to do without set embeded name in python side. 

But I found a little problem during the experiment.

Like this case.

```
    @keyword('EmbedArgument"${a}":"${b}"')
    def embed_argument(self, a, b):
        logger.info("Get Embed Argument: %s, %s" % (a,b))
```

And get this error.
![image](https://github.com/MarketSquare/robotframework-browser/assets/29817738/be53d622-fa7a-4038-9d5a-ef801296adb8)

It's a little wired.

**Comment by aaltat** [comment]
That indeed is strange, I did read user guide and it didn’t provide clear answer. But I asked in slack and let’s see what the answer is.

**Comment by aaltat** [comment]
The embedded arguments do work, when I have this plugin:

```python
from robot.api.deco import keyword

from Browser.base.librarycomponent import LibraryComponent


class ExamplePlugin(LibraryComponent):

    @keyword("foo is '${a}':'${b}' ")
    def method(self, a, b):
        print(a, b)
```
And when I import it like this
```robot
Library     Browser
...             plugins=${CURDIR}ExamplePlugin.py
```
And use it like this:
```robot

*** Variables ***
${a}    1
${b}    2

*** Test Cases ***
Example
    foo is '${a}':'${b}'
```

all works like expected.

**Comment by Zoupers** [comment]
Yes, that's could work. And I found that I can solve the problem I propose before by change keyword name to lowercase which won't effect the function at all.

**Comment by aaltat** [comment]
I guess you have a solution and we can close the issue.
