### ISSUE TITLE
Switch / Close keyword improvements

### ISSUE THREAD

**Issue by xylix** [MarketSquare/robotframework-browser#284]
- [x] Support SeleniumLibrary style `NEW` argument in Switch / Close keywords
  - Should this technically be the second to last one since the last one is _current_?
  - Add a new data structure that contains all the pages / contexts besides the stack. Stack if for tracking the usage history
- [x] Document the options at a single place or keyword specifically?
- [x] Implement `ALL` enum functionality

**Comment by Finalrykku** [comment]
Have Implemented ALL to all keyword documentations. Will commit the changes by the next pull request.
