### ISSUE TITLE
Robot Framework gets stuck after writing reports when used together with AutoRecorder and Filehandling promises

### ISSUE THREAD

**Issue by lasselindqvist** [MarketSquare/robotframework-browser#2864]
**Describe the bug**
Robot Framework gets stuck after writing reports when used together with AutoRecorder (https://github.com/sebastianciupinski/robotframework-autorecorder) and file handling promises.
I have managed to reproduce this with both Firefox and Chrome, so it does not seem to be dependent on any specific browser.

**To Reproduce**
Have resources file:
```
*** Settings ***
Library     AutoRecorder

```
and a test file

```
*** Settings ***
Library    Browser
Resource   ${CURDIR}/resources.robot

*** Test Cases ***
Promisetest
    New Browser     firefox    headless=False
    New Context     ignoreHTTPSErrors=True    acceptDownloads=True
    New Page    https://google.com

    ${dl_promise}        Promise To Wait For Download    filename.txt
    Wait For     ${dl_promise}      timeout=3

Promisetest2
    New Browser     firefox    headless=False
    New Context     ignoreHTTPSErrors=True    acceptDownloads=True
    New Page    https://google.com
    ${dl_promise}        Promise To Wait For Download    filename.txt
    Wait For     ${dl_promise}      timeout=3
```

Execute all tests:
`python -m robot .`

This only happens when you execute multiple tests. It does not matter if the other tests immediately skip the test execution by having a Skip statement in them.
Now if you move the AutoRecorder import away from the resource file and directly into the test file this does not happen.
Also if you remove AutoRecorder import or Promise To Wait For Download it also does not get stuck.
In this example there is not file to actually download, but the same problem happens even if the file was properly downloaded.
This happens for both file download and upload promises.

**Expected behavior**
The Robot test execution ends properly.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows/Linux
 - Browser: Chrome/Firefox

**Additional context**
I am not sure if this is a problem with Robot framework itself, browser library or Autorecorder.

**Comment by aaltat** [comment]
Have tried to enable RF system log and see what it says: https://robotframework.org/robotframework/latest/RobotFrameworkUserGuide.html#system-log

**Comment by aaltat** [comment]
@allcontributors please add @lasselindqvist for bugs

**Comment by lasselindqvist** [comment]
the syslog shows nothing that helps solve this mystery:
```
20230616 10:38:15.913 | INFO  | Ended suite 'Robot'.
20230616 10:38:15.915 | INFO  | Output: C:\Users\username\git\project\robot\output.xml
20230616 10:38:15.915 | INFO  | Tests execution ended. Statistics:
4 tests, 1 passed, 1 failed, 2 skipped
20230616 10:38:16.539 | INFO  | Log: C:\Users\username\git\project\robot\log.html
20230616 10:38:16.811 | INFO  | Report: C:\Users\username\git\project\robot\report.html
```
and then it gets stuck

**Comment by aaltat** [comment]
Have you looked at the output.xml and is there something funny looking, no idea what it could be. But I am pretty much out of good ideas from our side. I think you should report the issue to RF core issue tracker, perhaps also include the output.xml file too.

**Comment by aaltat** [comment]
Because this looks like problem in RF core side, please open issue there and I am going to close this issue.
