### ISSUE TITLE
WebKit is not supported when using Persistent Context

### ISSUE THREAD

**Issue by david-ns** [MarketSquare/robotframework-browser#2875]
**Describe the bug**
When using Persistent Context, only Chromium and Firefox are supported. WebKit throws an error:
`Invalid browserType for New Persistent Context`

**To Reproduce**
Launch a New Persistent Context with `webkit` as browser.

**Expected behavior**
A new Persistent Context is created with WebKit as the browser.

**Desktop (please complete the following information):**
 - OS: macOS 12.6.6
 - Browser: Safari
 - Version: 16.2.0

**Additional context**
It looks like WebKit is missing here: https://github.com/MarketSquare/robotframework-browser/blob/7b518d8c953725468076204564a4c9ee581dc977/node/playwright-wrapper/playwright-state.ts#L645

**Comment by aaltat** [comment]
@xylix you made the feature, do you recall why WebKit is not supported?

**Comment by aaltat** [comment]
@allcontributors please add @david-ns for bugs

**Comment by Snooz82** [comment]
I think it was just forgotten to be added in the list of Browsers.
I fixed it and briefly tested and it worked.
Is fixed with #2926
