### ISSUE TITLE
Document Take Screenshot default screenshot path

### ISSUE THREAD

**Issue by xylix** [MarketSquare/robotframework-browser#290]

**Comment by Finalrykku** [comment]
I just found out that Take Screenshot has no default file name. If a test is executed like
`.../project/rfbrowser>robot tests\.`
and the test contains the function without arguments like 
`Take Screenshot`
a file `.../project/rfbrowser.png` is created.

Maybe a filename should be required?

**Comment by xylix** [comment]
Fixed in aab154f6c39a4d68eac0f886997a3d5c10160ddf
