### ISSUE TITLE
Version issue on dockerhub

### ISSUE THREAD

**Issue by DrVanScott** [MarketSquare/robotframework-browser#2952]
Hi,

the releases here on github are kind of "v16..." or now "v17..."

Currently on dockerhub the "17.x" version is only available without leading "v". Older version are available with both variants.

Which one is the correct/official schema?

**Comment by aaltat** [comment]
The docker image is automatically created by a GitHub action. The action is triggered by a creation of a tag and far I can see all tags are in same format. But I guess something has changed, no idea what it should be.

**Comment by DrVanScott** [comment]
I don't find any CD code which pushes images to docker hub. Maybe that code is not part of this repository. Or is this a manual task? Then it would even be more important to clarify, which versioning schema is the correct one to use.

But as versions are named/tagged "v..." in github, i would say it would be best to use the same schema for tags on dockerhub?

**Comment by aaltat** [comment]
Automatic push is done in here https://github.com/MarketSquare/robotframework-browser/blob/main/.github/workflows/dockers.yml

**Comment by DrVanScott** [comment]
Thanks for helping me with the workflow file. As it looks from its content, tagging is done for both - dockerhub and github registry - in the same way:  without the leading "v".

But the question remains, why there are "v" tags (and non-V tags for the same releases) for older releases on docker hub? And interestingly, the thing also changed on github registry as you can see here: https://github.com/MarketSquare/robotframework-browser/pkgs/container/robotframework-browser%2Frfbrowser-stable/versions?filters%5Bversion_type%5D=tagged

Maybe the issue is because before cutting out the docker worklow out of the release workflow, both taggings were defined in different ways? https://github.com/MarketSquare/robotframework-browser/commit/041a1b69da9825cfab21afabbf111c4a4683496b#diff-262d44eaf4bec1ca370d4ecd6e380b70cab17f0150e848c894cddfcfff89bcbfL29

**Comment by Snooz82** [comment]
I would say yes.

use `17.x` on Docker-Hub or Github.

the actual versions are `17.x` only the github tags have the leading v
