### ISSUE TITLE
Some Keywords [Documentation:] show in Log.html a link to Playwright Locator

### ISSUE THREAD

**Issue by Alpha-Centauri-00** [MarketSquare/robotframework-browser#2957]
As mentioned in Slack [Thread](https://robotframework.slack.com/archives/C015KB1QSDN/p1689270988009669) that some keywords have a link to a locator page in playwright. 

![image](https://github.com/MarketSquare/robotframework-browser/assets/56655042/82e502f8-c088-4f2c-aee1-3ff196f41bdf)

but I think the link should be to Browser Docs instead. (Finding Elements)

**Describe the solution you'd like**
The solution is easy, since there is already a class that takes the first line of a Keyword's docu and shows that in Log.html
I've changed it locally and it works just fine. like this:

`"""Returns a reference to a Browser Docu [https://marketsquare.github.io/robotframework-browser/Browser.html#Finding%20elements|Finding Elements].`

![image](https://github.com/MarketSquare/robotframework-browser/assets/56655042/91953f1a-75c1-425b-9b35-f520a312c2d6)

Keywords to edit:

- Get Element
- Get Elements
- Get Element by Role

**Comment by Snooz82** [comment]
But it literally return a reference to a Playwright Locator object.
Therefore the link is correct
