### ISSUE TITLE
Wait For Response does raise error on OPTIONS response with Preflighted requests in CORS

### ISSUE THREAD

**Issue by madworx** [MarketSquare/robotframework-browser#2970]
**Describe the bug**
Regarding discussion in [Slack](https://robotframework.slack.com/archives/C015KB1QSDN/p1689964433949609).

Wait For Response does raise error on OPTIONS response with [Preflighted requests in CORS](https://developer.mozilla.org/en-US/docs/Web/HTTP/Methods/OPTIONS#preflighted_requests_in_cors)

**To Reproduce**
1. Promise To   Wait For Response ...

when frontend/Javascript code does OPTIONS request before POST.

**Expected behavior**
If browser does OPTIONS request before POST request, I'd expect Browser Library not to fail on account of 

"No data found for resource with given identifier"

**Comment by Snooz82** [comment]
@allcontributors please add @madworx for bugs

**Comment by madworx** [comment]
Fixed in d5405e6a783ea1054cec52dc01f1eef1b30a3bb6.

Thanks @Snooz82!
