### ISSUE TITLE
Wait For Response throws an error "the JSON object must be str, bytes or bytearray, not NoneType"

### ISSUE THREAD

**Issue by suhasbhattu** [MarketSquare/robotframework-browser#2983]
**Describe the bug**
I am using `Wait For Response` keyword to wait for the response from a GET call. But it's throwing an error `the JSON object must be str, bytes or bytearray, not NoneType`.

**To Reproduce**
I am using the `Wait For Response` as follows:

`Wait For Response     response => response.url().endsWith(‘students’) && response.request().method() === ‘GET’ timeout=30s`

The keywords waits till the API returns response but it throws an error: `the JSON object must be str, bytes or bytearray, not NoneType`.

I have tried to check the inside code for this and I have found that the error is returned when `postData` which is returned in the response of the request is None. My GET api does not have any payload so `postData` will always be None.

**Comment by Snooz82** [comment]
Please check this again with Browser version 17.1.1
There was a fix regarding `Wait For Response`

**Comment by suhasbhattu** [comment]
It is working after upgrading library to 17.1.1. Thanks!!
Is there some issue with the older version, we are using 11.4.0

**Comment by Snooz82** [comment]
Yes definitely. There were many bugfixes and also many new features since v11.4.0.

please see the Releases and Release Nodes for more information.

be aware that we strongly recommend to always use the newest versions and fix the backwards incompatibilities right away, when they appear.

we use semantic versioning.

https://semver.org/

**Comment by aaltat** [comment]
Also we don’t provide fixes for older versions, we only move versions forward. It’s always recommended to upgrade to the latest version, most of the time changes are small (if any) and doing changes in small increments is easier.
