### ISSUE TITLE
Add support for Component Testing

### ISSUE THREAD

**Issue by orenault** [MarketSquare/robotframework-browser#2984]
Playwright is now able to perform component testing.
This seems still to be "experimental":
https://playwright.dev/docs/test-components

But can you add keywords to support this great feature ?
(which is available with tools like cypress)
Regards
Olivier

**Comment by Snooz82** [comment]
Hi Oliver,

i doubt that this is possible.
For what i have seen, this is a feature of Playwright Test. Not the playwright browser api.

therefore it is not what we do.
