### ISSUE TITLE
Set FirefoxUserPrefs, Chrome prefs in `New Browser` Keyword

### ISSUE THREAD

**Issue by sandhyagd87** [MarketSquare/robotframework-browser#2987]
Requirement to launch firefox and chrome browser with user preferences.

Example: Launch firefox with DOH settings. Set "network.trr.mode":3 in firefox before launching the browser

There are keywords "New Browser", "New Context", "New Page", "New Persistent Context"
None of them accepts firefox_user_prefs as argument.

Tried sending  args["network.trr.mode=3", "network.trr.uri=https://xxx/xxx/dns-query" in "New Browser" and in "New Persistent Context". On the launch of browser these details are not set.

It works with pytest-playwright by calling
def test_run(playwright: Playwright) -> None:
     firefox = playwright.firefox
    browser = firefox.launch(firefox_user_prefs={"network.trr.mode": 3}, headless=False, slow_mo=100)

However, I would like to use Browser keywords to set browser (firefox, chrome) options and not use pytest-playwright as rest of my tests are all using Browser library

**Comment by Snooz82** [comment]
This option is not yet available with `New Browser`

i changed the title of you issue.

**Comment by Snooz82** [comment]
There are also other args missing:

`New Browser`:
- chromiumSandbox
- firefoxUserPrefs
- ignoreDefaultArgs (got new types)

`New Context`:
- baseURL
- proxy
- serviceWorkers

`New Persistent Context` similar to the above. `firefoxUserPrefs` are not available with the persistent context. Maybe they have to be set in the profile it self?!
