### ISSUE TITLE
Question - argument - enable_presenter_mode

### ISSUE THREAD

**Issue by martamedovova-ext91522** [MarketSquare/robotframework-browser#3006]
Hello, 
why does argument "enable_presenter_mode" shows banner with keywords? It is not even mentioned in documentation and what "show_keyword_call_banner" is for, the both have almost the same fuction?

Is there a bug or was it a purpose with these two arguments?

**Comment by aaltat** [comment]
@allcontributors please add @martamedovova-ext91522 for bugs

**Comment by Snooz82** [comment]
This behaviour is documented under the `Importing` Section under `show_keyword_call_banner` and also under the keyword `Show Keyword Call Banner` .

But i also added now a sentence at the docs unter `enable_presenter_mode`.
