### ISSUE TITLE
Allow disabling automatic screenshot after a failing keyword

### ISSUE THREAD

**Issue by mikaukora** [MarketSquare/robotframework-browser#302]
**Is your feature request related to a problem? Please describe.**
When trying to minimise the total size of artefacts generated by task or test run 
automatically created screenshots may be unwanted.

**Describe the solution you'd like**
Solution similar to SeleniumLibrary's Register Keyword To Run On Failure would enable
disabling or customising the behaviour in case of error.

**Describe alternatives you've considered**
Browser library doesn't seem to have way to disable the screenshots currently.

**Additional context**
Additional challenge is related to handling of failures under keywords that ignore error exception,
Run Keyword And Ignore Error etc. It would be great to be able to prevent screenshots after failures under
those keywords since also the error exception is ignored. We have implemented listener for that purpose already in [RPA.Browser](https://rpaframework.org/libraries/robotloglistener/index.html#mute-run-on-failure).

**Comment by aaltat** [comment]
Done in #327
