### ISSUE TITLE
Argument show_keyword_call_banner shows banner only at Chromium browser

### ISSUE THREAD

**Issue by martamedovova-ext91522** [MarketSquare/robotframework-browser#3030]
Hello, 
why is argument show_keyword_call_banner sets on True to show banner only at Chromium browser and not at Edge or Chrome browser? 
Is it a bug or a purpose???
Thanks

**Comment by aaltat** [comment]
@allcontributors please add @martamedovova-ext91522 for bugs

**Comment by aaltat** [comment]
@allcontributors please add @martamedovova-ext91522 for bugs

**Comment by Snooz82** [comment]
I can not reproduce this issue.
It works fine under Chrome and Chromium and Firefox.

@aaltat can you test it with Edge?

**Comment by martamedovova-ext91522** [comment]
Sure.
I will present you a our strategie to start test and settings for engine.

 *** Settings *** 
 - Export Browser library below - : 
 
Library  Browser  auto_closing_level=MANUAL  enable_playwright_debug=${LOG}  timeout=${NORMALNI_CAS}
...  enable_presenter_mode=${PREZENTACNI_MOD}  show_keyword_call_banner=${BANNER}

# Variables for tests
${PROHLIZEC}                    Edge     #(Chromium / Chrome / Edge)
${LOG}                               False
${PREZENTACNI_MOD}     False
${BANNER}                        True 

KW Start browser
    ${edge_cesta}  Set Variable If
    ...  '${SYSTEM}' == 'Linux'   ${/}usr${/}bin${/}microsoft-edge
    ...  '${SYSTEM}' == 'Darwin'  ${/}Applications${/}Microsoft\ Edge.app${/}Contents${/}MacOS${/}Microsoft\ Edge
    ...                           C:${/}Program Files (x86)${/}Microsoft${/}Edge${/}Application${/}msedge.exe

   ${prohlizec_cesta}  Set Variable If
    ...  '${prohl}' == 'edge'      ${edge_cesta}
 
${prohl}  Set Variable If  '${prohl}' in ['chrome', 'edge']  chromium  ${prohl}

New Browser  browser=${prohl}  executablePath=${prohlizec_cesta}  headless=${HEADLESS}

I cut off some lines, but hope it will be helpfull for you. 

The thing is we custome our browser.

Our Edge version is: Verze 116.0.1938.69

**Comment by Snooz82** [comment]
I still can not reproduce.

Keyword Call Banner works on my test machines.
On all browsers (chromium, chrome, edge, firefox and webkit) it works correctly.
I can not test with 116 of edge, but i tested it with 118.0.2088.46 .

i tested with this code on windows 11
```
*** Settings ***
Library     Browser    auto_closing_level=MANUAL    enable_playwright_debug=${LOG}    timeout=${TIME}
...             enable_presenter_mode=${PRESENT_MODE}    show_keyword_call_banner=${BANNER}
Library     RobotDebug

*** Variables ***
${BROWSER}          Edge    # (Chromium / Chrome / Edge)
${LOG}              False
${PRESENT_MODE}     False
${BANNER}           True
${TIME}             10s
${HEADLESS}         False


*** Test Cases ***
KW Start browser
    ${browser_path}    Set Variable    C:${/}Program Files (x86)${/}Microsoft${/}Edge${/}Application${/}msedge.exe
    New Browser    browser=chromium    headless=${HEADLESS}    executablePath=${browser_path}    
    New Page    https://robotframework-browser.org
    Get Title
    Debug
```

i therefore close that task.
if there is anyone who can deliver a reproducible code with a good description, please open a new issue.
