### ISSUE TITLE
Close page does not have the runBeforeUnload option.

### ISSUE THREAD

**Issue by Zoupers** [MarketSquare/robotframework-browser#3054]
https://github.com/MarketSquare/robotframework-browser/blob/e2573de908b1b6a3e0befe7f93128359d1a75bd0/node/playwright-wrapper/playwright-state.ts#L517

The code above and this document [playwright - page close](https://playwright.dev/docs/api/class-page#page-close). Sometimes we need the unload function.

So I think it should be a bug.

**Comment by aaltat** [comment]
Adding  the missing argument to Close Page keyword is useful enhancement to have. Also we should add new keyword which allows to define the default value when automatic page closing is done by the library.

@allcontributors please add @Zoupers for ideas
