### ISSUE TITLE
New Browser remote URL and desired capabilities for Selenoid

### ISSUE THREAD

**Issue by edsherwin** [MarketSquare/robotframework-browser#3061]
Library should allow remote URL and desired capabilities keyword as integration to execute tests inside Selenoid Browsers

example using Selenium Library

*** Settings ***
Library   SeleniumLibrary

*** Variables ***
#SELENOID SETUP
${SELENOID_URL} =                   http://localhost:4444/wd/hub
${BROWSER_NAME} =                   chrome
${BROWSER_VERSION} =                108.0
${PLATFORM} =                       LINUX
${DESIRED_CAPABILITES} =            browserName=chrome        enableVideo=${True}

*** Test Cases ***
Execute Tests in Selenoid Environment
    [Documentation]   Run various tests in Selenoid environment
    ${selenoid_caps}=   Create Dictionary   browserName=${BROWSER_NAME}   version=${BROWSER_VERSION}   platform=${PLATFORM}     enableVideo=${True}     enableVNC=${True}
    Open Browser    remote_url=${SELENOID_URL}   desired_capabilities=${selenoid_caps}

**Comment by aaltat** [comment]
Browser library is based on Playwright. If you can find API from Playwright which allows to fulfill your needs, then it can be considered to be implemented.

**Comment by aaltat** [comment]
I looked at Playwright API quickly and couldn’t find anything that would satisfy your needs. Therefore closing the issue.
