### ISSUE TITLE
Wait For Response throw exception when response is empty with DELETE method

### ISSUE THREAD

**Issue by infoTrainingym** [MarketSquare/robotframework-browser#3096]
**Describe the bug**
`Wait For Response` throw exception when response is empty with DELETE method. "the JSON object must be str, bytes or bytearray, not NoneType"

**To Reproduce**
1. Endpoint with DELETE Verb and empty response.
2. Use `Wait For Response    response => ('${method}' == 'all' || response.request().method() == '${method}') && response.request().method() != 'OPTIONS' && '${status_code}'.indexOf(response.status()) >= 0`
3. [ FAIL ] the JSON object must be str, bytes or bytearray, not NoneType 

**Expected behavior**
Allow empty response to test when response is empty. 

**Additional context**
With GET Verb the behavior is correct.
robotframework-browser 17.4.0

**Comment by aaltat** [comment]
@allcontributors please add @infoTrainingym for bugs

**Comment by Snooz82** [comment]
I can not reproduce this error.

Please reopen it, if this is reproducable. 
We need a specific Server Response and please run in in TRACE so that we get the specific line in code where the exception happens.
