### ISSUE TITLE
Support first/last/nth locators

### ISSUE THREAD

**Issue by gforcada** [MarketSquare/robotframework-browser#3133]
**Is your feature request related to a problem? Please describe.**
In a test I'm trying to select the first element of a list, but as there are multiple results, the test fails with:

```
AssertionError: Error: locator.click:
Error: strict mode violation:
locator('xpath=//*[@id="select2-drop"]//*[@class="select2-match"]') resolved to 2 elements:
```

**Describe the solution you'd like**
I see that on playwright documentation there are actions/modifiers to locators like first/last/nth:

https://playwright.dev/docs/api/class-locator#locator-first
https://playwright.dev/docs/api/class-locator#locator-last
https://playwright.dev/docs/api/class-locator#locator-nth

**Describe alternatives you've considered**
I tried css and xpath selectors, but somehow they do not work, specially with xpath doing:

```
//*[@id="an-id"]//*[@class="my-class"][1]
```

Seems to not work either 😕

**Comment by aaltat** [comment]
The first/nth/last already can be achieved by using css locator, see more details in https://playwright.dev/docs/other-locators

Your xpath is close, but not totally correct: 
`(//*[@id="an-id"]//*[@class="my-class"])[1]` should work better.

**Comment by aaltat** [comment]
Closing because need can be already done.
