### ISSUE TITLE
Installation Failure of robotframework-browser in Python 3.12 Due to grpcio Dependencies

### ISSUE THREAD

**Issue by Camatius** [MarketSquare/robotframework-browser#3138]
## Describe the bug
In Python version 3.12, the modules `grpcio` and `grpcio-tools` version 1.58 do not work. The issue is resolved in version 1.59. However, Browser-library has version 1.58 set in its dependencies. Consequently, the installation via `pip install robotframework-browser` fails in Python 3.12.

## To Reproduce
1. Use Python version 3.12.
2. Run the command `pip install robotframework-browser`.
3. Observe that the installation fails due to an issue with `grpcio` and `grpcio-tools` version 1.58.

## Expected behavior
The installation of `robotframework-browser` should succeed without errors, even with Python version 3.12. The modules `grpcio` and `grpcio-tools` should work correctly with the installed version.

## Desktop (please complete the following information):
 - OS: [e.g. Windows, Linux, macOS]
 - Python Version: 3.12

## Additional context
A solution could be to update the dependencies of Browser-library to use `grpcio` and `grpcio-tools` version 1.59 or later, which does not exhibit the problem in Python 3.12. This update will ensure compatibility and successful installation on Python 3.12.

**Comment by aaltat** [comment]
This is already fixed in the main code line and will be available in the next release.

@allcontributors please add @Camatius for bugs.

**Comment by aaltat** [comment]
Release 17.5.2 is out.
