### ISSUE TITLE
Misleading log message

### ISSUE THREAD

**Issue by gforcada** [MarketSquare/robotframework-browser#3156]
**Describe the bug**
When one sets `PLAYWRIGHT_BROWSERS_PATH=/home/jenkins/robot-browsers/` the `rfbrowser init` command still says:

```
Installing browser binaries to /home/jenkins/.buildout/eggs/cp312/robotframework_browser-17.5.2-py3.12.egg/Browser/wrapper
```

Though, it actually installs correctly on the expected location.

**To Reproduce**
1. create a python virtual environment and install `robotframework-browser` on it
2. set environment variable `PLAYWRIGHT_BROWSERS_PATH` to a path
3. run `rfbrowser init`
4. see that the browsers are actually downloaded to the path set on the environment variable, but the `rfbrowser init` makes you think otherwise

**Expected behavior**
Use the path set on the environment variable on the log output.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: linux
 - Version: rf-browser 17.5.2

**Additional context**

**Comment by aaltat** [comment]
So the log message is wrong, that should be possible to fix.

@allcontributors please add @gforcada for bugs

**Comment by gforcada** [comment]
Thanks! 🤗
