### ISSUE TITLE
Issue with self-closing popups on Firefox browser.

### ISSUE THREAD

**Issue by terckert** [MarketSquare/robotframework-browser#3173]
**Describe the bug**
I believe this bug may be related to the following playwright tickets but am bringing it here to raise awareness or see if the issue rests with BrowserLibrary:
Issue I opened with Playwright: https://github.com/microsoft/playwright/issues/27543
Issue my ticket was linked to: https://github.com/microsoft/playwright/issues/26900

I have been running into issues writing tests that have to interact with elements that use the window.close() method in firefox. Initially I thought it was an issue with iframes, however, writing the test directly in playwright I noticed that it was failing on the click portion. I have reproduced a simplified version of the live site I'm testing. It can be found with the below links:
Website: https://terckert.github.io/pw-firefox-test/
Code: https://github.com/terckert/pw-firefox-test

It is only an issue with firefox browsers. The test was initially written in BrowserLibrary. After it kept failing, I rewrote it in straight playwright. Playwright fails on the click function, Browser Library fails to find the next object after clicking the button. As stated, I believe they're related, but since they fail at different points and produce different traces I figured it was best to log it here as well.
 
**To Reproduce**
Run the following test:
```js
*** Settings ***
​
Library    Browser
​
*** Test Cases ***
Attempt To Access Iframes In Chrome
    Open Browser
    ...  https://terckert.github.io/pw-firefox-test/
    ...  chromium
    
    FOR  ${counter}  IN RANGE  0  4 
        Log  ${counter}
        ${og_prefix} =  Set Selector Prefix  \#iframe-id >>>  # Iframe accessor
        Click  \#iframe-button
        Set Selector Prefix  ${og_prefix}  # Remove iframe accessor
        ${og_browser} =  Switch Page  NEW
        Click  \#popup-button
        Switch Page  ${og_browser}
    END
​
Attempt To Access Iframes In Firefox
    Open Browser
    ...  https://terckert.github.io/pw-firefox-test/
    ...  firefox
    
    FOR  ${counter}  IN RANGE  0  4 
        Log  ${counter}
        ${og_prefix} =  Set Selector Prefix  \#iframe-id >>>  # Iframe accessor
        Click  \#iframe-button
        Set Selector Prefix  ${og_prefix}  # Remove iframe accessor
        ${og_browser} =  Switch Page  NEW
        Click  \#popup-button
        Switch Page  ${og_browser}
    END
```
**Expected behavior**
I expect the chromium test to pass. The firefox test will fail trying to find the object #iframe-id >>> #iframe-button on the second loop.

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Firefox

**Comment by aaltat** [comment]
@allcontributors please add @terckert fir bugs

**Comment by Snooz82** [comment]
@aaltat Can you please check that?
I can not test Firefox on my Devices.

**Comment by aaltat** [comment]
I can reproduce the issue. No idea what causes it, at least yet.

**Comment by aaltat** [comment]
I can not anymore reproduce the issue. @terckert can you? If not then we can assume that later PW release has fixed the issue.

**Comment by terckert** [comment]
I just upgraded browser and my node files and it looks like everything is working now. I cannot reproduce.
