### ISSUE TITLE
Drag item and Mouse Button up/down with coordinates 

### ISSUE THREAD

**Issue by Finalrykku** [MarketSquare/robotframework-browser#318]
**Is your feature request related to a problem? Please describe.**
Mouse Button click works with coordinates. Mouse Button down/up does not. I have to use Mouse move first. Isn't it a litte complicated/confusing? Wouldn't it be great if Mouse Button up/down would work like Mouse Move -> Mouse button up/down as well as Mouse Button click?

In Addition: A keyword for drag and drop an element. A shortcut for the following steps:
- Get coordinates for place a (source)
- Get coordinates for place b (destination)
- mouse down at source
- mouse up at destination

**Comment by Snooz82** [comment]
Fixed already.
