### ISSUE TITLE
Need a way to define the playwright-log.txt outputdir when using Browser in python

### ISSUE THREAD

**Issue by Massukio** [MarketSquare/robotframework-browser#3203]
**Is your feature request related to a problem? Please describe.**
When executing robotframework with Browser, I can define the OUTPUTDIR by --outputdir in command line.
However, when executing Brower purely in python, I find no way to set the OUTPUTDIR to where ever I want.
```
browser = Browser(enable_playwright_debug=True)
```

**Describe the solution you'd like**
An API in python side to define the customized output location for browser debug log.

**Comment by aaltat** [comment]
@allcontributors please add @Massukio for ideas

**Comment by aaltat** [comment]
After the fix, this is possibe:

**Comment by aaltat** [comment]
After the fix, this is possible:
```Python
    browser = Browser.Browser()
    assert browser.outputdir == "."
    browser.outputdir = "/foo/bar"
    assert browser.outputdir == "/foo/bar"
```
