### ISSUE TITLE
[Setting Scope is broken] "Set Browser Timeout" does not work together with "Wait for Condition"

### ISSUE THREAD

**Issue by HenrikSchuette** [MarketSquare/robotframework-browser#3208]
**Describe the bug**
When using the "Set Browser Timeout" together with the "Wait For Condition" keyword in multiple tests of the same suite, the Set Browser Timeout" Keyword fails with an Index Error. This seems to be related to the self._stack property in "settings_stack.py". Calling the keyword "Wait for conditions" adds a new entry to the stack:
![image](https://github.com/MarketSquare/robotframework-browser/assets/98702737/5d055ba0-3544-48dd-8a11-5f2c11149692)
This entry has the scope test although it should be of scope "Suite" which results in poping the last item of the stack:
![image](https://github.com/MarketSquare/robotframework-browser/assets/98702737/46eccb97-acaa-468c-9043-a175743b53cb)

**To Reproduce**
```*** Settings ***
Library    Browser

*** Test Cases ***
Test1
    Open Expample Page
    Change Browser Timeout
    Open Expample Page
    Change Browser Timeout

Test2
    Open Expample Page
    Change Browser Timeout
    Open Expample Page
    Change Browser Timeout

*** Keywords ***
Change Browser Timeout
    ${old_timeout}    Set Browser Timeout    1s
    Log    Setting browser timeout to 1s
    [Teardown]    Set Browser Timeout    ${old_timeout}

Open Expample Page
    New Browser    chromium    ${False}
    New Context
    New Page    https://robotframework.org/
    Wait For Condition    title     matches     .*

```

**Expected behavior**
The tests run without an Index error.

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: chromium
 - Version: 17.5.2

**Comment by aaltat** [comment]
Looks like a bug, @Snooz82 you made this feature what you think?

@allcontributors please add @HenrikSchuette for bugs

**Comment by Snooz82** [comment]
@aaltat correct.
I am already started working on it.
It’s a problem in Scope, that I have to analyze. 
it’s a bit tricky.
