### ISSUE TITLE
`Wait For Elements State` implies more than 1 element

### ISSUE THREAD

**Issue by Noordsestern** [MarketSquare/robotframework-browser#326]
**Describe the bug**
Just a small thing: I tried to use the keyword `Wait For Element State`, which failed. The keyword name is `Wait For Elements State` (plural). 

Maybe rename keyword to `Wait for Element State` hence `Elements` implies plural and not ~~`Element's`~~.

**Comment by Snooz82** [comment]
@mkorpela @aaltat @xylix Lets decide if we want to rename and deprecate or close that issue.

In general i think Markus is right.
Question is it worth the "friction" ?

**Comment by aaltat** [comment]
Keyword name is funny, I vote deprecation (with long period) and removal of the keyword.

**Comment by Snooz82** [comment]
I descoped it from 12.4.0 because this is not an urgent issue.
Maybe at the same time, we could refactor it that it can wait for multiple states to come true.

Like 
```robotframework
Wait For Element States    id=password    visible   disabled   readonly   timeout=10sec
```

```python
def wait_for_elements_state(
        self,
        selector: str,
        *states: ElementState = ElementState.visible,
        timeout: Optional[timedelta] = None,
        message: Optional[str] = None,
    ):
```

**Comment by Snooz82** [comment]
I will close this issue.
There is now `Wait For Condition` and `Get Element States`.
Some people still prefer this keyword and i think we should not remove or rename it.

Yes the name is a bit bad, but it is massively used.
It would really be a huge impact to nearly every user to remove or rename it.
