### ISSUE TITLE
`Take Screenshot` fails while page is navigating

### ISSUE THREAD

**Issue by Noordsestern** [MarketSquare/robotframework-browser#328]
**Describe the bug**
For debugging purpose I added a few `Take Screenshot` keywords in my test case. *Sometimes* after an action (like `click`) the `Take Screenshot` fails with error below:

```
page.screenshot: Cannot take a screenshot while page is navigating
Note: use DEBUG=pw:api environment variable and rerun to capture Playwright logs.
```

**Expected behavior**
`Take screenshot` should wait *some time* until navigation is completed

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: firefox (headless=*False*)

**Comment by aaltat** [comment]
There has been several releases release from Browser library and from PlayWright side. Do you still see have the problem?

**Comment by Noordsestern** [comment]
I think we can close this. I had tried to migrate a test case and don't remember anymore which one it was. Not even which project.
