### ISSUE TITLE
Video from Browserstack

### ISSUE THREAD

**Issue by gbhandarkavathe** [MarketSquare/robotframework-browser#3280]
I am executing my test script at Browser Stack 
Test script is storing the tracing locally 
    Browser.New Context    tracing=browser/traces/traces.zip    recordVideo={'dir':'videos', 'size':{'width':1080, 'height':720}}    viewport={'width': 1512, 'height': 865}
On executing the test cases at  BrowserStack it is throwing an error 
    Error: Path is not available when connecting remotely. Use saveAs() to save a local copy.
Is there any provision for this.

**Comment by aaltat** [comment]
I tough this issue is fixed, which version you are using and have you tried with the latest release?

**Comment by aaltat** [comment]
Ah now I recall, we made fix in file download, but not for traces: https://github.com/MarketSquare/robotframework-browser/issues/2615 So this is valid issue, most likely same logic can be applied also for traces.

**Comment by aaltat** [comment]
@allcontributors please add @gbhandarkavathe for bugs

**Comment by aaltat** [comment]
Actually when I was able to reproduce the problem, the error is not caused by tracing, it is caused by creating the video.

**Comment by aaltat** [comment]
Could not easily find way to save video on remote browser. Just decided to suppress the error and not support video on remote browser.
