### ISSUE TITLE
Matches should work also with multiline strings

### ISSUE THREAD

**Issue by simonmeggle** [MarketSquare/robotframework-browser#3292]
When `Get Text`  returns me

```
HOME
Workbox
```

then 

✅ `Get Text  element  matches  HOME` 
✅ `Get Text  element  matches  Workbox`
❌ `Get Text  element  matches  HOME.*Workbox` 

It would be great if there would be _some_ support out of the box for result strings which are multiline.  

(See also https://robotframework.slack.com/archives/C015KB1QSDN/p1701255745908669)

**Comment by Snooz82** [comment]
As written in Slack adding `\n` instead of the dot would already now work.

I looked for the flags and we will add `re.DOTALL` flag to `matches`

**Comment by aaltat** [comment]
Belongs to AssertionEngine side: https://github.com/MarketSquare/AssertionEngine/issues/176 closing this one.
