### ISSUE TITLE
Migration aid for SL locators

### ISSUE THREAD

**Issue by xylix** [MarketSquare/robotframework-browser#33]
## TODO:

- [ ] Migration aid for migrating impcompatible locators from SL syntax
- [ ] Documentation where our consistent locator default differ from SeleniumLibrary's heavily keyword specific defaults

## Details:

Some poking and implementation of compatibility is probably necessary. 

We don't want users of seleniumlibrary to need to rewrite their selectors for no good benefit.

However playwright does also expose some advanced selector API's like using `selector >> selector` to combine different selector engine selectors to select deeper elements. We will probably want to support this in some form to enable advanced use cases, and it is probably quite easy to expose

23.6. notes:
- We might want to break compatibility with seleniumlibrary's default selector behaviour (kw specific defaults)
- Sanest default would be the same as playwright's (css)
- Playwright's selector strategy syntax doesn't play well with robot's support for python named arguments (`foo=bar`)

**Comment by aaltat** [comment]
This should be separate project. Also there are users that have do it and did not need migration aid.
