### ISSUE TITLE
"Wait Until Network Is Idle" failure message shows inapropriate "tip" 

### ISSUE THREAD

**Issue by simonmeggle** [MarketSquare/robotframework-browser#3333]
![image](https://github.com/MarketSquare/robotframework-browser/assets/1897410/8a5a6822-d030-42a3-b058-9a735607c301)

I personally do not find this kind of generic "tip" very helpful. Any chance to make them context-aware? 

"_...as the targeted element(s) couldn't be found._"

This reads as the reason for the failure, which is not true - this Keyword does not use any selector at all.

**Comment by aaltat** [comment]
Good point and very true. We should fix this.

@allcontributors please add @simonmeggle for bugs

**Comment by aaltat** [comment]
Fixed the implementation so that tip talks about selector if keyword has argument `selector` in their namespace.
