### ISSUE TITLE
Documentation: "Click" does not have "noWaitAfter" option

### ISSUE THREAD

**Issue by simonmeggle** [MarketSquare/robotframework-browser#3334]
https://marketsquare.github.io/robotframework-browser/Browser.html#Click

> - Wait for initiated navigation to either succeed or fail, unless `noWaitAfter` option is set.

=> This is only valid for [Click With Options](https://marketsquare.github.io/robotframework-browser/Browser.html#Click%20With%20Options). 

`Click` does not have it.

**Comment by aaltat** [comment]
Good catch, will fix it.
