### ISSUE TITLE
The log cannot show the root cause of a failed click anymore

### ISSUE THREAD

**Issue by simonmeggle** [MarketSquare/robotframework-browser#3343]
The docs of [Click](https://marketsquare.github.io/robotframework-browser/Browser.html#Click) say that there are a handful of steps performed inside. 

Unfortunately, Playwright changed / condensed its error output which leads to the effect that it is not possible anymore to see why a click failed. 

This failed keyword for example does not tell me that anything has failed: 

![image](https://github.com/MarketSquare/robotframework-browser/assets/1897410/04958fcc-768a-4097-8ba6-fdb54d7ee86e)

![image](https://github.com/MarketSquare/robotframework-browser/assets/1897410/a0b15e43-62f4-44ab-bc19-6b97cdfdfd39)

Would it be possible to provide a little more information about what exactly failed in the case of an error like this? If I could read “Waiting For Navigation” or something, I could get a clue …

Thanks

**Comment by aaltat** [comment]
@allcontributors please add @simonmeggle for ideas.

We in practice just relay PW side exception and that’s it. But we can investigate can we provide more information from PW side.

**Comment by aaltat** [comment]
After Playwright update, I see
<img width="1111" alt="image" src="https://github.com/MarketSquare/robotframework-browser/assets/2665023/89d9ab12-b0ca-43ec-a638-71b38e41334a">
Which is way better, I think we can close the issue.

**Comment by aaltat** [comment]
Closing because PW logs are now better
