### ISSUE TITLE
Connect to Lambdatest and parallel running using pabot

### ISSUE THREAD

**Issue by praveenkannan1987** [MarketSquare/robotframework-browser#3354]
**Is your feature request related to a problem? Please describe.**
Connect to Lambdatest

**Describe the solution you'd like**
I want to connect it to lambdatest
browser:chromium
platform:windows 10
user:username
accesskey:accesskey
video:true
tunnel:true
tunnelname: reg12

I want to connect to lambdatest and run three chromium at time in a lambda machine.

**Comment by aaltat** [comment]
Lambdatest seems to only support Selenium, but Browser library is powered by Playwright. I think we can’t help you on this matter.
