### ISSUE TITLE
Cannot launch browser server with Additional arguements from terminal or cmd.

### ISSUE THREAD

**Issue by gitkatsi** [MarketSquare/robotframework-browser#3363]
**Describe the bug**
Cannot launch browser server with additional arguments from terminal or cmd when  additional argument contains "="

**To Reproduce**
command
```
rfbrowser  --silent launch-browser-server chromium port=9000 wsPath=/testpath args=--remote-debugging-port=9222
```
throws
```
.venv\lib\site-packages\Browser\entry.py", line 488, in convert_options_types
    key, value = option.split("=")
```

**Expected behavior**
launch browser with remote debugging port 9222 enabled. 

**Desktop (please complete the following information):**
 - windows linux
 - chrome
 - 18.0.0

**Additional context**
the problem seems to be in the line 488 of entry,py 

```python 
key, value = option.split("=")
```
if i modify it to 
```python
key, value = option.split("=", maxsplit=1)
```
it accepts the following format from terminal
```
args="['--remote-debugging-port=9222']"
```

Any suggestions are welcome but i believe it is a bug affecting only arguments that need a value assigned. 

The same format from python runs as expected. 
```python 
br = Browser()
br.launch_browser_server(browser=SupportedBrowsers.chromium, port=9000, wsPath='testpath', args=["--remote-debugging-port=9222"])
```

**Comment by aaltat** [comment]
Good catch, do you want to submit pull request to fix it too?

@allcontributors please add @gitkatsi for bugs

**Comment by aaltat** [comment]
Closed by https://github.com/MarketSquare/robotframework-browser/pull/3364
