### ISSUE TITLE
"Webkit" loads a blank page when automated tests are run on Windows

### ISSUE THREAD

**Issue by srajendran123** [MarketSquare/robotframework-browser#3372]
**Describe the bug**
Using an iPad browser agent and a "Webkit" browser, the app loads a blank page when tests are run on Windows. The same automated tests load the app fine when executed on Mac.

**To Reproduce**
1. On a Windows machine, through automation load 'https://pwa-br-us-a.qa.tillster.com/' url using "New Persistent Context" keyword with the following parameters:
              browser - "webkit"
              user agent - Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/16.0 Safari/605.1.15
              viewport - "{'width': 810, 'height': 1010}"

Expected behavior:
Loads the app

Actual behavior:
Loads a blank page

Desktop:
 - OS: Windows
 - Browser: Webkit through automation
 - Version: Playwright version 1.0 [1]

**Comment by srajendran123** [comment]
![image (3)](https://github.com/MarketSquare/robotframework-browser/assets/85199839/e0d9124d-a596-4721-962e-0aca3a531221)

**Comment by srajendran123** [comment]
In the Steps to Reproduce above, if I replace "webkit" with Chromium browser along with the same user agent, app loads fine.

**Comment by aaltat** [comment]
I do not have any good advises for you. I would enabled developer tools and check do you see any obvious errors. 

But this is more question to your development team, than for us, why your application does not work with WekKit. Also you could consult Robot Framework community, either Slack or Forum: https://robotframework.org/#community

But because we can not help you, I am going to close this issue.

**Comment by srajendran123** [comment]
Hello @aaltat,

This application https://pwa-br-us-a.qa.tillster.com has been designed specifically for iPad safari users. 

One thing we observed was the user agent that has been passed through the test data file is not honored when using webkit. Rather, the system config where the test runs on is passed as the user agent. 

I am attaching the videos for more info. 

[chromium.webm.zip](https://github.com/MarketSquare/robotframework-browser/files/13970669/chromium.webm.zip)
[webkit.webm.zip](https://github.com/MarketSquare/robotframework-browser/files/13970670/webkit.webm.zip)

**Comment by srajendran123** [comment]
Hello @aaltat - I am not sure how this works. Since this issue is closed, should I open a new ticket or it can be tracked here? Please suggest. Thanks.
