### ISSUE TITLE
"useragent" passed is not honored when using "webkit" browser.

### ISSUE THREAD

**Issue by srajendran123** [MarketSquare/robotframework-browser#3383]
**Describe the bug**
user-agent passed file is not honored when using WebKit. Rather, the system config where the test runs is passed as the user agent.

**To Reproduce**
1. Through automation load any url using "New Persistent Context" or with a combination of New Browser/New Context/New Page) keyword with the following parameters:
browser - "webkit"
user agent - Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/16.0 Safari/605.1.15
viewport - "{'width': 810, 'height': 1010}"

**Actual behavior**
Observe that user-agent passed is not honored when using WebKit. Rather, the system config where the test runs is passed as the user agent.

**Screenshots**
[chromium.webm.zip](https://github.com/MarketSquare/robotframework-browser/files/13993940/chromium.webm.zip)
[webkit.webm.zip](https://github.com/MarketSquare/robotframework-browser/files/13993941/webkit.webm.zip)

**Desktop (please complete the following information):**
OS: Windows
Browser: Webkit through automation
Version: Playwright version 1.0 [1]

**Additional context**
When loading a webpage using chromium or firefox without user agent, none is passed to user agent as expected. However, same issue as described exists when using webkit, system config where the test runs is passed as the user agent.

**Comment by srajendran123** [comment]
@aaltat - Just wondering, if there any update on this ticket? Thanks.

**Comment by aaltat** [comment]
Not yet, https://robocon.io/ is near and it’s eating all available time

**Comment by aaltat** [comment]
I do not quite follow what you did expect to happen, but you can change user agent as you want in [New Context](https://marketsquare.github.io/robotframework-browser/Browser.html#New%20Context) keyword `userAgent` argument. I did check code and we should not set user agent inside of our code. So either it is done by Playwright or by the browser binaries itself. But in any case user agent is easy to change as you want.

**Comment by srajendran123** [comment]
@aaltat When "webkit" is used, user agent provided in the script is not used when loading the application. Please refer to the attached webkit zip file above. 

<img width="1689" alt="image" src="https://github.com/MarketSquare/robotframework-browser/assets/85199839/2be3b347-281b-4ab5-b3a6-71d71dd9d7dc">

In the screenshot, mac useragent is provided in the script "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/16.0 Safari/605.1.15" . However, application is loaded with windows user agent, as the test is run on windows machine.  

This is not an issue when using "chromium" browser. App is loaded with whatever useragent passed in the automation script. Please refer to the attached windows zip file above. 

Please let me know, if additional info is needed.

**Comment by srajendran123** [comment]
Here is the code, we are using to invoke the app

New Persistent Context         url=${url}           browser=${execution_browser}        headless=${headless}       userAgent=${userAgent}                viewport=${viewport}

url - "https://pwa-br-us-a.qa.tillster.com/"
browser - "webkit"
user agent - Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/16.0 Safari/605.1.15
viewport - "{'width': 810, 'height': 1010}"

**Comment by aaltat** [comment]
Browser library doesn’t not alter the parameter, we pass it as is in the Playwright side. This is a bug in the upstream side, meaning Playwright or Apple. Also we can’t fix this in the Browser library side. 

You need to raise the issue with Playwright and in the worst case to Apple. But because we can’t fix this, I am going to close this issue.

**Comment by srajendran123** [comment]
Hi Rene,

Can we please get an update on this ticket?

Thanks,

Sharmila

**Comment by aaltat** [comment]
No updates, no-one has not looked at the problem. If have a need, easiest way is to debug the issue by you and provide the fix.

**Comment by srajendran123** [comment]
Hello @aaltat @Snooz82 - We don't have the expertise to contribute to the fix for this issue. Would be great, if this could be looked into by the RF team. Thanks.

**Comment by aaltat** [comment]
We understand, but we can’t give you a timeline or estimate when this could be fixed. Most likely answer is later than sooner.

**Comment by Snooz82** [comment]
That works with current version.

```robotframework
New Persistent Context    browser=webkit    userAgent=Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/16.0 Safari/605.1.1
  5     viewport={'width': 810, 'height': 1010}    headless=False    url=https://www.whatsmyua.info/
  ```

**Comment by srajendran123** [comment]
thanks for checking, Renee. 

It looks like the network tab on the webkit displays the useragent of the system where the scripts are running. However, [loading ](https://www.whatsmyua.info/) displays the user agent passed in the script.
