### ISSUE TITLE
Documentation: Get Cookies "expiry" value should be "expires" instead

### ISSUE THREAD

**Issue by anacomparada** [MarketSquare/robotframework-browser#3532]
https://marketsquare.github.io/robotframework-browser/Browser.html#Get%20Cookie

Possible typo in the value "expiry" where it should be "expires" instead. See https://playwright.dev/docs/api/class-browsercontext#browsercontextaddcookiescookies

> expiry	Lifetime of a cookie. Returned as datatime object or None if not valid time received.

The typo also appears in the example code

> `Should Be Equal   ${cookie.expiry.year}     ${2020}`

**Comment by anacomparada** [comment]
@aaltat I try to do a PR but it seems I don't have permission to do a Push yet.

**Comment by aaltat** [comment]
GitHub has good instructions how to create PR from a fork https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request?platform=windows

**Comment by anacomparada** [comment]
Thank you @aaltat, already done.
