### ISSUE TITLE
Add more browser types when run Browser.entry script for browser installation 

### ISSUE THREAD

**Issue by siongwai** [MarketSquare/robotframework-browser#3547]
**Is your feature request related to a problem? Please describe.**
Playwright has support more [browsers ](https://playwright.dev/docs/browsers#google-chrome--microsoft-edge)(chrome and edge) installation compare to robot browser init script.

**Describe the solution you'd like**
Add all supported browsers from default playwright node installation to Browser.entry script

**Comment by aaltat** [comment]
Browser library relies Playwright to perform the installation. It seems that Playwright has extended the support at least to Edge and perhaps to some others too. But in practice the what ever Playwright supports in installing we can support also.

**Comment by aaltat** [comment]
Playwright 1.46 seems to support now: chromium, chrome, chrome-beta, msedge, msedge-beta, msedge-dev, firefox, webkit.
