### ISSUE TITLE
Wait For Response's response display Error 'the JSON object must be str, bytes or bytearray, not NoneType'

### ISSUE THREAD

**Issue by nfaustin** [MarketSquare/robotframework-browser#3549]
**Describe the bug**
The response of keyword Wait for Response display Error 'the JSON object must be str, bytes or bytearray, not NoneType'

**To Reproduce**
Open a site and wait for the page information loaded using the Wait For Response keyword to check if the API is returning data.

**Expected behavior**
Response did not display error and able to parse the data

Sample Error

![image](https://github.com/MarketSquare/robotframework-browser/assets/3782948/70b340bf-b350-4392-9b3b-3d376cea351a)
![image](https://github.com/MarketSquare/robotframework-browser/assets/3782948/a35aa3eb-32da-4dba-aeba-6507ed09f650)

This is the sample API response : 
`{
    'status': 200,
    'body': '{"full_name":"sample full name","email":"sample@mail.com","div_id":"2345","save_id":"1111","page":0}',
    'headers': {
        'pragma': 'no-cache',
        'date': 'Fri, 12 Apr 2024 18:01:11 GMT',
        'content-encoding': 'gzip',
        'x-powered-by': 'Sails <sailsjs.com>',
        'etag': 'W/"80c-asdfasdvqw4taef"',
        'vary': 'Origin, Accept-Encoding',
        'content-type': 'application/json; charset=utf-8',
        'access-control-allow-origin': 'https://url.com',
        'cache-control': 'private, no-cache, no-store, must-revalidate',
        'access-control-allow-credentials': 'true',
        'expires': '-1'
    },
    'statusText': '',
    'url': 'https://url.com/api/load?rec_id=23886&div_id=6449',
    'ok': True,
    'request': {
        'headers': {
            'sec-ch-ua': '"Not A(Brand";v="24", "Chromium";v="110"',
            'content-type': 'application/json',
            'referer': '',
            'sec-ch-ua-mobile': '?0',
            'authorization': 'Bearer wasdfhuiowyerbsdfuiwelrbsdliufy',
            'user-agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/110.0.0.0 Safari/537.36',
            'sec-ch-ua-platform': '"Windows"'
        },
        'method': 'GET',
        'postData': None
    }
}
`

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser : Chrome
 - robotframework-browser==16.0.0 (also reproducible in 18.xx)

**Additional context**
Upon investigation, was able to fix the issue by converting first the data by using dumps() then proceed on loads() on method _jsonize_content() on file network.py. 

See screenshot.
![TypeError-NoneType](https://github.com/MarketSquare/robotframework-browser/assets/3782948/598dd220-70b2-4e2a-9164-dd608bbf7a5c)

Hope this help since this is crucial on our automation script to wait the data loaded before proceeding the flow.

**Comment by aaltat** [comment]
@allcontributors please add @nfaustin for bugs

**Comment by aaltat** [comment]
Are you interested to do a PR to fix the problem?

**Comment by nfaustin** [comment]
Confirmed issue is fixed now in latest 18.4.0. Thanks.
