### ISSUE TITLE
Remove the "tips" and ANSI colors on errors

### ISSUE THREAD

**Issue by simonmeggle** [MarketSquare/robotframework-browser#3557]
I want to discuss the sense of these “tips” wich always come up on a selector error: 

```
Tip: Use Set Browser Timeout for increasing the timeout or double check your locator as the targeted element(s) couldnt be found.
```

I think everybody which works with Browser lib for some time has seen this message multiple times -  but always takes an decision based on his own judgement and not on what the library proposes.
If, for example, a timeout is exceeded when loading a page, the error message `Timeout 10000ms exceeded` reads accordingly. This is enough to know what happened. 

Increasing the timeout _can_ be a solution to the problem.
Also a wrong locator _can_ be a solution, yes.
But other problems (not mentioned in the tip) are at least as likely.

---

I already posted in Slack some time ago. But right now I got a request from a customer to "_increase the timeout_" in a failed test. 
Looking closer I saw that the page had a problem and the selector was not found. 
This is exactly what I mean: these "Tips" lead to false assumptions, especially on untrained staff.

**Comment by Snooz82** [comment]
@aaltat i am fine with the proposal to streamline the error.

**Comment by aaltat** [comment]
@allcontributors please add @simonmeggle for ideas

**Comment by Snooz82** [comment]
I will also remove the ANSI colors from the Playwright error messages.
