### ISSUE TITLE
Enable Tracing only on first retry

### ISSUE THREAD

**Issue by sarathselvi** [MarketSquare/robotframework-browser#3597]
**Is your feature request related to a problem? Please describe.**
When we run suite with more than 100 testcases, tracing.zip takes up space. For testcases that are passed, we will not be using the tracing anyways
**Describe the solution you'd like**
A better way would be to add an option to enable trace only if the tests failed and it is retried like we already have in Playwright - **_trace: 'on-first-retry'_**

**Comment by aaltat** [comment]
Browser library doesn’t know is the execution first one or a retry one. For the library it’s a an execution as any other one. Therefore for the library, we can’t detect such state.

But you as a user can most likely set a variable from command line when rerunning is done and based on the variable enable or disable trace.

**Comment by aaltat** [comment]
Also I have heard that people do similar things by using a listener.
