### ISSUE TITLE
rfbrowser --version fails with exception from 

### ISSUE THREAD

**Issue by rasjani** [MarketSquare/robotframework-browser#3600]
when running `rfbrowser --version` in the shell, command throws exception from subprocess.run() from get_rf_version().

https://github.com/MarketSquare/robotframework-browser/blame/main/Browser/entry/__main__.py#L233

This call has `check=True` which makes subprocess to throw exception when exit code is non-zero.

Accorrding to https://robotframework.org/robotframework/latest/RobotFrameworkUserGuide.html#return-codes

When user runs robot --version, exit code is explicitly set to 251 and thus, using `check=True` causes the issue.

**Comment by aaltat** [comment]
Aha, good catch. I will make release today and push this one also in.

@allcontributors please @rasjani for bugs

**Comment by aaltat** [comment]
@allcontributors please add @rasjani for bugs.
