### ISSUE TITLE
Documentation for New Context keyword and baseURL argument does not mention  Wait For Navigation

### ISSUE THREAD

**Issue by rasjani** [MarketSquare/robotframework-browser#3636]
At following line; https://github.com/MarketSquare/robotframework-browser/blob/main/Browser/keywords/playwright_state.py#L563

```When using `Go To`, `Wait For Request` or `Wait For Response` it takes the base URL in consideration by using the URL() constructor for building the corresponding URL.```

However, `baseURL` seems to also be working for `Wait For Navigation` with my quick try.

**Comment by aaltat** [comment]
Thank you for noticing this and also for providing the fix.
