### ISSUE TITLE
Get Elements should not raise timeout exception when no elements found. It should return an empty list.

### ISSUE THREAD

**Issue by mkorpela** [MarketSquare/robotframework-browser#366]
**Is your feature request related to a problem? Please describe.**
Selectors can match multiple targets. Currently Get element just "randomly" returns the first match.
This might not be the correct thing.
Get Element is used so that further manipulations or validations can be made to that element. Selector might match 0, 1 or N elements.

**Describe the solution you'd like**
Replace Get Element with Get Elements that returns a list of matches. Also have assertion engine there for easy manipulation of that list such as `Get Elements   selector   then   value[0]`

**Describe alternatives you've considered**
Get Element might also raise an error when multiple matches.

**Comment by vincenzo-gasparo** [comment]
Hi, in my opinion Get Elements should allow to return an empty list instead of raising "Could not find element with selector `XXX` within timeout." exception, just like SeleniumLibrary

**Comment by mkorpela** [comment]
This seems to already work. Although Bug defined here is a valid one. I'll edit the title.

**Comment by mkorpela** [comment]
@aaltat I think we need to handle the timeout.

**Comment by mkorpela** [comment]
I mean that it will with the exception waiting version wait until timeout

**Comment by aaltat** [comment]
Yes, it will search elements until it finds at least it one or it will raise an exception in the node side. But I don't understand why waiting is bad?

**Comment by mkorpela** [comment]
I think get elements should be instant check

**Comment by mkorpela** [comment]
But better have this discussion on slack.

**Comment by mkorpela** [comment]
From dynamic behaviour point of view (such as crawling unknown site), it is a normal situation that elements are not found. So it also can’t take 10 seconds when ending to this kinds of pages..

**Comment by mkorpela** [comment]
Maybe I just need to set the timeout to 0.. 🤪

**Comment by aaltat** [comment]
I agree if it should do check quickly,  users can set timeout on smaller value. What shall we do with the issue?

**Comment by mkorpela** [comment]
I think you fixed it, I just kind of forgot that timeout setting is an option.
