### ISSUE TITLE
Add the kwarg timeout to Connect to Browser

### ISSUE THREAD

**Issue by mardukbp** [MarketSquare/robotframework-browser#3668]
**Is your feature request related to a problem? Please describe.**
When calling New Browser the kwarg "timeout" determines the time that Browser Library waits for the browser to start. The standard value is 30s. When connecting to a running browser with Connect to Browser there is no way to change the time that Browser Library waits for the connection to be established. Playwright does support this parameter.

**Describe the solution you'd like**
Connect to Browser has a kwarg "timeout".

**Describe alternatives you've considered**
N/A

**Additional context**

**Comment by aaltat** [comment]
Sounds reasonable 

@allcontributors please add @mardukbp for ideas.

**Comment by mardukbp** [comment]
@aaltat This enhancement is not urgent. Feel free to lower its priority.

**Comment by Snooz82** [comment]
fixed in #3930
