### ISSUE TITLE
Support defining custom npm registry in rfbrowser init

### ISSUE THREAD

**Issue by aaltat** [MarketSquare/robotframework-browser#3686]
If rfbrowser init is run in environment where public npm register is not available supporting `npm install —registry` could be handy.

**Comment by fhennig42** [comment]
I think you can just use the `npm_config_registry` environment variable like this:
```
npm_config_registry=https://registry.example.org rfbrowser init
```

**Comment by aaltat** [comment]
This is about same as https://github.com/MarketSquare/robotframework-browser/issues/2135 Closing this one as duplicate.
