### ISSUE TITLE
Lazy initializing of playwright

### ISSUE THREAD

**Issue by Noordsestern** [MarketSquare/robotframework-browser#3757]
**Is your feature request related to a problem? Please describe.**
We have test cases that do not use a Browser keyword, however due to reasons, some of the keywords used import a resource file with Browser library. Thus Browser library is created and playwright is initialized.

The issue is that these particular test cases without using Browser require proxies, thus test case pauses, tries to connect to the playwright port and finally prints an error message. The test case itself passes, since no browser automation is used, anyway.

**Describe the solution you'd like**
As discussed with @Snooz82 the initialization of playwright on startup is only required on when using jsextensions. So a later initialization as default and immediate initialization for jsextensions may work.
@Snooz82 said making playwright a property would do the trick (whatever that means, i am merely a parrot 🦜 here)

**Comment by aaltat** [comment]
@allcontributors please @Noordsestern for ideas

@Snooz82 what was idea behind this request?

**Comment by aaltat** [comment]
@allcontributors please add @Noordsestern for ideas
