### ISSUE TITLE
Protobuf gencode version 5.27.2 is older then the runtime version 5.28.1 at playwright.proto. Please avoid checked-in Protobuf gencode that can be obsolete.

### ISSUE THREAD

**Issue by Houbein** [MarketSquare/robotframework-browser#3789]
**Describe the bug**
In version 18.8.1 rfbrowserinit fails with the following error: 
Failed to download Chromium 129.0.6668.29 (playwright build v1134) caused by Download failure, code=1
at ChildProcess.<anonymous> (c:\Python312\Lib\site-packages\Browser\wrapper\node_modules\playwright-core\lib\server\registry\browserFetcher.js:91:16)

There is also a warning: 
c:\Python312\Lib\site-packages\google\protobuf\runtime_version.py:122: UserWarning: Protobuf gencode version 5.27.2 is older then the runtime version 5.28.1 at playwright.proto. Please avoid checked-in Protobuf gencode that can be obsolete.

**To Reproduce**
Install version 18.8.1
run rfbrowserinit

**Desktop:**
 - OS: Windows 10 22h2

**Additional context**
Downgrading to 18.8.0 solves the issue.

**Comment by aaltat** [comment]
The download is controlled by Playwright and we can’t fix it. Because we run Windows also in our CI, the binary should be there, have you retried the installation and see what it says?

The protobuf warning is Browser library problem and I did notice it too after the release. Need to see how it can be fixed.

**Comment by aaltat** [comment]
@allcontributors please add @Houbein for bugs

**Comment by aaltat** [comment]
I think this is caused by https://github.com/protocolbuffers/protobuf/issues/18096 and we need to wait for new release from protobuf.

**Comment by Snooz82** [comment]
We fixed it so, that we have now downgraded the protobuf version.
