### ISSUE TITLE
RFB closing socket and ending playwright execution when handling multiple dialogs

### ISSUE THREAD

**Issue by henriquediassep** [MarketSquare/robotframework-browser#3801]
**Describe the bug**
In case a dialog was already handled before, if you try to execute a command that required dialog handling, it closes the socket, kill playwright execution and ends up failing all the following tests.

**To Reproduce**
1. Go to any context that requires handling dialogs
2. Use "Handle Future Dialogs    action=accept"
3. Interact with the item where handling the dialog is necessary
4. Repeat the process

**Expected behavior**
In case the dialog was already handled, only a warning perhaps should be included

**Screenshots**
![image](https://github.com/user-attachments/assets/11c287dc-4536-400c-a5e8-df359711d703)

**Desktop (please complete the following information):**
 - OS: Windows 11 (but happens also on pipeline running Ubuntu)
 - Browser: Chrome 
 - Version: Chrome: 128.0.6613.138 Robot Framework Browser: Latest (18.8.1)

**Additional context**
Even though I'm interacting with different element, they both seems to trigger the same alert dialog. After doing the first time, it works completely fine, but when getting to the second run, it logs "socket closed" and all the following keywords have the response "ConnectionError: Playwright process has been terminated with code 1". Could it be a different way to handle that? or at least not closing all the following executions for it.

Also, this could be related to https://github.com/MarketSquare/robotframework-browser/issues/3785

**Comment by aaltat** [comment]
@allcontributors please add @henriquediassep for bugs

**Comment by aaltat** [comment]
This is [most likely) same as #3785 In #3785 there is proposal for a fix, but the keywords syntax needs some thinking, would you have good ideas? 

I am closing this issue, please post you comment in #3785
