### ISSUE TITLE
Create release with updated Playwright & dependencies

### ISSUE THREAD

**Issue by Houbein** [MarketSquare/robotframework-browser#3899]
Create release with updated Playwright & dependencies: 

- Playwright 1.49 
- grpcio 1.68.0
- grcpio-tools 1.68.0 
- protobuf 5.28.3 (The " Protobuf gencode version 5.27.2 is older then the runtime version 5.28.1 at playwright.proto. Please avoid checked-in Protobuf gencode that can be obsolete" warning that was present in 5.28.1 is solved in 5.28.3)

**Comment by aaltat** [comment]
Yes, release is planned when few last things are ready. 1) The coverage report new few changes before it, #3887 can be merged 
2) @Snooz82 planned to implement the https://playwright.dev/docs/api/class-tracing#tracing-group for the library 

But most likely we are able to push release latest next week out.
