### ISSUE TITLE
Getting the error while Open Browser key word with firefox browser

### ISSUE THREAD

**Issue by nagaraj0312** [MarketSquare/robotframework-browser#390]
**Describe the bug**
While running the below keyword i am getting the error if the firefox browser is used if i am using the chromium browser it is working fine

Open Browser    http://google.com	firefox

I have attached the playwright log also
[playwright-log.txt](https://github.com/MarketSquare/robotframework-browser/files/5214269/playwright-log.txt)

**To Reproduce**

**Expected behavior**

**Screenshots**
![firefox](https://user-images.githubusercontent.com/15028268/93020577-8084ba80-f5fb-11ea-8f67-a90084e2e488.png)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by mkorpela** [comment]
Thank you for the bug report!

**Comment by aaltat** [comment]
I can not reproduce the issue. Please update to the latest library version and run `rfbrowser init` again. This looks like a missing dependency form the Playwright side.

**Comment by aaltat** [comment]
Closing due inactivity.
