### ISSUE TITLE
A logger.console statement in get_element_by_role bloating console output

### ISSUE THREAD

**Issue by ArttuKnowit** [MarketSquare/robotframework-browser#3924]
**Describe the bug**
On line 975 in getter.py file in the method get_element_by_role() there is the line logger.console(self.get_frame_selector()) which often causes an empty line to be printed in the output.

**To Reproduce**
1. Run any script where the "Get Element By Role" keyword is used
2. Observe the console output

**Expected behavior**
No empty lines or unnecessary or unprompted console outputs appear

**Screenshots**
![browser_issue_screenshot](https://github.com/user-attachments/assets/7f8d1543-bf5a-4a5e-bb15-e9ee0bbe3475)

**Desktop (please complete the following information):**
 - OS: Windows 10 Enterprise
 - Browser: any
 - Version: 22H2
 - Experience: Windows Feature Experience Pack 1000.19060.1000.0

**Additional context**
This line can simply be removed and has probably been left there by accident.

**Comment by aaltat** [comment]
@allcontributors please add @ArttuKnowit for bugs

**Comment by Snooz82** [comment]
will be fixed in #3927
