### ISSUE TITLE
Close Browser is hanging using chromium browser in headless false mode

### ISSUE THREAD

**Issue by gdroes** [MarketSquare/robotframework-browser#393]
**Describe the bug**
Close Browser is hanging using chromium browser in headless false mode. 
In this case you will not get a proper log file and report.
The browser firefox and webkit are working fine.

**To Reproduce**
lease use this example: 
Starting browser with a page
    New Browser    chromium    headless=false
    New Context    viewport={'width': 1920, 'height': 1080}
    New Page       https://marketsquare.github.io/robotframework-browser/Browser.html
    Get Title      ==    Browser
    Get Browser Catalog
    Close Page
    Close Context
    Close Browser

**Expected behavior**
I expect the browser is closed and the log files are created.

**Screenshots**
none

**Desktop (please complete the following information):**
 - OS: windows 10
 - Browser chromium
 - Version latest version from playwright

**Comment by aaltat** [comment]
There is log file also from playwright side, it should be in the `${OUPUT_DIR}/playwright-log.txt`. Would it be possible to see what that log file contains?

**Comment by gdroes** [comment]
Hi, I also put the execution time log also to the archive.
[playwright-log.zip](https://github.com/MarketSquare/robotframework-browser/files/5223572/playwright-log.zip)

**Comment by aaltat** [comment]
I can not reproduce the issue with latest Browser library version. Could you update the Browser library and run `rfbrowser init`

**Comment by gdroes** [comment]
Hi, seems to be a local installation issue. After a new installation the problem has gone. We can close this ticket.
