### ISSUE TITLE
Protobuf version used by robotframework-browser was yanked from PyPI

### ISSUE THREAD

**Issue by sd-yazzoom** [MarketSquare/robotframework-browser#3946]
**Describe the bug**
The version of protobuf used by robotframework-browser was yanked from PyPI

**To Reproduce**
- make sure you have robotframework-browser in your pipfile
- pipenv lock

**Expected behavior**
No warnings

**Desktop (please complete the following information):**
 - MacOS (but OS independant)
 - Browser independant
 - Node 22.x
 - Python 3.12
 - robotframework 
 - robotframework-browser 19.1

**Additional context**
A fixed protobuf version is available (5.29.1), but due to the strict requirements of robotframework-browser, only version 5.29.0 is accepted (understandable as you probably want people to use the same dependencies as was tested)

**Comment by sd-yazzoom** [comment]
More info about the yanked protobuf version:
https://pypi.org/project/protobuf/#history

Suggested fix (sorry wanted to do a pull request, but didn't know how):
https://github.com/sd-yazzoom/robotframework-browser/commit/50c384ec4b94721e8e5dc94592b0607c680c9de2

**Comment by aaltat** [comment]
Will be fixed in #3941
