### ISSUE TITLE
[Feature] Go to should return HTTP status code

### ISSUE THREAD

**Issue by mkorpela** [MarketSquare/robotframework-browser#395]
**Describe the bug**
We should detect 404 and 500 return codes.
page.goto will not throw an error when any valid HTTP status code is returned by the remote server, including 404 "Not Found" and 500 "Internal Server Error". The status code for such responses can be retrieved by calling response.status().

So return code should be returned when we navigate to a page.

**Comment by Snooz82** [comment]
implemented by #3222
