### ISSUE TITLE
Highlight Elements does not work with Get Elements

### ISSUE THREAD

**Issue by Snooz82** [MarketSquare/robotframework-browser#401]
**Describe the bug**
Get Element(s) return guid which represent an element. If you try to use this guid in the keyword `Highlight Elements` there is an exception

**To Reproduce**
```
${elem}=    Get Element     div
Highlight Elements    ${elem}
```

**Expected behavior**
That should work

**Comment by mkorpela** [comment]
Narrowed this down to difference in how ElementHandle and "normal" selectors are handled and how "$$eval" and "$eval" work differently in these cases. There is a related puppeteer issue https://github.com/puppeteer/puppeteer/issues/2004

**Comment by mkorpela** [comment]
This just works wrong in this specific cases where method is eval https://github.com/MarketSquare/robotframework-browser/blob/ab58eb0629fc93e0aac34e9db5cb7518c8636769/node/playwright-wrapper/playwirght-invoke.ts#L86

**Comment by mkorpela** [comment]
Should call page.evaluate(myfunction, elementhandler)

**Comment by mkorpela** [comment]
Fixed mostly after https://github.com/MarketSquare/robotframework-browser/commit/f849627d5587e11179129e37b88525d69db4031e
This fix does not give possibility to modify the visuals of the highlight.
