### ISSUE TITLE
Get Page Ids is only working with New Page

### ISSUE THREAD

**Issue by gdroes** [MarketSquare/robotframework-browser#407]
**Describe the bug**
Get Page Ids is only working with New Page. If you open a new Tab via a href link. The new Page is not detected by "Get Page Ids"

**To Reproduce**
Please try this code and compare the result.
Get Page ID Which Is Working Well
    ${page_id1} =   New Page    https://robotframework.org/
    ${page_id2} =   New Page    https://robocon.io/
    ${ret} =   Get Page Ids   ALL

Get Page ID Which Is NOT Working
    ${page_id1} =   New Page    https://robotframework.org/
    Click    xpath=//*[@id="navigation"]/li[9]/a
    ${ret} =   Get Page Ids   ALL

**Expected behavior**
I expect to get the IDs of all Pages back. The IDs are needed to switch between the Pages.

**Desktop (please complete the following information):**
 - OS: Windows 10 latest release
 - Browser chrom
 - Version latest version

**Comment by mkorpela** [comment]
This is most likely a timing issue.
Get Page  NEW
will be improved in the next release so that navigation between pages should become a new level of fun.

**Comment by mkorpela** [comment]
Switch Page change fixes the issue. Timing can not be really improved. Fact is that Get Page Ids is called before the page exists. Sleep shows that once the page exists it is identified correctly.
