### ISSUE TITLE
Switch Page  NEW  = to page that has been created after the current page

### ISSUE THREAD

**Issue by mkorpela** [MarketSquare/robotframework-browser#413]
**Is your feature request related to a problem? Please describe.**

Switch Page NEW does not work reliably after an action that triggers a page creation. Many times it just binds to current one.
We need a mechanism to ensure that the page is opened and ready for use.

**Comment by aaltat** [comment]
Could be related #407

**Comment by mkorpela** [comment]
Switch Page  CREATED, would bind to one that is not the current one and must be created after current. It would also wait for this and timeout if nothing happens after the default timeout.

**Comment by mkorpela** [comment]
Switch page NEW https://github.com/MarketSquare/robotframework-browser/pull/414 improved

**Comment by mkorpela** [comment]
Fixed
