### ISSUE TITLE
Click without permissions on headless browser seems to jam everything 

### ISSUE THREAD

**Issue by mkorpela** [MarketSquare/robotframework-browser#416]
**Describe the bug**

This seems to jam everything at click level and not able to continue when working with default headless browser.
```
Context with no Geolocation Permission
    New Context
    New Page           https://www.openstreetmap.org/
    Click              span.icon.geolocate
    Take Screenshot
```

The click would require a location and permissions to use location services.

**Comment by aaltat** [comment]
I think this has changed with PlayWright releases because the example test works. Closing.
