### ISSUE TITLE
[Feature] Relative selector support

### ISSUE THREAD

**Issue by idxn** [MarketSquare/robotframework-browser#418]
**Is your feature request related to a problem? Please describe.**
A special locator to visually locate an element will reduce the maintenance cost of the script and it actually matches the E2E test because your locator won't tie to any HTML structure and simulate the real user that uses his/her own eyes

**Describe the solution you'd like**
Use https://www.npmjs.com/package/playwright-relative-selector

**Describe alternatives you've considered**
N/A

**Additional context**
https://github.com/microsoft/playwright/issues/2877

**Comment by mkorpela** [comment]
https://github.com/getgauge/taiko/wiki/Taiko's-Proximity-Selector

**Comment by mkorpela** [comment]
Selector distance should be square pixels (least square method).

**Comment by mkorpela** [comment]
Relative selectors (above/below/right/left) have at least theoretical problems with responsive sites that will change the layout based on viewport size. Elements might not be on same places relative to each other on different screen sizes.

**Comment by mkorpela** [comment]
I think we should implement a new keyword `Get Closest Element  selector:str  close_to_selector:str` to experiment with the proximity concept. We should not too much diverse from Playwright selector syntax. This prevents future problems of Playwright side syntax evolving and us maintaining our own stuff.

**Comment by mkorpela** [comment]
https://www.selenium.dev/documentation/en/getting_started_with_webdriver/locating_elements/#relative-locators

**Comment by mkorpela** [comment]
`Get Closest Element  selector  visualrelation  close_to_selector`

**Comment by idxn** [comment]
Since playwright will launch in 1.8, it's good chance to implement in robotframework-browser.

https://github.com/jfgreffier/playwright-relative-selector/issues/16#issuecomment-711923044

**Comment by idxn** [comment]
we might not need to do anything. we might just update the locator string according to the playwright doc. https://playwright.dev/docs/selectors#selecting-elements-based-on-layout

**Comment by aaltat** [comment]
We don't alter selectors in the keywords, so what is supported by Playwright should work. Therefore can we close the issue?

**Comment by mkorpela** [comment]
I believe this is done.
