### ISSUE TITLE
New Page, New Context, New Browser

### ISSUE THREAD

**Issue by xylix** [MarketSquare/robotframework-browser#42]
- Could work as a "hidden" improvement over the "open browser" use (for example for testing different user logins in same test)
- Figure out how Playwright's context's isolation  differs from how Playwright's browsers are isolated
- Can we run test suited just in clean contexts within one browser or is launching multipl contexts mandatory?

`New Page`, `New Context` keywords, change Open Browser to `New Browser`

**Comment by mkorpela** [comment]
Mentioned in https://github.com/MarketSquare/robotframework-browser/issues/49 <-- so currently this is a duplicate.
