### ISSUE TITLE
`Fill secret` leaks the secret into log.html

### ISSUE THREAD

**Issue by Tattoo** [MarketSquare/robotframework-browser#421]
**Describe the bug**
According to [documentation](https://marketsquare.github.io/robotframework-browser/Browser.html#Fill%20Secret):

> The difference to Fill Text is that this keyword does not log the text to be written into the text field.

However, one can get the content of `secret` to log.html

**To Reproduce**
1. Create a test case that uses `Fill Secret`
    eg. 
   ```
    *** Settings ***
    Library    Browser    retry_assertions_for=5s

    *** Variables ***
    ${HEADLESS}=    ${True}
    ${BROWSER}=    chromium

    *** Test Cases ***
    TC
        Open browser    http://google.com    browser=${BROWSER}    headless=${HEADLESS}
        Click    css=iframe >>> id=introAgreeButton
        Fill secret    xpath=//input[@title="Search"] | //input[@title="Haku"]     I'm a secret!
    ```
1. Run the test with `--loglevel TRACE`

**Expected behavior**
"I'm a secret" shouldn't appear in log.html

**Screenshots**
<img width="811" alt="Screenshot 2020-10-15 at 21 11 20" src="https://user-images.githubusercontent.com/280218/96169578-03ff3780-0f2b-11eb-85ea-a7611cd4269d.png">

**Comment by aaltat** [comment]
Yes, this is True. Although that logging is done by Robot Framework core, I recall @Snooz82 having some idea how to solve it.

**Comment by Snooz82** [comment]
When the real value is just given as argument, RobotFramework logs it.
That is a core feature of RF.

We could intercept the "log_message" to delete the given argument if we could use Listener API version 3, what we can not use yet, due to missing `start_keyword` Function there.

So at the moment. We can not change that.

You can solve it on two ways:
1. Just put the secret into a variable. Then it is not revealed in Loglevel info! But still in Trace.
2. This is much more complex: use CryptoLibrary to encrypt your password and hide it from the logs.

This issue will now be closed, due to be out of scope of a library.

**Comment by Tattoo** [comment]
It is not out of scope of your library as your documentation gives the impression that this is safe, when it is not. Please re-open.

**Comment by aaltat** [comment]
Yes, there is a bug in the documentation and we should fix our docs.

**Comment by mkorpela** [comment]
Related https://github.com/MarketSquare/robotframework-browser/issues/112

**Comment by Snooz82** [comment]
> The difference to Fill Text is that this keyword does not log the text to be written into the text field.

Where is a bug in docs?

**Comment by Snooz82** [comment]
@Tattoo where do we give an impression, that robot framework does not log passwords that are given in plain text?

It is not our scope to change Robot frameworks logs!

That keyword does not log the text. That is what happen!
When you do not want to read passwords, put them in variables.

**Comment by Tattoo** [comment]
@Snooz82 I've literally quoted the part from your documentation which gives the user an impression that `Fill secret` is secure when it's not, as discussed.

**Comment by Snooz82** [comment]
@Tattoo yes, but that is absolutely correct! The keyword does not log it.

**Comment by mkorpela** [comment]
I think @Tattoo is correct when stating that `Fill Secret` gives the impression of not logging the given value anywhere.
@Snooz82 has also pointed out that currently a library can not control the trace logging as it happens before the keyword is called.

**Comment by mkorpela** [comment]
I think this is a bug. We give the impression of a mechanism that takes a plain text value from the file and inputs it silently to the field in question.

**Comment by mkorpela** [comment]
I was thinking that one option would also be to have a surrogate in Robot Framework side.
Something that works as an ID to a concrete value that lives somewhere else than in Robot Framework world.

**Comment by mkorpela** [comment]
Many cloud based systems use env variables for this kind of data.

**Comment by aaltat** [comment]
Yes, [env variable](https://robotframework.org/robotframework/latest/RobotFrameworkUserGuide.html#environment-variable) is good idea 
`Fill Secret selector %{SECRET_PASSWORD}`

**Comment by mkorpela** [comment]
https://github.com/MarketSquare/robotframework-browser/pull/484

**Comment by mkorpela** [comment]
https://github.com/MarketSquare/robotframework-browser/pull/486

**Comment by Snooz82** [comment]
The usage of "plain" text should be deprecated and a warning should be given to the user.
