### ISSUE TITLE
Assert future dialogs

### ISSUE THREAD

**Issue by emakaay** [MarketSquare/robotframework-browser#440]
Converting a couple of projects using selenium library to robotframework-browser.

One of the things that can't be converted is checking the text within a dialog.

With browser it is possible to accept or decline a future dialogs, but it would be nice to have the possibility to check the text within the dialog. Same as in selenium library. When te future dialogs doesn't contain the expected text, the test should fail.

**Comment by emakaay** [comment]
I would like to add some code for this issue.

I completed some tests, and (part) of the actual code. I need help to finish it. But I can't push the code to the repository. 
Do I need some special authorisation ?

Greets Erik

**Comment by mkorpela** [comment]
@emakaay you should be able to open a pull request with your code. https://docs.github.com/en/free-pro-team@latest/github/collaborating-with-issues-and-pull-requests/creating-a-pull-request

**Comment by aaltat** [comment]
This should be doable with https://playwright.dev/docs/api/class-dialog#dialogmessage

**Comment by emakaay** [comment]
Hello tatu,

I know this page.
I tried to implement this feature a few weeks ago.... Again. But failed to
get it working.


I tried 2 approaches:
1) determine dialog text within anonymous function and throw an exception
when it is not the expected value. Not a nice solution, because of the
exception, and I was only able to do a equals check.

2) get the dialog text from anonymous function, and return in to the handle
future dialog function. Then you could use the assertion function to check
the dialog. But couldn't get this to work. AND now I explain myself I think
that it is strange to handle the dialog text in an asynchronous function

All in all.... I don't have the JavaScript knowledge to do it. But this
feature is something that we use extensively in our tests(selenium based).
And some project can't/won't switch over to browser because of this.

Greets, Erik
