### ISSUE TITLE
Docs for "Wait For Request/Response" have wrong timeout unit

### ISSUE THREAD

**Issue by simonmeggle** [MarketSquare/robotframework-browser#442]
Small typo in the documentation: 

https://marketsquare.github.io/robotframework-browser/Browser.html#Wait%20For%20Response
https://marketsquare.github.io/robotframework-browser/Browser.html#Wait%20For%20Request

The timeout unit is not milliseconds as the documentation states, but seconds.

**Comment by aaltat** [comment]
Thank you pointing this out. Also the type hint is wrong, that should be fixed also.
