### ISSUE TITLE
Add optional message parameter to 'Wait For Elements State' 

### ISSUE THREAD

**Issue by simonmeggle** [MarketSquare/robotframework-browser#446]
I really treasure the fact that SL keywords like [Element should be visible](https://robotframework.org/SeleniumLibrary/SeleniumLibrary.html#Element%20Should%20Be%20Visible) have an optional _message_ parameter to override the default error message coming from the keyword itself.

This helps non-tech people to understand better what really happened. 

(Pseudo) example: 

```
ReportCheck 5AAFS                                                     | PASS |
------------------------------------------------------------------------------
ReportCheck 5BB11                                                     | FAIL |
Property innerText `-` should match `\d+(\.\d+)?\s.C`
------------------------------------------------------------------------------
```

vs. 
```
ReportCheck 5AAFS                                                     | PASS |
------------------------------------------------------------------------------
ReportCheck 5BB11                                                     | FAIL |
Error: The report table could not be found. See KB-300-11 for a possible solution.
------------------------------------------------------------------------------
```

It would be great if the [Wait For Elements State](https://marketsquare.github.io/robotframework-browser/Browser.html#Wait%20For%20Elements%20State) keyword in BL would also have an optional _message_ parameter. 

Thanks :-) 
Simon

**Comment by aaltat** [comment]
I agree, our error messages could be improved. Also in other ways than this. But in any case, providing way to provide custom error message is is useful.

**Comment by mkorpela** [comment]
A suggestion: The custom message could be a pattern also. It could contain ${selector}, ${state} and ${timeout}..

**Comment by simonmeggle** [comment]
The pattern approach could be a good default which makes the default message more informative for tech people.

It then could be overridden with a custom message to make it lot easier to localize problems.

Or even more, make the default pattern accessible by a placeholder variable within the custom message ?

**Comment by aaltat** [comment]
Also see #595
