### ISSUE TITLE
Docker images fails in git CI/CD pipeline

### ISSUE THREAD

**Issue by april-wang88** [MarketSquare/robotframework-browser#460]
When I pushed the images: docker.pkg.github.com/marketsquare/robotframework-browser/rfbrowser-stable:v1.7.0 to my git container, and use the images in git CI/CD pipeline, an error is reported:
**Could not connect to the playwright process at port 37999**
But this image works in my local window machine.

**Comment by estimation** [comment]
Hi, I had the same issue on my company's gitlab server.

Below are the error message of playwright-log.txt
E1029 09:13:57.410024918     193 server_chttp2.cc:40]        {"created":"@1603962837.409973758","description":"No address added out of total 2 resolved","file":"../deps/grpc/src/core/ext/transport/chttp2/server/chttp2_server.cc","file_line":394,"referenced_errors":[{"created":"@1603962837.408996791","description":"Failed to add port to server","file":"../deps/grpc/src/core/lib/iomgr/tcp_server_custom.cc","file_line":404,"referenced_errors":[{"created":"@1603962837.408986690","description":"Failed to initialize UV tcp handle","file":"../deps/grpc/src/core/lib/iomgr/tcp_uv.cc","file_line":72,"grpc_status":14,"os_error":"address family not supported"}]},{"created":"@1603962837.409968207","description":"Failed to add port to server","file":"../deps/grpc/src/core/lib/iomgr/tcp_server_custom.cc","file_line":404,"referenced_errors":[{"created":"@1603962837.409965628","description":"Failed to initialize UV tcp handle","file":"../deps/grpc/src/core/lib/iomgr/tcp_uv.cc","file_line":72,"grpc_status":14,"os_error":"address family not supported"}]}]}
{"level":30,"time":"2020-10-29T09:13:57.410Z","pid":193,"hostname":"runner-kb2n2huy-project-5811-concurrent-0","msg":"Listening on 47669"}

**Comment by mkorpela** [comment]
Thank you for the report!
Could be related to https://github.com/grpc/grpc/issues/10532

**Comment by mkorpela** [comment]
Might be that localhost is not secure enough.

**Comment by mkorpela** [comment]
https://stackoverflow.com/questions/56422797/address-family-not-supported-grpc-docker

**Comment by mkorpela** [comment]
https://github.com/grpc/grpc-node/issues/1209

**Comment by mkorpela** [comment]
"I managed to bypass this by migrating to grpc/grpc-js instead of using the c-core version."

**Comment by mkorpela** [comment]
@estimation or @april-wang88 does this still happen with version 2.0?

**Comment by april-wang88** [comment]
@mkorpela The bug has been fixed in version 2.0, thanks! And I'm also confused why I need to login before I pull this public image, otherwise "no basic auth credentials" will be reported.

**Comment by estimation** [comment]
@mkorpela My problem has been solved. Thank you.

**Comment by mkorpela** [comment]
Great to know! 
@april-wang88 I'm opening another issue about docker image login.

**Comment by mkorpela** [comment]
https://github.com/MarketSquare/robotframework-browser/issues/466 <-- new issue about docker image login.
