### ISSUE TITLE
One step install

### ISSUE THREAD

**Issue by mkorpela** [MarketSquare/robotframework-browser#465]
**Is your feature request related to a problem? Please describe.**

Currently installing robotframework-browser requires 3-4 steps:
1. Have Python >=3.7 installed
2. Install node.js
3. `pip install robotframework-browser`
4. `rfbrowser init` (install npm packages, download and copy browser drivers to correct locations)

We should simplify this to make more people try the library.

**Describe the solution you'd like**
Wheels can contain prebuilt binaries. We should have as ready as possible prebuilt package for win, linux and osx.
  - Package node + npm packages to an executable: https://github.com/vercel/pkg
  - Have browser drivers already in the wheel package and just copy them to correct location / configure PW to use them from our custom location

**Describe alternatives you've considered**
playwright-python could also be an option.

**Comment by xylix** [comment]
@martinRenou Do you know how to get `npm install --production` to run after setup.py? We have had problems hooking it up in the past. It would be a big improvement for pip users as well as make stuff a bit simpler for the conda package.

**Comment by martinRenou** [comment]
You can define a custom setuptools Command class, as we do here in ipyleaflet: https://github.com/jupyter-widgets/ipyleaflet/blob/master/setup.py#L80

This way the npm command is run during the `pip install .` or when building the wheel, then you can publish the JS code (or your binary once the pkg PR is in) as data_files or package_data in your module.

**Comment by mkorpela** [comment]
Too complex :(

**Comment by martinRenou** [comment]
It's not that complex honestly. And it's a bit of complexity that would simplify the user workflow enormously, users would not have to install nodejs anymore (which many pip users have difficulties achieving).

**Comment by martinRenou** [comment]
I could come up with a PR if that is something you would be interested in. This would increase your PyPi package size, but users have to download those data anyway when running `rfbrowser init`. It would also allow us to have a working conda package.

**Comment by mkorpela** [comment]
If I remember correctly Pypi has a thight package size limit.
The browsers around 500MB when installed in `rfbrowser init`

**Comment by mkorpela** [comment]
But PRs are very much welcome if you come up with a working solution.

**Comment by martinRenou** [comment]
> The browsers around 500MB when installed in rfbrowser init

Ok, I haven't realized it would be **that** big. Then maybe the solution I suggested is not that great.
