### ISSUE TITLE
Docker image pull without login

### ISSUE THREAD

**Issue by mkorpela** [MarketSquare/robotframework-browser#466]
Currently login is required to pull our docker image. Should not be

**Comment by mkorpela** [comment]
"..why I need to login before I pull this public image, otherwise "no basic auth credentials" will be reported."

**Comment by NemoHostem** [comment]
This is definitely a fallback in cloud-based pipelines, which use a lot of open-source packages and can't have authentication as a part of process.
This is a Github issue, which have been open for over a year: https://github.community/t/docker-pull-from-public-github-package-registry-fail-with-no-basic-auth-credentials-error/16358/37
Possible workaround for this is to add the image openly available to dockerhub.

E.g. In Github action simply add one more job to tag and push latest image to dockerhub: (_ = spacebar)
services:
__robotframework-browser:
____#image: docker.pkg.github.com/marketsquare/robotframework-browser/rfbrowser-stable:v2.3.1:latest
____image: docker.io/xxxx/robotframework-browser/rfbrowser-stable:latest

**Comment by xylix** [comment]
Fixed by the image now being on dockerhub (see https://hub.docker.com/r/marketsquare/robotframework-browser ). We could document this fact better though.

**Comment by pokaalinkanssayohon** [comment]
Please fix these docker image lines in documentation (command line and Dockerfile options) as well. Thank You! 
Very nice extension overall, well done!
