### ISSUE TITLE
The link to playwright's 'deviceDescriptors.ts' of keywords 'Get Device' and 'Get Devices' has been changed

### ISSUE THREAD

**Issue by estimation** [MarketSquare/robotframework-browser#473]
**Describe the bug**
The link to playwright's 'deviceDescriptors.ts' of keywords 'Get Device' and 'Get Devices' has been changed.
The link points to 
https://github.com/Microsoft/playwright/blob/master/src/deviceDescriptors.ts
but actually should point to
https://github.com/Microsoft/playwright/blob/master/src/server/deviceDescriptors.ts

**To Reproduce**
1. Go to keyword documentation
2. Click on 'Get Device' or 'Get Devices'
3. Click on the link 'deviceDescriptor.ts'
4. See error, 404 not found

**Comment by aaltat** [comment]
@all-contributors please add estimation for Bug reports
