### ISSUE TITLE
Firefox on Windows needs DLLs - show message after installation

### ISSUE THREAD

**Issue by simonmeggle** [MarketSquare/robotframework-browser#494]
This is not really a bug, but not at all a feature request - so call it a bug :-) 

Firefox can only be used on Windows if there is at least `vcruntime140_1.dll` on the system (probably others?).
This has to be done manually (and it's ok not top ship DLLs with rf-browser...). 

During my research about this dependency I stumbled on [this issue](https://github.com/microsoft/playwright/issues/4293) on the playwright project where I read that playwright _already_ prints out a proper message about those missing DLLs and how to fix this by hand. 

I cannot remember to see such a message during the rfbrowser installation and I think it gets lost somewhere during the npm installation process. If so (and I hope that I am right) it would be great if in the end of `rfbrowser init` the user again gets informed that he needs to install the dlls before he can use Firefox. 

There is one [closed issue](https://github.com/MarketSquare/robotframework-browser/issues/390) here about exactly this problem and it was closed to inactivity. Without any hint to the real cause users probably get lost; that's why I am trying to document the problem here.

**Comment by aaltat** [comment]
This should be fixed when next playwright release is made. For time being, you could follow these instructions to install the missing dll https://answers.microsoft.com/en-us/windows/forum/all/vcruntime1401dll-missing-where-to-get/268964c7-6910-4cdd-9a96-b03f4c1f6954

**Comment by mkorpela** [comment]
@all-contributors, please add @simonmeggle for bugs.

**Comment by mkorpela** [comment]
@all-contributors please add @simonmeggle for userTesting

**Comment by aaltat** [comment]
Playwright 1.6.0 is out, could you update to Playwright 1.6.0 and see is this still a problem for you?

**Comment by aaltat** [comment]
Closing due inactivity.

**Comment by dpgraham** [comment]
I'm seeing this problem on my Windows tests. It can't find `vcrUNTIME140_1.dll` (but it is being bundled with `vcrUNTIME140.dll`)
