### ISSUE TITLE
Self signed certificates do not work on Firefox, Edge or Webkit

### ISSUE THREAD

**Issue by NemoHostem** [MarketSquare/robotframework-browser#499]
**Describe the bug**
The application is in development phase and is run locally using localhost:5001. Application uses self signed certificates in development phase. Firefox, Edge and Webkit all have SSL / certification issues, which leads to failed builds.

**Firefox:**
`
page.goto: SSL_ERROR_UNKNOWN
=========================== logs ===========================
navigating to "https://localhost:5001/", waiting until "load"
`
**Edge:**
`
page.goto: net::ERR_CERT_AUTHORITY_INVALID at https://localhost:5001/
=========================== logs ===========================
navigating to "https://localhost:5001/", waiting until "load"
`
**Webkit:**
`
page.goto: Problem with the SSL CA cert (path? access rights?)
=========================== logs ===========================
navigating to "https://localhost:5001/", waiting until "load"
`

**To Reproduce**
1. Create an application with self signed certificate
2. Create a robot test, which navigates to 'localhost:<port>'
3. Start the application on port <port>
4. Run `robot tests`
5. See error in command line

**Expected behavior**
The navigation test to the localhost:<port> should pass and not throw SLL/Certification error.

On Chrome this works:
Chrome resource file:
```
*** Settings ***
Documentation     Resource file for basic use cases in Chrome
Library           Browser

*** Variables ***
${HOST}           localhost:5001
${LOGIN URL}      https://${HOST}/
${BROWSER}        chromium
${HEADLESS}       ${True}

Robot test file: (APP_NAME is defined in this file)

*** Test Cases ***
Suite setup
    New Browser     ${BROWSER}  ${HEADLESS}  
    args=['--allow-insecure-localhost']
    New Context     ignoreHTTPSErrors=${True}   bypassCSP=${True}

Navigating to home page
    [Tags]      Home
    New Page    ${LOGIN URL}
    Get Text    h1     ==   ${APP_NAME}
```

Command line:
`Navigating to home page                                           | PASS |`

**Issues**
Navigating to home page test case is similar for every browser. bypassCSP is not necessarily needed, but it does not help either.

Firefox: (Navigating to home page does not work with this suite setup)
```
Suite setup
    New Browser     ${BROWSER}  ${HEADLESS}   
    args=['--accept-untrusted-certificates', '--allow-insecure-localhost']
    New Context     ignoreHTTPSErrors=${True}   bypassCSP=${True}
```

Webkit: (Navigating to home page does not work with this suite setup)
```
Suite setup
    New Browser     ${BROWSER}  ${HEADLESS}   
    args=['--allow-insecure-localhost']
    New Context     ignoreHTTPSErrors=${True}   bypassCSP=${True}
```

Edge: (Navigating to home page does not work with this suite setup)
```
Suite setup
    Open edge       ${HEADLESS}
    New Context     ignoreHTTPSErrors=${True}   bypassCSP=${True}
```

Open edge keyword: (EDGE_PATH exists in this file)
```
Open edge
    [Documentation]     Opens Microsoft Edge browser
    [Arguments]         ${headless}
    New Browser         browser=chromium
    ...                 headless=${headless}
    ...                 executablePath=${EDGE_PATH}
    ...                 args=['--ignore-certificate-errors', '--allow-insecure-localhost']
```

**Desktop (please complete the following information):**
 - OS: Win10 & VM Ubuntu (Not OS specific issue)
 - Browser: Firefox, Edge, Webkit (Safari)
 - Version: latest browser versions in Playwright

**Additional context**
This does not provide solution, but is similar issue: https://github.com/microsoft/playwright/issues/802
Any documentation or solution helps.

**Comment by mkorpela** [comment]
Thank you for the issue. Self signed certificates are a common issue and we have to think about how to best handle this case.

**Comment by aaltat** [comment]
I self signed certs and made a simple https server:
```
from http.server import HTTPServer, BaseHTTPRequestHandler
import ssl


class SimpleHTTPRequestHandler(BaseHTTPRequestHandler):

    def do_GET(self):
        self.send_response(200)
        self.end_headers()
        self.wfile.write(b'Hello, world!')


httpd = HTTPServer(('localhost', 4443), SimpleHTTPRequestHandler)

httpd.socket = ssl.wrap_socket(
    httpd.socket,
    keyfile="key.pem",
    certfile="cert.pem",
    server_side=True
)

httpd.serve_forever()
```
Then I did run this one
```
*** Settings ***
Library           Browser

*** Test Cases ***
Test Cert chromium
    New Browser     chromium
    New Context     ignoreHTTPSErrors=True
    New Page        https://localhost:4443/
    Take Screenshot

Test Cert firefox
    New Browser     firefox
    New Context     ignoreHTTPSErrors=True
    New Page        https://localhost:4443/
    Take Screenshot

Test Cert webkit
    New Browser     webkit
    New Context     ignoreHTTPSErrors=True
    New Page        https://localhost:4443/
    Take Screenshot
```
Webkit did not work because in my Ubuntu Webkit is missing some dependency and it does not lunch with. But chrommium and Firefox did work normally. We did have discussion in Slack and @Snooz82 had an idea that [automatic closing](https://marketsquare.github.io/robotframework-browser/Browser.html#Automatic%20page%20and%20context%20closing) feature is causing the problem. You could try change the auto_closing_level to MANUAL or SUITE.

**Comment by aaltat** [comment]
Because this work as expected, I am closing this issue.
