### ISSUE TITLE
The argument 'saveAs' of 'Wait For Download' is not working

### ISSUE THREAD

**Issue by estimation** [MarketSquare/robotframework-browser#501]
**Describe the bug**
The argument 'saveAs' of keyword 'Wait For Download' is not working.

**To Reproduce**

> *** Settings ***
Library    OperatingSystem
Library    Browser    timeout=20s    enable_playwright_debug=true    auto_closing_level=MANUAL
*** Variables ***
${dwl}    c:${/}temp${/}npp
${url}    https://notepad-plus-plus.org/downloads/v7.9.1/
*** Test Cases ***
TC01 Download NPP
    New Browser    chromium    headless=false    downloadsPath=${dwl}
    New Context    acceptDownloads=${TRUE}
    New Page
    Go To    ${url}
    ${dwl_promise}    Promise To    Wait For Download    saveAs=npp7.exe
    Click    //*[@id="main"]/p[5]/a
    ${file_path}=    Wait For    ${dwl_promise}
    File Should Exist    ${file_path}
    Log    ${file_path}

**Expected behavior**
File should be downloaded successfully and saved with name 'npp7.exe'

**Screenshots**
File downloaded succefully, but the name is incorrect.
![image](https://user-images.githubusercontent.com/16793171/99026987-2a0a0d00-25a7-11eb-96b4-0ca666526008.png)
Though download location of chrome browser is not changed to 'C:/temp/npp' I specified in the script, but the file was actually downloaded in the folder
![image](https://user-images.githubusercontent.com/16793171/99027245-b61c3480-25a7-11eb-9cc7-b5df3c00af52.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome
 - Version: 88.0.4287.0
 - Browser library: 2.1.0

**Comment by aaltat** [comment]
There is bug, but the bug is in the documentation. `saveAs` argument does not define the filename, as the documentation incorrectly claims, but it defines a path where the file is saved. The enhancement in https://github.com/MarketSquare/robotframework-browser/issues/597 in next release will change the functionality and return also the suggested filename from the browser/web app.

**Comment by aaltat** [comment]
@all-contributors please add @estimation for userTesting
