### ISSUE TITLE
robotframework-browser not available on pypi ? On purpose

### ISSUE THREAD

**Issue by emakaay** [MarketSquare/robotframework-browser#516]
I would like to test the new version of browser.
But I could not find it on pypi.org, even after 3 days after release.

Possibly there is a reason for this, but normally you're quit swift with updating.

Any reason for the delay ?

I'm looking for version 2.2.0. this was not clear at first

**Comment by mkorpela** [comment]
Hi,
Common cause for not finding project from pypi is that only Python 3.7 or newer is supported.
Can you check you are accessing pypi from Python 3.7 or greater?

**Comment by aaltat** [comment]
I can't see the release in web pages https://pypi.org/project/robotframework-browser/#history

**Comment by emakaay** [comment]
I'm. Using python 3.7.3

But I'm not using pip install.

I was looking at: https://pypi.org/project/robotframework-browser/#history

It's not there!

I can't use pip install because of corporate restrictions. I only can
download from pypi.org. and install manually

**Comment by aaltat** [comment]
Our CI release task failed and therefore it's not in PyPi https://github.com/MarketSquare/robotframework-browser/actions/runs/372350280

**Comment by emakaay** [comment]
Can a rerun fix the missing artifact ?

**Comment by aaltat** [comment]
Would need reminding how that pipeline actually works and what failed, which is hard in mobile. Or we could do 2.2.1.

**Comment by emakaay** [comment]
Version 2.2.1 works for me

**Comment by mkorpela** [comment]
Thank you for the info! Pushed 2.2.0 to PyPI
