### ISSUE TITLE
Get rid of rfbrowser init

### ISSUE THREAD

**Issue by martinRenou** [MarketSquare/robotframework-browser#518]
I am currently making a conda package for robotframework-browser: https://github.com/conda-forge/staged-recipes/pull/13300

It should soon be possible for users to run the following in order to get it to work:
```
conda install -c conda-forge robotframework-browser
```

Note that this **does not** require nodejs to be installed on the user machine, which is convenient, because it's not required to run `rfbrowser init`.

In this issue, I would like to suggest getting rid of `rfbrowser init`. My idea is that we could run `npm install --production` in the `setup.py` directly, this would mean that:
- `pip install robotframework-browser` will be enough to get it to work
- it's not required any more that the user machine has `nodejs` installed, only the dev machine (when making the release or when making a dev install)

Please tell me what you think.

**Comment by aaltat** [comment]
Actually we have been thinking about install, but little bit differently. Have you seen https://github.com/MarketSquare/robotframework-browser/pull/478

**Comment by xylix** [comment]
I think running `npm install --production` in the setup.py directly would be an improvement for most of our users. 

However making `conda install` the only supported way to install robotframework-browser is a hard sell for pip-using users. 

Also with the current master, just running `npm install --production` on setup.py time wouldn't still enable users to run the project without node.js. It still needs node as a runtime dependency to execute the backend (see https://github.com/MarketSquare/robotframework-browser/blob/333504f976d5a8a3d30463c7a95f9804c0ea0544/Browser/playwright.py#L85 ). We have been looking into using `pkg` to remove the runtime dependency on node, and that is what most of the work at #478 is about.

**Comment by martinRenou** [comment]
> However making conda install the only supported way to install robotframework-browser is a hard sell for pip-using users

Sorry if I was not clear, I really not meant to say this.

If we run the `npm install --production` inside of the `setup.py`, then no need for users to run `rfbrowser init` on their machine anymore.

Then they only need to run `pip install` or `conda install` to get it working.

> time wouldn't still enable users to run the project without node

I see, I missed this. I will need to update the conda package and put `nodejs` as a runtime dependency then.

> We have been looking into using pkg to remove the runtime dependency on node, and that is what most of the work at #478 is about.

Interesting, I did not know about `pkg`. So instead of shipping the entire `node_modules` you would be shipping a single binary containing all your JS code?

**Comment by martinRenou** [comment]
Sorry, I see this issue is actually a duplicate of #465

**Comment by xylix** [comment]
@martinRenou Yeah pkg achieves shipping of a single binary containing all JS code and a bundled node runtime.
