### ISSUE TITLE
AttributeError: module 'google.protobuf.descriptor' has no attribute '_internal_create_key' when running rfbrowser init

### ISSUE THREAD

**Issue by vikitech83** [MarketSquare/robotframework-browser#530]
**Describe the bug**
AttributeError: module 'google.protobuf.descriptor' has no attribute '_internal_create_key' when running rfbrowser init

**To Reproduce**
1. setup Ubuntu 20.04.1 LTS
and Python 3.8.5

**Expected behavior**
rf browser should work
but :
.local/lib/python3.8/site-packages/Browser/generated/playwright_pb2.py", line 21, in <module>
    create_key=_descriptor._internal_create_key,
AttributeError: module 'google.protobuf.descriptor' has no attribute '_internal_create_key'

**Comment by mkorpela** [comment]
This was fixed in 2.3.3. Thank you for the report!
