### ISSUE TITLE
Implement / document how users can affect elements in iframes through playwright's selectors

### ISSUE THREAD

**Issue by xylix** [MarketSquare/robotframework-browser#54]
Work on testing this functionality started and tests are currently on master as skipped tests. 

There is some unintuitive behaviour with `>>` and playwright's shadow dom piercing. Some of it is documented here https://github.com/microsoft/playwright/issues/1375#issuecomment-613682241

**Comment by yanne** [comment]
Implemented in 1b1b1fb98e082719ed3ea6bfba8e1a823936bf22
