### ISSUE TITLE
Rename `text=` argument of Fill text

### ISSUE THREAD

**Issue by xylix** [MarketSquare/robotframework-browser#581]
Rename the argument to something that doesn't conflict with `Fill text  text=my_text_to_look_for` syntax

**Comment by mkorpela** [comment]
The text selector does not seem to match the text value of an input field.
What should this match?

**Comment by manykarim** [comment]
It can happen for cascading locators.
e.g. if a text label is next to your input field and you need to go one level up in the DOM you might have something like:
Fill text    text=Username >> .. >> input    Testuser

In such cases, you will get an error

**Comment by mkorpela** [comment]
Fixed in v4.0.0
