### ISSUE TITLE
Wait For Download should also allow browser suggested filename

### ISSUE THREAD

**Issue by adrian-evo** [MarketSquare/robotframework-browser#597]
**Is your feature request related to a problem? Please describe.**
Currently with Wait For Download keyword it is only possible to download with a custom name (saveAs argument) or random guid.

**Describe the solution you'd like**
The issue is similar with Playwright issue: https://github.com/microsoft/playwright/issues/2058 where the proposed solution was to use download.suggestedFilename()

The enhanced **Wait For Download** keyword, would allow for saveAs argument a special string to save with suggested filename, e.g. **Wait For Download**  _saveAs=DEFAULT_

**Describe alternatives you've considered**
As altenative I implemented a jsextension with a custom keyword **Wait For Download With File Name** that is returning a list with downloaded file path and suggested filename, that can be used in Robot Framework to rename the file. But obviously an integrated functionality in Browser library would be more elegant:

https://github.com/adrian-evo/robotframework-browser-extension

**Additional context**
In my web applications that I am testing (industrial web configurator for electrical motors and other industrial components), it is very important to check if the downloads respect certain naming conventions, e.g. like motors datasheets.

**Comment by aaltat** [comment]
I am not fan of magic string, because they can collide with excising implementation. But we can expose it to return based on new argument.

**Comment by aaltat** [comment]
After discussing the with rest of the team we decided to change the default implementation so that it will always return a dictionary which contains path where the file is saved and the suggested filename. Therefore added the bicwic label.
