### ISSUE TITLE
Could not connect to the playwright process

### ISSUE THREAD

**Issue by DrVanScott** [MarketSquare/robotframework-browser#599]
**Describe the bug**
I have a working test scenario using your docker image, running robot. The same setup on a differen docker host leads to error messages

    Could not connect to the playwright process

and

```
<_InactiveRpcError of RPC that terminated with:
	status = StatusCode.UNAVAILABLE
	details = "failed to connect to all addresses"
	debug_error_string = "{"created":"@1608286023.662143927","description":"Failed to pick subchannel","file":"src/core/ext/filters/client_channel/client_channel.cc","file_line":4165,"referenced_errors":[{"created":"@1608286023.662136260","description":"failed to connect to all addresses","file":"src/core/ext/filters/client_channel/lb_policy/pick_first/pick_first.cc","file_line":397,"grpc_status":14}]}"
>
```

Just in case this could be somehow related to IPv6: The working docker host has a ipv6 stack (at least /proc/sys/net/ipv6 exists), the non-working docker host does not have this key, only ipv4

Can you please give some advice how to dig deeper in that issue. How can i provide more information?

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.04, headless
 - Browser [chrome]
 - rfbrowser-stable:v2.4.0

**Comment by aaltat** [comment]
Is this a problem with latest release or can we close the issue?

**Comment by DrVanScott** [comment]
This is with the docker image v2.4.0. I can check with the latest one and will come back with the results in a few days...

**Comment by DrVanScott** [comment]
I've just checked this with v3.0.1 and the issue is still the same. Do you have an idea how to provide more information?

**Comment by DrVanScott** [comment]
Exporting these variables


    GRRPC_TRACE=all
    GRPC_VERBOSITY=debug

helped me to find out the root cause. The failing docker host had been configured to export "http_proxy" variables to the containers. grpc seems to use this proxy even for localhost. Explicitly unsetting http(s)_proxy solved the problem for me.

**Comment by aaltat** [comment]
Thank you for your investigation. I guess we can close the issue now?
