### ISSUE TITLE
Improve select list functionality

### ISSUE THREAD

**Issue by anton264** [MarketSquare/robotframework-browser#608]
**Is your feature request related to a problem? Please describe.**
In the old seleniumlibrary checking list items was pretty easy since you could get every list item in a @{list} like so:
```   
 ${theList}    Get List Items    id:cars
    Length Should Be    ${theList}    4
    Should Contain    ${theList}    Volvo
    Should Contain    ${theList}    Saab
    Should Contain    ${theList}    Mercedes
    Should Contain    ${theList}    Audi
```
Example html:
```
<label for="cars">Choose a car:</label>
<select name="cars" id="cars">
  <option value="volvo">Volvo</option>
  <option value="saab">Saab</option>
  <option value="mercedes">Mercedes</option>
  <option value="audi">Audi</option>
</select>
```

This is hard to replicate in browser library since keyword `Get Selected Options` forces you to select an option.

**Describe the solution you'd like**
A solution like this should work, right now it just returns `none`

```
*** Settings ***
Library        Browser
*** Test Cases ***
List
    New Browser        headless=False   
    New Page    file:///list.html
    ${list}    Get Selected Options    id=cars    text
    Log To Console    ${list}
```

**Describe alternatives you've considered**
Using `Get Text` will return all the items but they are not list-like, just a string separated by newlines. It might be an option to have that return a list if there are several items.

**Comment by aaltat** [comment]
I do not quite see the problem, the [Get Select Options](https://marketsquare.github.io/robotframework-browser/Browser.html#Get%20Select%20Options) returns a list selects. The [Get Selected Options](https://marketsquare.github.io/robotframework-browser/Browser.html#Get%20Selected%20Options) only selected options. 

Also it is possible to do something like this: 
`Get Select Options    id=cars    validate    [v["label"] for v in value] == ["Volvo", "Saab", "Mercedes", "Audi"]`

Which in SeleniumLibrary translates to this one:
```
   ${theList}    Get List Items    id:cars
    Length Should Be    ${theList}    4
    Should Contain    ${theList}    Volvo
    Should Contain    ${theList}    Saab
    Should Contain    ${theList}    Mercedes
    Should Contain    ${theList}    Audi
