### ISSUE TITLE
Enum completion must have a type annotation

### ISSUE THREAD

**Issue by mkorpela** [MarketSquare/robotframework-browser#61]
Enum conversion will not happen correctly without type annotation.
Right:
`assertion_operator: AssertionOperator = AssertionOperator.NO_ASSERTION`
Wrong:
`assertion_operator = AssertionOperator.NO_ASSERTION`

**Comment by mkorpela** [comment]
Run keyword and expect error test required

**Comment by xylix** [comment]
I guess we would need a keyword that does the `wrong` thing to be able to have a test for this?

**Comment by mkorpela** [comment]
Yep. Some `Run Keyword and expect error  Get Title  ValueError: Argument 'assertion_operator' got value 'wrong'*  wrong  thing`

**Comment by xylix** [comment]
```
Expect Enum Conversion Fails
    Run Keyword and expect error	""  Get Title  ==  "abc"
```
This test doesn't fail with a `AttributeError: 'str' object has no attribute 'name'`, instead == gets converted correctly. Even though the signature of `Get Title` is 
```    
    @keyword
    def get_title(
        self,
        assertion_operator=AssertionOperator.NO_ASSERTION,
        assertion_value: Any = None,
    ):
```

**Comment by mkorpela** [comment]
Yep. It must be `assertion_operator: AssertionOperator = AssertionOperator.NO_ASSERTION` for now. Until libcorething is fixed. After that Optional

**Comment by mkorpela** [comment]
The thing https://github.com/robotframework/PythonLibCore/issues/64

**Comment by xylix** [comment]
No my point was that the `Get Title` assertion_operator type is in the `wrong` way. But it works correctly. Trying to run 
`Get Title  NO_ASSERTION` in robot test also works correctly, so it does cast the enum correctly.

I thanks I misunderstood what kind of test you were referring to in `Run keyword and expect error test required`. The examples on the thread's first message don't have Optional at all, and that was the only type conversion problem I was aware of.
