### ISSUE TITLE
Cannot send RegExp as argument to a JavaScript extension, for example as url for waitForNavigation function

### ISSUE THREAD

**Issue by adrian-evo** [MarketSquare/robotframework-browser#616]
I would need the following type of keyword that is missing from Browser library:
```
async function waitForNavigation(page, args, logger) {
  logger(args[0]);
  await page.waitForNavigation({
    url: args[0],
  });
  return await page.title();
}
```
```
  Go To  https://www.google.com
  Click  text=Sign in
  # Wait For Navigation  https://accounts.google.com/signin/v2...
  Wait For Navigation  /.*signin.*/

```
- When passing the complete url string as argument from Robot Framework (e.g. https://accounts.google.com/signin/v2...), the keyword passes.
- When passing a RegExp as argument from Robot Framework (e.g. /.*signin.*/), the keyword fails.

However, when the extension is modified as following:
```
  await page.waitForNavigation({
    url: /.*signin.*/,
  });
```
which means ignoring the argument and passing the same RegExp directly in the function, the keyword passes.

Is this an issue or maybe I am missing something in the way how to pass such arguments to a JS extension?

**Comment by mkorpela** [comment]
All args in RF are by default strings. There is no native support for Regexps. So I would at this point say that it is working as expected.

Good point anyway that the type could be somehow communicated from JS to RF side.

**Comment by adrian-evo** [comment]
Thanks, quite clear now. It means for now that I will assume the first argument is always a RegExp and convert it accordingly in the extension function. It works in this way.
