### ISSUE TITLE
Support custom locator to locate element

### ISSUE THREAD

**Issue by lynhbn** [MarketSquare/robotframework-browser#619]
**Is your feature request related to a problem? Please describe.**
Support custom locator to locate element

**Describe the solution you'd like**
In SeleniumLibrary, we can use the keyword "Add locator strategy" to register a custom locator approach using a custom keyword that returns a WebElement.

Then we can use it like `Click Element | custom:example`

Please support this feature, since this one is crucial & widely used.

Thank you so much!

**Comment by mkorpela** [comment]
Hi @lynhbn
Could you give a concrete example custom locator strategy?
This would help us to validate that our approach will work for you.

**Comment by lynhbn** [comment]
> Hi @lynhbn
> Could you give a concrete example custom locator strategy?
> This would help us to validate that our approach will work for you.

In my project, I'm using custom locator to locate every elements rather than using CSS class or element id...
I'm using their labels to determine which element is being pointed to.

For example, the page currently is having some textboxes:
Customer Name: [____________________]
Customer Address: [____________________]

Then I will write a custom locator named "item" to locate the corresponding textboxes using their own labels:
`Click Element | item:Customer Name`
`Click Element | item:Customer Address`
This approach works pretty well in many cases & reduce effort for inspecting elements to find their HTML attributes. Moreover, I can also verify their labels to check whether they are correct or not.

SeleniumLibrary supports it. I hope you guys can also support it.

**Comment by xylix** [comment]
Specifically for labels we might even want to implement it ourselves. 

But adding support for simple strategies should be quite easy. Playwright provides an API we could make use of on Browser side.

**Comment by mkorpela** [comment]
```RobotFramework
*** Test Cases ***
testing
    ${forName}=  Get Attribute  text=User Name:  for
    type text  input#${forName}   moi
```

**Comment by mkorpela** [comment]
This is possible with js extensions: see "Example module keyword for custom selector registering" from https://marketsquare.github.io/robotframework-browser/Browser.html
