### ISSUE TITLE
How to go to an url that is directly downloading a document

### ISSUE THREAD

**Issue by adrian-evo** [MarketSquare/robotframework-browser#620]
**Is your feature request related to a problem? Please describe.**
I would need to go to an Url that is not loading a web page, but instead it is just downloading e.g. a pdf or zip file.
With the current implementation, in such case the Go To keyword is throwing ERR_ABORTED

**Describe the solution you'd like**
Ideally, `Go To` keyword should not throw an error if the result of the navigation is a downloaded document instead of loading a page. The same is working fine on SeleniumLibrary.

**Describe alternatives you've considered**
Fortunately this can be solved with a custom extension keyword:

```
async function goToDocument(page, args, logger) {
  try {
    await page.goto(args[0],{
	  		waitUntil: 'networkidle',  
    });
  }
  catch (ERR_ABORTED) {
	logger('Catch ERR_ABORTED')
  }
  return await page.title();
}

```

**Comment by aaltat** [comment]
Have you seen this https://marketsquare.github.io/robotframework-browser/Browser.html#Download ?

**Comment by adrian-evo** [comment]
Thanks, indeed didn't noticed that keyword. I guess I was used to selenium go to keyword since the user would do the same in the browser.

However, I tried and noticed the downloaded filename is not the suggested one by browser, the same issue as #597, so I cannot use it. I guess it makes sense that this keyword is implemented the same way that Wait For Download?

**Comment by aaltat** [comment]
Yes we should change this in same way as Wait For Download.

**Comment by aaltat** [comment]
I am going to close this one in favor of #642 To get cleaner history
