### ISSUE TITLE
Add support for 'does not contain' to mimic seleniumLibrary keyword 'Element Should Not Contain'

### ISSUE THREAD

**Issue by emakaay** [MarketSquare/robotframework-browser#659]
The assertion engine used at keywords like get text, can't perform 'does not contain'. 

At this moment I I can't convert mentioned selenium keyword (in a nice manner).
I'm able to do this in an 'validate' expression, but I think this is too technical to use for most testers

**Comment by leeuwe** [comment]
fixed in: https://github.com/MarketSquare/AssertionEngine/pull/12
Not yet in this repository

**Comment by aaltat** [comment]
Not yet, but using AssertionEngine as a dependency for this project and cleaning old code is next on the todo list for me. Just need to find time to do it.

**Comment by leeuwe** [comment]
I know, just marking progess in case anyone already wants to adopt it. I'll be patient!

**Comment by emakaay** [comment]
@aaltat 
With version 4.0.1 of robotframework-browser this is fixed.

I can do Get Text <selector> not contains <something>. Perfect!

One little niggle.  When looking at the documentation of Get Text and click on "Assertions", there is no notion of "not contains". When you click on the link "AssertionOperator", there a notion of "not contains"

**Comment by aaltat** [comment]
The doc problem is fixed in #863. But because this actually done and ready [assertion engine](https://github.com/aaltat/AssertionEngine) side, I am closing this issue.
