### ISSUE TITLE
Auto closing and closing should log more explicitly

### ISSUE THREAD

**Issue by xylix** [MarketSquare/robotframework-browser#664]
- Auto closing should WARN on never used Browsers and Contexts
  - When non-used objects are made 
  - [ ] Maybe also document pages that have no operations executed on them
- On New Page and New Context implicit browser / context openings should have INFO prints when it happens

**Comment by aaltat** [comment]
Also it might be good log something if new page opens new browser and context. It would help on many situations.

**Comment by aaltat** [comment]
The #918 logs in the `New Page` keyword If browser and/or content was created automatically in info level. Also `New Context` keyword logs if browser was created automatically.

**Comment by mkorpela** [comment]
Something wrong with GH Actions.. failed on my machine.

**Comment by aaltat** [comment]
I am going to split this issue. Now there is logging if new browser and/or context is opened implicitly. But auto closing side is not done. See #974

**Comment by mkorpela** [comment]
Logging in auto closing seems hard as RF does not keep logging outside of keywords.

**Comment by aaltat** [comment]
I have not seen problem with this for a while. I think it is time to close and we can always return to the issue if user report problems.
