### ISSUE TITLE
Screenshot urls are not matching in pabot logs

### ISSUE THREAD

**Issue by pokaalinkanssayohon** [MarketSquare/robotframework-browser#669]
When executing browser extension with pabot, screenshot url includes pabot process id (e.g. 0 or 1) and url in log.html doesn't contain this pabot prosess id.
Workspace file: 1-TC1_FAILURE_SCREENSHOT_1.png
Url in log.html: TC1_FAILURE_SCREENSHOT_1.png

**To Reproduce**
1. Execute test case which fails by using pabot

**Expected behavior**
Url in log.html should match with workspace file

**Screenshots**

**Desktop (please complete the following information):**
 - OS: robotframework-browser docker container and same behavior in macOS 10.15.7
 - Browser [chromium]
 - robotframework-browser: 3.0.0.
[](url)

**Comment by pokaalinkanssayohon** [comment]
I was comparing results to pabot with selenium hub+nodes setup and there are screenshot url's ok. On the other hand, screenshot url's are in pabot with selenium hub+nodes same (including these pabot process id's) but url's in log.html are correct ones. Is this behavior/bug in pabot/robot instead of browser extension?

**Comment by pokaalinkanssayohon** [comment]
![Screen Shot 2021-01-18 at 12 53 08](https://user-images.githubusercontent.com/34340500/104909159-22445b80-5990-11eb-9894-644eece7e495.png)
![Screen Shot 2021-01-18 at 12 53 58](https://user-images.githubusercontent.com/34340500/104909172-25d7e280-5990-11eb-8cbe-b23677677fc2.png)

**Comment by pokaalinkanssayohon** [comment]
![Screen Shot 2021-01-18 at 12 53 58](https://user-images.githubusercontent.com/34340500/104909629-cdedab80-5990-11eb-94d7-aa5749090def.png)

**Comment by mkorpela** [comment]
This is pabot behaviour. It is renaming screenshot files during log composing.

**Comment by pokaalinkanssayohon** [comment]
Ok, what might be the reason, that log.html file has different url with browser vs selenium?

**Comment by aaltat** [comment]
Perhaps you are using older Pabot version which does not yet have this feature. Another option is that you are not using feature correctly. Example we use Pabot to [transfer ](https://github.com/MarketSquare/robotframework-browser/blob/master/tasks.py#L311-L313) `png` and `webm` files from subfolders. Please check your configurations.

In any case this is pabot feature and nothing to with Browser library and therefore I am closing this issue.
