### ISSUE TITLE
Question. How to convert (Selenium) Simulate Event to robotframework-browser

### ISSUE THREAD

**Issue by emakaay** [MarketSquare/robotframework-browser#670]
Hello,

I'm converting a selenium based project to robotframework-browser.

I encounter the following line of code:
`Simulate Event     id=someId     change`

How would I rewrite that in browser ?I tried: 
`Browser.Execute JavaScript    (element) => element.change()     id=someId`

But that doesn't work. Any suggestions?

**Comment by aaltat** [comment]
In SeleniumLibrary it is based on custom [JS execution](https://github.com/robotframework/SeleniumLibrary/blob/1705cf8bb7091e8d1161871fc932f9934ef69f6f/src/SeleniumLibrary/keywords/element.py#L880-L891) I think you can create [custom keyword in JS](https://marketsquare.github.io/robotframework-browser/Browser.html#Extending%20Browser%20library%20with%20a%20JavaScript%20module) which does the same thing.

**Comment by aaltat** [comment]
Closing issue.

**Comment by emakaay** [comment]
(For someone who has the same problem)
Eventually I used the following code:
Browser.Execute JavaScript    (elem) => {elem.change}    id=someId

So I was close all along :)
