### ISSUE TITLE
Unable to extend the  docker images

### ISSUE THREAD

**Issue by wanghui-00** [MarketSquare/robotframework-browser#679]
**Describe the bug**
when I tried to extend the docker images, and install some linux package, the user of pwuser is Permission denied

**To Reproduce**
1. docker run -it marketsquare/robotframework-browser /bin/bash
2. pwuser@000bf67f668a:/$ apt-get install gettext-base
    E: Could not open lock file /var/lib/dpkg/lock-frontend - open (13: Permission denied)
   E: Unable to acquire the dpkg frontend lock (/var/lib/dpkg/lock-frontend), are you root?
3.  pwuser@000bf67f668a:/$ su root
    Password:
  the password is unknown to us, also sudo command is not supported
**Expected behavior**
I can change the user to root, and install the package I wanted.

**Screenshots**

**Desktop (please complete the following information):**
 - win10
 - Browser [chrome]

**Comment by xylix** [comment]
You should use a Dockerfile to extend the image.

For example
```Dockerfile
FROM marketsquare/robotframework-browser:latest
USER root
RUN apt-get install gettext-base
USER pwuser
```
should work.


For actually logging in as root, it might be possible using docker runs `--workdir` argument. See https://github.com/oracle/docker-images/issues/1336#issuecomment-530789709 for reference.

But the recommendation is to create your own Dockerfile to extend the image.

**Comment by wanghui-00** [comment]
Thanks so much, @xylix  I have successfully extend the images by create my own Dockerfile

**Comment by wanghui-00** [comment]
close
