### ISSUE TITLE
How to wait for accepted / dismissed Dialog

### ISSUE THREAD

**Issue by emakaay** [MarketSquare/robotframework-browser#680]
**Is your feature request related to a problem? Please describe.**
I have the following test-scenario:

- I have a list with 1 item
- When I select an item from that list, I can delete it by pressing a delete button.
- Pressing the Delete button will result in a confirmation dialog box.
- After ok is pressed in this dialog box, I would like to check if  row is gone.

Therefore I'v written the following test code(assuming the table is shown):
```
Handle Future Dialogs    accept
Browser.Click     ${delete.button}
${rows}    Get Element Count    //*[@id='tableId']//table/tbody/tr
Should be True    ${rows} == 0

```

Problem with this solution is that I query the table too soon.
It is possible that the table is queried when the dialog still has to be 'accepted'.
Resulting in a failing test, because the number of elements is still unequal to zero. It is in fact 1.

I fixed this with the following code:
```
Handle Future Dialogs    accept
Browser.Click     ${delete.button}
Wait Until Network Is Idle
${rows}    Get Element Count    //*[@id='tableId']//table/tbody/tr
Should be True    ${rows} == 0

```
This works, but introduces (possibly) a long waittime of at least 500ms (the minimum wait time of the Wait Until Network). The only reason why I choose this solution is because I could not find a solution with a promise.

I had the following promise code:
```
${promise}    Promise To    Handle Future Dialogs    accept
Browser.Click     ${delete.button}
Wait For    ${promise}
${rows}    Get Element Count    //*[@id='tableId']//table/tbody/tr
Should be True    ${rows} == 0

```
But after seeing that this didn't work I realised you can only use promises on actual actions. Handle Future Dialogs is something that will or will not occur. But not the actual action.

**My Question is, what is the most optimal way to wait for a handled Dialog ?**

**Comment by aaltat** [comment]
I think this should work: 
```
Handle Future Dialogs    accept
Browser.Click     ${delete.button}
${rows}    Get Element Count    //*[@id='tableId']//table/tbody/tr    0
```

**Comment by emakaay** [comment]
Will try this tomorrow.

Thanks for fast response

**Comment by emakaay** [comment]
this worked!
