### ISSUE TITLE
Error installing robotframework-browser 3.1.0

### ISSUE THREAD

**Issue by emakaay** [MarketSquare/robotframework-browser#682]
**Describe the bug**
got error after upgrading robotframework-browser from 3.0.1 to 3.1.0.
Normally upgrading is quite easy, but it had problems executing: 'rfbrowser init'.

When I encountered this, I deinstalled robotframework-browser using the command: pip uninstall robotframework-browser, and deleted c:\python37\lib\site-packages\Browser afterwards to remove all node modules.

Then I installed robotframework-browser again and executed ' rfbrowser init'  again, but still with an error.

Any Ideas ? (note: after this I also cleaned the npm cache and tried again. It didn't help. (location: c:\Users\user\AppData\Local\npm-cache\)

Using node 14.15.1, and npm 7.0.7

```
rfbrowser init
Installing node dependencies...
Installing rfbrowser node dependencies at c:\python37\lib\site-packages\Browser\wrapper
npm ERR! code ERESOLVE

npm ERR! ERESOLVE unable to resolve dependency tree

npm ERR!

npm ERR! While resolving: robotframework-playwright@3.1.0

npm ERR! Found: @typescript-eslint/parser@3.10.1

npm ERR! node_modules/@typescript-eslint/parser

npm ERR!   dev @typescript-eslint/parser@"^3.10.1" from the root project

npm ERR!

npm ERR! Could not resolve dependency:

npm ERR! peer @typescript-eslint/parser@"^4.0.0" from @typescript-eslint/eslint-plugin@4.14.0

npm ERR! node_modules/@typescript-eslint/eslint-plugin

npm ERR!   dev @typescript-eslint/eslint-plugin@"^4.0.0" from the root project

npm ERR!

npm ERR! Fix the upstream dependency conflict, or retry

npm ERR! this command with --force, or --legacy-peer-deps

npm ERR! to accept an incorrect (and potentially broken) dependency resolution.

npm ERR!

npm ERR! See C:\Users\user\AppData\Local\npm-cache\eresolve-report.txt for a full report.



npm ERR! A complete log of this run can be found in:

npm ERR!     C:\Users\user\AppData\Local\npm-cache\_logs\2021-01-21T21_19_36_147Z-debug.log





Traceback (most recent call last):
  File "c:\python37\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\python37\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Python37\Scripts\rfbrowser.exe\__main__.py", line 7, in <module>
  File "c:\python37\lib\site-packages\Browser\entry.py", line 39, in run
    rfbrowser_init(arg2 == "--skip-browsers")
  File "c:\python37\lib\site-packages\Browser\entry.py", line 104, in rfbrowser_init
    + f"Node process returned with exit status {process.returncode}"
RuntimeError: Problem installing node dependencies.Node process returned with exit status 1
```

The content of: C:\Users\user\AppData\Local\npm-cache\eresolve-report.txt for a full report.
```
# npm resolution error report

2021-01-21T21:19:36.142Z

While resolving: robotframework-playwright@3.1.0
Found: @typescript-eslint/parser@3.10.1
node_modules/@typescript-eslint/parser
  dev @typescript-eslint/parser@"^3.10.1" from the root project

Could not resolve dependency:
peer @typescript-eslint/parser@"^4.0.0" from @typescript-eslint/eslint-plugin@4.14.0
node_modules/@typescript-eslint/eslint-plugin
  dev @typescript-eslint/eslint-plugin@"^4.0.0" from the root project

Fix the upstream dependency conflict, or retry
this command with --force, or --legacy-peer-deps
to accept an incorrect (and potentially broken) dependency resolution.

Raw JSON explanation object:

{
  "code": "ERESOLVE",
  "current": {
    "name": "@typescript-eslint/parser",
    "version": "3.10.1",
    "whileInstalling": {
      "name": "robotframework-playwright",
      "version": "3.1.0",
      "path": "c:\\python37\\lib\\site-packages\\Browser\\wrapper"
    },
    "location": "node_modules/@typescript-eslint/parser",
    "dependents": [
      {
        "type": "dev",
        "name": "@typescript-eslint/parser",
        "spec": "^3.10.1",
        "from": {
          "location": "c:\\python37\\lib\\site-packages\\Browser\\wrapper"
        }
      }
    ]
  },
  "edge": {
    "type": "peer",
    "name": "@typescript-eslint/parser",
    "spec": "^4.0.0",
    "error": "INVALID",
    "from": {
      "name": "@typescript-eslint/eslint-plugin",
      "version": "4.14.0",
      "whileInstalling": {
        "name": "robotframework-playwright",
        "version": "3.1.0",
        "path": "c:\\python37\\lib\\site-packages\\Browser\\wrapper"
      },
      "location": "node_modules/@typescript-eslint/eslint-plugin",
      "dependents": [
        {
          "type": "dev",
          "name": "@typescript-eslint/eslint-plugin",
          "spec": "^4.0.0",
          "from": {
            "location": "c:\\python37\\lib\\site-packages\\Browser\\wrapper"
          }
        }
      ]
    }
  },
  "peerConflict": null,
  "strictPeerDeps": false,
  "force": false
} 
```

The content of: C:\Users\user\AppData\Local\npm-cache\_logs\2021-01-21T21_19_36_147Z-debug.log 
`0 verbose cli [
0 verbose cli   'C:\\Program Files\\nodejs\\node.exe',
0 verbose cli   'C:\\Users\\emaka\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js',
0 verbose cli   'install',
0 verbose cli   '--production'
0 verbose cli ]
1 info using npm@7.0.7
2 info using node@v14.15.1
3 timing config:load:defaults Completed in 1ms
4 timing config:load:file:C:\Users\emaka\AppData\Roaming\npm\node_modules\npm\npmrc Completed in 1ms
5 timing config:load:builtin Completed in 1ms
6 timing config:load:cli Completed in 2ms
7 timing config:load:env Completed in 1ms
8 timing config:load:file:c:\python37\lib\site-packages\Browser\wrapper\.npmrc Completed in 0ms
9 timing config:load:project Completed in 1ms
10 timing config:load:file:C:\Users\emaka\.npmrc Completed in 0ms
11 timing config:load:user Completed in 0ms
12 timing config:load:file:C:\Program Files\nodejs\etc\npmrc Completed in 1ms
13 timing config:load:global Completed in 1ms
14 timing config:load:cafile Completed in 0ms
15 timing config:load:validate Completed in 0ms
16 timing config:load:setUserAgent Completed in 1ms
17 timing config:load:setEnvs Completed in 1ms
18 timing config:load Completed in 9ms
19 verbose npm-session 03806fc7d46b6aa6
20 timing npm:load Completed in 20ms
21 timing arborist:ctor Completed in 0ms
22 timing arborist:ctor Completed in 0ms
23 timing idealTree:init Completed in 21ms
24 timing idealTree:userRequests Completed in 0ms
25 silly idealTree buildDeps
26 silly fetch manifest @grpc/grpc-js@^1.2.4
27 http fetch GET 304 https://registry.npmjs.org/@grpc%2fgrpc-js 225ms (from cache)
28 silly fetch manifest @types/uuid@^8.3.0
29 http fetch GET 200 https://registry.npmjs.org/@types%2fuuid 79ms
30 silly fetch manifest google-protobuf@3.14.0
31 http fetch GET 200 https://registry.npmjs.org/google-protobuf 68ms
32 silly fetch manifest playwright@^1.8.0
33 http fetch GET 200 https://registry.npmjs.org/playwright 37ms (from cache)
34 silly fetch manifest uuid@^8.3.2
35 http fetch GET 200 https://registry.npmjs.org/uuid 48ms
36 silly fetch manifest @types/express@^4.17.11
37 http fetch GET 304 https://registry.npmjs.org/@types%2fexpress 54ms (from cache)
38 silly fetch manifest @types/pino@^6.3.5
39 http fetch GET 304 https://registry.npmjs.org/@types%2fpino 80ms (from cache)
40 silly fetch manifest @types/react@^17.0.0
41 http fetch GET 304 https://registry.npmjs.org/@types%2freact 70ms (from cache)
42 silly fetch manifest @types/react-dom@^17.0.0
43 http fetch GET 304 https://registry.npmjs.org/@types%2freact-dom 78ms (from cache)
44 silly fetch manifest @types/react-router-dom@^5.1.7
45 http fetch GET 304 https://registry.npmjs.org/@types%2freact-router-dom 67ms (from cache)
46 silly fetch manifest @typescript-eslint/eslint-plugin@^4.0.0
47 http fetch GET 304 https://registry.npmjs.org/@typescript-eslint%2feslint-plugin 118ms (from cache)
48 silly fetch manifest @typescript-eslint/parser@^3.10.1
49 http fetch GET 304 https://registry.npmjs.org/@typescript-eslint%2fparser 103ms (from cache)
50 silly fetch manifest eslint@^7.18.0
51 http fetch GET 304 https://registry.npmjs.org/eslint 44ms (from cache)
52 timing idealTree Completed in 1354ms
53 timing command:install Completed in 1360ms
54 verbose stack Error: unable to resolve dependency tree
54 verbose stack     at Arborist.[failPeerConflict] (C:\Users\emaka\AppData\Roaming\npm\node_modules\npm\node_modules\@npmcli\arborist\lib\arborist\build-ideal-tree.js:1015:25)
54 verbose stack     at Arborist.[loadPeerSet] (C:\Users\emaka\AppData\Roaming\npm\node_modules\npm\node_modules\@npmcli\arborist\lib\arborist\build-ideal-tree.js:995:36)
54 verbose stack     at async Arborist.[buildDepStep] (C:\Users\emaka\AppData\Roaming\npm\node_modules\npm\node_modules\@npmcli\arborist\lib\arborist\build-ideal-tree.js:761:11)
54 verbose stack     at async Arborist.buildIdealTree (C:\Users\emaka\AppData\Roaming\npm\node_modules\npm\node_modules\@npmcli\arborist\lib\arborist\build-ideal-tree.js:203:7)
54 verbose stack     at async Promise.all (index 1)
54 verbose stack     at async Arborist.reify (C:\Users\user\AppData\Roaming\npm\node_modules\npm\node_modules\@npmcli\arborist\lib\arborist\reify.js:121:5)
54 verbose stack     at async install (C:\Users\user\AppData\Roaming\npm\node_modules\npm\lib\install.js:38:5)
55 verbose cwd c:\python37\lib\site-packages\Browser\wrapper
56 verbose Windows_NT 10.0.19042
57 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\user\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "install" "--production"
58 verbose node v14.15.1
59 verbose npm  v7.0.7
60 error code ERESOLVE
61 error ERESOLVE unable to resolve dependency tree
62 error
63 error While resolving: robotframework-playwright@3.1.0
63 error Found: @typescript-eslint/parser@3.10.1
63 error node_modules/@typescript-eslint/parser
63 error   dev @typescript-eslint/parser@"^3.10.1" from the root project
63 error
63 error Could not resolve dependency:
63 error peer @typescript-eslint/parser@"^4.0.0" from @typescript-eslint/eslint-plugin@4.14.0
63 error node_modules/@typescript-eslint/eslint-plugin
63 error   dev @typescript-eslint/eslint-plugin@"^4.0.0" from the root project
63 error
63 error Fix the upstream dependency conflict, or retry
63 error this command with --force, or --legacy-peer-deps
63 error to accept an incorrect (and potentially broken) dependency resolution.
63 error
63 error See C:\Users\user\AppData\Local\npm-cache\eresolve-report.txt for a full report.
64 verbose exit 1
`

**Comment by aaltat** [comment]
Hmmm, could not reproduce the problem in Windows, but I am using node 12 and you are using 14. Needs more investigation, but it looks like some dependency problem in node side.

**Comment by emakaay** [comment]
I think so too. But don't know how to fix it.
Was really eager to test if the problem was fixed with the select options.

I saw that a fix was pushed to playwright 1.8.0, which is in this release

Have a nice evening,
Erik

**Comment by aaltat** [comment]
The quick options is to back to 3.0.1 release. If this turns out the be missing upstream problem, we should make new release which downgrades the dependency. But now I need some sleep.

**Comment by emakaay** [comment]
No problem. Get some sleep first..... I will do the same.

I was just testing on my private laptop first. No harm done.

But now I don't have playwright 1.8.0 😀

But that will come.... Eventually..... Baby steps

**Comment by mkorpela** [comment]
@emakaay: What is the NODE_ENV environmental variable value in your env?

**Comment by emakaay** [comment]
Hi Miko,

I don't have a NODE_ENV environment variable.
Should I have one ?

Erik

**Comment by mkorpela** [comment]
Hi Erik,
No you should not. I'm just trying to understand why it seems that the system is trying to install a development dependency when it should only install production related dependencies. The error comes from a mismatch between two linter versions. Might also be that it will automatically also report dependency errors anyway..

**Comment by emakaay** [comment]
I completely deinstalled nodejs and python.
Afterwards I installed the exact same versions and performed a 'rfbrowser init' 
That worked !

Fingers crossed when installation on pre-existing installations

**Comment by aaltat** [comment]
It is good that you got it working, but it would be nice to understand what was causing the error. 

But at least we did increase the node coverage for this and are using node 12 and node 14 in the CI. So that we would be able to better detect these kind of issues.

**Comment by emakaay** [comment]
Nice,

I saw that nodejs was used in combination with python 3.8 and 3.9, but not
3.7 ( the version I'm using). is this on purpose

**Comment by aaltat** [comment]
We do test with Python 3.7, 3,8 and 3,9 in [CI](https://github.com/MarketSquare/robotframework-browser/blob/master/.github/workflows/on-push.yml#L22), but we test installation with Python [3,8 and node 12&14](https://github.com/MarketSquare/robotframework-browser/blob/master/.github/workflows/on-push.yml#L100-L101). So both side should be now covered.

Python version should not affect the node version. Python is used to launch the node process to install playwright and other dependencies. Node side should not care how it is launched, should only look what it needs to install and where that stuff is going.

**Comment by emakaay** [comment]
I did not have any issue installing the new version of robotframework-browser on work environment.
For me.... this issue can be closed
