### ISSUE TITLE
Add support for recordHar when creating new context

### ISSUE THREAD

**Issue by aaltat** [MarketSquare/robotframework-browser#704]
Add support for Playwright recordHar option in New Context keyword. See details in PL [docs](https://playwright.dev/docs/api/class-browser?_highlight=recordha#browsernewcontextoptions)

This has been requested by users in Slack.

**Comment by mkorpela** [comment]
https://github.com/microsoft/playwright/issues/4928

**Comment by mkorpela** [comment]
https://github.com/MarketSquare/robotframework-browser/issues/634 <-- same but different
