### ISSUE TITLE
Add SeleniumLibrary Set Screenshot Directory keyword counterpart

### ISSUE THREAD

**Issue by Virvatuli** [MarketSquare/robotframework-browser#732]
**Is your feature request related to a problem? Please describe.**

I am working in a project, where we would like to redefine the output directory of **Take Screenshot** keyword. Currently the path can´t be changed. Therefore we would like the library to have a common keyword to set the screenshot directory path.

**Describe the solution you'd like**

A SeleniumLibrary [Set Screenshot Directory](https://robotframework.org/SeleniumLibrary/SeleniumLibrary.html#Set%20Screenshot%20Directory) keyword counterpart could to be added to Browser library. Then it would be possible to define needed screenshot related setting with two library keywords. Like this:

```
Configure Screenshot Settings
   Browser.Set Screenshot Directory    ${WANTED_SCREENSHOT_DIRECTORY_PATH}
   Browser.Take Screenshot             filename=robotframework-browser-screenshot-{index}
```
**Describe alternatives you've considered**

Adding a **path** argument to **Take Screenshot** keyword  could also be an option.

**Comment by leeuwe** [comment]
Hi @Virvatuli. In my experience `Browser.Take Screenshot` already takes a full path, meaning you can easily create your own userkeyword to achieve this, like:
```Make Screenshot
    [arguments]  ${filename}=robotframework-browser-screenshot-{index}  ${selector}=None
    ${ImgDir}=  Set Variable  ${EXECDIR}${/}mydir${/}
    Take Screenshot  ${ImgDir}${filename}  ${selector}

**Comment by Virvatuli** [comment]
@leeuwe Thank you for your reply and advice on this matter. I managed to implement your given solution to our project and it works nicely.  I didn´t realize you can do this by just reading the keyword's documentation, but I am still a beginner.

**Comment by aaltat** [comment]
SO we can close the issue?

**Comment by Virvatuli** [comment]
@aaltat You can close the issue, if there isn´t any other need for this SeleniumLibrary Set Screenshot Directory keyword counterpart. 

Otherwise it would be a good thing to add this use information of the screenshot output directory to the [Take Screenshot](https://marketsquare.github.io/robotframework-browser/Browser.html#Take%20Screenshot) documentation. Currently the path is only mentioned in the first sentence of keyword's documentation and the other relevant information is: _The file will be saved into the robot framework ${OUTPUTDIR}/browser/screenshot directory by default_. So, there could be more information on the path and it's use, since other beginners might also run into this puzzle.

**Comment by aaltat** [comment]
Improving documentation is always good idea.

**Comment by aaltat** [comment]
@all-contributors please add  Virvatuli for bug reporting.
