### ISSUE TITLE
rfbrowser init seems to fail when multiple python installs

### ISSUE THREAD

**Issue by mkorpela** [MarketSquare/robotframework-browser#746]
**Describe the bug**
More than one report from not finding browsers for example:
```
Error: browserType.launch: Failed to launch chromium because executable doesn't exist at /***/lib/python3.7/site-packages/Browser/wrapper/node_modules/playwright/.local-browsers/chromium-854489/chrome-linux/chrome
```

That are fixed by running `python -m Browser.entry init` although `rfbrowser init` has already been executed.
This seems to be because we are putting the browsers to custom locations that are inside the python installs.
When rfbrowser init is executed in the wrong python env than where they should be, then we are in trouble.

**Comment by aaltat** [comment]
Yes, this might happen due OS path issues. But using python -m Browser.entry init is documented and closing issue.
