### ISSUE TITLE
[Get Selected Options] keyword returns error "Error: page.$$eval: Evaluation failed: DOMException: Failed to execute 'evaluate' on 'Document': The string './/select[@name='brandCategory'] option' is not a valid XPath expression."

### ISSUE THREAD

**Issue by vuongvvv** [MarketSquare/robotframework-browser#757]
**Describe the bug**
[Get Selected Options] keyword returns error "Error: page.$$eval: Evaluation failed: DOMException: Failed to execute 'evaluate' on 'Document': The string './/select[@name='brandCategory'] option' is not a valid XPath expression."

**To Reproduce**
![2021-03-03_11-23-25](https://user-images.githubusercontent.com/23648562/109752635-565b9f00-7c13-11eb-9b0b-16a6113ab4ad.jpg)

1. `Get Selected Options    selector=//select[@name='brandCategory']           option_attribute =label        assertion_operator=equal          Food & Drink`

**Expected behavior**
"Get Selected Options" keyword should work with "//select[@name='brandCategory']" xpath

**Desktop:**
 - OS: MAC OS Catalina 10.15.7
 - Browser Chromium
 - Version 71.0.3542.0

**Comment by aaltat** [comment]
The error message says that your xpath is `'.//select[@name='brandCategory'] option' ` and I agree that it's not valid xpath. Could you fix the xpath and try again.

**Comment by vuongvvv** [comment]
- I tried with "//select[@name='brandCategory']" xpath -> Still got the same error

![Log_1](https://user-images.githubusercontent.com/23648562/109920245-98a4df00-7cec-11eb-8408-5f83d15b370b.jpg)
![Log_2](https://user-images.githubusercontent.com/23648562/109920255-9c386600-7cec-11eb-9e2f-3ee1fb90c10f.jpg)

**Comment by aaltat** [comment]
This is actually a bug in Browser library side: https://github.com/MarketSquare/robotframework-browser/blob/bdf001ed3e33e0b5ea5fd146cf0da36dfcd0e766/node/playwright-wrapper/getters.ts#L49 We append  ` option` to the selector and therefore it fails.

**Comment by emakaay** [comment]
I think issue #630 would be fixed with this also
