### ISSUE TITLE
Add `not contains` to AssertionEngine

### ISSUE THREAD

**Issue by leeuwe** [MarketSquare/robotframework-browser#759]
When you're used to the Selenium Library, a key AssertionOperator is missing, namely `Not Contains`. 
Please add this to the AssertionEngine

I've considered checking if it contains, and expecting this to return FALSE, but it's not a nice way of doing it.

**Comment by Snooz82** [comment]
`Get Title   matches    ^((?!robot).)*$`

This would pass if not robot is im the title.


you could also use `validate`

I would not like to implement for all options a negative expression.

**Comment by leeuwe** [comment]
Although from a technical viewpoint I can agree on this, I do think it would serve the community migrating from selenium well to have one more negative expression here. It fits right into the assertion list in my opinion.

**Comment by emakaay** [comment]
I like the 'not contains' assertion as well. Compared to selenium it is missing

**Comment by leeuwe** [comment]
Added in https://github.com/MarketSquare/AssertionEngine/releases/tag/v0.0.2
Thanks @aaltat!
