### ISSUE TITLE
\<select\> related keyword improvements

### ISSUE THREAD

**Issue by xylix** [MarketSquare/robotframework-browser#76]
- [x] Figure out why deselecting with playwrights page.select() doesn't work
  - [x] Work around and get a way for users to deselect
ports assertion syntax
- [x] `Select From List By Label`, `Select From List By Value` are now refactored into `Select Option By`

**Comment by Snooz82** [comment]
@xylix 

* [x]  Figure out why deselecting with playwrights page.select() doesn't work
   * [x]  Work around and get a way for users to deselect
* [ ]  Add some more "complicated" tests (maybe from SL side)
* [ ]  Document API and behaviour differences from SL's similar keywords
* [x]  Get the keyword `List Selection Should Be` to use our latest improvements (assertion syntax)
* [x]  `Select From List By Label`, `Select From List By Value` are now refactored into `Select Option By`

Test could still be improved a bit.
Documentation should be fine. What are you missing here?
