### ISSUE TITLE
Enable keyword documentation for JsExtentions

### ISSUE THREAD

**Issue by leeuwe** [MarketSquare/robotframework-browser#775]
**Is your feature request related to a problem? Please describe.**
Browser has the possibility to be extended with CommonJS. The code written in CommonJS is currently not being picked up by keyword documentation engine `robot.libdoc`.

**Describe the solution you'd like**
Make it possible to add keyword documentation in a way similair like described here: https://github.com/robotframework/SeleniumLibrary/blob/master/docs/extending/extending.rst#generating-keyword-documentation

**Describe alternatives you've considered**
Currently I simply have to know and trust the keyword written in CommonJS exists. Although editors can't find it, they can be found on runtime.

**Comment by mkorpela** [comment]
https://github.com/MarketSquare/robotframework-browser/pull/1565

**Comment by leeuwe** [comment]
All tested and works beautifully. Also very nice you can now use LSP's keyword completion after running `python -m robot.libdoc -f libspec Browser::jsextension=path/to/your/extensions.js libspecs/browser.libspec`
