### ISSUE TITLE
Get Text not waiting anymore after upgrade from 3.2.0 to 3.3.1

### ISSUE THREAD

**Issue by emakaay** [MarketSquare/robotframework-browser#782]
**Describe the bug**
When using Get Text  directly after a change of web page is triggered, the "should be" assertion fails directly.

After detecting this behaviour I installed robotframework-browser (3.2.0) again, and performed "rfbrowser init".
After this the test worked as expected.

To be sure the robotframework-browser (3.3.1) was the problem, I installed it again(also with rfbrowser-init), and re-tested. The problem occurred again. At this moment I can't use v3.3.1 of robotframework-browser.

Any reason for this ?

**Comment by mkorpela** [comment]
There are couple of changes in 3.3.1 compared to 3.2.0 in `Get Text`:
1. input and textarea elements values will be considered as text (these used to return empty innerText)
2. Optional 4th argument called message has been added to Get Text

Could your problem be related to one of these?

**Comment by mkorpela** [comment]
I'm able to reproduce the problem. Thank you for reporting.

**Comment by mkorpela** [comment]
https://github.com/MarketSquare/robotframework-browser/pull/783

**Comment by mkorpela** [comment]
@all-contributors please add emakaay for bug reporting.

**Comment by mkorpela** [comment]
Done.
