### ISSUE TITLE
Highlight element

### ISSUE THREAD

**Issue by mkorpela** [MarketSquare/robotframework-browser#79]
Blink / highlight selector shown element.

     elements.forEach((e) => {
        let d = document.createElement('div');
        d.appendChild(document.createTextNode(''));
        d.style.position = "fixed";
        const rect = e.getBoundingClientRect();
        d.style.top = "" + rect.top + "px";
        d.style.left = "" + rect.left + "px";
        d.style.width = "" + rect.width + "px";
        d.style.height = "" + rect.height + "px";
        d.style.border = "1px solid red";
        setTimeout(() => { d.remove(); }, 5000);
     });

**Comment by xylix** [comment]
Implemented in 4066e2d
