### ISSUE TITLE
Download need pageot be loaded before keyword can perform the download

### ISSUE THREAD

**Issue by adrian-evo** [MarketSquare/robotframework-browser#791]
Please check the following issue. Just as a reproducible example, when I try to directly download a file with the given url, the keyword does not seem to be consistent or maybe also it is not clear how to use it:

1. If New Page does not have an url, the Download keyword fails with "Error: page.evaluate: Evaluation failed: TypeError: Failed to fetch"

```
    New Browser    headless=${FALSE}
    New Context    acceptDownloads=${TRUE}
    New Page

    ${res}  Download  https://www.gutenberg.org/ebooks/135.epub.noimages?session_id=5ae7d248d2d09dff3ebd65f8914dccd32b8ad9cd

```

2. If New Page does have as url the root url of the file to be downloaded, then the download succeeds but the returned suggestedFilename is wrong:

"${res} = {'saveAs': '...1ba1bf58-228b-4691-b788-3e29ee1625ad', 'suggestedFilename': 'https___www.gutenberg.org_ebooks_135.epub.noimages_session_id=5ae7d248d2d09dff3ebd65..."
   
```
    New Browser    headless=${FALSE}
    New Context    acceptDownloads=${TRUE}
    New Page  https://www.gutenberg.org

    ${res}  Download  https://www.gutenberg.org/ebooks/135.epub.noimages?session_id=5ae7d248d2d09dff3ebd65f8914dccd32b8ad9cd
```

Related also to #620 and #642

**Comment by mkorpela** [comment]
Download should also check acceptDownloads

**Comment by aaltat** [comment]
I did try this one and there is an error, in PL logs I see
```
(node:6059) UnhandledPromiseRejectionWarning: Error: server must be bound in order to start
    at Server.start (/home/tatu/workspace/robotframework-playwright/Browser/wrapper/index.js:16666:19)
    at /home/tatu/workspace/robotframework-playwright/Browser/wrapper/index.js:67798:12
    at bindResultPromise.then.errorString (/home/tatu/workspace/robotframework-playwright/Browser/wrapper/index.js:16608:25)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
(node:6059) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:6059) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```
I can think we have bug, but I lies on node side and I have leave it for someone else.

**Comment by aaltat** [comment]
We did have discussion and how the keywords is correct. When using `Download` keyword, there must always page loaded. But we should document this feature.
