### ISSUE TITLE
New keyword Get Element Value to match Selenium keyword Element Value Should Be

### ISSUE THREAD

**Issue by VilleSalonen** [MarketSquare/robotframework-browser#805]
**Is your feature request related to a problem? Please describe.**
SeleniumLibrary provided a keyword Element Value Should Be which could be used to assert any type of form input value. With Browser tester must determine which type of input is being used and then use appropriate keywords such as `Get Text` or `Get Selected Options`.

I ran into this as we have quite a complex form in our application and lots of tests which assert values of different types of inputs. When using SeleniumLibrary we were able to just use Element Value Should Be keyword but now I would need to complicate the code by inspecting element types.

**Describe the solution you'd like**
Get Element Value would get input value from any type of input element and it would support assertion operators.
```
Get Element Value    //select[2]     ==    Mobile   #assertion content
Get Element Value    select#names    *=    Mikko    #assertion contain
```

**Describe alternatives you've considered**
Currently I circumvented the problem by writing my own wrapper as JavaScript seems to return element value easily no matter which type of input is being used.

```
Element Value Should Be
    [Arguments]    ${element_id}    ${expected_value}
    Wait For Elements State    ${element_id}    visible
    ${actual_value}    Execute Javascript   document.getElementById('${element_id.replace("#", "")}').value
    Should Be Equal As Strings    '${expected_value}'    '${actual_value}'
```

**Comment by aaltat** [comment]
The *`Get Text´ keyword should also work with input and textarea elements. But it is not documented anywhere that it actually does work and that is a bug which should be fixed.
