### ISSUE TITLE
NTLM authentication seems to be also supported

### ISSUE THREAD

**Issue by olga-zm** [MarketSquare/robotframework-browser#814]
**Is your feature request related to a problem? Please describe.**
We have to test some Sharepoint pages, that require NTLM authentication. The keyword "New Context" has the parameter httpCredentials for Basic authentication: "Contexts do also support http credentials to be set, so that basic authentication can also be tested."
I tried this keyword for our pages and it seems to work also for NTLM auth out of the box.   

**Describe the solution you'd like**
Could you please verify this and update the documentation, it's a huge plus point of your library and definitely worth mentioning.
 
**Describe alternatives you've considered**

**Additional context**
https://github.com/microsoft/playwright/issues/2662:
You can set http credentials for direct browser auth popups (basic auth, digest auth) on context level:

Our example of success:
[robot@mon-002 ~]$ curl -I https://xxx/organisation/alle
HTTP/1.1 401 Unauthorized
Content-Length: 16
Content-Type: text/plain; charset=utf-8
Server: Microsoft-IIS/10.0
SPRequestDuration: 3
SPIisLatency: 0
**WWW-Authenticate: NTLM**
X-Powered-By: ASP.NET
MicrosoftSharePointTeamServices: 16.0.0.10369
X-Content-Type-Options: nosniff
X-MS-InvokeApp: 1; RequireReadOnly
Date: Thu, 18 Mar 2021 09:18:21 GMT

*** Settings ***
Library   Browser

** Test Cases ***
Example Test
    New Browser    firefox
    New Context    httpCredentials={'username': 'xxx', 'password': 'xxx'}
    New Page   https://xxx/organisation/alle
    Click     text=Sprache
    Take Screenshot

![image](https://user-images.githubusercontent.com/80836036/111603992-28f71f80-87d5-11eb-8c6a-ad1d6d8989c4.png)

**Comment by xylix** [comment]
Thanks for the heads-up! Will be investigating with upstream if this is intended and documenting it.

**Comment by aaltat** [comment]
@all-contributors please add olga-zm for documentation

**Comment by aaltat** [comment]
@all-contributors please add olga-zm for bugs
