### ISSUE TITLE
Get Browser Ids returns browser IDs of browsers closed by AutoClosingLevel TEST or SUITE

### ISSUE THREAD

**Issue by VilleSalonen** [MarketSquare/robotframework-browser#819]
**Describe the bug**
Get Browser Ids contains browser IDs of implicitly closed browsers. Explicitly closed browsers are not included.

**To Reproduce**
```
*** Settings ***
Suite Setup       Create Browser
Force Tags        repro
Library           Browser

*** Test Cases ***
Good - Creates Browser And Closes It Explicitly
    ${browser_id}    Create Browser
    Log To Console    Created second browser
    Close Browser    ${browser_id}

Good - Check Browser Amount
    ${browser_ids}    Get Browser Ids
    ${browser_amount}    Get Length    ${browser_ids}
    Should Be Equal As Integers    ${browser_amount}    1

Bad - Creates Browser But Does Not Explicitly Close It
    Create Browser
    Log To Console    Created second browser

Bad - Check Browser Amount
    ${browser_ids}    Get Browser Ids
    ${browser_amount}    Get Length    ${browser_ids}
    Should Be Equal As Integers    ${browser_amount}    1

*** Keywords ***
Create Browser
    ${browser_id}    New Browser    chromium    headless=false
    New Context    viewport={'width': 1920, 'height': 1080}
    New Page       https://marketsquare.github.io/robotframework-browser/Browser.html
    [Return]    ${browser_id}
```

**Expected behavior**
Documentation of Get Browser Ids states: "Returns a list of ids from open browsers." I would expect that both implicitly and explicitly closed browsers would be omitted.

**Desktop:**
 - OS: Windows 10 2004
 - Browser Chromium
 - Version 90
 - Robot Framework Browser version 4.0.1

**Additional context**
Based on initial code investigation this might actually be a bug in Playwright and not Browser but I am not sure yet.

**Comment by VilleSalonen** [comment]
This might be related to this part of the code: https://github.com/MarketSquare/robotframework-browser/blob/23a44ea8821e3de62b536121bbbfa92ffca357bd/Browser/browser.py#L757

Does that auto closing still leave browsers in Playwright's internal data structures?

**Comment by Snooz82** [comment]
Hi,

auto closing does only close context and page by purpose.

why would you want to close the browser?

**Comment by VilleSalonen** [comment]
Typically you wouldn't so this is probably not that interesting of a bug. I am currently migrating our existing Selenium tests over to Browser. In Selenium tests we have some tests where a second browser is opened and closed during the test. One of those tests was missing the explicit closing of browser so Browser caused auto close.

Based on your comment Browser probably only closed Page and Context so Browser was correct in reporting that browser is still open even if it had no Context or Page open anymore. My example where I used Close Browser closed Page, Context and Browser so browser was not open at all.

**Comment by mkorpela** [comment]
It is stil a reproducible bug.

**Comment by mkorpela** [comment]
@all-contributors please add VilleSalonen for bugs

**Comment by aaltat** [comment]
There is improved docs in the related PR, but I think this is not properly fixed.

**Comment by aaltat** [comment]
After looking this more closely, I think how the Browser library reports browser/context/pages is correct. The context and pages are closed based on their auto closing level and browser are left open until test suite execution ends. The documentation was unclear how the Browser library works.

**Comment by Snooz82** [comment]
I would also say, that the only "bug" was an unclear docs. From my tests, browser catalog works as expected.

**Comment by aaltat** [comment]
I agree, the docs where confusing and it very easy to understand docs in incorrect way.
