### ISSUE TITLE
Problem using -E space:_

### ISSUE THREAD

**Issue by Williamsbsa** [MarketSquare/robotframework-browser#860]
**Describe the bug**
I was searching about the ```-v``` option in the ```robot --help``` guide and I found a example about the use of space between words: ``` -v hi:Hi_World -E space:_  =>  ${hi} = `Hi World` ```. 
But when I try this with my specific parameters I always receive this error message: ```[ ERROR ] option -E not recognized```

**Comment by aaltat** [comment]
This has nothing to with Browser library, it is related to Robot Framework core and how to use command line flags. Next time choose more carefully where where you seek support. 

Closing issue because it is not Browser library related.
