### ISSUE TITLE
 Keyword 'Take Screenshot' could not be run on failure: 'NoneType' object is not iterable

### ISSUE THREAD

**Issue by Ivan-Feofanov** [MarketSquare/robotframework-browser#868]
Trying to get screenshot on failure, but getting only this message:
` Keyword 'Take Screenshot' could not be run on failure: 'NoneType' object is not iterable`

In the same time if I explicitly putting keyword `Take Screenshot` im my .robot file screenshot is successfully saved.

I tried official image `marketsquare/robotframework-browser` and got the same behavior.
requirements.txt:
```
robotframework==4.0
robotframework-browser==4.1.0
```

Robot-file:
```
*** Settings ***
Library  Browser
*** Settings ***
Suite Setup  Enter LK
*** Keywords ***
Enter LK
    new page  %{URL}
    get title  ==   Asserted title
    fill text  xpath=//input[@name='username']    %{USERNAME}
    click  "Enter"
    fill text  xpath=//input[@name='password']    %{PASSWORD}
    click  "Enter"
    wait for elements state  "Main"  timeout=10
*** Test Cases ***
Successeful login
    [Tags]  Smoke
    get element state  "Exit"   attached  ==  ${True}

```

What I'm doing wrong? A couple months ago it was working.

**Update:** when I wrote explicitly
```python
        run_on_failure: str = "Browser.Take Screenshot",
```
instead of 
```python
        run_on_failure: str = "Take Screenshot",
```
in line 621 (https://github.com/MarketSquare/robotframework-browser/blob/master/Browser/browser.py#L621)

It saved screenshots but it doesn't looks like correct behavior. Maybe there are mistakes in test setup?

**Comment by aaltat** [comment]
It is hard to say, but would it be possible to see full stack trace from the? You can get it by running tests with `--loglevel trace `.

**Comment by Ivan-Feofanov** [comment]
> It is hard to say, but would it be possible to see full stack trace from the test? You can get it by running tests with `--loglevel trace `.

Output isn't changed. As my investigation shows it can happens because variable `test_name` [here](https://github.com/MarketSquare/robotframework-browser/blob/master/Browser/browser.py#L884) evaluates in `None`

**Comment by mkorpela** [comment]
Seems like a bug. Test name is not availablr in suite setup. Thank you for reporting!

**Comment by aaltat** [comment]
@all-contributors please add Ivan-Feofanov for bugs

**Comment by Ivan-Feofanov** [comment]
> @all-contributors please add Ivan-Feofanov for bugs

Seems like bot has bugs too ))
