### ISSUE TITLE
Issue with `Wait For Response`

### ISSUE THREAD

**Issue by wlad** [MarketSquare/robotframework-browser#872]
**Describe the bug**
I wonder why `Wait For Response` succeeds on the first URL but fails on second. The first one is a GET request while the second one is a POST request.
```
# 1. works
Wait For Response   https://keycloak.dummy.de/auth/realms/foo/protocol/openid-connect/login-status-iframe.html
# OR
Wait For Response    /openid-connect/login-status-iframe

# 2. does NOT work
Wait For Response    https://keycloak.dummy.de/auth/realms/foo/protocol/openid-connect/token
```

```
TimeoutError: page.waitForResponse: Timeout while waiting for event "response"
=========================== logs ===========================
waiting for response /.*\/openid-connect\/token/
```

both request can be seen in browser dev tools. 
![image](https://user-images.githubusercontent.com/64201310/112730208-94a55f00-8f30-11eb-9088-5a13927716a6.png)

What could be the reason for different behaviour? Any ideas how to fix or workaround it?

**Comment by mahula** [comment]
@wlad did you try it in reverse order?
The screenshot seems to show that the token reqest got its respons earlier than the login status request. After waiting for the login status response there won't be a token response - it already happened.

**Comment by mkorpela** [comment]
If the order is unknown you can use https://marketsquare.github.io/robotframework-browser/Browser.html#Promise%20To

**Comment by aaltat** [comment]
Is this a problem or can we close the issue?

**Comment by wlad** [comment]
@aaltat  it seem it's an missing feature. This issue could be renamed into a feature request(?)
![image](https://user-images.githubusercontent.com/64201310/114371129-7b332280-9b80-11eb-824f-a4007bd364ac.png)

**Comment by rsandbach** [comment]
This may be resolved by #1533 , both Wait For Request and Response should support predicates, [Example](https://github.com/MarketSquare/robotframework-browser/blob/d7ee1d5e7bb6cc9a92cb4c8faf624c2b54eee7b2/atest/test/03_Waiting/wait_for_http.robot#L28)

**Comment by wlad** [comment]
@rsandbach thank you!
Does it also work without a matcher? Looks like this `matcher=request => request.url().endsWith('api/get/json') && request.method() === 'GET'` is one string, thus I guess it works only in combinatiion with the matcher parameter.

I'd consider this a workaround, since it's not useable without matcher parameter and also seems not to be documented in KW docs (at least as an example). That means one have to be aware of this playwright internals to be able to utilize it.

Something like this would be really cool
```robotframework
Wait For Response    /openid-connect/login-status-iframe    method=GET
```

**Comment by rsandbach** [comment]
The keyword parameter names are optional. You should be able to whip together your own Keyword to accomplish the syntax you are requesting. I don't have enough context in this domain to know if it makes sense to create a built in keyword for URL / METHOD.

```robot
# Matches any URL that contains the supplied URL (treated as RegEx).
Wait For Response url
    Click    \#delayed_request
    Wait For Response /api/get/json

# Simplified Syntax
Wait For Method Example
    Click    \#delayed_request
    Wait For Response Method  api/get/json   GET

*** Keywords ***
Wait For Response Method
    [Arguments]    ${url}    ${method}
    Wait For Response    response => response.url().endsWith('${url}') && response.request().method() === '${method}'
```

**Comment by aaltat** [comment]
Let's assume that #1533 and push release out to confirm it.

**Comment by wlad** [comment]
@rsandbach 
> You should be able to whip together your own Keyword to accomplish the syntax you are requesting.

Of course, I am, after I have seen your example. Many thanks for that btw. But somebody else might not be aware of the option `...response.request().method() === GET/POST` if it is not documented anywhere in the KW docs.
