### ISSUE TITLE
Importing with 'enable_presenter_mode' does not work as expected

### ISSUE THREAD

**Issue by wlad** [MarketSquare/robotframework-browser#873]
**Describe the bug**
Trying to use documented import option `enable_presenter_mode` https://marketsquare.github.io/robotframework-browser/Browser.html#Importing

**To Reproduce**
**Option 1) Steps to reproduce the behavior:**
importing as
```robotframework
*** Settings ***
Library    Browser    enable_presenter_mode=True
```

results in
```
[ ERROR ] Unexpected error: ValueError: Argument 'timeout' got value 'enable_presenter_mode=True'
that cannot be converted to timedelta: Invalid time string 'enable_presenter_mode=True'.
```

**Option 2) Steps to reproduce the behavior:**
importing as
```robotframework
*** Settings ***
Library    Browser    timeout=5s    enable_presenter_mode=True
```

results in
```
[ ERROR ] Error in file '/home/wlad/.../login.robot' on line 28: Library 'Browser'
got unexpected named argument 'enable_presenter_mode'.
```

**Expected behavior**
slowmo, highlighting and all the promised stuff :)

**Desktop (please complete the following information):**
 - OS: linux
 - chrome based Browser

**Comment by aaltat** [comment]
Can not reproduce the issue, I tried with Robot Framework 3.2.2 and 4.0 with latest Browser library 4.1.0. 

I do not have good ideas why you get error, but I would assume that your RF version is too old.

**Comment by wlad** [comment]
```
$ pip list
...
robotframework               4.0
robotframework-browser       3.1.0
...
```

sorry, my browser lib was outdated :pray: 

can't reproduce with latest version 4.1.0.
