### ISSUE TITLE
`EOFError: EOF when reading a line` when using `Open Browser` when targeting non-existing elements

### ISSUE THREAD

**Issue by janipalsamaki** [MarketSquare/robotframework-browser#891]
`robotframework-browser==4.2.0`

The log displays a cryptic `EOFError: EOF when reading a line` as the reason for failure when using `Open Browser` and `Click` when targeting non-existing elements (or elements that are not visible):

```robot
*** Settings ***
Library           Browser

*** Tasks ***
EOFError: EOF when reading a line
    Open Browser    https://robotframework-browser.org/
    Click    css=#foobar
```

When using `New Page` instead of `Open Browser`, a better error message is generated in the log:

```
TimeoutError: page.click: Timeout 10000ms exceeded.
=========================== logs ===========================
waiting for selector "css=#foobar"
============================================================
```

Is it possible to generate the more specific error message when using `Open Browser` to avoid confusion?

**Comment by aaltat** [comment]
Yes, it should be possible, although I am amazed that it does not generate the same error message. 

But as the keyword documenting states, open browser keyword should not be used for production usage. Instead New Browser/Context/Page should be used.

**Comment by aaltat** [comment]
I can not reproduce the problem, I get same error message regardless which keyword is used to open the browser/context/page.
