### ISSUE TITLE
Browser Keyword "Fill Secret" generates warning in combination with Robotframework 4.0

### ISSUE THREAD

**Issue by emakaay** [MarketSquare/robotframework-browser#893]
**Describe the bug**
Extra output is generated which wasn't there with RF 3.2.x

The following message is generated every time the keyword Fill Secret is used:
- Direct assignment of values as 'secret' is deprecated.Use variables or environment variables instead.

Here is the robot log (output.xml)

```
<kw name="Fill Secret" library="Browser">
<arg>//input[@Id='password']</arg>
<arg>${Password}</arg>
<tag>PageContent</tag>
<tag>Setter</tag>
<doc>Fills the given secret from ``variable_name`` into the
text field found by ``selector``.</doc>
<msg timestamp="20210331 12:28:19.614" level="WARN">Direct assignment of values as 'secret' is deprecated.Use variables or environment variables instead.</msg>
<status status="PASS" starttime="20210331 12:28:19.614" endtime="20210331 12:28:19.627"/>
</kw>
<kw name="Click" library="Browser">

```
A clear and concise description of what the bug is.-

**To Reproduce**
Every time Fill Secret is used

```
New Context locale=nl-NL
New Page https://accounts.google.com/signin
Fill Text id=identifierId me@gmail.com
Click text=Volgende
Fill Secret //*[@name='password'] password
```
The test will fail, but it generates the error.
 
**Expected behavior**
I would expect NO warnings. Like with RF 3.2.X

**Desktop
 - OS: Windows (64 bit)
 - Browser: using robotframework 4.20 with chromium
 - RF: 4.0

**Comment by mkorpela** [comment]
This is a feature. You should not use directly your secret as it will be written to log by Robot Framework without libraries ability to hide it.
Instead you should hide your secret to a variable and give that variable as an argument.

**Comment by emakaay** [comment]
@mkorpela 
Hello Miko,

I understand you closed this "bug". I did not explain myself very clearly. First I posted a piece out of output.xml. There is was visible that password **was** in a variable. But the test contained the password in plain text. Which is a reason to display the warning.

With the following code (where the secret is in a variabele) I still get the warning
```
*** Settings ***
Library    Browser

*** Test Cases ***

Fill Secret With Variable
	${secret}    Set Variable    me@gmail.com

	New Browser    chromium     headless=false
	New Context    locale=nl-NL
	New Page    https://accounts.google.com/signin
	Fill Secret     id=identifierId     ${secret}

```

```
robot robot.robot
==============================================================================
Robot
==============================================================================
[ WARN ] Direct assignment of values as 'secret' is deprecated.Use variables or environment variables instead.
Fill Secret With Variable                                             | PASS |
------------------------------------------------------------------------------
Robot                                                                 | PASS |
 
```

There is a bug or I don't understand the warning. In this example the secret IS in a variable, so it shouldn't complain. I tried this code in RF 3.2.2 (combined with browser 4.20) and also with RF 4.0, but the reaction is the same. Which is strange to me, because I didn't see the message before.

Any thoughts about this ?

**Comment by aaltat** [comment]
Having variables is fine, but directly using `${variable}` can leak the secret to many Robot Framework outputs, which is not desirable. Also for us, in the library level, it's not possible to influence RF running context in that level. 

As a solution we offer users to map variables with internal syntax. Example if your secret is in `${password}` variable, use it like 
```
Fill Secret     id=identifierId     $password 
```
Then library will dig the variable value,  the secret, from Robot Framework without exposing it into RF output files.  Same syntax applies for environment variables but with `%` prefix. 

The documentation is somewhat conflicting and could be improved. Specially the last chapter is wrong.
