### ISSUE TITLE
Testing target webapp with extra functionality

### ISSUE THREAD

**Issue by mkorpela** [MarketSquare/robotframework-browser#9]
atest should have test targets that represent current web techs.
That means a progressive webapp with asynchronous functionalities and device specific functionalities such as user location.

MVP done at #84

**Comment by idxn** [comment]
Is cypress real word app suitable? It may reduce your effort to maintain the AUT.
https://github.com/cypress-io/cypress-realworld-app

**Comment by xylix** [comment]
Requirements:
- Way to change a DOM element with timeout (to test our timeout configuration keywords)
- Way to test creating new windows / ensuring user input goes into latest? window by default

**Comment by yanne** [comment]
The skeleton for this app has already been implemented. Closing this, as new features may be added to the app when needed.
