### ISSUE TITLE
Missing .local_browsers folder after install

### ISSUE THREAD

**Issue by y2j444** [MarketSquare/robotframework-browser#912]
**Describe the bug**
Error running browser library after install

**To Reproduce**
ran these steps to install browser
set PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD=1

npm i -D playwright

npm i -D playwright-chromium

rfbrowser init

**Expected behavior**
Should be able to run robot framework test automation but an error occurs looking for .local_browsers folder

Error: browserType.launch: Failed to launch chromium because executable doesn't exist at c:\program files\python38\lib\site-packages\Browser\wrapper\node_modules\playwright\.local-browsers\chromium-857950\chrome-win\chrome.exe

**Desktop (please complete the following information):**
 - Win10
 - Browser chrome

**Comment by aaltat** [comment]
Then you need to define `executablePath` in the New Browser keyword. Browser library by default assumes that browser binaries are in the location mentioned in the error message. But you are installing playwright and browser binaries by using the library standard tooling.

**Comment by y2j444** [comment]
Ok. I’ll do that. Thank you
