### ISSUE TITLE
Wait For Navigation keyword should support regex and waitUntil

### ISSUE THREAD

**Issue by vincenzo-gasparo** [MarketSquare/robotframework-browser#916]
Wait For Navigation Keyword only support exact match for the URL, it would be nice to allow a partial match with a regex support.

Also the playwright API support a waitUntil argument. [Playwright API](https://playwright.dev/docs/api/class-page?_highlight=waitforna#pagewaitfornavigationoptions)

I thought about two ways to add the regex support:
- Add a **regex** boolean argument
- Use an enum to specify the type of the url

I prefer the first option since I don't think it would make sense to support the **function(URL):boolean** type

**Comment by mkorpela** [comment]
@vincenzo-gasparo your PR is now merged. Is there additional tasks you would like to do related to this issue?

**Comment by aaltat** [comment]
I am going to assume that there is not anything more left and I will close the issue. If there is more, please reply or open new issue.
