### ISSUE TITLE
Is an empty cell in a table considered 'hidden' ?

### ISSUE THREAD

**Issue by emakaay** [MarketSquare/robotframework-browser#935]
**Describe the bug**
I'm testing the visibility of cells in a table. 
Most of these cells have a value in the cell, and checking visibility of the cell is fine.
I encountered a number of empty cells, which all fail the visible check. Like the reproduction script below.

My question: Is this expected behaviour ? I would reason that an empty cell is still visible. If this is expected behaviour, how should I check if cell is available ?

**To Reproduce**

```
*** Settings ***
Library           Browser

*** Test Cases ***
Empty cell of table not Considered visible
    New Browser    browser=chromium headless=false
    New Context
    New Page    https://www.tutorialspoint.com/css/css_empty-cells.htm
    Browser.Wait For Elements State    //table[@class='empty']/tbody/tr[3]/td[2]    visible

```
**Expected behavior**
See above

**Screenshots**
not applicable

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser robotframework 4.30(chromium)

**Comment by mkorpela** [comment]
Hi,

The table is inside of an iframe so you must pierce that iframe to get access to elements.

I got this working:
```RobotFramework
*** Settings ***
Library           Browser

*** Test Cases ***
Empty cell of table not Considered visible
    New Browser    browser=chromium  headless=false
    New Context
    New Page    https://www.tutorialspoint.com/css/css_empty-cells.htm
    Click   button[aria-label="Consent"]
    Sleep   2s
    Get Text    //html/body/div[1]/div/div[2]/iframe >>> body > table > tbody > tr:nth-child(3) > td:nth-child(3)  ==  \
```

**Comment by mkorpela** [comment]
Was there some other example or should we close this issue?

**Comment by emakaay** [comment]
Hello Mikko,

I did not know that i needed to pierce the iframe.
But I'm trying to determine what the reaction **should** be when using "Wait For Elements State"    with <some selector>     visible. I'm not trying to get the text. Should a empty cell be considered visible !

This was the case with selenium !

**Comment by mkorpela** [comment]
Empty cell with is in my opinion visible.

**Comment by emakaay** [comment]
I expanded the test a little bit, and I can see that visible is checked correctly

`*** Settings ***
Library           Browser

*** Test Cases ***
Empty cell of table not Considered visible
    New Browser    browser=chromium  headless=false
    New Context
    New Page    https://www.tutorialspoint.com/css/css_empty-cells.htm
	#
	# Validate values can be read
	Get Text    //html/body/div[1]/div/div[2]/iframe >>> body > table > tbody > tr:nth-child(2) > td:nth-child(2)  ==  value
	Get Text    //html/body/div[1]/div/div[2]/iframe >>> body > table > tbody > tr:nth-child(2) > td:nth-child(3)  ==  value
	Get Text    //html/body/div[1]/div/div[2]/iframe >>> body > table > tbody > tr:nth-child(3) > td:nth-child(2)  ==  value
    Get Text    //html/body/div[1]/div/div[2]/iframe >>> body > table > tbody > tr:nth-child(3) > td:nth-child(3)  ==  \
	#
	# Validate fields are visible
	Wait For Elements State    //html/body/div[1]/div/div[2]/iframe >>> body > table > tbody > tr:nth-child(2) > td:nth-child(2)  visible
	Wait For Elements State    //html/body/div[1]/div/div[2]/iframe >>> body > table > tbody > tr:nth-child(2) > td:nth-child(3)  visible
	Wait For Elements State    //html/body/div[1]/div/div[2]/iframe >>> body > table > tbody > tr:nth-child(3) > td:nth-child(2)  visible
    Wait For Elements State    //html/body/div[1]/div/div[2]/iframe >>> body > table > tbody > tr:nth-child(3) > td:nth-child(3)  visible`

I have to look closely at the other tests, to see why they fail. It looks the same. But this issue can be closed
