### ISSUE TITLE
ElementHandle selector

### ISSUE THREAD

**Issue by mkorpela** [MarketSquare/robotframework-browser#94]
**Is your feature request related to a problem? Please describe.**
Selectors do not yeat expose a direct reference to a dom element. This does that. Can be used for example when iterating through multiple matching elements.

**Describe the solution**

Add a selector `element=UUID` that lives at most until the page is closed.

**Describe alternatives you've considered**
Exposing some kind of more complex object what also discussed. But we would want this to be really simple on RF side and go nicely together woth other selectors.

**Comment by xylix** [comment]
Implemented in eb20f6
