### ISSUE TITLE
New Context >> httpCredentials Logs password clearly to log.html

### ISSUE THREAD

**Issue by dalaakso** [MarketSquare/robotframework-browser#946]
**Describe the bug**
Password is in readable form and should be hidden. Expect to work as Fill Secret.

**To Reproduce**
Create New Context and enter httpCredentials

**Comment by aaltat** [comment]
@all-contributors please add @dalaakso  for bugs

**Comment by aaltat** [comment]
I think it would be best to use idea that we use for [Fill Secret](https://marketsquare.github.io/robotframework-browser/Browser.html#Fill%20Secret) and [Type Secret](https://marketsquare.github.io/robotframework-browser/Browser.html#Type%20Secret) keywords. We keep the functionality that it is possible to give `httpCredentials` as plain text or as Robot Framework variable, but we display a warning for it. Also we add functionality to use `$secret` and `%secret` variables and keyword will resolve the variable internally. 

Also keywords now logs the `httpCredentials`, with other arugments
