### ISSUE TITLE
Promise To Wait For Download keyword documentation issue

### ISSUE THREAD

**Issue by janipalsamaki** [MarketSquare/robotframework-browser#949]
https://marketsquare.github.io/robotframework-browser/Browser.html#Promise%20To%20Wait%20For%20Download has an example that has the following line where the argument points to a directory:

```
${dl_promise}        Promise To Wait For Download    /path/to/download/folder
```

At least with `4.3.0` this only works when pointing to a file, not a dir, so something like:

```
${dl_promise}        Promise To Wait For Download    /path/to/download/folder/file.txt
```

When pointing to a dir, the following error is thrown:

```
Error: download.saveAs: EISDIR: illegal operation on a directory, copyfile '/var/folders/4k/dxsc660s44b73gm609l95l0w0000gn/T/playwright_downloads-RBREyq/de951510-0ef0-4343-8b93-907bb164bf63' -> '/Users/<myusernamehere>'
```

Expected: Accepts a dir, or the example in the keyword docs is updated.

**Comment by aaltat** [comment]
@all-contributors please add @janipalsamaki for bugs
