### ISSUE TITLE
Initializing `value` inside conditional can lead to unhelpful exception

### ISSUE THREAD

**Issue by rasjani** [MarketSquare/robotframework-browser#957]
https://forum.robotframework.org/t/get-text-results-in-error-in-case-of-svg-element/1681/4

Code:

```        
    with self.playwright.grpc_channel() as stub:
            response = stub.GetText(Request().ElementSelector(selector=selector))
            logger.debug(response.log)
            if response.body:
                value = json.loads(response.body)
            return verify_assertion(
                value, assertion_operator, assertion_expected, "Text", message
            )
```

So, if get text's response request fails and response doesnt have truthy body attribute, verify_assertation will fail because value is not defined...

I modified the title, similar pattern to store `value` only  if `response.body` is truthy is in few other spots too..

**Comment by aaltat** [comment]
Yes, looks like you are correct. Needs to be fixed.

**Comment by aaltat** [comment]
@all-contributors please add rasjani for bugs
