### ISSUE TITLE
How can I use this library and still request a different profile when browser is launched?  

### ISSUE THREAD

**Issue by Nastaran200** [MarketSquare/robotframework-browser#963]
Question:
my current script has the following where I open Firefox and run the test using specific profile? also does it have selenium library or I have to add that?

*** Settings ***
Documentation    Verify x site can be accessed
Library    SeleniumLibrary

*** Variables ***
${URL}      https://sitex.com   

*** Test Cases ***
Start firefox
    Open Browser    ${URL}   browser=ff   ff_profile_dir=/Users/me/Documents/newprofile1

How would I change my script here after using Browser library and this container:
*** Settings ***
Documentation    Verify x site can be accessed
Library    SeleniumLibrary
Library    Browser

*** Variables ***
${URL}      https://sitex.com   

*** Test Cases ***
Start firefox
    Open Browser    ${URL}   browser=ff   ff_profile_dir=/Users/me/Documents/newprofile1

**Comment by aaltat** [comment]
This is not supported by Playwirght, as far I know. There are ways to emulate same thing example by adding cookies or manipulating http headers. 

If you want support for it, please raise an issue to Playwright side. But because there is not anything which we could do on Browser library side, closing this issue.

**Comment by aaltat** [comment]
This is now days supported in [PW launchPersistentContext](https://playwright.dev/docs/api/class-browsertype/#browser-type-launch-persistent-context). Which is different that the [PW launch](https://playwright.dev/docs/api/class-browsertype/#browser-type-launch). Main difference is that `launch` returns a PW browser instance, but `launchPersistentContext` returns directly a context. The browser/context/page is deeply hard coded in the Browser library side, but I do not think it is impossible to do this. It might be hard and is definitely out of my TS skills.

**Comment by mferturk** [comment]
I need to load an chrome extension through robotframework-browser.  Since 'new context' keyword creates an incognito tab, it is not possible to load an extension. This feature might be useful to achieve that.

**Comment by tomekTieto** [comment]
I vote for implementation of  [launch persisten context from playwrith](https://playwright.dev/python/docs/api/class-browsertype/?_highlight=launch_per#browser-type-launch-persistent-context) that would be really useful. One of the problems that I'm facing is that in incognito mode a browser console log is really pure, only few things being logged.

**Comment by valentijnpeters** [comment]
launch persisten context from playwrith   YES PLEASE!!! make it a ON/OFF switch... 
I really do not want to use an incognito modus in some cases. it should be possible to turn that off very easily!

please in new version Browser library.

**Comment by mkorpela** [comment]
@valentijnpeters you can also open the context on suite setup to re-use the same context in multiple tests.

**Comment by xylix** [comment]
If you need to share cookie or LocalStorage auth between multiple tests check out https://marketsquare.github.io/robotframework-browser/Browser.html#Save%20Storage%20State
