### ISSUE TITLE
"Get Elements" keyword returning wrong elements

### ISSUE THREAD

**Issue by TeddyTeddy** [MarketSquare/robotframework-browser#965]
**Describe the bug**

Below  given a list with a filter from system under test. As you see, note that there is an **unfiltered set of permissions** to select from
and also the items in the list can be filtered:

![Permissions](https://user-images.githubusercontent.com/1288807/117262782-4c942900-ae5a-11eb-9590-7a7bae45a52a.png)

In our test case, we enter "postings | blog post | Can add blog post" text to the filter:

![Permissions2](https://user-images.githubusercontent.com/1288807/117263955-700ba380-ae5b-11eb-8d81-5bf16381ab1c.png)

As you see, we have in the UI **a filtered set of permissions**, which contains only one element.

For the **unfiltered set of permissions**, the DOM looks like:

![Permissions_HTML](https://user-images.githubusercontent.com/1288807/117264879-57e85400-ae5c-11eb-935f-9ade3b4dff3e.png)

For the **filtered set of permissions**, the DOM looks like
![Permissions2_HTML](https://user-images.githubusercontent.com/1288807/117265370-d7762300-ae5c-11eb-8a32-58e1710b5bca.png)

So, if we use xpath selector **//*[@id="id_permissions_from"]/option** with **Get Elements** keyword, for the filtered set of permissions, we should get only one element. But we don't. Instead, we get **the unfiltered set of permissions**. That is the bug.

**To Reproduce**
I made a demo test suite, by running it, you are able to reproduce the problem.

**Installation:**

1. Clone https://github.com/TeddyTeddy/robot-fw-browser-library-tests
2. Create a virtual environment: python -m venv .venv/
3. At the project root, activate the venv: source .venv/bin/activate
4. At the project root, install the dependencies: python -m pip install -r requirements.txt

Steps to reproduce the behavior (in linux):
1. At the project root, run the test suite by executing; ./run
2. Go to Results/log.html at the project root to see the test results
![permissions_results](https://user-images.githubusercontent.com/1288807/117267819-58361e80-ae5f-11eb-8e88-40a1ff3b47b5.png)

As you see the problem happens in my **Choose All Filtered Permissions** keyword, which logs that **the unfiltered set of permissions** elements, which **Get Elements** keyword returning. Instead,  **Get Elements** keyword must have returned the filtered set of elements, which contains only 1 element. 

3. Go to  [my test code](https://github.com/TeddyTeddy/robot-fw-browser-library-tests/blob/ec30f913491a113a660085c9cb4372e5cc6c13e9/Libraries/Src/AddGroupPage.py#L157) to see how Get Elements keyword gets called

**Expected behavior**
So, if we use xpath selector **//*[@id="id_permissions_from"]/option** with **Get Elements** keyword, then the filtered set of permissions, we should get only a list with one element. On the contrary, we get a list of unfiltered permissions, which contains all the permissions in the list.

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.04
 - Browser: chromium
 - Version: Version 90.0.4430.93 (Official Build) snap (64-bit)

**Additional context**

**Comment by aaltat** [comment]
If the elements are are present in the DOM, those elements are returned. Keyword does not take in account are elements visible or not. The seconds screenshot from DOM does not show what elements are present under the `select`.

**Comment by TeddyTeddy** [comment]
Based on @aaltat comments 

>"If the elements are are present in the DOM, those elements are returned. Keyword does not take in account are elements visible or not.

This ticket can be closed.
