### ISSUE TITLE
"Click" keyword can accept an element in place of a selector; Documentation is missing for this

### ISSUE THREAD

**Issue by TeddyTeddy** [MarketSquare/robotframework-browser#966]
**Describe the bug**
According to the [click keyword documentation](https://marketsquare.github.io/robotframework-browser/Browser.html#Click), the first positional argument should be a selector of type str. However, [in my experimental test suite](https://github.com/TeddyTeddy/robot-fw-browser-library-tests/blob/e886bbb3b0672b08ec02b0e9dbc25c34a7150726/Libraries/Src/AddGroupPage.py#L170), I was able to pass an element from DOM to the click keyword and it did click on the element(s) I passed.
Should the documentation be updated to reflect this?

**To Reproduce**
If you want to see that the element(s) passed in the experimental code do receive a click event, then do:

**Installation:**

1. Clone https://github.com/TeddyTeddy/robot-fw-browser-library-tests
2. Create a virtual environment: python -m venv .venv/
3. At the project root, activate the venv: source .venv/bin/activate
4. At the project root, install the dependencies: python -m pip install -r requirements.txt

**Steps to reproduce the behavior (in linux):**

At the project root, run the test suite by executing; ./run

**Expected behavior**
If the behavior is correct for click keyword receiving DOM elements and being able to clicking on them, then the documentation for the click can be updated to reflect this feature.

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.04
 - Browser: Chromium
 - Version 90.0.4430.93 (Official Build) snap (64-bit)

**Comment by JaPyR** [comment]
Actually it's mentioned in [Finding elements](https://marketsquare.github.io/robotframework-browser/Browser.html#Element%20reference%20syntax) section.

**Comment by mkorpela** [comment]
Browser Library reference to an element is a special selector that targets that specific element. These are strings in the form `element=UUID`.
No plain element objects are returned by the library.

**Comment by TeddyTeddy** [comment]
@JaPyR Thanks for pointing that. It feels more natural to see examples in the Keyword descriptions also. SeleniumLibrary has quite good examples, **whereas Browser Library still missing good examples per keyword in the documentation.** Can anyone take an action point on this?

@mkorpela So, the title for this very ticket is wrong then. It should be; "Click" keyword can accept an element selector.
As @JaPyR noted, documentation is not missing for this.

Closing this ticket
