### ISSUE TITLE
Visible <option> element is recognized as hidden

### ISSUE THREAD

**Issue by TeddyTeddy** [MarketSquare/robotframework-browser#987]
**Describe the bug**
In system under test (SUT), in groups page, we have a dropdown as shown below:
![OptionVisible](https://user-images.githubusercontent.com/1288807/117798891-3f13e000-b25a-11eb-8156-f7f35ea056c3.png)

As you see, the dropdown has "Delete Selected Groups" option which is visible. When we want to click on the option, we receive the following error:

> waiting for selector "//*[@id="changelist-form"]/div[1]/label/select/option[contains(.,"Delete selected groups")]" to be visible
>   selector resolved to hidden <option value="delete_selected">Delete selected groups</option>

**To Reproduce**

Installation of the demo code in a venv (Linux):
1. git clone https://github.com/TeddyTeddy/robot-fw-browser-library-tests.git
2. cd into robot-fw-browser-library-tests folder
3. python -m venv .venv/
4. source .venv/bin/activate
5. git checkout ddf266392c84400c81dffc5edab39b6db1ac2493
6. python -m pip install -U pip
5. python -m pip install -r requirements.txt
6. rfbrowser init

Prerequisites:
1. Login to SUT using [this link](https://glacial-earth-31542.herokuapp.com/admin/login/?next=/admin/auth/group/)  (username:hakan, password: h1a2k3a4)
2. Go to [Groups Page](https://glacial-earth-31542.herokuapp.com/admin/auth/group/)
3. Delete **blog_editors** group if it exists

Steps to reproduce the behavior (linux):
In command line
1. cd into robot-fw-browser-library-tests folder
2. Execute the test suite: ./run
3. After test suite finishes, you will see the error:

```
==============================================================================
DjangoAdminSiteTestSuite :: This is a test suite for Django Admin Site        
==============================================================================
Logging In As Admin                                                   | PASS |
------------------------------------------------------------------------------
Creating "Blog Editors" Group                                         | FAIL |
Text 'Action: 
---------
Delete selected groups' (str) should be 'Action:
---------
Delete selected groups' (str)
------------------------------------------------------------------------------
Deleting "Blog Editors" Group                                         | FAIL |
TimeoutError: page.waitForSelector: Timeout 30000ms exceeded.
=========================== logs ===========================
waiting for selector "//*[@id="changelist-form"]/div[1]/label/select/option[contains(.,"Delete selected groups")]" to be visible
selector resolved to hidden <option value="delete_selected">Delete selected groups</option>
============================================================
Note: use DEBUG=pw:api environment variable to capture Playwright logs.
------------------------------------------------------------------------------
DjangoAdminSiteTestSuite :: This is a test suite for Django Admin ... | FAIL |
3 tests, 1 passed, 2 failed
==============================================================================
```
Instead of
```
Deleting "Blog Editors" Group                                         | FAIL |
TimeoutError: page.waitForSelector: Timeout 30000ms exceeded.
=========================== logs ===========================
waiting for selector "//*[@id="changelist-form"]/div[1]/label/select/option[contains(.,"Delete selected groups")]" to be visible
selector resolved to hidden <option value="delete_selected">Delete selected groups</option>
```

**Expected behavior**
Element with the selector 
`"//*[@id="changelist-form"]/div[1]/label/select/option[contains(.,"Delete selected groups")]" `
should have been clicked. But BrowserLibrary claims that the element is hidden, which is not.

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.04
 - Browser Chromium 
 - Version 90.0.4430.93 (Official Build) snap (64-bit)

**Additional context**
The error happens in [GroupsPage.py, line 121](https://github.com/TeddyTeddy/robot-fw-browser-library-tests/blob/8d68ba271424c4dcbbd30d07afbf94caf7888a8c/Libraries/Src/GroupsPage.py#L121)

**Comment by aaltat** [comment]
Since release 10.0 this functionality is rewritten. Could you retest and report is it still a problem.

**Comment by aaltat** [comment]
Closing due inactivity.
