### ISSUE TITLE
Execute Javascript keyword returns "ReferenceError: document is not defined"

### ISSUE THREAD

**Issue by TeddyTeddy** [MarketSquare/robotframework-browser#991]
**Describe the bug**
Trying to achieve the actions in **0:25 to 0:30** of the following video:
https://www.youtube.com/watch?v=8u9Bnwfax3o

I have JS code that generates key events to the filtering input field in the video as such:

        def enter_search_term_in_available_permissions_filter(self, permission_search_term):
        # IMPORTANT: There are 2 options here, only comment out one option at a time and run the test suite
        # *********************** OPTION #1 start **********************************************************
        # self._loader.bl.fill_text(selector=locator['add_group_page']['input_permission_field'],
        #                          txt=permission_search_term)
        # *********************** OPTION #1 end ************************************************************
        # *********************** OPTION #2 start **********************************************************
        input_permission_field = self._loader.bl.get_element(selector=locator['add_group_page']['input_permission_field'])
        logger.info(permission_search_term)
        fill_text_js_function = ( 'function fill_permission_field() {\n'
                f'input_field = document.getElementById("id_permissions_input");\n'
                'input_field.focus();'
                f'permission_search_term = "{permission_search_term}"\n'
                'var i;\n'
                'for (i = 0; i < permission_search_term.length; i++) {\n'
                 'input_field.dispatchEvent(new KeyboardEvent("keydown",  {"key":permission_search_term[i]}));\n'
                'input_field.dispatchEvent(new KeyboardEvent("keypress", {"key":permission_search_term[i]}));\n'
                'input_field.dispatchEvent(new KeyboardEvent("keyup", {"key":permission_search_term[i]}));\n'
               '}}\n'
               'fill_permission_field();\n'
        )

        self._loader.bl.execute_javascript(function=fill_text_js_function, selector=input_permission_field)

When execute_javascript() runs in BrowserLibrary, i get
`ReferenceError: document is not defined`

**To Reproduce**
Installation of the demo code into a venv (Linux):

1. git clone https://github.com/TeddyTeddy/robot-fw-browser-library-tests.git
2. cd into robot-fw-browser-library-tests folder
3. python -m venv .venv/
4. source .venv/bin/activate
5. git checkout 3cc92ad
6. python -m pip install -U pip
7. python -m pip install -r requirements.txt
8. rfbrowser init

Prerequisites:
1. Login to system under test using [this link](https://glacial-earth-31542.herokuapp.com/admin/login/?next=/admin/) (username:hakan, password: h1a2k3a4)
2. Go to [Groups Page](https://glacial-earth-31542.herokuapp.com/admin/auth/group/) in system under test
3. Delete **blog_editors** group if it exists

Steps to reproduce the issue (linux):
In command line:
1. Go to project folder's root
2. Note that error happens [in line 149 of AddGroupPage.py](https://github.com/TeddyTeddy/robot-fw-browser-library-tests/blob/3cc92ad79af7a0bb4012697283186f3b60088cd3/Libraries/Src/AddGroupPage.py#L149).
3. Execute the test suite by running in the project root: **./run**

**Expected behavior**
Key down/press/up events should be sent to the filtering input element as shown in the video.

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.04
 - Browser Chromium
 - Version 90.0.4430.93 (Official Build) snap (64-bit)

**Additional context**
I do not know, if the problem is in BrowserLibrary side or not. Any explanation to fix this issue would be helpful.

**Comment by aaltat** [comment]
This looks like a problem in your JS code. Closing issue because we don't provide this kind of support. Better please would be Robot Framework slack, user group mailing list or forum.
