### ISSUE TITLE
Setting browser path by PLAYWRIGHT_BROWSERS_PATH not working anymore

### ISSUE THREAD

**Issue by simonmeggle** [MarketSquare/robotframework-browser#992]
It is not possible anymore to change the location of playwright browser binaries with `PLAYWRIGHT_BROWSERS_PATH`. 

Before commit 391ddcf8efff24bf49fd71487c5414343e2899b0 it was possible. 

The referenced commit added the line 

```python
    os.environ["PLAYWRIGHT_BROWSERS_PATH"] = "0"
```

This **hardcodes** the binary path to the default: 

```python 
# lib\site-packages\Browser\wrapper\node_modules\playwright\lib\utils\registry.js

    const envDefined = utils_1.getFromENV('PLAYWRIGHT_BROWSERS_PATH');
    if (envDefined === '0') {
        result = path_1.default.join(__dirname, '..', '..', '.local-browsers'); # <<< always used
    }
    else if (envDefined) {
        result = envDefined; # <<< not possible anymore!
    }
```

I would expect Browser to behave as it did before this commit and to respect the variable `PLAYWRIGHT_BROWSERS_PATH` again to work as it is intended and documented by Playwright: https://playwright.dev/docs/installation/#managing-browser-binaries

**Comment by aaltat** [comment]
@all-contributors please add @simonmeggle q for bugs

**Comment by aaltat** [comment]
Done in cc18e1becdda06fe1e90714c73fa10058e04b937
